### ISSUE TITLE
Seems like JIRA collector is leaking file handles.

### ISSUE THREAD

**Issue by rohitstatic** [capitalone/Hygieia#1002]
Hi,

JIRA collector runs fine for some time after which it throws the following exception.

```
java.lang.RuntimeException: Reactor httpclientnot set up correctly
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient.<init>(DefaultHttpClient.java:134)
        at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:53)
        at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:35)
        at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication(AsynchronousJiraRestClientFactory.java:42)
        at com.capitalone.dashboard.client.JiraRestClientSupplier.get(JiraRestClientSupplier.java:63)
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.<init>(TeamDataClientImpl.java:55)
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:108)
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:29)
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.nio.reactor.IOReactorException: Failure opening selector
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.<init>(AbstractMultiworkerIOReactor.java:163)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.<init>(DefaultConnectingIOReactor.java:80)
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient.<init>(DefaultHttpClient.java:96)
        ... 17 common frames omitted
Caused by: java.io.IOException: Too many open files
        at sun.nio.ch.EPollArrayWrapper.epollCreate(Native Method)
        at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:130)
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:69)
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
        at java.nio.channels.Selector.open(Selector.java:227)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.<init>(AbstractMultiworkerIOReactor.java:161)
        ... 19 common frames omitted

```
I tried increasing the ulimit to 10000 in mysystem but it is only a matter of time till it hits that number and breaks down.

I am running the collector using nohup command and not docker. Would it help if I ran it using docker. Also what are the optimal hardware configurations required here. I am running on a machine wiht 9 GB of RAM and have currently have no free memory left.

**Comment by MarkRx** [comment]
@pxk5958 have you seen this at all?

**Comment by pxk5958** [comment]
I have never seen that error in our Hygieia instance which runs for days together, but we run it in docker. We have 8GB of RAM allocated to the VM and we run most of the collectors too.

@rohitstatic By some time, how long do you mean?

**Comment by pxk5958** [comment]
https://ecosystem.atlassian.net/browse/JRJC-145 seems to be related

**Comment by rohitstatic** [comment]
By some time I mean till the time the limit for the file handles set in the system is reached.

https://ecosystem.atlassian.net/browse/JRJC-145  this definitely seems to be related and I checked we are no where using close() method on JRJC. Can you please guide me as to where should the client be closed to avoid this leak.

**Comment by pxk5958** [comment]
Could you check which version of JRJC you end up using? They seem to have mentioned it's fixed from 2.0.0 in that issue I linked above. Jira collector's pom.xml says it uses 3.0.0, so you really shouldn'[t be facing this problem.

**Comment by rohitstatic** [comment]
@pxk5958  I am not sure how you can reproduce this issue, but if we can close the jirarestclient when we are done with that, I think the error should recover.

**Comment by tabladrum** [comment]
@pxk5958 did you fix this in any later code? I don't see it. Just confirming.

**Comment by pxk5958** [comment]
Nope I didn't

**Comment by satishc1** [comment]
@rohitstatic Try with latest codebase and if still and issue then reopen. You'll need to follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137
