### ISSUE TITLE
Unable to fetch project/repo content from Gitlab

### ISSUE THREAD

**Issue by vishnuvangala** [capitalone/Hygieia#1026]
Can someone help me why am I unable to pull the projects data from gitlab. From the exception I can clearly notice that it is trying to hit "https" instead of "http". I have given "gitlab.protocol=http" in my application.properties file of gitlab. Not sure what is wrong with my configuration.. could some one help me here. When I access the same url with "http" I can see some data there..

GitLab Console:
-------------------------------
```
2016-12-09 18:08:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2016-12-09 18:08:00,013 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-12-09 18:08:00,013 INFO  c.c.d.collector.CollectorTask - Starting...
2016-12-09 18:08:00,014 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-12-09 18:08:00,347 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "**https://192.168.XXX.XXX/api/v3/projects/gitlab1%2FMyProject/repository/commits/?ref_name=master&since=2016-12-09T17:58:00Z&per_page=100":Connect to 192.168.XXX.XXX:443 [/192.168.XXX.XXX] failed: Connection refused (Connection refused); nested exception is org.apache.http.conn.HttpHostConnectException: Connect to 192.168.XXX.XXX:443 [/192.168.XXX.XXX] failed: Connection refused (Connection refused)**
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient.makeRestCall(DefaultGitlabGitClient.java:92) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient.getCommits(DefaultGitlabGitClient.java:69) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collecteur.GitlabGitCollectorTask.collect(GitlabGitCollectorTask.java:98) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 192.168.XXX.XXX:443 [/192.168.XXX.XXX] failed: Connection refused (Connection refused)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:142) ~[httpclient-4.3.6.jar!/:4.3.6]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319) ~[httpclient-4.3.6.jar!/:4.3.6]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363) ~[httpclient-4.3.6.jar!/:4.3.6]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219) ~[httpclient-4.3.6.jar!/:4.3.6]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195) ~[httpclient-4.3.6.jar!/:4.3.6]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86) ~[httpclient-4.3.6.jar!/:4.3.6]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[httpclient-4.3.6.jar!/:4.3.6]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.3.6.jar!/:4.3.6]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.3.6.jar!/:4.3.6]
        at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:569) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 15 common frames omitted
```
application.properties file:
------------------------------
```properties
gitlab.key=c+Dp9KHNhVg7ZPS2PoMIL
logging.file=./logs/gitlab.log
gitlab.cron=0 0/1 * * * *
gitlab.host=192.168.XXX.XXX
gitlab.protocol=http
gitlab.port=80
gitlab.selfSignedCertificate=false
gitlab.apiToken=ffGxDmVUG_onXXXXYYY
gitlab.commitThresholdDays=15
```

**Comment by rob-miller-777** [comment]
I'm guessing you don't have the latest changes.  The port and protocol support was only merged into master 3 days ago.  Have you pulled the new code since then?

**Comment by vishnuvangala** [comment]
@rob-miller-777 
Looks like I pulled my code last week and started setup of HYGIEIA..  Are you sure no one has got this exception earlier? is this fixed in latest code? I still doubt.. But anyhow I will pull the code now and will have a test again now and update here.. 
Thanks,
Vishnu

**Comment by vishnuvangala** [comment]
Thanks @rob-miller-777 
GitLab collector worked after I pulled the latest code..  Looks like now I have similar kind of problem with JIRA collector. Can you help me with this please?

Closing this and opening a new ticket for JIRA.

**Comment by rob-miller-777** [comment]
No problem.  Unfortunately I can't provide the same support for Jira, I haven't worked with that one at all since we don't actually have Jira here.  Let me know if you have any other gitlab questions though.

**Comment by vishnuvangala** [comment]
Thanks @rob-miller-777 ,
    One quick question regarding git-lab is.. I dont see the widget getting updated automatically.. we are performing some commits on project and I have set the cron job property as 1min in my git-lab.properties file. But still I dont see them updated in widget.. Unless I click on edit and click on save.. then I'm able to see the updated results there.. any idea?

**Comment by rob-miller-777** [comment]
If you refresh the page, do you see the new data?  The dashboard and the collector are on different timers.  So even if the collector retrieves new data, you won't see it on the dashboard until the dashboard refreshes what it has by calling the UI.  If you don't see the data when you refresh the page, but you do see it when you update the configuration of the widget, my guess would be that you are running into a bug I found.  It seems like there is an issue with all widgets where if you have the same widget running for the same data on multiple dashboards, and one dashboard is either deleted, or removes that widget, it will disable that widget on all dashboards that widget is on.  So for example in Gitlab, if DashboardA and DashboardB both have an SCM widget looking at GitlabRepo1.  If DashboardB is either deleted, or changes that widget to look at GitlabRepo2, it will also disable it for DashboardA.
