### ISSUE TITLE
Jira Colloctor is retrieving nothing without Team plugin?

### ISSUE THREAD

**Issue by xpdable** [capitalone/Hygieia#1028]
See my comments at the end of #974 

After I moved to the latest version of Jira-Collector with a seems-to-be mandatory Team plugin, all new-added data in my jira is not retrieved into mongodb even I set some fake field in config file for the team.
My Jira does not have that plugin and no plan to install it.
However we'd like to use the new function of the stastics in Issue.
Could you help on this?

**Comment by MarkRx** [comment]
@pxk5958

**Comment by MarkRx** [comment]
PR #1030

**Comment by tabladrum** [comment]
We are encountering some issues while testing out this PR. More details to come @satishc1

**Comment by tabladrum** [comment]
We are encountering some issues while testing out this PR 1030. More details to come @satishc1

**Comment by satishc1** [comment]
@xpdable Functionality merged in https://github.com/capitalone/Hygieia/pull/1137 Use latest codebase and follow cleanup instructions provided in PR.

**Comment by xpdable** [comment]
@satishc1 @tabladrum @MarkRx  I've moved to latest codebase, Jira collector seems works with some exception.

> 2017-02-05 14:08:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2017-02-05 14:08:00,004 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-05 14:08:00,004 INFO  c.c.d.collector.CollectorTask - http://jirag.int.thomsonreuters.com/
2017-02-05 14:08:00,005 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-05 14:08:00,005 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2017-02-05 14:08:00,551 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: http://jirag.int.thomsonreuters.com/rest/tempo-teams/1/team
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_91]
	at java.net.URLConnection.getContent(Unknown Source) ~[na:1.8.0_91]
	at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJiraClient.java:196) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:57) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_91]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
2017-02-05 14:08:00,554 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2017-02-05 14:08:00,554 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2017-02-05 14:08:03,368 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1768
2017-02-05 14:08:05,213 INFO  c.c.d.collector.CollectorTask - Project Data         1768        4s
2017-02-05 14:08:05,214 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...


I infer the exception SHOULD be there as I have no team plugins. but is that BY DESIGN of un-handled exception ?

**Comment by satishc1** [comment]
@xpdable If you do not have tempo teams, please set the following to blank in your properties file.
feature.jiraTeamFieldName=
