### ISSUE TITLE
Unable to build/run JIRA collector

### ISSUE THREAD

**Issue by Mahendra1260** [capitalone/Hygieia#1033]
While running the JIRA collector, I am getting the below exception:
```
Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.UnsatisfiedDependencyException:
  Error creating bean with name 'defaultJiraClient' defined in URL 
  [jar:file:/apps/capitablOne/Hygieia/collectors/feature/jira/target/jira-feature-collector.jar!/com/capitalone/dashboard/client/DefaultJiraClient.class]:
    Unsatisfied dependency expressed through constructor argument with index 1 of type [com.capitalone.dashboard.util.FeatureWidgetQueries]: :
      **Error creating bean with name 'featureWidgetQueries' defined in URL** 
  [jar:file:/apps/capitablOne/Hygieia/collectors/feature/jira/target/jira-feature-collector.jar!/com/capitalone/dashboard/util/FeatureWidgetQueries.class]: 
    Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException:
      Failed to instantiate [com.capitalone.dashboard.util.FeatureWidgetQueries]:
        Constructor threw exception; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException:
          **Error creating bean with name 'featureWidgetQueries'** defined in URL 
  [jar:file:/apps/capitablOne/Hygieia/collectors/feature/jira/target/jira-feature-collector.jar!/com/capitalone/dashboard/util/FeatureWidgetQueries.class]:
    Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException:
      Failed to instantiate [com.capitalone.dashboard.util.FeatureWidgetQueries]:
        Constructor threw exception; nested exception is java.lang.NullPointerException_
```

Secondly, as per the properties file, I am not able to find my custom field. When I am trying **https://[your-jira-domain-name]/rest/api/2/issuetype/**

It is giving me some binary output.

 Please suggest

**Comment by MarkRx** [comment]
Are you building your own code? Is it the latest? Try a clean build from the root.

Is there more to the stack trace?

**Comment by Mahendra1260** [comment]
@MarkRx  Tried building the fresh code by pulling the latest code from git hub: Still the same exception: 

**Below it trace:**

_Starting Application v2.0.4-SNAPSHOT on no1010042176090.corp.adobe.com with PID 30686 (/apps/capitablOne/Hygieia/collectors/feature/jira/target/jira-feature-collector.jar started by root in /apps/capitablOne/Hygieia/collectors/feature/jira)
2016-12-14 04:52:18,483 DEBUG com.capitalone.dashboard.Application - Running with Spring Boot v1.2.5.RELEASE, Spring v4.1.7.RELEASE
2016-12-14 04:52:18,549 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7051269c: startup date [Wed Dec 14 04:52:18 UTC 2016]; root of context hierarchy
2016-12-14 04:52:20,565 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-12-14 04:52:20,633 INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
2016-12-14 04:52:21,029 WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultJiraClient' defined in URL [jar:file:/apps/capitablOne/Hygieia/collectors/feature/jira/target/jira-feature-collector.jar!/com/capitalone/dashboard/client/DefaultJiraClient.class]: Unsatisfied dependency expressed through constructor argument with index 1 of type [com.capitalone.dashboard.util.FeatureWidgetQueries]: : Error creating bean with name 'featureWidgetQueries' defined in URL [jar:file:/apps/capitablOne/Hygieia/collectors/feature/jira/target/jira-feature-collector.jar!/com/capitalone/dashboard/util/FeatureWidgetQueries.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.capitalone.dashboard.util.FeatureWidgetQueries]: Constructor threw exception; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'featureWidgetQueries' defined in URL [jar:file:/apps/capitablOne/Hygieia/collectors/feature/jira/target/jira-feature-collector.jar!/com/capitalone/dashboard/util/FeatureWidgetQueries.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.capitalone.dashboard.util.FeatureWidgetQueries]: Constructor threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1139) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1042) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at com.capitalone.dashboard.Application.main(Application.java:21) [jira-feature-collector.jar!/:2.0.4-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [jira-feature-collector.jar!/:2.0.4-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'featureWidgetQueries' defined in URL [jar:file:/apps/capitablOne/Hygieia/collectors/feature/jira/target/jira-feature-collector.jar!/com/capitalone/dashboard/util/FeatureWidgetQueries.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.capitalone.dashboard.util.FeatureWidgetQueries]: Constructor threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1139) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1042) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 23 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.capitalone.dashboard.util.FeatureWidgetQueries]: Constructor threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 36 common frames omitted
Caused by: java.lang.NullPointerException: null
        at java.io.File.<init>(File.java:277) ~[na:1.8.0_45]
        at org.stringtemplate.v4.STGroupDir.<init>(STGroupDir.java:53) ~[ST4-4.0.8.jar!/:4.0.8]
        at com.capitalone.dashboard.util.FeatureWidgetQueries.<init>(FeatureWidgetQueries.java:31) ~[jira-feature-collector.jar!/:2.0.4-SNAPSHOT]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 38 common frames omitted
2016-12-14 04:52:21,037 INFO  o.s.b.l.ClasspathLoggingApplicationListener - Application failed to start with classpath:_

**Comment by Mahendra1260** [comment]
@MarkRx  **Below is the content of my properties file:**

_dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.port=8081
version.number=1
logging.file=./logs/jira.log
feature.pageSize=100
feature.deltaStartDate=2016-11-01T00:00:00.000000
feature.masterStartDate=2016-11-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-11-01T00:00:00.000000
feature.cron=0 * * * * *
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
feature.sprintDays=60
feature.sprintEndPrior=7
feature.scheduledPriorMin=2
feature.jiraBaseUrl=https://<my-jira-host>/
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraProjectId=ENV
feature.jiraCredentials=<my-credential-token>
# OAuth is not fully implemented; please blank-out the OAuth values:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
#############################################################################
feature.jiraIssueTypeId=Story

#############################################################################
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10000

#############################################################################
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10002


# In Jira, your instance will have its own custom field created for "story points"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10003_

**Comment by MarkRx** [comment]
You are missing this property: 

> #In-built folder housing prepared REST queries (required)
> feature.queryFolder=jiraapi-queries

**Comment by Mahendra1260** [comment]
Thanks for finding out the missing property. Let me try build with this also..

Additionally, while trying to get customfield, I am getting some binary output instead of json output.

Like:
https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]

it gives some binary symbol output. Any reason why?

**Comment by Mahendra1260** [comment]
@MarkRx  i am able to build the collector after adding the missing property..

While collecting data, jira collector is throwing exception as below::


_2016-12-14 16:12:00,004 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-12-14 16:12:01,868 ERROR c.c.d.client.DefaultJiraClient - IOException
**java.io.FileNotFoundException: https://my-jira-host/rest/tempo-teams/1/team**
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_45]
        at java.net.URLConnection.getContent(URLConnection.java:739) ~[na:1.8.0_45]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:434) ~[na:1.8.0_45]
        at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJiraClient.java:192) ~[jira-feature-collector.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:61) [jira-feature-collector.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2016-12-14 16:12:06,369 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1153
2016-12-14 16:12:08,654 INFO  c.c.d.collector.CollectorTask - Team Data            1153        8s_

**Comment by Mahendra1260** [comment]
How do I find value for the below properties:

1.feature.jiraSprintDataFieldName=
2.feature.jiraEpicIdFieldName=

**Comment by MarkRx** [comment]
Your stack trace is issue #1028.

How to obtain those fields is documented here: https://github.com/capitalone/Hygieia/tree/master/collectors/feature/jira

**Comment by Mahendra1260** [comment]
Apologies for mentioning it again.

# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=

What does it mean by **[some-issue-name],** does it mean the issue id? or issue number?# 


https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=

how to find the customefield from the above url.

Suppose i have an issue whose number is TEAM-1234. How do I make the url to fetch the right data?

**Comment by Mahendra1260** [comment]
@MarkRx 
While JIRA collector integration, in my properties file I have mentioned the project ID for the project I want to analyse. While selecting the project in Dashboard UI, I can see all the project which are there on my JIRA instance. 
Why I am seeing all the project in the list even though I have given one ID in the properties file:?

**Comment by MarkRx** [comment]
There is no spot in the properties file to restrict to a specific project. The jira collector will gather all project names and provide them as a drop down.

**Comment by Mahendra1260** [comment]
Thanks @MarkRx  for the reply.
I noticed one property in the properties files as below
**_feature.jiraProjectId=MyProjectID_**

What is the significance of the above property ?

I am not having acces to the other Projects, even then also I am seeing data from such projects. Do you think its a matter on security concern?

**Comment by MarkRx** [comment]
There is no field called feature.jiraProjectID. I do not know where that came from.

Jira does not have a user role system. The jira collector will pick up whatever the user has access to that is defined in the jira collector properties. Creating such a system is no small task and I don't see it being done any time soon if at all.

**Comment by amitmawkin** [comment]
No activity , hence closing this issue. @Mahendra1260  if you feel you still have issues you can open a new one

**Comment by charan1011** [comment]
@Mahendra1260 Did you get answer to these questions? I have the same doubt.

....What does it mean by [some-issue-name], does it mean the issue id? or issue number?#....
