### ISSUE TITLE
Issue fetching data from jira

### ISSUE THREAD

**Issue by varundevopsid99** [capitalone/Hygieia#1059]
i have configured Hygieia to fetch data from jira but i keep on getting following error, please help:

2017-01-03 14:07:00,434 INFO  c.c.d.collector.CollectorTask - Team Data              11        0s
2017-01-03 14:07:00,595 INFO  c.c.d.collector.CollectorTask - Project Data           11        0s
2017-01-03 14:07:00,750 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
	at com.capitalone.dashboard.util.FeatureWidgetQueries.getStoryQuery(FeatureWidgetQueries.java:111) ~[classes/:na]
	at com.capitalone.dashboard.client.DefaultJiraClient.getIssues(DefaultJiraClient.java:94) ~[classes/:na]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:160) ~[classes/:na]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [classes/:na]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:1) [classes/:na]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [classes/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]

**Comment by varundevopsid99** [comment]
Issue fixed after updating application.properties file with following values:

feature.jiraIssueTypeNames=Story
feature.jiraStoryPointsFieldName=customfield_10002
