### ISSUE TITLE
Jenkins collector fetch jobs name but not further details fetch

### ISSUE THREAD

**Issue by anandsit** [capitalone/Hygieia#1069]
Hi Team,

Please help with the below error. I am getting this error when Jenkins collector (not plugin). Not sure what configuration is missing. 
```
2017-01-04 13:50:00,012 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-01-04 13:50:00,074 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:50:00,074 INFO  c.c.d.collector.CollectorTask - https://jenkins.xxxxxxxxxxxxxxxxx.net/
2017-01-04 13:50:00,074 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:50:01,299 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     1s
2017-01-04 13:50:01,302 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2017-01-04 13:50:01,309 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-01-04 13:50:01,309 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2017-01-04 13:50:01,309 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:50:01,309 INFO  c.c.d.collector.CollectorTask - 
2017-01-04 13:50:01,310 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:50:01,310 WARN  c.c.d.collector.DefaultHudsonClient - Credentials for the following url was not found. This could happen if the domain/subdomain/IP address in the build url returned by Jenkins and the Jenkins instance url in your Hygieia configuration do not match: "api/json?tree=jobs"
2017-01-04 13:50:01,310 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(Unknown Source) ~[na:1.8.0_111]
	at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:137) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:76) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:565) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:523) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:194) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:98) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]
2017-01-04 13:52:00,012 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-01-04 13:52:00,035 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:52:00,035 INFO  c.c.d.collector.CollectorTask - https://jenkins.xxxxxxxxxxxxxxxxx.net/
2017-01-04 13:52:00,035 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:52:01,121 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     1s
2017-01-04 13:52:01,125 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2017-01-04 13:52:01,131 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-01-04 13:52:01,131 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2017-01-04 13:52:01,131 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:52:01,132 INFO  c.c.d.collector.CollectorTask - 
2017-01-04 13:52:01,133 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:52:01,133 WARN  c.c.d.collector.DefaultHudsonClient - Credentials for the following url was not found. This could happen if the domain/subdomain/IP address in the build url returned by Jenkins and the Jenkins instance url in your Hygieia configuration do not match: "api/json?tree=jobs"
2017-01-04 13:52:01,134 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(Unknown Source) ~[na:1.8.0_111]
	at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:137) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:76) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:565) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:523) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:194) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:98) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]
2017-01-04 13:54:00,011 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-01-04 13:54:00,058 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:54:00,058 INFO  c.c.d.collector.CollectorTask - https://jenkinsxxxxxxxxxxxxx.net/
2017-01-04 13:54:00,058 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:54:00,888 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2017-01-04 13:54:00,891 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2017-01-04 13:54:01,219 ERROR c.c.d.collector.DefaultHudsonClient - Unknown error in getting build details. URL=https://jenkinsxxxxxxxxxxxxxxxxxxxx.net/job/Gateway-update-weights/19/
java.lang.NullPointerException: null
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getString(DefaultHudsonClient.java:432) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.addChangeSets(DefaultHudsonClient.java:297) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getBuildDetails(DefaultHudsonClient.java:250) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.addNewBuilds(HudsonCollectorTask.java:193) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:95) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]
```
Thanks
Anand

**Comment by anandsit** [comment]
Below is the first run, where it fetch the number of jobs details but nothing further

2017-01-04 13:32:00,012 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-01-04 13:32:00,049 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:32:00,050 INFO  c.c.d.collector.CollectorTask - https://jenkinsxxxxxxxxxxxxxxxxxxxx.net/
2017-01-04 13:32:00,050 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:32:03,718 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     3s
2017-01-04 13:32:03,894 INFO  c.c.d.collector.CollectorTask - New jobs              130        0s
2017-01-04 13:32:04,086 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-01-04 13:32:04,086 INFO  c.c.d.collector.CollectorTask - Finished                         4s
2017-01-04 13:32:04,086 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:32:04,086 INFO  c.c.d.collector.CollectorTask - 
2017-01-04 13:32:04,086 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-04 13:32:04,087 WARN  c.c.d.collector.DefaultHudsonClient - Credentials for the following url was not found. This could happen if the domain/subdomain/IP address in the build url returned by Jenkins and the Jenkins instance url in your Hygieia configuration do not match: "api/json?tree=jobs"
2017-01-04 13:32:04,096 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(Unknown Source) ~[na:1.8.0_111]
	at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:137) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:76) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:565) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:523) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:194) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:98) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]

**Comment by MarkRx** [comment]
> Credentials for the following url was not found. This could happen if the domain/subdomain/IP address in the build url returned by Jenkins and the Jenkins instance url in your Hygieia configuration do not match: "api/json?tree=jobs"

Please post your config

**Comment by anandsit** [comment]
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=192.168.99.100

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=

# Database Password - default is blank
dbpassword=

# Collector schedule (required)
jenkins.cron=0 0/2 * * * *

# The page size
jenkins.pageSize=1000

# Jenkins server (required) - Can provide multiple
jenkins.servers[0]=https://jenkins.xxxxxxxxxxxxxxx.net/

# If using username/token for api authentication
#   (required for Cloudbees Jenkins Ops Center) see sample
jenkins.servers[1]=

# Another option: If using same username/password Jenkins auth,
#   set username/apiKey to use HTTP Basic Auth (blank=no auth)
jenkins.usernames[0]=<my jenkins username>
jenkins.apiKeys[0]=20a31axxxxxxxxxxxxxecbe1e0

# Determines if build console log is collected - defaults to false
jenkins.saveLog=true
~
~

**Comment by anandsit** [comment]
@MarkRx  - Please find the above config

**Comment by tabladrum** [comment]
Please go to Manage Jenkins -> System Config and verify that the Jenkins URL set in there and is correct.

**Comment by anandsit** [comment]
Thanks!! im travelling and will be able to test only on coming Monday.  If required, please close the ticket. Thanks for the help

**Comment by anandsit** [comment]
I verified the URL was configured. Still getting the same error. Can you please help

**Comment by RayanZahab** [comment]
> Please go to Manage Jenkins -> System Config and verify that the Jenkins URL set in there and is correct.

YOU JUST SAVED me ! 👍 after 2 wasted days!!!
