### ISSUE TITLE
Exception in API and UI layer

### ISSUE THREAD

**Issue by Mahendra1260** [capitalone/Hygieia#1079]
@tabladrum 
Hi Topo,
Recently I updated the code and built the packages. Started the dashboard as per below step.

1. Started api layer using java jar command
2. Started UI layer using gulp command.

Below is the exception on api log:
```
2017-01-10 08:46:04,354 ERROR c.c.d.rest.RestApiExceptionHandler - null
java.lang.NullPointerException: null
        at com.capitalone.dashboard.service.ServiceServiceImpl.refreshService(ServiceServiceImpl.java:109) ~[api.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.rest.ServiceController.refreshService(ServiceController.java:78) ~[api.jar!/:2.0.5-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor168.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) [spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) [spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) [spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at com.capitalone.dashboard.config.LoggingFilter.doFilter(LoggingFilter.java:111) [api.jar!/:2.0.5-SNAPSHOT]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85) [spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```
Similarly UI log as below:
```
[**08:44:32] Starting 'build'...
[08:44:32] Starting 'clean'...
[08:44:32] Finished 'clean' after 85 ms
[08:44:32] Starting 'assets'...
[08:44:32] Starting 'themes'...
[08:44:32] Starting 'fonts'...
[08:44:32] Starting 'js'...
[08:44:32] Starting 'views'...
[08:44:32] Starting 'test-data'...
[08:44:47] Finished 'assets' after 15 s
[08:44:47] Finished 'themes' after 15 s
[08:44:48] Finished 'test-data' after 15 s
[08:44:48] Finished 'views' after 15 s
[08:44:48] Finished 'js' after 15 s
[08:44:48] Finished 'fonts' after 16 s
[08:44:48] Starting 'html'...
[08:44:49] gulp-inject 1 files into index.html.
[08:44:49] gulp-inject 100 files into index.html.
[08:44:49] Finished 'html' after 402 ms
[08:44:49] Finished 'build' after 16 s
[08:44:49] Starting 'serve'...
[08:44:49] Finished 'serve' after 518 ms
[BS] Local URL: http://localhost:3000
[BS] External URL: http://myIPAddress:3000
[BS] Serving files from: dist/
[Proxy] { [Error: socket hang up] code: 'ECONNRESET' }
[Proxy] { [Error: socket hang up] code: 'ECONNRESET' }
[Proxy] { [Error: socket hang up] code: 'ECONNRESET' }
[Proxy] { [Error: socket hang up] code: 'ECONNRESET' }
```

**Comment by Mahendra1260** [comment]
closing as its duplicate
https://github.com/capitalone/Hygieia/issues/1032

**Comment by Mahendra1260** [comment]
Reopening as its a different exception

@MarkRx

**Comment by MarkRx** [comment]
You have a monitoring widget referencing a service that cannot be found in your database

**Comment by Mahendra1260** [comment]
@MarkRx 
I added a service which was failing, later removed the same service, still the same error.
Any idea, how do I add the same in my database

**Comment by Mahendra1260** [comment]
Issue resolved after I deleted the service from monitoring widget.
Closing the issue
