### ISSUE TITLE
Stash collector does not write any logs 

### ISSUE THREAD

**Issue by anandsit** [capitalone/Hygieia#1086]
Hi Team,

Initially, the stash collector was running every 5 min and throwing "401 unauthorized error". I added the secret key into my API container and stash collector. After that, when i restarted all the processes, the stash collector starts up successfully but fails to collect any data from stash (private repo) and fails to write any log as well. 
```
2017-01-11 19:08:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2017-01-11 19:08:00,010 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-11 19:08:00,010 INFO  c.c.d.collector.CollectorTask - Starting...
2017-01-11 19:08:00,010 INFO  c.c.d.collector.CollectorTask - -----------------------------------
```

**Comment by anandsit** [comment]
After 10min, it gave this error

2017-01-11 19:08:00,010 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-11 19:19:43,006 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https://stash.jcpenney.com/rest/api/1.0/projects/ECOMM/repos/platform/commits?until=master&limit=25&start=2875
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://stash.jcpenney.com/rest/api/1.0/projects/ECOMM/repos/platform/commits?until=master&limit=25&start=2875":Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:227) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:88) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:132) [bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.

**Comment by MarkRx** [comment]
Are you able to hit that url in a browser?

**Comment by anandsit** [comment]
It works now!! looks like it took more than 15min to collect data

**Comment by satishc1** [comment]
@anandsit Closed.
