### ISSUE TITLE
SonarQube collector appends junk URL and collection fails

### ISSUE THREAD

**Issue by anandsit** [capitalone/Hygieia#1089]
Hi Team,

I see that the sonarqube collector is adding junk URL and collector fails to collect information. 
```
2017-01-12 18:25:00,050 INFO  c.c.d.collector.CollectorTask - http://sonar.company.comhttp://maven.xxxxxxxxxxxxxxxxxx.net:9000/sonar
2017-01-12 18:25:00,050 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-12 18:25:00,096 ERROR c.c.d.collector.DefaultSonarClient - org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://sonar.company.comhttp/maven.xxxxxxxxxxxxxxxxxx.net:9000/sonar/api/resources?format=json":sonar.company.comhttp; nested exception is java.net.UnknownHostException: sonar.company.comhttp
2017-01-12 18:25:00,097 INFO  c.c.d.collector.CollectorTask - Fetched projects   0             0s
2017-01-12 18:25:00,097 INFO  c.c.d.collector.CollectorTask - New projects            0        0s
2017-01-12 18:25:00,102 INFO  c.c.d.collector.CollectorTask - Updated                 0        0s
2017-01-12 18:25:00,102 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-01-12 18:30:00,028 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2017-01-12 18:30:00,029 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2017-01-12 18:30:00,037 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at java.util.ArrayList.addAll(Unknown Source) ~[na:1.8.0_111]
	at com.capitalone.dashboard.model.SonarCollector.prototype(SonarCollector.java:19) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.SonarCollectorTask.getCollector(SonarCollectorTask.java:57) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.SonarCollectorTask.getCollector(SonarCollectorTask.java:26) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:52) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]
2017-01-12 18:30:00,046 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-12 18:30:00,049 INFO  c.c.d.collector.CollectorTask - http://sonar.company.comhttp://maven.xxxxxxxxxxxxxxxxxx.net:9000/sonar
2017-01-12 18:30:00,049 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-12 18:30:00,088 ERROR c.c.d.collector.DefaultSonarClient - org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://sonar.company.comhttp/maven.xxxxxxxxxxxxxxxxxx.net:9000/sonar/api/resources?format=json":sonar.company.comhttp; nested exception is java.net.UnknownHostException: sonar.company.comhttp
2017-01-12 18:30:00,089 INFO  c.c.d.collector.CollectorTask - Fetched projects   0             0s
2017-01-12 18:30:00,089 INFO  c.c.d.collector.CollectorTask - New projects            0        0s
2017-01-12 18:30:00,092 INFO  c.c.d.collector.CollectorTask - Updated                 0        0s
2017-01-12 18:30:00,092 INFO  c.c.d.collector.CollectorTask - Finished                         0s
```

**Comment by anandsit** [comment]
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=192.168.99.100

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=

# Database Password - default is blank
dbpassword=

# Collector schedule (required)
sonar.cron=0 0/5 * * * *

# Sonar server(s) (required) - Can provide multiple
isonar.servers[0]=http://maven.xxxxxxxxxxxxxxxxxx:9000/sonar

# Sonar Metrics
sonar.metrics=ncloc,line_coverage,violations,critical_violations,major_violation
s,blocker_violations,sqale_index,test_success_density,test_failures,test_errors,
tests

**Comment by anandsit** [comment]
Also, the collector was initially able to pull the project names but when the collector was restarted, it fails to fetch even the project name

**Comment by anandsit** [comment]
I think, i was running two collectors. Now i started freshly and get the below error

2017-01-12 19:00:00,031 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at java.util.ArrayList.addAll(Unknown Source) ~[na:1.8.0_111]
	at com.capitalone.dashboard.model.SonarCollector.prototype(SonarCollector.java:19) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.SonarCollectorTask.getCollector(SonarCollectorTask.java:57) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.SonarCollectorTask.getCollector(SonarCollectorTask.java:26) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:52) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]

**Comment by anandsit** [comment]
Now resolved.

**Comment by sidatgithub** [comment]
How did this solved? I have the same issue
