### ISSUE TITLE
Need info on jenkins collector configuration.

### ISSUE THREAD

**Issue by shilpsl1** [capitalone/Hygieia#1098]
Hi,
**I am facing below error, Please help if any solution**

Jenkins does not have any credentials. Below is the application.properties content,
```properties
dbname=dashboard
dbusername=dashboarduser
dbpassword=dashpassword
dbhost=10.0.0.0
dbport=27017
logging.file=./logs/jenkins.log
jenkins.cron=0 0/5 * * * *
jenkins.servers[0]=http://10.0.0.0:8000/jenkins
```

I tried URL using curl command, it is connecting...
```
# curl -v http://10.0.0.0:8000/jenkins
* About to connect() to 10.0.0.0 port 8000 (#0)
*   Trying 10.0.0.0... connected
* Connected to 10.0.0.0 (10.0.0.0) port 8000 (#0)
```
I also tried using http://10.0.0.0:8000 it gives 404 error.
```
2017-01-17 15:45:29,900 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2017-01-17 15:45:29,919 INFO  com.capitalone.dashboard.Application - Started Application in 8.462 seconds (JVM running for 9.948)
2017-01-17 15:50:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-01-17 15:50:00,062 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-17 15:50:00,067 INFO  c.c.d.collector.CollectorTask - http://10.0.0.0:8000/jenkins
2017-01-17 15:50:00,068 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-17 15:50:00,152 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 403 Forbidden
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:461) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:98) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) [jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522) [na:1.8.0-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:277) [na:1.8.0-internal]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191) [na:1.8.0-internal]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [na:1.8.0-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153) [na:1.8.0-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [na:1.8.0-internal]
	at java.lang.Thread.run(Thread.java:785) [na:1.8.0-internal]
2017-01-17 15:50:00,158 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://10.0.0.0:8000/jenkins 0s
```

**Comment by evaldasou** [comment]
try to add username and API key for jenkins configuration.

**Comment by shilpsl1** [comment]
I have tried adding username and API key as well, same issue persists.

**Comment by MarkRx** [comment]
Are you running old code? Line 461 in DefaultHusonClient is a comment.

**Comment by shilpsl1** [comment]
I set jenkins Security to false. Now I am able to get the dashboard view.

**Comment by satishc1** [comment]
@shilpsl1 Closed. Reopen if still an issue.

**Comment by indrgun** [comment]
Setting Jenkins Security to false is not acceptable because it means anybody can do anything without any authentication configured.

**Comment by shilpsl1** [comment]
yes right!!! But somehow that user was blocked or not able to use it. By setting it to false, assigned new user it works.

**Comment by tabladrum** [comment]
By using the following format for the jenkins server, you should be able to config the collector to read (provided the user has read access):

``jenkins.servers[0]=https://user:apikey@jenkins-server.com``

**Comment by suppu07** [comment]
Hi ,

i have the similar kind of issue .. i have configured all fine but still i face 404 error

properties file:
#Database Name
    dbname=dashboarddb

    #Database HostName - default is localhost
    dbhost=localhost

    #Database Port - default is 27017
    dbport=27017

    #Database Username - default is blank
    dbusername=

    #Database Password - default is blank
    dbpassword=

    #Collector schedule (required)
    jenkins.cron=0 0/1 * * * *

    #Jenkins server (required) - Can provide multiple
    jenkins.servers[0]=http://*.*.*.*:8081/

    #If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
   # jenkins.servers[1]=http://supriya:a86b12a46a346**************@5*.***.***.**:8081

    #Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
    jenkins.username=supriya
    jenkins.apiKey=a86b12a46a346df1e********************

    #Determines if build console log is collected - defaults to false
    jenkins.saveLog=false


errro logs:
2017-07-11 07:31:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-07-11 07:31:00,021 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-07-11 07:31:00,021 INFO  c.c.d.collector.CollectorTask - http://*.*.*.*:8081/
2017-07-11 07:31:00,021 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-07-11 07:31:00,062 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 403 Forbidden
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:591) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:183) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:103) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]


after i did curl i got below details 

* Rebuilt URL to: http://*.*.*.*:8081/
*   Trying 5*.*.*.*:...
* Connected to 5*.*.*.*: (*.*.*.*:) port 8081 (#0)
> GET / HTTP/1.1
> Host: 5*.*.*.*::8081
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Date: Tue, 11 Jul 2017 07:34:11 GMT
< X-Content-Type-Options: nosniff
< Set-Cookie: JSESSIONID.25bca527=1rifcwp22x0r2ajgu6kq89mbh;Path=/;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Content-Type: text/html;charset=UTF-8
< X-Hudson: 1.395
< X-Jenkins: 2.60.1
< X-Jenkins-Session: 8294fef6
< X-You-Are-Authenticated-As: anonymous
< X-You-Are-In-Group-Disabled: JENKINS-39402: use -Dhudson.security.AccessDeniedException2.REPORT_GROUP_HEADERS=true or use /whoAmI to diagnose
< X-Required-Permission: hudson.model.Hudson.Read
< X-Permission-Implied-By: hudson.security.Permission.GenericRead
< X-Permission-Implied-By: hudson.model.Hudson.Administer
< Content-Length: 793
< Server: Jetty(9.2.z-SNAPSHOT)
<
<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2F'/><script>window.location.replace('/login?from=%2F');</script></head><body style='background-color:white; color:white;'>


can anyone help me what exactly missing.......................
