### ISSUE TITLE
Unable to resolve Jira exception

### ISSUE THREAD

**Issue by anandsit** [capitalone/Hygieia#1101]
Hi, please help in resolving the below error
```
2017-01-17 18:20:01,836 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: https://jira.xxxxxxx.com/rest/tempo-teams/1/team
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1834) ~[na:1.8.0_11]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439) ~[na:1.8.0_11]
        at java.net.URLConnection.getContent(URLConnection.java:739) ~[na:1.8.0_11]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:434) ~[na:1.8.0_11]
        at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJiraClient.java:192) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:61) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_11]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_11]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_11]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_11]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_11]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_11]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]
2017-01-17 18:20:05,536 INFO  c.c.d.collector.CollectorTask - Team Data             295        5s
2017-01-17 18:20:09,287 INFO  c.c.d.collector.CollectorTask - Project Data          295        3s
2017-01-17 18:20:16,030 INFO  c.c.d.collector.CollectorTask - Story Data              1        6s
2017-01-17 18:20:16,030 INFO  c.c.d.collector.CollectorTask - Finished                        16s
```
Also, help me in understanding how to configure Jira as currently with all permutation and combination, my dashboard always shows 0 TODO, 0 WIP and 0 DONE. But the database has data from jira

**Comment by MarkRx** [comment]
Will be fixed in #1030

**Comment by satishc1** [comment]
@anandsit Functionality merged in https://github.com/capitalone/Hygieia/pull/1137 Use latest codebase and follow cleanup instructions provided in PR.

If your dashboard shows 0 TODO, 0 WIP and 0 DONE, Functionality merged in https://github.com/capitalone/Hygieia/pull/1054 which adds the ability to display metrics based on the number of tickets instead of estimates.

**Comment by anandsit** [comment]
Thanks much!! will try today..
