### ISSUE TITLE
Jenkins Controller StackOverflow Exception

### ISSUE THREAD

**Issue by kavitha0624** [capitalone/Hygieia#1107]
Hi,

My jenkins widget works fine when I configure it with local jenkins. When I am using my company's jenkins, I am seeing the data but then I am seeing the stackoverflow exceptions in the console. Can anyone suggest me how to deal with it pls?

2017-01-19 16:29:00,155 INFO  c.c.d.collector.CollectorTask - https://jenkm1.company.com:8443/job/mid-org/
2017-01-19 16:29:00,155 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-01-19 16:32:10,756 INFO  c.c.d.collector.CollectorTask - Fetched jobs                   190s
2017-01-19 16:32:10,762 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2017-01-19 16:32:27,237 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.StackOverflowError: null
        at org.springframework.data.repository.util.ClassUtils.unwrapReflectionException(ClassUtils.java:158) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:477) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.sun.proxy.$Proxy42.save(Unknown Source) ~[na:na]
        at com.capitalone.dashboard.event.BuildEventListener.processBuild(BuildEventListener.java:121) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.event.BuildEventListener.onAfterSave(BuildEventListener.java:60) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:92) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:33) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.data.mongodb.core.MongoTemplate.maybeEmitEvent(MongoTemplate.java:1611) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.doSave(MongoTemplate.java:978) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.save(MongoTemplate.java:921) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.save(SimpleMongoRepository.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_20]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_20]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:475) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.sun.proxy.$Proxy42.save(Unknown Source) ~[na:na]
        at com.capitalone.dashboard.event.BuildEventListener.processBuild(BuildEventListener.java:121) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]

**Comment by tabladrum** [comment]
Someone else had reported the same issue here https://github.com/capitalone/Hygieia/issues/1078#issuecomment-273886066

But could not reproduce. Seems some spring "feature" but would like to take a closer look. Can we reproduce? Also, will you be able to show us using screen share on google hangout?

**Comment by satishc1** [comment]
@kavitha0624 Rebuild and deploy with latest codebase. Make sure you rebuild all modules including  Api, collector(s) and UI and see if the issue persists.

**Comment by continuum-prateek-agarwal** [comment]
@tabladrum I am also facing the same issue while fetching the build details from jenkins collector. 

Can you please assist /let us know if this issue is solved.
