### ISSUE TITLE
NULL pointer Exceptions in API on starting UI

### ISSUE THREAD

**Issue by avadhmr** [capitalone/Hygieia#1108]
Everything was working fine untill we started getting exceptions all of a sudden.
Tried restarting API/UI multiple times and even re created DB but no luck.
Now on even starting UI, we get below exception :: 

2017-01-20 11:22:48,584 INFO  o.s.web.servlet.DispatcherServlet - FrameworkServl
et 'dispatcherServlet': initialization completed in 151 ms
2017-01-20 11:22:48,781 INFO  org.mongodb.driver.connection - Opened connection
[connectionId{localValue:6, serverValue:12}] to 127.0.0.1:27017
2017-01-20 11:22:52,338 ERROR c.c.d.rest.RestApiExceptionHandler - null
java.lang.NullPointerException: null
        at com.capitalone.dashboard.service.DashboardServiceImpl.get(DashboardSe
rviceImpl.java:66) ~[api-2.0.4.jar!/:2.0.4]
        at com.capitalone.dashboard.rest.DashboardController.getDashboard(Dashbo
ardController.java:60) ~[api-2.0.4.jar!/:2.0.4]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.
0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.
0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:
1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_111]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvok
e(InvocableHandlerMethod.java:221) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEAS
E]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeF
orRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.
7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocabl
eHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-
webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776) ~[spring
-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705) ~[spring-web
mvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapt
er.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.1.7.RELEASE.ja
r!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:959) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:893) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:967) [spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServl
et.java:858) [spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) [tomcat-
embed-core-8.0.23.jar!/:8.0.23]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:843) [spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-
embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:291) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52
) [tomcat-embed-websocket-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at com.capitalone.dashboard.config.LoggingFilter.doFilter(LoggingFilter.
java:111) [api-2.0.4.jar!/:2.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterIntern
al(CharacterEncodingFilter.java:85) [spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEAS
E]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107) [spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:219) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:106) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:502) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:142) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:79) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:88) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:518) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp
11Processor.java:1091) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(
AbstractProtocol.java:668) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1521) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoin
t.java:1478) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na
:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [n
a:1.8.0_111]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]

**Comment by avadhmr** [comment]
We are also facing the issue https://github.com/capitalone/Hygieia/issues/1032

**Comment by tabladrum** [comment]
Have you manually modified any data? Or are you running a brand new install?

**Comment by avadhmr** [comment]
I haven't done any manual modifications.
For #1032  I noticed it fails if your dashboard name has "." in it.....e.g.   Overdraft-services1.0 had issues...but not overdraft-services

**Comment by avadhmr** [comment]
I deleted db...restarted machine...created db...started api....and on starting UI...still got the exceptions.

**Comment by tabladrum** [comment]
Ok. For a quick check, can you clean your browser cache and see if anything changes.

**Comment by avadhmr** [comment]
cleaning cache didn't help. still getting same error on starting UI

**Comment by avadhmr** [comment]
Everything else seems to be running fine...apart from getting that exception at startup.....not sure if it is going to have some after effects at a later stage.

Is there anything we can do regarding dashboard names for #1032

**Comment by tabladrum** [comment]
Also noticed that your API version is 2.0.4 which is quite old. But that shouldn't cause an issue unless you have the latest UI

**Comment by avadhmr** [comment]
yes..we were earlier using old UI...but now we have switched to latest one from master.

**Comment by tabladrum** [comment]
The cause of the null pointer is this: API call is made to retrieve a dashboard, but the dashboard is not there in the "dashboard" collection in Mongo. If you have removed the data from Mongo, I am thinking (a) there is some other browser instance still trying to pull up an old dashboard or (2) Your browser has the URL in the history and you are using that as a bookmark and that creates the error. 

Other than those, I cant think of anything else. Would like to see it in a screen share if possible.

**Comment by tabladrum** [comment]
Having said that, the API should return a 404 in this case.

**Comment by avadhmr** [comment]
Well....all seems to be working nice today..I am not getting any error on starting UI and no exceptions are observed.

However, as I pointed out earlier For #1032  there are errors if your dashboard name has "." in it.....e.g. Overdraft-services1.0 had issues...but not overdraft-services.

**Comment by avadhmr** [comment]
I am closing this, as the underline issue is not occurring anymore. Thanks for all the support.
