### ISSUE TITLE
Issues with Jira collector

### ISSUE THREAD

**Issue by avadhmr** [capitalone/Hygieia#1114]
Getting Below exceptions::

2017-01-23 12:20:00,004 INFO  c.c.d.collector.CollectorTask - Running Collector:
 Jira
2017-01-23 12:20:00,005 INFO  c.c.d.collector.CollectorTask - ------------------
-----------------
2017-01-23 12:20:00,005 INFO  c.c.d.collector.CollectorTask - ***********************
2017-01-23 12:20:00,005 INFO  c.c.d.collector.CollectorTask - ------------------
-----------------
2017-01-23 12:20:00,627 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: https://jira.*************/rest/tempo-teams/
1/team
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown S
ource) ~[na:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown So
urce) ~[na:1.8.0_111]
        at java.net.URLConnection.getContent(Unknown Source) ~[na:1.8.0_111]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(Unknown
Source) ~[na:1.8.0_111]
        at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJir
aClient.java:192) ~[jira-feature-collector-2.0.4.jar!/:2.0.4]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInf
ormation(TeamDataClientImpl.java:61) [jira-feature-collector-2.0.4.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(Featu
reCollectorTask.java:107) [jira-feature-collector-2.0.4.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(Featu
reCollectorTask.java:28) [jira-feature-collector-2.0.4.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.ja
va:63) [core-2.0.4.jar!/:2.0.4]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnabl
e.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar
!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(Re
schedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$201(Unknown Source) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na
:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [n
a:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]
2017-01-23 12:20:01,234 INFO  c.c.d.collector.CollectorTask - Team Data
     77        1s
2017-01-23 12:20:01,782 INFO  c.c.d.collector.CollectorTask - Project Data
     77        0s
2017-01-23 12:20:05,549 ERROR c.c.d.collector.FeatureCollectorTask - Failed to c
ollect jira information
java.lang.NumberFormatException: For input string: "BBW-154"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[na:1.
8.0_111]
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[na:1.8.0_111]
        at java.lang.Double.parseDouble(Unknown Source) ~[na:1.8.0_111]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.processFeat
ureData(StoryDataClientImpl.java:315) ~[jira-feature-collector-2.0.4.jar!/:2.0.4
]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateMongo
Info(StoryDataClientImpl.java:236) ~[jira-feature-collector-2.0.4.jar!/:2.0.4]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStory
Information(StoryDataClientImpl.java:166) ~[jira-feature-collector-2.0.4.jar!/:2
.0.4]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(Featu
reCollectorTask.java:119) [jira-feature-collector-2.0.4.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(Featu
reCollectorTask.java:28) [jira-feature-collector-2.0.4.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.ja
va:63) [core-2.0.4.jar!/:2.0.4]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnabl
e.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar
!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(Re
schedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$201(Unknown Source) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na
:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [n
a:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]

Properties file ::

# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=http://proxy.com
#feature.jiraProxyPort=9000
feature.jiraBaseUrl=https://jira.*******************
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
feature.jiraCredentials=**********************
# OAuth is not fully implemented; please blank-out the OAuth values:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

feature.jiraIssueTypeNames=Story

#feature.jiraSprintDataFieldName=customfield_10000

feature.jiraEpicIdFieldName=customfield_10000

feature.jiraStoryPointsFieldName=customfield_10001

#feature.jiraTeamFieldName=customfield_10703

**Comment by xpdable** [comment]
I think you are meeting #1030

**Comment by avadhmr** [comment]
Ok I understand #1030 might be the cause of ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: https://jira.*************/rest/tempo-teams/
1/team


but what about ERROR c.c.d.collector.FeatureCollectorTask - Failed to c
ollect jira information
java.lang.NumberFormatException: For input string: "BBW-154"
at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[na:1.
8.0_111]

**Comment by tabladrum** [comment]
Its' trying to convert a string to double for the story points. But the string is not numeric. I think your mapping ``feature.jiraStoryPointsFieldName=customfield_10001`` is incorrect. If you are not using story points, I would comment out that line.

**Comment by avadhmr** [comment]
I commented out that line but getting a different error now 
2017-01-25 10:52:07,847 ERROR c.c.d.client.DefaultJiraClient - No result was ava
ilable from Jira unexpectedly - defaulting to blank response. The reason for thi
s fault is the following:RestClientException{statusCode=Optional.of(400), errorC
ollections=[ErrorCollection{status=400, errors={}, errorMessages=[Error in the J
QL Query: Expecting operator before the end of the query. The valid operators ar
e '=', '!=', '<', '>', '<=', '>=', '~', '!~', 'IN', 'NOT IN', 'IS' and 'IS NOT'.
]}]}

**Comment by tabladrum** [comment]
Do you know which custom field is your JIRA using?

**Comment by avadhmr** [comment]
I have below ones set in the properties file  based on the info got from hitting the rest api

feature.jiraSprintDataFieldName=customfield_10005

feature.jiraEpicIdFieldName=customfield_10000

**Comment by tabladrum** [comment]
How about feature.jiraStoryPointsFieldName

**Comment by avadhmr** [comment]
As per your inputs above, I commented out that line.

Strangely I can't find "story points" section when I hit the rest api for an issue

**Comment by tabladrum** [comment]
Ok. So, the collector will log some error but you can ignore it for now. It still will collect things.

**Comment by avadhmr** [comment]
Yes..I get the output 

2017-01-25 11:30:02,357 INFO  c.c.d.collector.CollectorTask - Team Data      78        2s
2017-01-25 11:30:03,533 INFO  c.c.d.collector.CollectorTask - Project Data     78        1s
2017-01-25 11:30:05,543 INFO  c.c.d.collector.CollectorTask - Story Data      1        2s
2017-01-25 11:30:05,544 INFO  c.c.d.collector.CollectorTask - Finished              5s

But nothing visible o UI..is it because of #1030 ?

**Comment by tabladrum** [comment]
Yes. Should be done in couple of days.

**Comment by avadhmr** [comment]
Cool...Thanks for all the support :+1:

**Comment by avadhmr** [comment]
Closing this as underlying issue is duplicate of #1030

**Comment by MarkRx** [comment]
correction: having data show up when not using estimates will be added in #1054
