### ISSUE TITLE
Unable to start api with the latest hygieia code

### ISSUE THREAD

**Issue by rohanb3** [capitalone/Hygieia#1130]
Hi,

Have cloned the repo today - 28-Jan-2017. Was able to compile it successfully.
Am also able to start the collectors and do gulp serve successfully. But when trying to start the api am getting the below error. Not sure if have missed anything:

api.properties file is as below:
# dashboard.properties
dbname=dashboarddb
dbusername=admin
dbpassword=admin123
dbhost=localhost
dbport=27017
#dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=localhost:27017
#server.contextPath=[Web Context path if any]
server.port=8080
#version.number=@application.version.number@
key=x+PIzci6AWiPZP7HMjvySiATg2Kwv87c

Command and Error Log:
=================

C:\Devops\Hygieia\api\target>java -jar api.jar --spring.config.location=dashboard.properties -Djasypt.encryptor.password=hygieiasecret

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.2.5.RELEASE)

2017-01-28 21:04:15,797 INFO  com.capitalone.dashboard.Application - Starting Application v2.0.5-SNAPSHOT on Lenovo-PC with PID 6316 (C:\Devops\Hygieia\api\target\api.jar started by Rohan in C:\Devops\Hygieia\api\target)
2017-01-28 21:04:15,952 INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7e87f06e: startup date [Sat Jan 28 21:04:15 IST 2017]; root of context hierarchy
2017-01-28 21:04:20,531 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Post-processing PropertySource instances
2017-01-28 21:04:20,614 INFO  c.u.j.c.StringEncryptorConfiguration - String Encryptor custom Bean not found with name 'jasyptStringEncryptor'. Initializing String Encryptor based on properties with name 'jasyptStringEncryptor'
2017-01-28 21:04:20,694 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2017-01-28 21:04:20,718 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource servletConfigInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2017-01-28 21:04:20,751 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource servletContextInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2017-01-28 21:04:20,782 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2017-01-28 21:04:20,814 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemEnvironment [org.springframework.core.env.SystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
2017-01-28 21:04:20,840 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource random [org.springframework.boot.context.config.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2017-01-28 21:04:20,871 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource applicationConfig: [classpath:/application.properties] [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2017-01-28 21:04:20,905 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource class path resource [version.properties] [org.springframework.core.io.support.ResourcePropertySource] to EncryptableMapPropertySourceWrapper
2017-01-28 21:04:20,955 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-01-28 21:04:21,150 INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
2017-01-28 21:04:21,716 WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.autoconfigure.web.ServerProperties org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration.properties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties': Could not bind properties to [unknown] (target=server, ignoreInvalidFields=false, ignoreUnknownFields=false, ignoreNestedProperties=false); nested exception is java.lang.IllegalStateException: Required Encryption configuration property missing: jasypt.encryptor.password
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at com.capitalone.dashboard.Application.main(Application.java:45) [api.jar!/:2.0.5-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_111]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [api.jar!/:2.0.5-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.autoconfigure.web.ServerProperties org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration.properties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties': Could not bind properties to [unknown] (target=server, ignoreInvalidFields=false, ignoreUnknownFields=false, ignoreNestedProperties=false); nested exception is java.lang.IllegalStateException: Required Encryption configuration property missing: jasypt.encryptor.password
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:193) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:156) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        ... 12 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.autoconfigure.web.ServerProperties org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration.properties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties': Could not bind properties to [unknown] (target=server, ignoreInvalidFields=false, ignoreUnknownFields=false, ignoreNestedProperties=false); nested exception is java.lang.IllegalStateException: Required Encryption configuration property missing: jasypt.encryptor.password
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1210) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:523) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1060) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.getCustomizers(EmbeddedServletContainerCustomizerBeanPostProcessor.java:74) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.postProcessBeforeInitialization(EmbeddedServletContainerCustomizerBeanPostProcessor.java:66) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.postProcessBeforeInitialization(EmbeddedServletContainerCustomizerBeanPostProcessor.java:54) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 20 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.autoconfigure.web.ServerProperties org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration.properties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties': Could not bind properties to [unknown] (target=server, ignoreInvalidFields=false, ignoreUnknownFields=false, ignoreNestedProperties=false); nested exception is java.lang.IllegalStateException: Required Encryption configuration property missing: jasypt.encryptor.password
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 35 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties': Could not bind properties to [unknown] (target=server, ignoreInvalidFields=false, ignoreUnknownFields=false, ignoreNestedProperties=false); nested exception is java.lang.IllegalStateException: Required Encryption configuration property missing: jasypt.encryptor.password
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:303) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:250) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 37 common frames omitted
Caused by: java.lang.IllegalStateException: Required Encryption configuration property missing: jasypt.encryptor.password
        at com.ulisesbocchio.jasyptspringboot.configuration.StringEncryptorConfiguration.getRequiredProperty(StringEncryptorConfiguration.java:80) ~[jasypt-spring-boot-1.9.jar!/:na]
        at com.ulisesbocchio.jasyptspringboot.configuration.StringEncryptorConfiguration.lambda$static$0(StringEncryptorConfiguration.java:41) ~[jasypt-spring-boot-1.9.jar!/:na]
        at com.ulisesbocchio.jasyptspringboot.encryptor.LazyStringEncryptor$SingletonFunction.lambda$new$1(LazyStringEncryptor.java:50) ~[jasypt-spring-boot-1.9.jar!/:na]
        at com.ulisesbocchio.jasyptspringboot.encryptor.LazyStringEncryptor$SingletonFunction.apply(LazyStringEncryptor.java:63) ~[jasypt-spring-boot-1.9.jar!/:na]
        at com.ulisesbocchio.jasyptspringboot.encryptor.LazyStringEncryptor.decrypt(LazyStringEncryptor.java:32) ~[jasypt-spring-boot-1.9.jar!/:na]
        at org.jasypt.properties.PropertyValueEncryptionUtils.decrypt(PropertyValueEncryptionUtils.java:72) ~[jasypt-1.9.2.jar!/:na]
        at com.ulisesbocchio.jasyptspringboot.EncryptablePropertySource.getProperty(EncryptablePropertySource.java:19) ~[jasypt-spring-boot-1.9.jar!/:na]
        at com.ulisesbocchio.jasyptspringboot.wrapper.EncryptableMapPropertySourceWrapper.getProperty(EncryptableMapPropertySourceWrapper.java:28) ~[jasypt-spring-boot-1.9.jar!/:na]
        at org.springframework.boot.bind.PropertySourcesPropertyValues.getEnumerableProperty(PropertySourcesPropertyValues.java:140) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.bind.PropertySourcesPropertyValues.processEnumerablePropertySource(PropertySourcesPropertyValues.java:124) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.bind.PropertySourcesPropertyValues.processPropertySource(PropertySourcesPropertyValues.java:106) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.bind.PropertySourcesPropertyValues.<init>(PropertySourcesPropertyValues.java:94) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.bind.PropertiesConfigurationFactory.getPropertyValues(PropertiesConfigurationFactory.java:281) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:252) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:227) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:296) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        ... 50 common frames omitted
2017-01-28 21:04:23,206 INFO  o.s.b.l.ClasspathLoggingApplicationListener - Application failed to start with classpath: [jar:file:/C:/Devops/Hygieia/api/target/api.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/core-2.0.5-SNAPSHOT.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-boot-1.2.5.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-context-4.1.7.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/commons-codec-1.9.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-test-4.1.7.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-data-mongodb-1.8.0.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-tx-4.1.7.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-beans-4.1.7.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-expression-4.1.7.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-data-commons-1.11.0.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/mongo-java-driver-3.0.2.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jcl-over-slf4j-1.7.12.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/querydsl-jpa-3.6.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/querydsl-core-3.6.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jsr305-1.3.9.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/mysema-commons-lang-0.2.4.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/bridge-method-annotation-1.13.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/querydsl-apt-3.6.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/querydsl-codegen-3.6.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/codegen-0.6.5.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/ecj-4.3.1.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/javax.inject-1.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/querydsl-mongodb-3.6.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/json-simple-1.1.1.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jasypt-spring-boot-starter-1.9.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jasypt-spring-boot-1.9.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jasypt-1.9.2.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-boot-starter-web-1.2.5.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-boot-starter-1.2.5.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-boot-autoconfigure-1.2.5.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-boot-starter-logging-1.2.5.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jul-to-slf4j-1.7.12.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/log4j-over-slf4j-1.7.12.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/snakeyaml-1.14.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-boot-starter-tomcat-1.2.5.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/tomcat-embed-core-8.0.23.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/tomcat-embed-el-8.0.23.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/tomcat-embed-logging-juli-8.0.23.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/tomcat-embed-websocket-8.0.23.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-core-4.1.7.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-web-4.1.7.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-aop-4.1.7.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/aopalliance-1.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-webmvc-4.1.7.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/validation-api-1.1.0.Final.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/hibernate-validator-5.1.3.Final.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jboss-logging-3.1.3.GA.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/javax.el-api-3.0.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jackson-databind-2.5.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jackson-annotations-2.5.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jackson-core-2.5.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jackson-core-asl-1.9.13.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/jackson-mapper-asl-1.9.13.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/logback-classic-1.1.3.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/logback-core-1.1.3.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/slf4j-api-1.7.12.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/commons-lang-2.6.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/guava-16.0.1.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/joda-time-2.7.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/springfox-swagger2-2.4.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/swagger-annotations-1.5.6.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/swagger-models-1.5.6.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/springfox-spi-2.4.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/springfox-core-2.4.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/springfox-schema-2.4.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/springfox-swagger-common-2.4.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/springfox-spring-web-2.4.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-plugin-core-1.1.0.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/spring-plugin-metadata-1.2.0.RELEASE.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/springfox-swagger-ui-2.4.0.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/classmate-1.3.1.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/joda-convert-1.8.1.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/commons-io-2.1.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/commons-beanutils-1.9.2.jar!/, jar:file:/C:/Devops/Hygieia/api/target/api.jar!/lib/commons-collections-3.2.1.jar!/]

Thanks,
Rohan

**Comment by rohanb3** [comment]
Just using --spring.config.location in the command resolved the issue.

Thanks.

**Comment by thashi** [comment]
@rohanb3 Can you please help to figure out the issue (Same as yours, [ticket](https://github.com/capitalone/Hygieia/issues/1190))?

My **application.properties** as follows. (I didn't change anything whatever checked out , as it is)

> dbname=dashboarddb
dbusername=dashboarduser
dbpassword=ENC(C9PLVDJ/1OfkT/3jvC/wEB20R1XPJtg9)
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080

Command i tried
`java -jar api.jar --spring.config.location=dashboard.properties-Djasypt.encryptor.password=hygieiasecret`
