### ISSUE TITLE
Hygie Dashboard API Layer: API connectivity issue 

### ISSUE THREAD

**Issue by Clement06** [capitalone/Hygieia#1151]
#255 Unable to connect with the API Layer in Hygieia Dashboard. Getting error as "WARN o.s.web.servlet.PageNotFound - Request method 'POST' not supported"

Command used and tried for API layer
java -jar api.jar --spring.config.name=api --spring.config.location=G:\NewLearning\Hygieia-master\api\dashboard.properties

In the UI , API connectivity is showing as red crossed
Please assit

**Comment by Clement06** [comment]
@tabladrum @amitmawkin : Could you please help me on this? thanks

**Comment by Clement06** [comment]
T' not supported
2017-02-04 12:38:06,724 WARN  o.s.web.servlet.PageNotFound - Request method 'POST' not supported
2017-02-04 12:39:02,004 WARN  o.s.web.servlet.PageNotFound - Request method 'POST' not supported
2017-02-04 12:39:07,767 WARN  o.s.web.servlet.PageNotFound - Request method 'POST' not supported
2017-02-04 12:39:13,627 WARN  o.s.web.servlet.PageNotFound - Request method 'POST' not supported
2017-02-04 12:39:51,148 WARN  o.s.web.servlet.PageNotFound - Request method 'POST' not supported


Dashboard.properties
dbname=dashboard
dbusername=dashboarduserClemo
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
dbreplicaset=false
server.contextPath=/api
server.port=8080
version.number=@application.version.number@

**Comment by satishc1** [comment]
@Clement06 Check to ensure you don't have any other process running on port 8080. Also use a tool like RoboMongo to connect to your database with the database username/password you have in the dashboard.properties file.

**Comment by Clement06** [comment]
Thanks Satish, I am able to connect that successfully. I am not able to find the target folder in the API folder  and also when I try to have mvn clean install on Hygieia Master , I am getting the below dependencies issue s
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd
 (pmd) on project Hygieia: Execution pmd of goal org.apache.maven.plugins:maven-
pmd-plugin:3.6:pmd failed: Plugin org.apache.maven.plugins:maven-pmd-plugin:3.6
or one of its dependencies could not be resolved: The following artifacts could
not be resolved: net.sourceforge.pmd:pmd-core:jar:5.3.5, com.beust:jcommander:ja
r:1.35, net.sourceforge.pmd:pmd-java:jar:5.3.5, net.sourceforge.pmd:pmd-javascri
pt:jar:5.3.5, net.sourceforge.pmd:pmd-jsp:jar:5.3.5: Failure to find net.sourcef
orge.pmd:pmd-core:jar:5.3.5 in http://nexus-repos.via.novonet:8585/nexus/content
/groups/public was cached in the local repository, resolution will not be reatte
mpted until the update interval of releases has elapsed or updates are forced ->

Please help me on this issue @satishc1 @tabladrum @amitmawkin

**Comment by satishc1** [comment]
@Clement06 Does the maven log have any connect or timeout errors ? Also try running mvn clean install from the Hygieia folder in a network not restricted by proxy.

**Comment by Clement06** [comment]
@satishc1 
Hi Sathish, thanks for your timely reply.

Today I tried connecting the API , its not working again. I by mistakenly gave mvn clean in api folder, so all my files haven been cleaned.
**Below are the logs, Please help me on this issue Sathish at the earliest,thanks**

@jdamick @davidroman

**Comment by Clement06** [comment]
2017-02-09 22:17:23,625 INFO  o.a.coyote.http11.Http11NioProtocol - Pausing ProtocolHandler ["http-nio-8080"]
2017-02-09 22:17:23,629 INFO  o.a.catalina.core.StandardService - Stopping service Tomcat
2017-02-09 22:17:23,643 WARN  o.a.c.loader.WebappClassLoaderBase - The web application [api] appears to have started a thread named [cluster-ClusterId{value='589cea641703310718376fa7', description='null'}-127.0.0.1:27017] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
 com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForSignalOrTimeout(DefaultServerMonitor.java:237)
 com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForNext(DefaultServerMonitor.java:218)
 com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:167)
 java.lang.Thread.run(Unknown Source)
2017-02-09 22:17:23,665 WARN  o.a.c.loader.WebappClassLoaderBase - The web application [api] appears to have started a thread named [pool-1-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
 java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
 java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 java.lang.Thread.run(Unknown Source)
2017-02-09 22:17:23,695 INFO  o.apache.catalina.util.LifecycleBase - The stop() method was called on component [StandardServer[-1]] after stop() had already been called. The second call will be ignored.
2017-02-09 22:17:23,700 INFO  o.a.coyote.http11.Http11NioProtocol - Stopping ProtocolHandler ["http-nio-8080"]
2017-02-09 22:17:23,703 INFO  o.a.coyote.http11.Http11NioProtocol - Destroying ProtocolHandler ["http-nio-8080"]
2017-02-09 22:17:23,709 INFO  o.s.b.l.ClasspathLoggingApplicationListener - Application failed to start with classpath: [jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/core-2.0.5-SNAPSHOT.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-boot-1.2.5.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-context-4.1.7.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/commons-codec-1.9.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-test-4.1.7.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-data-mongodb-1.8.0.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-tx-4.1.7.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-beans-4.1.7.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-expression-4.1.7.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-data-commons-1.11.0.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/mongo-java-driver-3.0.2.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/jcl-over-slf4j-1.7.12.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/querydsl-jpa-3.6.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/querydsl-core-3.6.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/jsr305-1.3.9.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/mysema-commons-lang-0.2.4.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/bridge-method-annotation-1.13.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/querydsl-apt-3.6.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/querydsl-codegen-3.6.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/codegen-0.6.5.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/ecj-4.3.1.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/javax.inject-1.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/querydsl-mongodb-3.6.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/json-simple-1.1.1.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-boot-starter-web-1.2.5.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-boot-starter-1.2.5.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-boot-autoconfigure-1.2.5.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-boot-starter-logging-1.2.5.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/jul-to-slf4j-1.7.12.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/log4j-over-slf4j-1.7.12.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/snakeyaml-1.14.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-boot-starter-tomcat-1.2.5.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/tomcat-embed-core-8.0.23.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/tomcat-embed-el-8.0.23.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/tomcat-embed-logging-juli-8.0.23.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/tomcat-embed-websocket-8.0.23.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-core-4.1.7.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-web-4.1.7.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-aop-4.1.7.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/aopalliance-1.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-webmvc-4.1.7.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/validation-api-1.1.0.Final.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/hibernate-validator-5.1.3.Final.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/jboss-logging-3.1.3.GA.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/javax.el-api-3.0.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/jackson-databind-2.5.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/jackson-annotations-2.5.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/jackson-core-2.5.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/jackson-core-asl-1.9.13.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/jackson-mapper-asl-1.9.13.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/logback-classic-1.1.3.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/logback-core-1.1.3.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/slf4j-api-1.7.12.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/commons-lang-2.6.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/guava-16.0.1.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/joda-time-2.7.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/springfox-swagger2-2.4.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/swagger-annotations-1.5.6.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/swagger-models-1.5.6.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/springfox-spi-2.4.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/springfox-core-2.4.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/springfox-schema-2.4.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/springfox-swagger-common-2.4.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/springfox-spring-web-2.4.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-plugin-core-1.1.0.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/spring-plugin-metadata-1.2.0.RELEASE.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/springfox-swagger-ui-2.4.0.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/classmate-1.3.1.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/joda-convert-1.8.1.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/commons-io-2.1.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/commons-beanutils-1.9.2.jar!/, jar:file:/G:/NewLearning/Hygieia-master/api/target/api.jar!/lib/commons-collections-3.2.1.jar!/]
2017-02-09 22:17:23,935 INFO  o.s.b.a.l.AutoConfigurationReportLoggingInitializer - 

Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)


2017-02-09 22:17:23,942 ERROR o.s.boot.SpringApplication - Application startup failed
java.lang.IllegalStateException: Tomcat connector in failed state
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:157) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) ~[spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at com.capitalone.dashboard.Application.main(Application.java:41) [api.jar!/:2.0.5-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_91]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [api.jar!/:2.0.5-SNAPSHOT]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
2017-02-09 22:17:24,018 INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@14e51ebe: startup date [Thu Feb 09 22:16:56 GMT 2017]; root of context hierarchy
2017-02-09 22:17:24,031 INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2017-02-09 22:17:24,050 INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'

**Comment by satishc1** [comment]
@Clement06 Was your build issue resolved ? Can you post your build log ?

**Comment by satishc1** [comment]
@Clement06 Closed. Reopen with build log if still an issue.
