### ISSUE TITLE
Null pointer exception in jira collector after connecting to Jira server

### ISSUE THREAD

**Issue by roshanvc** [capitalone/Hygieia#1154]
When the jira collector connects to my jira server. It throws null pointer exception twice. What could be the reason for the error. Please see the log below.
```
2017-02-07 10:53:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2017-02-07 10:53:00,007 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-07 10:53:00,009 INFO  c.c.d.collector.CollectorTask - http://10.147.66.158:8989/
2017-02-07 10:53:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-07 10:53:00,010 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2017-02-07 10:53:10,984 ERROR c.c.d.client.DefaultJiraClient - IOException
java.net.ProtocolException: Server redirected too many  times (20)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1884) ~[na:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_111]
        at java.net.URLConnection.getContent(URLConnection.java:739) ~[na:1.8.0_111]
        at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJiraClient.java:192) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:61) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2017-02-07 10:53:12,710 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 75
2017-02-07 10:53:13,132 INFO  c.c.d.collector.CollectorTask - Team Data              75       13s
2017-02-07 10:53:13,132 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2017-02-07 10:53:14,381 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 75
2017-02-07 10:53:14,719 INFO  c.c.d.collector.CollectorTask - Project Data           75        1s
2017-02-07 10:53:14,720 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2017-02-07 10:53:14,726 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
        at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:320) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:726) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:152) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

This is the property file which we have used
```
#PageSize
feature.pageSize=50

# api.query.folder=${base.config.dir}/jiraapi-queries
feature.queryFolder=jiraapi-queries
# Jira API Query file names (String template requires the files to have .st extension)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

#Jira Connection Details
#feature.jiraProxyUrl=
#feature.jiraProxyPort=
######################
# Trending Query need Number of Days After today to filter out Sprints which ends in future.
# This will used to filter Kanban project which has 20 years of Sprints
feature.sprintDays=60
# Trending Query also need Number of Days prior to look for Sprints which has already Ended
feature.sprintEndPrior=7
######################
#Scheduled Job prior minutes to recover data created during execution time
feature.scheduledPriorMin=2
#Delta change date that modulates the collector item task (which should not see changes often)
feature.deltaCollectorItemStartDate=20016-10-01T00:00:00.000000

######################
#Spring Application Properties
spring.data.mongodb.database=dashboarddb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=dashboarduser
spring.data.mongodb.password=dbpassword

#Jira Connection Details
feature.jiraBaseUrl=http://myjiraserver.com/
feature.jiraCredentials=UGFsYW5pdmVsbjpUdXR1QDA2Kg==
#feature.jiraOauthAuthtoken=oauth, not used
#feature.jiraOauthRefreshtoken=oauth, not used
#feature.jiraOauthRedirecturi=uri.this.is.test:uri
#feature.jiraOauthExpiretime=234567890987
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide the name value reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:
# https://[your-jira-domain-name]/rest/api/2/issuetype/.  It is listed as
# attribute "name" in the JSON response.
feature.jiraIssueTypeId=7
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name <em>com.atlassian.greenhopper.service.sprint.Sprint</em>;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10700
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10702

######################
#Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

#StartDate
feature.deltaStartDate=2017-01-30T00:00:00.000000
feature.masterStartDate=2016-10-01T00:00:00.000000

#Core Artifacts
# These arrays of status mappings must be completed in order for custom source system statuses to be providable by
# Hygieia.  Currently, Hygieia only maps to the following 3 status mappings:  to do, doing, and done.  You can find
# all available issue status mappings by going to your instance's version of the following API call:
# http://fake.jira.com/rest/api/2/status/.  Your statuses are listed in the JSON response as "name."
feature.todoStatuses[0]=OPEN
feature.doingStatuses[0]=IN PROGRESS
feature.doingStatuses[1]=TEST
feature.doingStatuses[2]=TESTING
feature.doneStatuses[0]=DONE
feature.doneStatuses[1]=CLOSED
```

**Comment by satishc1** [comment]
@roshanvc Try setting feature.pageSize to 25.
Also change feature.jiraIssueTypeId to feature.jiraIssueTypeNames and set its value accordingly.
Also add/set as blank feature.jiraTeamFieldName= 
to specify no tempo teams

**Comment by roshanvc** [comment]
@satishc1 : Tried to suggestions, still getting the same error :-(

**Comment by satishc1** [comment]
@roshanvc Does your jira setup have tempo teams ? Paste your command that you are using to start the jira collector.

**Comment by Sbrenthughes** [comment]
@roshanvc - Are you still facing this issue? If so, can you please paste the command you are using?

**Comment by Sbrenthughes** [comment]
@roshanvc I am closing this issue. If you are still facing problems please reopen.
