### ISSUE TITLE
Unable to add/save repository in UI

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1162]
[UI save err.docx](https://github.com/capitalone/Hygieia/files/766951/UI.save.err.docx)

Whenever I click save button in UI, its not responding any  , no error- not saving & closing as well.

Please help to resolve the issue.
I took latest Hygieia code today, from https://github.com/capitalone/Hygieia.git
------------------
Below are my config setup 
-------------------------
**generated Key is:**

Your secret key is:
ASxkmNlSfH+KPv4cbroNvIoCI4nlASn7
Sample encrypted string with the above key for 'thisIsMyPassword' is:
DnQHMKVkOXWfmtuyCZyfvu14ck2BkbUZ

**bitbucket Prop file has**

# mandatory:
git.host=bitbucket.1243.com
git.api=/rest/api/1.0/

git.key=ASxkmNlSfH+KPv4cbroNvIoCI4nlASn7
github.key=ASxkmNlSfH+KPv4cbroNvIoCI4nlASn7

**api.properties has**
key=ASxkmNlSfH+KPv4cbroNvIoCI4nlASn7

**Comment by satishc1** [comment]
@smsuresh Run the bitbucket collector once. Then try saving the UI config.

**Comment by smsuresh** [comment]
Thanks Satish!  ( @satishc1 )  , im able to save now, but im seeing the below err even though the credential is correct..

2017-02-13 01:30:01,052 INFO  c.c.d.collector.CollectorTask - Repo Count              1        1s
2017-02-13 01:30:01,052 INFO  c.c.d.collector.CollectorTask - New Commits             0        1s
2017-02-13 01:30:01,052 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2017-02-13 01:35:00,005 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2017-02-13 01:35:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-13 01:35:00,009 INFO  c.c.d.collector.CollectorTask - Starting...
2017-02-13 01:35:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-13 01:35:00,939 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https://bitbucket.abc.com/rest/api/1.0/projects/abc/repos/cart-api/commits?until=feature%2Fsprint6&limit=25
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:227) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:88) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:132) [bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2017-02-13 01:35:00,964 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s

**Comment by Sbrenthughes** [comment]
@smsuresh can you open new issue if the current problem is still happening?
