### ISSUE TITLE
Unable to connect to jira

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1163]
Iam getting the below exception..

Our Jira setup doesn't have any "team" configuration..

2017-02-10 09:03:59,586 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 2]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=570848}
2017-02-10 09:04:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2017-02-10 09:04:00,240 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-10 09:04:00,240 INFO  c.c.d.collector.CollectorTask - https://jira.com/
2017-02-10 09:04:00,240 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-10 09:04:00,265 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2017-02-10 09:04:01,428 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2017-02-10 09:04:01,447 INFO  com.capitalone.dashboard.Application - Started Application in 17.124 seconds (JVM running for 19.646)
2017-02-10 09:04:02,561 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
        at com.google.common.base.Absent.get(Absent.java:42) ~[guava-14.0.jar!/:na]
        at com.capitalone.dashboard.client.DefaultJiraClient.getProjects(DefaultJiraClient.java:141) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.project.ProjectDataClientImpl.updateProjectInformation(ProjectDataClientImpl.java:58) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:113) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

Attached my properties file as well..

[myjira props.txt](https://github.com/capitalone/Hygieia/files/767271/myjira.props.txt)

**Comment by satishc1** [comment]
@smsuresh Which jira server are you trying to connect to?

**Comment by MarkRx** [comment]
The issue is something else but it looks like a bug in the error handling is causing it to get lost. According to the doc e.getStatusCode returns an Optional. I think you need to change the code to this:

```
if (e.getStatusCode().isPresent() && e.getStatusCode().get() == 401 ) {
					LOGGER.error("Error 401 connecting to JIRA server, your credentials are probably wrong. Note: Ensure you are using JIRA user name not your email address.");
				}
```

**Comment by smsuresh** [comment]
now im able to connect, but still not seeing any data in UI.



2017-02-13 01:39:00,002 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-13 01:39:00,002 INFO  c.c.d.collector.CollectorTask - https://myjira.abc.com/
2017-02-13 01:39:00,002 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-13 01:39:00,003 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2017-02-13 01:39:02,897 INFO  c.c.d.collector.CollectorTask - Project Data          867        2s
2017-02-13 01:39:12,486 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 100
2017-02-13 01:39:19,620 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 100 pageSize 100
2017-02-13 01:39:24,736 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 200 pageSize 52
2017-02-13 01:39:24,737 INFO  c.c.d.collector.CollectorTask - Story Data            252       21s
2017-02-13 01:39:24,737 INFO  c.c.d.collector.CollectorTask - Finished                        24s

**Comment by satishc1** [comment]
@smsuresh Check if you see the "collectorType" : "AgileTool" entry in your collectors mongo collection. If you do and if the UI is not letting you pick the JIRA feature config, then try clearing browser cache.

**Comment by satishc1** [comment]
@smsuresh Closed. Reopen if still an issue.
