### ISSUE TITLE
Jira(feature) widget not showing any data even after new version

### ISSUE THREAD

**Issue by anandsit** [capitalone/Hygieia#1164]
As mentioned in https://github.com/capitalone/Hygieia/pull/1137

I followed all the steps but still Jira does not show any data. Do you want me to upgrade Hygiei API and UI as well? 

After pulling the latest code, i built only Jira collector. Performed all the mentionyed cleanup task. Ran the new jira collector. The entry in the database looks like this

{
"_id" : ObjectId("589bcd2fc4c9565faf4ef41a"),
"_class" : "com.capitalone.dashboard.model.FeatureCollector",
"name" : "Jira",
"collectorType" : "AgileTool",
"enabled" : true,
"online" : true,
"lastExecuted" : NumberLong(1486605818627)
}

With this, UI did not recognize the collector (the drop down did not show Jira as an option).

When i change the collectorType from AgileTool to ScopeOwner, the dropdown is populated But the values in the UI are still 0 0 0 for any project and any value

2017-02-08 20:20:15,214 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: https://jira.xxxxxxxxxcom/rest/tempo-teams/1/team
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_74]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_74]
at java.net.URLConnection.getContent(Unknown Source) ~[na:1.8.0_74]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(Unknown Source) ~[na:1.8.0_74]
at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJiraClient.java:196) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:57) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_74]
at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_74]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_74]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_74]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_74]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_74]
at java.lang.Thread.run(Unknown Source) [na:1.8.0_74]
2017-02-08 20:20:15,214 INFO c.c.d.collector.CollectorTask - Team Data 0 0s
2017-02-08 20:20:15,967 INFO c.c.d.collector.CollectorTask - Project Data 331 0s
2017-02-08 20:20:16,672 INFO c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 1
2017-02-08 20:20:16,673 INFO c.c.d.collector.CollectorTask - Story Data 1 0s
2017-02-08 20:20:16,673 INFO c.c.d.collector.CollectorTask - Finished 1s

**Comment by satishc1** [comment]
@anandsit Yes rebuild all your modules. If you ever in doubt as to which modules need to be built, you can look at the list of files changed in a PR.

**Comment by MarkRx** [comment]
Set feature.jiraTeamFieldName to the empty string or remove it from your properties.

**Comment by anandsit** [comment]
as a general practice, it is okay to rebuild.

but in this case, will the rebuild resolve the issue ?

**Comment by anandsit** [comment]
@MarkRx  - Let me know the right value in DB. Is it ScopeOwner or AgileTool ? 

{
"_id" : ObjectId("589bcd2fc4c9565faf4ef41a"),
"_class" : "com.capitalone.dashboard.model.FeatureCollector",
"name" : "Jira",
"collectorType" : "AgileTool",
"enabled" : true,
"online" : true,
"lastExecuted" : NumberLong(1486605818627)
}

**Comment by MarkRx** [comment]
It should be AgileTool. ScopeOwner was the old one.

**Comment by anandsit** [comment]
@MarkRx  - when it is AgileTool, the Dropdown does not list Jira as an option. 

In that case, i need to update from API and UI components as well. Because Api is still old and probably looking for ScopeOwner in DB.

**Comment by MarkRx** [comment]
Correct

**Comment by anandsit** [comment]
Tried the latest code. 

1. Stopped Jira collector
2. Removed all DB entries related to jira
3. Deployed latest API, UI and jira collector code
4. Started API, UI and later Jira collector
5.  Still the feature widget dropdown does not show Jira as an option.

The moment i change AgileTool to ScopeOwner, the dropdown is populate but the data shown is 0 0 0

**Comment by satishc1** [comment]
@anandsit 
Don't change AgileTool to ScopeOwner.   Clear your browser cache after step 4 you've listed above and see if that helps.

**Comment by anandsit** [comment]
Thanks!! Now it is  resolved!! I am able to see jira data. Need to work deeper into Jira to understand what data Hygieia displays

**Comment by MilindDivre** [comment]
so what helped to resolve issue can you please brief even i am facing the same issue
