### ISSUE TITLE
Jenkins collector issue

### ISSUE THREAD

**Issue by eldojoseph** [capitalone/Hygieia#1168]
I am trying to connect to my Jenkins instance which is using folder plugin. When I try with Jenkins default URL it is not collecting data from any jobs under different folders. and when I am giving complete folder path, Hygieia is recognizing the jobs but it is not collecting build data and I could see below errors at logs. How can I fix this issue?

2017-02-12 15:01:08,696 ERROR c.c.d.collector.DefaultHudsonClient - Unknown error in getting build details. URL=<jenkins url>/job/<folder1>/job/<folder2>/job/<folder3>/job/<Job name>/1/
java.lang.NullPointerException: null
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getJsonArray(DefaultHudsonClient.java:281) ~[jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.addChangeSets(DefaultHudsonClient.java:230) ~[jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getBuildDetails(DefaultHudsonClient.java:177) ~[jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.addNewBuilds(HudsonCollectorTask.java:193) [jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:95) [jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_101]

**Comment by satishc1** [comment]
@eldojoseph Your log shows 2.0.2-SNAPSHOT. Try with the latest codebase and reopen if still an issue.

**Comment by eldojoseph** [comment]
Thanks @satishc1 it worked fine.
