### ISSUE TITLE
API Exceptions

### ISSUE THREAD

**Issue by xpdable** [capitalone/Hygieia#1174]
My api runs with below exceptions, could tell if there are critical or ?

> 2017-02-14 16:09:41,113 ERROR c.c.d.rest.RestApiExceptionHandler - invalid hexadecimal representation of an ObjectId: [{timestamp:1487059701768,status:500,error:Internal Server Error,exception:java.lang.StackOverflowError,message:No message available,path:/api/build}]
java.lang.IllegalArgumentException: invalid hexadecimal representation of an ObjectId: [{timestamp:1487059701768,status:500,error:Internal Server Error,exception:java.lang.StackOverflowError,message:No message available,path:/api/build}]
	at org.bson.types.ObjectId.parseHexString(ObjectId.java:519) ~[mongo-java-driver-3.0.2.jar!/:na]
	at org.bson.types.ObjectId.<init>(ObjectId.java:233) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.capitalone.dashboard.service.BinaryArtifactServiceImpl.create(BinaryArtifactServiceImpl.java:99) ~[api.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.rest.BinaryArtifactController.create(BinaryArtifactController.java:40) ~[api.jar!/:2.0.5-SNAPSHOT]

> 2017-02-14 16:08:21,757 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception [Handler processing failed; nested exception is java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError: null
	at java.nio.charset.CharsetDecoder.<init>(Unknown Source) ~[na:1.8.0_91]
	at java.nio.charset.CharsetDecoder.<init>(Unknown Source) ~[na:1.8.0_91]
	at sun.nio.cs.UTF_8$Decoder.<init>(Unknown Source) ~[na:1.8.0_91]
	at sun.nio.cs.UTF_8$Decoder.<init>(Unknown Source) ~[na:1.8.0_91]
	at sun.nio.cs.UTF_8.newDecoder(Unknown Source) ~[na:1.8.0_91]
	at java.lang.StringCoding.decode(Unknown Source) ~[na:1.8.0_91]
	at java.lang.String.<init>(Unknown Source) ~[na:1.8.0_91]
	at java.lang.String.<init>(Unknown Source) ~[na:1.8.0_91]
	at org.bson.io.ByteBufferBsonInput.readCString(ByteBufferBsonInput.java:124) ~[mongo-java-driver-3.0.2.jar!/:na]

**Comment by xpdable** [comment]
I have to upload the log for your further investigation
[api-log.log.txt](https://github.com/capitalone/Hygieia/files/775795/api-log.log.txt)

**Comment by MarkRx** [comment]
Do you have something POSTing builds to Hygieia? The build POST endpoint accepts a json that has a field called "buildId". If present it needs to correspond to a mongo object id (12 byte hex string).

**Comment by xpdable** [comment]
Yes, I am running an Artifact Collector, I'll try disable it and come back to you if still has issue.

**Comment by xpdable** [comment]
@MarkRx I am now running without artifact collector and still there are exceptions. What I could point out is that the GitLab collector is failing to get data in UI without Exceptions.

**Comment by xpdable** [comment]
@MarkRx @satishc1  Hi still I have the exception on the latest code where cause gitlab collector not showing the data. Could you help ?

As below screenshot, not data shows on the widget of gitlab
![image](https://cloud.githubusercontent.com/assets/2903719/23442894/6dd20cac-fe66-11e6-8868-94519db4b496.png)

**Comment by satishc1** [comment]
@xpdable Ping me on https://gitter.im/capitalone/Hygieia and we can setup a time to troubleshoot the issue you are having.
