### ISSUE TITLE
Unable to start api 

### ISSUE THREAD

**Issue by thashi** [capitalone/Hygieia#1190]
Can someone point me out whats wrong here? (i don't understand whats mentioned [here](https://github.com/capitalone/Hygieia/issues/1130))

Pulled latest code from master branch today.
`mvn install` was success.
`gulp serve` also started successfully.
**application.properties** file as follows

> dbname=dashboarddb
dbusername=dashboarduser
dbpassword=ENC(C9PLVDJ/1OfkT/3jvC/wEB20R1XPJtg9)
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080

When tried to start api
`D:\WorkSpace\IdeaProjects\Hygieia\api\target>java -jar api.jar --spring.config.location=dashboard.properties -Djasypt.encryptor.password=hygieiasecret`
Got following error.

> $ java -jar api.jar --spring.config.location -Djasypt.encryptor.password=hygieiasecret
13:12:35,236 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
13:12:35,243 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
13:12:35,244 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/D:/WorkSpace/IdeaProjects/Hygieia/api/target/api.jar!/logback.xml]
13:12:35,249 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
13:12:35,249 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/D:/WorkSpace/IdeaProjects/Hygieia/api/target/api.jar!/logback.xml]
13:12:35,249 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/D:/WorkSpace/IdeaProjects/Hygieia/api/target/api.jar!/lib/core-2.0.5-SNAPSHOT.jar!/logback.xml]
13:12:35,309 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@b5a76a9 - URL [jar:file:/D:/WorkSpace/IdeaProjects/Hygieia/api/target/api.jar!/logback.xml] is not of type file
13:12:35,556 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
13:12:35,595 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
13:12:35,615 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
13:12:35,703 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
13:12:35,884 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
13:12:35,890 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ROLLING]
13:12:35,962 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
13:12:35,965 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/devopsdashboard-api-%d{yyyy-MM-dd}.%i.log for the active file
13:12:35,972 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@5e0ab3b1 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/devopsdashboard-api-%d{yyyy-MM-dd}.%i.log'.
13:12:35,972 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@5e0ab3b1 - Roll-over at midnight.
13:12:35,977 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@5e0ab3b1 - Setting initial period to Tue Feb 21 13:12:35 IST 2017
13:12:35,982 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
13:12:35,983 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - Active log file name: logs/devopsdashboard-api-2017-02-21.0.log
13:12:35,983 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - File property is set to [null]
13:12:35,985 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
13:12:35,987 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ROLLING] to Logger[ROOT]
13:12:35,989 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
13:12:35,989 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
13:12:35,990 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@88c89bc - Registering current configuration as safe fallback point

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.2.5.RELEASE)

2017-02-21 13:12:36,716 INFO  com.capitalone.dashboard.Application - Starting Application v2.0.5-SNAPSHOT on ThashitharanPC with PID 10280 (D:\WorkSpace\IdeaProjects\Hygieia\api\target\api.jar started by TPC in D:\WorkSpace\IdeaProjects\Hygieia\api\target)
2017-02-21 13:12:36,854 INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@41bd239f: startup date [Tue Feb 21 13:12:36 IST 2017]; root of context hierarchy
2017-02-21 13:12:41,593 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Post-processing PropertySource instances
2017-02-21 13:12:41,657 INFO  c.u.j.c.StringEncryptorConfiguration - String Encryptor custom Bean not found with name 'jasyptStringEncryptor'. Initializing String Encryptor based on properties with name 'jasyptStringEncryptor'
2017-02-21 13:12:41,700 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2017-02-21 13:12:41,701 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource servletConfigInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2017-02-21 13:12:41,701 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource servletContextInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2017-02-21 13:12:41,702 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2017-02-21 13:12:41,702 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemEnvironment [org.springframework.core.env.SystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
2017-02-21 13:12:41,702 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource random [org.springframework.boot.context.config.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2017-02-21 13:12:41,702 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource applicationConfig: [classpath:/application.properties] [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2017-02-21 13:12:41,702 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource class path resource [version.properties] [org.springframework.core.io.support.ResourcePropertySource] to EncryptableMapPropertySourceWrapper
2017-02-21 13:12:41,720 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-02-21 13:12:41,890 INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
2017-02-21 13:12:42,509 WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.autoconfigure.web.ServerProperties org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration.properties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties': Could not bind properties to [unknown] (target=server, ignoreInvalidFields=false, ignoreUnknownFields=false, ignoreNestedProperties=false); nested exception is java.lang.IllegalStateException: Required Encryption configuration property missing: jasypt.encryptor.password
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at com.capitalone.dashboard.Application.main(Application.java:45) [api.jar!/:2.0.5-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_121]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [api.jar!/:2.0.5-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.autoconfigure.web.ServerProperties org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration.properties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties': Could not bind properties to [unknown] (target=server, ignoreInvalidFields=false, ignoreUnknownFields=false, ignoreNestedProperties=false); nested exception is java.lang.IllegalStateException: Required Encryption configuration property missing: jasypt.encryptor.password
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:193) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:156) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        ... 12 common frames omitted

**Comment by nireeshT** [comment]
@thashi  - #1130  is not using the encrypted password that resolved the issue. Remove encrypted password from the api.props and  use command 
==> java -jar api.jar --spring.config.location=api.properties 

if you want to use the encrypted password route - 
1) encrypt password using below command 
==> java -cp ~/.m2/repository/org/jasypt/jasypt/1.9.2/jasypt-1.9.2.jar  org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="<db password>" password=hygieiasecret algorithm=PBEWithMD5AndDES

2) use the encrypted password in api.properties as 
   dbpassword=ENC(<encrypted db password>)
3) add "asypt.encryptor.password" as a environment variable 
4) Start api with below command 
==>java -jar api.jar --spring.config.location=api.properties -Djasypt.encryptor.password=hygieiasecret

**Comment by satishc1** [comment]
@thashi Is your prop file called application.properties  or dashboard.properties ?   Your comment has application.properties but your command references dashboard.properties.

java -jar api.jar --spring.config.location=dashboard.properties -Djasypt.encryptor.password=hygieiasecret

**Comment by thashi** [comment]
@nireeshT Thanks it working now.
@satishc1 yup it my mistake. Thanks .

**Comment by alanmathew** [comment]
D:\Software\Hygieia-master\api\target>java -cp ~/.m2/repository/org/jasypt/jasypt/1.9.2/jasypt-1.9.2.jar  org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="db" password=dbpass alg
orithm=PBEWithMD5AndDES
Error: Could not find or load main class org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI


Please help me on this

**Comment by Mpluya** [comment]
@alanmathew you will need to adjust your command to where your maven (.m2) repository is.
