### ISSUE TITLE
JIRA Collector : java.text.ParseException: Unparsable sprint Error

### ISSUE THREAD

**Issue by smlcodes** [capitalone/Hygieia#1194]
```
2017-02-22 13:59:34,548 ERROR c.c.d.c.story.StoryDataClientImpl - Failed to obtain sprint data from [{"self":"https:\/\/jira.mydomain.com\/rest\/api\/2\/customFieldOption\/10000","value":"Impediment","id":"10000"}]
java.text.ParseException: Unparsable sprint: {"self":"https:\/\/jira.mydomain.com\/rest\/api\/2\/customFieldOption\/10000","value":"Impediment","id":"10000"}
	at com.capitalone.dashboard.util.ClientUtil.parseSprint(ClientUtil.java:340) ~[classes/:na]
	at com.capitalone.dashboard.util.ClientUtil.parseSprints(ClientUtil.java:287) ~[classes/:na]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.processSprintData(StoryDataClientImpl.java:470) [classes/:na]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateMongoInfo(StoryDataClientImpl.java:244) [classes/:na]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:166) [classes/:na]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [classes/:na]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:1) [classes/:na]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [classes/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]
2017-02-22 13:40:13,792 ERROR c.c.d.c.story.StoryDataClientImpl - Failed to obtain sprint data from [{"self":"https:\/\/jira.mydomain.com\/rest\/api\/2\/customFieldOption\/10000","value":"Impediment","id":"10000"}]
```

**Comment by MarkRx** [comment]
What version of jira are you running?

It's expecting Sprint data in the form of a raw toString due to how the api was returning the value. The Hygieia code works around this by attempting to reverse enginer that toString. If you are on a new version perhaps that bug has finally been fixed and it is correctly returning json.

Example:

> com.atlassian.greenhopper.service.sprint.Sprint@2189d27[id=2144,rapidViewId=1645,state=OPEN,name=Sprint 18,startDate=2016-05-31T14:06:46.350-04:00,endDate=2016-06-16T17:06:00.000-04:00,completeDate=2016-06-20T14:21:57.131-04:00,sequence=2144]

**Comment by smlcodes** [comment]
Thanks, it's Fixed now

**Comment by blasteravismaster** [comment]
Hi,

Im seeing the same error,

===
2018-06-11 07:29:10,003 ERROR c.c.d.c.story.StoryDataClientImpl - Failed to obtain sprint data from ["com.atlassian.greenhopper.service.sprint.Sprint@6028ebbc[id=2167,rapidViewId=665,state=ACTIVE,name=5004,goal=1) Event Correlation Deployment in Production\n2) Billing Deployment in UAT\n3) Code Freeze for R5 with support for CE v4 APIs,startDate=2018-06-07T16:21:41.124Z,endDate=2018-06-21T16:21:00.000Z,completeDate=<null>,sequence=2141]","com.atlassian.greenhopper.service.sprint.Sprint@75956ae6[id=2141,rapidViewId=665,state=CLOSED,name=5003,goal=,startDate=2018-05-24T15:38:40.333Z,endDate=2018-06-07T14:53:00.000Z,completeDate=2018-06-07T14:53:10.374Z,sequence=2139]"]
java.text.ParseException: Unparsable sprint: com.atlassian.greenhopper.service.sprint.Sprint@6028ebbc[id=2167,rapidViewId=665,state=ACTIVE,name=5004,goal=1) 
====

**Comment by ndungunjenga** [comment]
I am also getting the same issue as @blasteravismaster. The only difference with the expected result is **goal=1** is missing in the expected results.

`com.atlassian.greenhopper.service.sprint.Sprint@2189d27[id=2144,rapidViewId=1645,state=OPEN,name=Sprint 18,startDate=2016-05-31T14:06:46.350-04:00,endDate=2016-06-16T17:06:00.000-04:00,completeDate=2016-06-20T14:21:57.131-04:00,sequence=2144]`

**Comment by syedafirdaus** [comment]
What is the solution for this error?
