### ISSUE TITLE
Jenkins collector authentication failure

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#1209]
Recent changes to recursively getting job details seems to have broken authentication. Observe that the url pass in is "api/json?tree=jobs" and is missing the host.

> hygieia-jenkins-build                     | 2017-02-24 22:27:00,029 WARN  c.c.d.collector.DefaultHudsonClient - Credentials for the following url was not found. This could happen if the domain/subdomain/IP address in the build url returned by Jenkins and the Jenkins instance url in your Hygieia configuration do not match: "api/json?tree=jobs"
> hygieia-jenkins-build                     | 2017-02-24 22:27:00,038 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
> hygieia-jenkins-build                     | java.lang.IllegalArgumentException: URI is not absolute
> hygieia-jenkins-build                     |     at java.net.URI.toURL(URI.java:1088) ~[na:1.8.0_102]
> hygieia-jenkins-build                     |     at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:137) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
> hygieia-jenkins-build                     |     at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:76) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
> hygieia-jenkins-build                     |     at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:565) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
> hygieia-jenkins-build                     |     at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
> hygieia-jenkins-build                     |     at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
> hygieia-jenkins-build                     |     at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:592) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
> hygieia-jenkins-build                     |     at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:166) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
> hygieia-jenkins-build                     |     at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:101) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
> hygieia-jenkins-build                     |     at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
> hygieia-jenkins-build                     |     at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
> hygieia-jenkins-build                     |     at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
> hygieia-jenkins-build                     |     at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
> hygieia-jenkins-build                     |     at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
> hygieia-jenkins-build                     |     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
> hygieia-jenkins-build                     |     at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
> hygieia-jenkins-build                     |     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_102]
> hygieia-jenkins-build                     |     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_102]
> hygieia-jenkins-build                     |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
> hygieia-jenkins-build                     |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
> hygieia-jenkins-build                     |     at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]

**Comment by MarkRx** [comment]
It was a configuration error. My docker-compose had a missmatch between the server url indexes and the username/password indexes.
