### ISSUE TITLE
Error building UI with bower install failed for com.github.eirslett:frontend-maven-plugin

### ISSUE THREAD

**Issue by gauravjos** [capitalone/Hygieia#1213]
Error building from top level of Hygieia project
```
OS: Centos 7.2
Maven 3.3.9
Java version: 1.8.0_121
```
```bash
mvn clean install -pl UI
```
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.capitalone.dashboard:api:jar:2.0.5-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:UI 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UI ---
[INFO] 
[INFO] >>> maven-pmd-plugin:3.6:check (default) > :pmd @ UI >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ UI ---
[INFO] 
[INFO] <<< maven-pmd-plugin:3.6:check (default) < :pmd @ UI <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.6:check (default) @ UI ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:prepare-agent (default) @ UI ---
[INFO] argLine set to -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.7.6.201602180812/org.jacoco.agent-0.7.6.201602180812-runtime.jar=destfile=/home/centos/Hygieia/UI/target/jacoco.exec
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) @ UI ---
[INFO] Found proxies: []
[INFO] Node v5.4.1 is already installed.
[INFO] NPM 2.14.15 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.29:npm (npm install) @ UI ---
[INFO] Found proxies: []
[INFO] Running 'npm install' in /home/centos/Hygieia/UI
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.29:bower (bower install) @ UI ---
[INFO] Found proxies: []
[INFO] Running 'bower install' in /home/centos/Hygieia/UI
[ERROR] module.js:327
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module 'mout'
[ERROR]     at Function.Module._resolveFilename (module.js:325:15)
[ERROR]     at Function.Module._load (module.js:276:25)
[ERROR]     at Module.require (module.js:353:17)
[ERROR]     at require (internal/module.js:12:17)
[ERROR]     at Object.<anonymous> (/home/centos/Hygieia/UI/node_modules/bower/lib/bin/bower.js:4:12)
[ERROR]     at Module._compile (module.js:397:26)
[ERROR]     at Object.Module._extensions..js (module.js:404:10)
[ERROR]     at Module.load (module.js:343:32)
[ERROR]     at Function.Module._load (module.js:300:12)
[ERROR]     at Module.require (module.js:353:17)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.015 s
[INFO] Finished at: 2017-02-28T09:13:39+00:00
[INFO] Final Memory: 30M/72M
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:bower (bower install) on project UI: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by satishc1** [comment]
@gauravjos If inside a proxy try using a .bowerrc file. Refer to https://github.com/capitalone/Hygieia/issues/823

**Comment by satishc1** [comment]
@gauravjos Closed. Reopen if still an issue.
If you are inside a proxy make sure your env vars are set. And use a .bowerrc file as mentioned before.
export http_proxy=http://yourproxyhost:yourproxyport
export https_proxy=https://yourproxyhost:yourproxyport

export HTTP_PROXY=http://yourproxyhost:yourproxyport
export HTTPS_PROXY=https://yourproxyhost:yourproxyport

export all_proxy=http://yourproxyhost:yourproxyport
export ALL_PROXY=http://yourproxyhost:yourproxyport
