### ISSUE TITLE
"Given final block not properly padded" error for bitbucket collector

### ISSUE THREAD

**Issue by DomhnaillByrne** [capitalone/Hygieia#1222]
I'm getting the following error when trying to retrieve commits using the bitbucket collector.

```
2017-03-03 16:51:11,966 DEBUG c.c.d.collector.GitCollectorTask - {password=<encrypted-password>, scm=Bitbucket, branch=master, userID=uid, url=gitstash-url}::master
2017-03-03 16:51:19,207 DEBUG c.c.d.c.DefaultBitbucketServerClient - Rest Url: <this rest url is correct>
2017-03-03 16:51:23,988 ERROR c.c.d.c.DefaultBitbucketServerClient - Cannot decrypt this message
Given final block not properly padded
```

```
#Collector schedule (required)
git.cron=0 0/3 * * * *
git.host=https://gitstash-url
git.api=/rest/api/1.0/

#Maximum number of days to go back in time when fetching commits. Only applicable to Bitbucket Cloud.
git.commitThresholdDays=300

#Page size for rest calls. Only applicable to Bitbucket Server.
git.pageSize=25

#Bitbucket product
# Set to "cloud" to use Bitbucket Cloud (formerly known as Bitbucket)
# Set to "server" to use Bitbucket Server (formerly known as Stash)
# More information can be found here: href="https://github.com/capitalone/Hygieia/issues/609
git.product=server
git.key=<encryted-key>
```

Can anyone help with this? I've added the same git.key in my api properties file also.

**Comment by nireeshT** [comment]
@DomhnaillByrne  - Create a new dashboard, try not giving credentials while configuring bitbucket.

**Comment by smsuresh** [comment]
@DomhnaillByrne  Did that work?!  I m also facing the same issue now.. but didn't work :(    @nireeshT

**Comment by DomhnaillByrne** [comment]
@smsuresh It didn't work and had to park this a while back. I'll look into it again this week hopefully.

**Comment by tsr2017** [comment]
I am also getting this issue
Rest Url: http://mycompany.repo.com/rest/api/1.0/projects/test/repos/ios/commits?until=origin%2Fdevelop&limit=25
2017-08-31 16:10:00,035 ERROR c.c.d.c.DefaultBitbucketServerClient - Cannot decrypt this message
Given final block not properly padded
2017-08-31 16:10:00,035 DEBUG c.c.d.c.DefaultBitbucketServerClient - GET http://mycompany.repo.com/rest/api/1.0/projects/test/repos/ios/commits?until=origin%2Fdevelop&limit=25
2017-08-31 16:10:20,073 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from http://mycompany.repo.com/rest/api/1.0/projects/test/repos/ios/commits?until=origin%2Fdevelop&limit=25
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://mycompany.repo.com/rest/api/1.0/projects/test/repos/ios/commits?until=origin%2Fdevelop&limit=25": Connect to mycompany.repo.com:80 [mycompany.repo.com/10.1.13.198] failed: connect timed out; nested exception is org.apache.http.conn.ConnectTimeoutException: Connect to mycompany.repo.com:80 [mycompany.repo.com/10.1.13.198] failed: connect timed out
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:235) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:90) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:148) [bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to mycompany.repo.com:80 [mycompany.repo.com/10.1.13.198] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:143) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	... 15 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_144]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_144]
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar!/:4.5.1]
	... 28 common frames omitted

**Comment by nitin1706** [comment]
@tsr2017 : this seems like its not able to get the key from properties file or there is some error when using that key and consequently, next call is failing. Can you please share properties for bamboo collector?

**Comment by satishc1** [comment]
Follow the "Encryption for private repos" section in UI module readme.
![image](https://user-images.githubusercontent.com/21199084/30386538-0cc85126-9878-11e7-881c-8b63c6fa64b5.png)
