### ISSUE TITLE
Hygieia build failed : could not download Node.js: Got error code 403 from the server

### ISSUE THREAD

**Issue by HebbarA** [capitalone/Hygieia#1227]
We are trying to build Hygieia code but maven build fails with below error.

"Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) on project UI: Could not download Node.js: Got error code 403 from the server. -> [Help 1]"

We are able to accses nodeDownloadRoot and npmDownloadRoot through chrome browser with the user set in settings.xml(proxy settings) of maven. 
UI/pom.xml
--<execution>
            <id>install node and npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
              <nodeVersion>v5.4.1</nodeVersion>
              <npmVersion>2.14.15</npmVersion>
                <nodeDownloadRoot>http://nodejs.org/dist/</nodeDownloadRoot>
                <npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
            </configuration>
          </execution>

Environment : Red Hat Enterprise Linux Server release 7.1 (Maipo)

Can anyone guide us on how to resolve this issue since we are new to Hygieia.
Thanks

**Comment by satishc1** [comment]
@HebbarA Try building Hygieia on a network not restricted by proxy. If you can't then try https://github.com/capitalone/Hygieia/issues/1213

**Comment by mrpudn** [comment]
Yup - you're getting a 403 Unauthorized, which looks like a proxy authentication issue.

Your company has probably already configured chrome to authenticate with your proxy for you, which is why you are able to get to them in Chrome. You'll have to set your `http_proxy` and `https_proxy` environment variables in order for tools to be able to authenticate with the proxy.

**Comment by HebbarA** [comment]
As suggested, we have set the proxy (setting env_variables) and build the code. Getting same error.

**Comment by HebbarA** [comment]
We installed node, npm, bower and gulp on linux through yum commands and removed the execution sections of these in pom.xml of UI. Now when we build the code, the build is failing to  create assembly archive src. Getting below errors 

[DEBUG] All known ContainerDescriptorHandler components: [metaInf-spring, plexus, metaInf-services, file-aggregator]
[DEBUG] No ArtifactResolver with hint project-cache-aware
[DEBUG] FileSet[dist/] dir perms: -1 file perms: -1
[DEBUG] The archive base directory is 'null'
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  2.684 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 28.929 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 14.328 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SUCCESS [  5.767 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SUCCESS [  5.553 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  6.631 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  5.835 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  4.377 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SUCCESS [  5.057 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  6.079 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SUCCESS [  5.507 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [ 15.576 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  6.878 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  2.853 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SUCCESS [  7.065 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  5.097 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  3.312 s]
[INFO] com.capitalone.dashboard:gitlab-git-collector ...... SUCCESS [  5.727 s]
**[INFO] com.capitalone.dashboard:UI ........................ FAILURE [  0.729 s]**
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:19 min
[INFO] Finished at: 2017-03-07T16:39:42+05:30
[INFO] Final Memory: 131M/964M
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (create-archive) on project UI: Failed to create assembly: Error creating assembly archive src: You must set at least one file. -> [Help 1]**
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (create-archive) on project UI: Failed to create assembly: Error creating assembly archive src: You must set at least one file.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error creating assembly archive src: You must set at least one file.
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:541)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.apache.maven.plugin.assembly.archive.ArchiveCreationException: Error creating assembly archive src: You must set at least one file.
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:185)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:484)
        ... 22 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: You must set at least one file.
        at org.codehaus.plexus.archiver.tar.TarArchiver.execute(TarArchiver.java:114)
        at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:916)
        at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:445)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
        ... 23 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI

**Comment by satishc1** [comment]
@HebbarA Per your comment .."We installed node, npm, bower and gulp on linux through yum commands and removed the execution sections of these in pom.xml of UI." 

Try reverting back to the original pom.xml file and do the build in a network not restricted by proxy.

**Comment by HebbarA** [comment]
If is proxy issue then build should have failed for other components too. But build is failing only during installing node.js in UI step. We tried building the code after configuring proxy but still it is failing. So we installed node.js manually and removed from pom.xml.

**Comment by MarkRx** [comment]
Here is an example sh script I use to setup a Jenkins build that hits an internal artifactory repository:

```
#!/bin/bash

rm -rf UI/node
mkdir UI/node

# Install node
if [ ! -f UI/node/node ]; then
  echo "Extracting node..."
  mkdir -p UI/node/tmp
  curl ${ARTIFACTORY_URL}/tools/node/v5.4.1/node-v5.4.1-linux-x64.tar.gz | tar xz -C UI/node/tmp
  cp UI/node/tmp/node-v5.4.1-linux-x64/bin/node UI/node/node
  rm -rf UI/node/tmp
fi

# Install npm
if [ ! -f UI/node/npm ]; then
  echo "Extracting npm..."
  mkdir -p UI/node/node_modules/npm
  curl ${ARTIFACTORY_URL}/tools/npm/npm-2.14.15.tgz | tar xz -C UI/node/node_modules/npm --strip-components 1
  cp UI/node/node_modules/npm/bin/npm UI/node/npm
  
  # Install artifactory resolver
  export PATH=$PATH:$WORKSPACE/UI/node/
  UI/node/npm install bower-art-resolver
fi

echo "Creating .npmrc..."
cat > UI/.npmrc <<EOL
registry = ${ARTIFACTORY_URL}/api/npm/npm
phantomjs_cdnurl = ${ARTIFACTORY_URL}/tools/phantomjs/
EOL

echo "Creating .bowerrc..."
cat > UI/.bowerrc <<EOL
{
  "proxy": "<myproxy>",
  "https-proxy": "<myproxy>",
  "registry": "${ARTIFACTORY_URL}/api/bower/bower",
    "resolvers": [
      "bower-art-resolver"
    ]
}
EOL
```

**Comment by rrgautam** [comment]
@HebbarA : Did you manage to resolve these problems? I am facing exact same issue. Any help will be much appreciated

**Comment by HebbarA** [comment]
We removed node, npm from pom.xml and installed node and npm separately in our environment.
