### ISSUE TITLE
api jar fails with Hygieia 2.0.4 tag version

### ISSUE THREAD

**Issue by kavitha0624** [capitalone/Hygieia#1236]
Hi,

I am trying to setup the Hygieia 2.0.4 tag version in my local laptop.
The code has been compiled successfully. 

**When I am running the api.jar, I am seeing the below - The execution stops right after the below. I have the slf4j-api and slf4j-simple jars in the .m2 repository folder. Also, inside the .jar-->libs, I see the slf4j-api.jar. Can anyone please help me with this. Thanks in advance.** I am able to do gulp serve successfully and able to login to the dashboard too though. Also, when I access http://localhost:8080/api/dashboard, I see the json o/p too.
$ java -jar api.jar --spring.config.location=application.properties
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.2.5.RELEASE)

**And when I am running the collectors, I am seeing the similar issue there too ofcourse.**

$ java -jar jenkins-build-collector-2.0.4-SNAPSHOT.jar --spring.config.location=application.properties                                                                                                                           Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/JoranException
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:160)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        at com.capitalone.dashboard.Application.main(Application.java:13)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.joran.spi.JoranException
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 17 more
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/JoranException
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:160)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        at com.capitalone.dashboard.Application.main(Application.java:13)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.joran.spi.JoranException
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 17 more

**Comment by satishc1** [comment]
@kavitha0624 Check which logback jars are in your maven repo and whether they have the class in question.

**Comment by kavitha0624** [comment]
@satishc1 , checked my maven repo and the class is present in the logback jar - ch/qos/logback/core/joran/spi/JoranException

**Comment by nireeshT** [comment]
@kavitha0624  - add slf4j-simple.jar to classpath, that should solve the issue. Make sure slf4j-api.jar  is in classpath too.

**Comment by kavitha0624** [comment]
@nireeshT, adding the slf4j-simple.jar resolved the issue  and api is starting fine now. But the jenkins collector, after adding the same jar and few other jars it asked for, it no more shows the above errors but I am seeing the below now.

[taskScheduler-1] INFO com.capitalone.dashboard.collector.CollectorTask - Running Collector: Hudson
[taskScheduler-1] INFO com.capitalone.dashboard.collector.CollectorTask - -----------------------------------
[taskScheduler-1] INFO com.capitalone.dashboard.collector.CollectorTask - https://jenkm1.xxx.com:8443/job/middleware-ops-org/
[taskScheduler-1] INFO com.capitalone.dashboard.collector.CollectorTask - -----------------------------------
[taskScheduler-1] INFO com.capitalone.dashboard.collector.CollectorTask - Fetched jobs                     1s
[taskScheduler-1] INFO com.capitalone.dashboard.collector.CollectorTask - New jobs                0        0s
[taskScheduler-1] ERROR com.capitalone.dashboard.collector.DefaultHudsonClient - Unknown error in getting build details. URL=https://jenkm1.discoverfinancial.com:8443/job/middleware-ops-org/job/ddx-GWC_ddx-tsm_dev_Pipeline/2/
java.lang.NullPointerException
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getString(DefaultHudsonClient.java:370)
        at com.capitalone.dashboard.collector.DefaultHudsonClient.addChangeSets(DefaultHudsonClient.java:235)
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getBuildDetails(DefaultHudsonClient.java:188)
        at com.capitalone.dashboard.collector.HudsonCollectorTask.addNewBuilds(HudsonCollectorTask.java:193)
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:95)
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32)
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[taskScheduler-1] ERROR com.capitalone.dashboard.collector.DefaultHudsonClient - Unknown error in getting build details. URL=https://jenkm1.xxx.com:8443/job/middleware-ops-org/job/ddx-GWC_ddx-tsm_dev_Pipeline/1/
java.lang.NullPointerException
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getString(DefaultHudsonClient.java:370)
        at com.capitalone.dashboard.collector.DefaultHudsonClient.addChangeSets(DefaultHudsonClient.java:235)
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getBuildDetails(DefaultHudsonClient.java:188)
        at com.capitalone.dashboard.collector.HudsonCollectorTask.addNewBuilds(HudsonCollectorTask.java:193)
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:95)
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32)
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by nireeshT** [comment]
@kavitha0624  - you must be working on out-dated code. Please rebase to latest, mvn build on hygieia and run collectors.

**Comment by nireeshT** [comment]
@kavitha0624  - closing issue. Reopen if it is not resolved.
