### ISSUE TITLE
Jenkins collector issue

### ISSUE THREAD

**Issue by RAMESHBABU18** [capitalone/Hygieia#1262]
while running the jenkins collector getting an connection reset issue.., here is the log

2017-03-23 11:05:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-03-23 11:05:00,143 INFO  c.c.d.collector.CollectorTask - ------------------------------
2017-03-23 11:05:00,143 INFO  c.c.d.collector.CollectorTask - https://******.com/job/***/job/rak/job/kisr/
2017-03-23 11:05:00,143 INFO  c.c.d.collector.CollectorTask - ------------------------------
2017-03-23 11:15:02,828 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://******.com/job/***/job/rak/job/kisr/api/json?tree=jobs[name,url,builds[number,url]]":Connection reset; nested exception is java.net.SocketException: Connection reset
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:332) ~[jenkins-build-collector-2.0.31.jar!/:2.0.31]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:90) ~[jenkins-build-collector-2.0.31.jar!/:2.0.31]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) [jenkins-build-collector-2.0.31.jar!/:2.0.31]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-build-collector-2.0.31.jar!/:2.0.31]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.31.jar!/:2.0.31]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

can one any help me...,

**Comment by nireeshT** [comment]
@RAMESHBABU18  - url you are trying to make rest call should be behind network restricted by proxy. Set your collector to DEBUG level and run collector. It will give detail error message. 
Set loglevel to "DEBUG" in logback.xml

**Comment by satishc1** [comment]
@RAMESHBABU18 See if you can curl a command to the url. Reopen if its not a connectivity issue that a network/firewall change can resolve.
