### ISSUE TITLE
Jira collector connection issues

### ISSUE THREAD

**Issue by murali-kpmg** [capitalone/Hygieia#1329]
Hello,
 I'm trying to setup Hygieia - focusing on Jira collector to start with.
 When I bring up the Jira collector, I get a connection time out.
 I can see Jira is up and running.
 Mongodb, Jira (and MySQL)  as well as the collector are running in Ubuntu.

Here is the error message from the collector log:
2017-04-18 13:53:59,993 INFO  c.c.d.collector.CollectorTask - http://localhost:8
080/
2017-04-18 13:53:59,993 INFO  c.c.d.collector.CollectorTask - ------------------
-----------------
2017-04-18 13:53:59,998 INFO  c.c.d.collector.CollectorTask - Team Data
      0        0s
2017-04-18 13:54:00,340 INFO  c.c.d.collector.CollectorTask - Project Data
      6        0s
2017-04-18 13:56:07,362 ERROR c.c.d.client.DefaultJiraClient - IOException
java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:350) ~[na:1.8.0_121]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:206) ~[na:1.8.0_121]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:188) ~[na:1.8.0_121]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
        at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_121]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_12
1]

HEre are the collector configuration related to Jira:
# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
feature.jiraProxyUrl=http://proxy.com
feature.jiraProxyPort=9000
feature.jiraBaseUrl=http://localhost:8080/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
feature.jiraCredentials=amlyYXVzZXI6amlyYTEyMw==
# OAuth is not fully implemented; please blank-out the OAuth values:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

 
#############################################################################
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
#feature.jiraIssueTypeNames=Story
feature.jiraIssueTypeId=10000

 feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10002
feature.jiraStoryPointsFieldName=customfield_10003
feature.jiraTeamFieldName=

**Comment by murali-kpmg** [comment]
Can you please advise what could be wrong here?

Thanks
Murali

**Comment by satishc1** [comment]
@murali-kpmg Are you sure your jira url is http://localhost:8080/ ? If jira is running at that url, which port is your hygieia api running on ?

**Comment by satishc1** [comment]
@murali-kpmg Comment out the proxy settings if you don't have one.

**Comment by murali-kpmg** [comment]
Satish,
 I have not gotten to the UI installation yet. 

I tried commenting out the proxy settings:

2017-04-18 19:12:00,533 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
        at com.capitalone.dashboard.util.FeatureWidgetQueries.getStoryQuery(FeatureWidgetQueries.java:1
10) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.DefaultJiraClient.getIssues(DefaultJiraClient.java:94) ~[jir
a-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:160) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]

This looks like an improvement now - is this still a config issue now?

Thanks for your inputs/advice

**Comment by satishc1** [comment]
@murali-kpmg This setting looks incorrect. This needs to point to your jira server.
feature.jiraBaseUrl=http://localhost:8080/

**Comment by murali-kpmg** [comment]
Satish,
 This is how I'm planning to run the Hygieia components:

As a background, I'm trying to do a proof of case for now.

Mongo, Jira, Jenkins, Sonar, Git and their respective collectors will run in one Linux box - The UI will run in a windows box - I thought I could run the API in the Linux box too but so far I could not figure out how to configure the UI to connect to API running in a remote host.

Can you please comment if this configuration is feasible.

As the Jira server is running in the same machine as the collector, I have 
feature.jiraBaseUrl=http://localhost:8080/

Do you think this configuration is still incorrect?

**Comment by murali-kpmg** [comment]
Satish, Hygieia Team,
 I would appreciate your help. I have managed to get thru quite a few configuration issues by myself.
 
 My key question is - can the UI and API run in different hosts. I have made changes to gulpfile.js to get the UI connect to API - I can signup for an account now - I see the account created in mongodb but when i try to login with the new account, it doesnt work. I see this error message in api log:

o.s.web.servlet.PageNotFound - Request method 'POST' not supported

I would appreciate your help to resolve this please.
Our team thinks the product has lot of promise but we need to setup and see it for ourself to confirm.
Your help in the setup will be very much appreciated.

**Comment by murali-kpmg** [comment]
Satish, Team, 
 can you please advise on why i cant login thru the account created (details in the update above).

**Comment by nireeshT** [comment]
@murali-kpmg  - need more information on error. Can you run the api in debug mode, collect log and paste it here. For changing to debug mode - go to -> api/logback.xml - >  root level ="DEBUG"
Re-run api.

**Comment by murali-kpmg** [comment]
Thanks Nireesh - Here is what I see after turning on debugging:

2017-05-02 14:18:54,268 DEBUG o.s.web.servlet.DispatcherServlet - DispatcherServlet with name 'dispatcherServlet' processing POST request for [/api/login]
2017-05-02 14:18:54,268 DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping - Looking up handler method for path /login
2017-05-02 14:18:54,284 DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping - Did not find handler method for [/login]
2017-05-02 14:18:54,284 DEBUG o.s.w.s.h.SimpleUrlHandlerMapping - Matching patterns for request [/login] are [/**]
2017-05-02 14:18:54,284 DEBUG o.s.w.s.h.SimpleUrlHandlerMapping - URI Template variables for request [/login] are {}
2017-05-02 14:18:54,284 DEBUG o.s.w.s.h.SimpleUrlHandlerMapping - Mapping [/login] to HandlerExecutionChain with handler [ResourceHttpRequestHandler [locations=[class path resource [static/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@720607fe]]] and 1 interceptor
2017-05-02 14:18:54,284 DEBUG o.s.w.s.m.a.ResponseStatusExceptionResolver - Resolving exception from handler [ResourceHttpRequestHandler [locations=[class path resource [static/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@720607fe]]]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported
2017-05-02 14:18:54,284 DEBUG o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolving exception from handler [ResourceHttpRequestHandler [locations=[class path resource [static/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@720607fe]]]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported
2017-05-02 14:18:54,284 WARN  o.s.web.servlet.PageNotFound - Request method 'POST' not supported
2017-05-02 14:18:54,284 DEBUG o.s.web.servlet.DispatcherServlet - Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling

Application.properties for api is defined as follows:

 Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

server.contextPath=/api
server.port=8082

version.number=@application.version.number@

Please let me know what is the problem here?

**Comment by nireeshT** [comment]
@murali-kpmg  refer https://github.com/capitalone/Hygieia/issues/1151

**Comment by murali-kpmg** [comment]
I read thru the ticket log for #1151. I don't have any compilation issues for api.
The other ticket doesn't say conclusively if the issues were resolved.

As i said earlier, I'm able to signup for an id and I see the new id and password inserted into mongo.
But when i use the new id and password to login, I get this error.

Hygieia Team,
 Please answer the question above - I think this is not the same problem as #1151.

@tabladrum @amitmawkin : Could you please advise on this?
Many Thanks

**Comment by murali-kpmg** [comment]
Hygieia Team, can you please help with my question?

Thanks

**Comment by murali-kpmg** [comment]
It is connected to API but still seeing the errors:
2017-05-11 19:57:45,006 DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'basicErrorCon
troller'
2017-05-11 19:57:45,007 DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor - Written [{timestamp=Thu May 11 19:57:45 UTC 2017, statu
s=405, error=Method Not Allowed, exception=org.springframework.web.HttpRequestMethodNotSupportedException, message=Requ
est method 'POST' not supported, path=/api/login}] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@4116a7ed]
2017-05-11 19:57:45,007 DEBUG o.s.web.servlet.DispatcherServlet - Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2017-05-11 19:57:45,007 DEBUG o.s.web.servlet.DispatcherServlet - Successfully completed request
2017-05-11 19:57:45,007 DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'enableEncryptablePropertySourcesPostProcessor'
2017-05-11 19:57:45,007 DEBUG c.u.j.EnableEncryptablePropertySourcesPostProcessor - Application Event Raised: ServletRequestHandledEven

**Comment by murali-kpmg** [comment]
@tabladrum @amitmawkin : Could you please help?

**Comment by satishc1** [comment]
@murali-kpmg Your issue heading is "Jira collector connection issues", but your latest comments are trying to get the UI to talk to the api. Also it appears you have changed the api to run on port 8082 and your jira collector seems to be doing something with port 8080.

Try cleaning up your setup. Shutdown your collectors. Do a fresh build with the latest master. Run only the api (on port 8080) and see if it launches without any errors. Then run the UI and try to create an account. It that doesn't work, post your build log and api log.

**Comment by Sbrenthughes** [comment]
@murali-kpmg Please reopen if you experience anymore issues with your original Issue.
