### ISSUE TITLE
NumberFormatException Error while creating Docker

### ISSUE THREAD

**Issue by sraghu-rs** [capitalone/Hygieia#1364]
I am executing command "mvn clean package -pl UI docker:build" and getting java NumberFormatException error. Can someone help?

[INFO] Copying C:\Hygieia_git\Hygieia\UI\docker\default.conf -> C:\Hygieia_git\H
ygieia\UI\target\docker\default.conf
[INFO] Copying C:\Hygieia_git\Hygieia\UI\docker\Dockerfile -> C:\Hygieia_git\Hyg
ieia\UI\target\docker\Dockerfile
[INFO] Building image hygieia-ui
Step 1/7 : FROM docker.io/nginx:latest
Pulling from library/nginx
36a46ebd5019: Pulling fs layer
57168433389f: Pulling fs layer
57168433389f: Downloading [>                                                  ]
 228.5kB/21.53MBwnload complete
java.lang.NumberFormatException: For input string: "1B["
        at java.lang.NumberFormatException.forInputString(NumberFormatException.
java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.<init>(Integer.java:867)
        at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:122
)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
        at java.io.PrintStream.write(PrintStream.java:480)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        at java.io.PrintStream.write(PrintStream.java:526)
        at java.io.PrintStream.print(PrintStream.java:669)
        at java.io.PrintStream.println(PrintStream.java:806)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:423)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)

**Comment by UpeshGit** [comment]
Hey,  I am also facing the same issue, did you get any solution for this?

**Comment by MarkRx** [comment]
See if you can find any funny characters in the Dockerfile

**Comment by nitin1706** [comment]
@sraghu-rs : can you share full stack trace of error.

**Comment by nitin1706** [comment]
re-open if issue still exists.
