### ISSUE TITLE
No result was available from Jira unexpectedly

### ISSUE THREAD

**Issue by smlcodes** [capitalone/Hygieia#1376]
`Query : key in (0.0,1.0,13.0,2.0,3.0,4.0,5.0,20.0,8.0)
2017-05-09 13:14:08,020 ERROR c.c.d.client.DefaultJiraClient - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={}, errorMessages=[The issue key '0.0' for field 'key' is invalid., The issue key '1.0' for field 'key' is invalid., The issue key '13.0' for field 'key' is invalid., The issue key '2.0' for field 'key' is invalid., The issue key '20.0' for field 'key' is invalid., The issue key '3.0' for field 'key' is invalid., The issue key '4.0' for field 'key' is invalid., The issue key '5.0' for field 'key' is invalid., The issue key '8.0' for field 'key' is invalid.]}]}
RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={}, errorMessages=[The issue key '0.0' for field 'key' is invalid., The issue key '1.0' for field 'key' is invalid., The issue key '13.0' for field 'key' is invalid., The issue key '2.0' for field 'key' is invalid., The issue key '20.0' for field 'key' is invalid., The issue key '3.0' for field 'key' is invalid., The issue key '4.0' for field 'key' is invalid., The issue key '5.0' for field 'key' is invalid., The issue key '8.0' for field 'key' is invalid.]}]}
	at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.claim(DelegatingPromise.java:47)
	at com.capitalone.dashboard.client.DefaultJiraClient.getEpics(DefaultJiraClient.java:294)
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.loadEpicData(StoryDataClientImpl.java:652)
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateMongoInfo(StoryDataClientImpl.java:260)
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:167)
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:125)
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:1)
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

**Comment by MarkRx** [comment]
Double check your config. I suspect one of your fields is incorrect. Keys do not have decimals.

**Comment by smlcodes** [comment]
## application.properties config file in JIRA collector as follows. Pls let me know if any thing wrong.
### ('#') is removed for display purpose
` Database Name
dbname=jiradb

 Database HostName - default is localhost
dbhost=localhost

 Database Port - default is 27017
dbport=27017

 MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

 Database Username - default is blank
 dbusername=db

 Database Password - default is blank
 dbpassword=dbpass

 Logging File location
logging.file=./logs/jira.log

 PageSize - Expand contract this value depending on Jira implementation's
 default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

 Delta change date that modulates the collector item task
 Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

 Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

 ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

 JIRA CONNECTION DETAILS:
 Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
feature.jiraProxyUrl=http://proxy.com
feature.jiraProxyPort=9000
feature.jiraBaseUrl=https://jira.smlcodes.com
feature.jiraQueryEndpoint=rest/api/2
 For basic authentication, requires username:password as string in base64
 This command will make this for you:  echo -n username:password | base64
echo -n smlcodes:Scoder@166 | base64


credencials : 
feature.jiraCredentials=dmluYXlrdW1hci5wYXRlbDpNYXItMjAxNw==
 OAuth is not fully implemented; please blank-out the OAuth values:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=


 In Jira, general IssueType IDs are associated to various "issue"
 attributes. However, there is one attribute which this collector's
 queries rely on that change between different instantiations of Jira.
 Please provide a string name reference to your instance's IssueType for
 the lowest level of Issues (e.g., "user story") specific to your Jira
 instance.  Note:  You can retrieve your instance's IssueType Name
 listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
 Multiple comma-separated values can be specified.

feature.jiraIssueTypeNames=Story


 In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
 which includes a list of information.  This field allows you to specify that data field for your
 instance of Jira. Note: You can retrieve your instance's sprint data field name
 via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
 your custom field name describes the values in this field:
 https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]

feature.jiraSprintDataFieldName=customfield_10000


 In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
 which includes a list of information.  This field allows you to specify that data field for your instance
 of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
 queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
 epic value you expect to see, and is the only field that does this for a given issue:
 https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]

feature.jiraEpicIdFieldName=customfield_10002


 In Jira, your instance will have its own custom field created for "story points"
 This field allows you to specify that data field for your instance
 of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
 queried user story issue has story points set on it; your custom field name describes the
 story points value you expect to see:
 https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]

feature.jiraStoryPointsFieldName=customfield_10003


 In Jira, your instance will have its own custom field created for "team"
 This field allows you to specify that data field for your instance
 of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
 queried user story issue has team set on it; your custom field name describes the
 team value you expect to see:
 https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]

feature.jiraTeamFieldName=
feature.jiraIssueTypeId=Story`

**Comment by MarkRx** [comment]
You did not fill out the field name parameters.

**Comment by Sbrenthughes** [comment]
@smlcodes if you are still having problems please reopen.

**Comment by han2013** [comment]
how to solve?
