### ISSUE TITLE
Missing properties on docker api?

### ISSUE THREAD

**Issue by hgarciao** [capitalone/Hygieia#1383]
The documentation in : https://github.com/capitalone/Hygieia/tree/master/api
 Says  this about properties in api module : "All the above values are optional." 

But when i execute my docker image , it generates the following error:

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'activeDirectoryLdapAuthenticationProvider' defined in class path resource [com/capitalone/dashboard/config/WebSecurityConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider]: Factory method 'activeDirectoryLdapAuthenticationProvider' threw exception; nested exception is java.lang.IllegalArgumentException: Url cannot be empty
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at com.capitalone.dashboard.Application.main(Application.java:45)
        ... 6 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider]: Factory method 'activeDirectoryLdapAuthenticationProvider' threw exception; nested exception is java.lang.IllegalArgumentException: Url cannot be empty
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 23 more
Caused by: java.lang.IllegalArgumentException: Url cannot be empty
        at org.springframework.util.Assert.isTrue(Assert.java:68)
        at org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.<init>(ActiveDirectoryLdapAuthenticationProvider.java:118)
        at com.capitalone.dashboard.config.WebSecurityConfig.activeDirectoryLdapAuthenticationProvider(WebSecurityConfig.java:49)
        at com.capitalone.dashboard.config.WebSecurityConfig$$EnhancerBySpringCGLIB$$c4ddc67e.CGLIB$activeDirectoryLdapAuthenticationProvider$4(<generated>)
        at com.capitalone.dashboard.config.WebSecurityConfig$$EnhancerBySpringCGLIB$$c4ddc67e$$FastClassBySpringCGLIB$$decb3be4.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355)
        at com.capitalone.dashboard.config.WebSecurityConfig$$EnhancerBySpringCGLIB$$c4ddc67e.activeDirectoryLdapAuthenticationProvider(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 24 more

Note :  I am using only mongodb properties in my dockerfile

Please help me :(

**Comment by rob-miller-777** [comment]
Yeah, we found that as well the other day, and it's on a list of things we have to fix.  You could probably work around this by throwing any url into the "Ldap url" for now, and just "{}" for the user dn.  The only thing that wouldn't work is the ldap login.

**Comment by rob-miller-777** [comment]
See #1385

**Comment by satishc1** [comment]
Closed.
