### ISSUE TITLE
API not starting

### ISSUE THREAD

**Issue by murali-kpmg** [capitalone/Hygieia#1385]
I downloaded the latest code from Git, built  it and started API.
API shuts down with these errors:

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider]: Factory method 'activeDirectoryLdapAuthenticationProvider' threw exception; nested exception is java.lang.IllegalArgumentException: Url cannot be empty
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 23 more
Caused by: java.lang.IllegalArgumentException: Url cannot be empty
        at org.springframework.util.Assert.isTrue(Assert.java:68)
        at org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.<init>(ActiveDirectoryLdapAuthenticationProvider.java:118)
        at com.capitalone.dashboard.config.WebSecurityConfig.activeDirectoryLdapAuthenticationProvider(WebSecurityConfig.java:49)
        at com.capitalone.dashboard.config.WebSecurityConfig$$EnhancerBySpringCGLIB$$7e96236b.CGLIB$activeDirectoryLdapAuthenticationProvider$2(<generated>)
        at com.capitalone.dashboard.config.WebSecurityConfig$$EnhancerBySpringCGLIB$$7e96236b$$FastClassBySpringCGLIB$$d829ef8a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355)
        at com.capitalone.dashboard.config.WebSecurityConfig$$EnhancerBySpringCGLIB$$7e96236b.activeDirectoryLdapAuthenticationProvider(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)

This is the configuration file:
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

server.contextPath=/api
server.port=8080

This was done based on your comments in #1329 

Can you advise what could be wrong here?

**Comment by rob-miller-777** [comment]
@satishc1 Looks like the issue is that you still try to create the active directory bean even if no ldap server is provided.  You will probably have to do something similar to what I did in that config and check to see if they are provided before configuring that bean. This comes from #1374 .

**Comment by rob-miller-777** [comment]
#1383 is the same issue.

**Comment by murali-kpmg** [comment]
Sorry @rob-miller-777, do I need to make a config change or will this require code changes and a new release for me to test further?

**Comment by rob-miller-777** [comment]
You can probably hack around this by just setting the ldap url and user dn to something for now.  The ldap login obviously wouldn't work, but it should get it up and running.  

Throw this in there and see if it starts for now as a workaround.  It will require a code change to fix.
`auth.ldapServerUrl=ldap://foo`
`auth.ldapUserDnPattern=uid={0}`

**Comment by murali-kpmg** [comment]
With the dummy config for ldap, api comes up. Thanks @rob-miller-777

**Comment by rob-miller-777** [comment]
No problem, if I get some time today, I can put together a pull request to get that issue fixed.

**Comment by murali-kpmg** [comment]
perfect - this build solved by other problem of UI connecting to API (#1329) but I will be happy to update with your latest.

**Comment by satishc1** [comment]
@rob-miller-777 Ah yes.. the auth.ldapServerUrl property existence needs to be checked 👍 . I'll take a look at what needs to be changed in case you haven't already sent in a PR for it.

**Comment by rob-miller-777** [comment]
I have a pull request I am just waiting on some approvals here to submit, hopefully should have it open today, if not Monday at the latest.

**Comment by rob-miller-777** [comment]
In case you want an early preview, here's what I was thinking.  https://github.com/capitalone/Hygieia/compare/master...StateFarmIns:activeDirectoryFix

**Comment by satishc1** [comment]
@rob-miller-777 That looks good. Thank you. 👍
