### ISSUE TITLE
sonar collecter not displaying data

### ISSUE THREAD

**Issue by vgandra** [capitalone/Hygieia#1408]
Hello,

I'm getting below error when i configured sonar collecter, and not able to see the projects names in Configure Code Analysis Widget and giving no results found

2017-05-22 16:17:00,000 INFO c.c.d.collector.CollectorTask - Running Collector: Sonar
2017-05-22 16:17:00,002 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
at java.util.ArrayList.addAll(ArrayList.java:577) ~[na:1.8.0_131]
at com.capitalone.dashboard.model.SonarCollector.prototype(SonarCollector.java:29) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.SonarCollectorTask.getCollector(SonarCollectorTask.java:57) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]

can anyone help on this???

Thanks!!!

**Comment by kavalpatel15** [comment]
Hey vgandra,
Could you post your sonar.properties files?

**Comment by vgandra** [comment]
Thanks for your quick turn.!!!

Here is my .properties file


dbname=dashboarddb
#dbusername=dashboarduser
#dbpassword=ENC(C9PLVDJ/1OfkT/3jvC/wEB20R1XPJtg9)
#dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
auth.ldapServerUrl=ldap://foo
auth.ldapUserDnPattern=uid={0}

# Collector schedule (required)
sonar.cron=0 0/1 * * * *

# Sonar server(s) (required) - Can provide multiple
sonar.servers[0]=http://19.68.11.15:9000
# Sonar version, match array index to the server. If not set, will default to version prior to 6.
sonar.versions[0]=5.6.3
# Sonar Metrics - Required.
#Sonar versions lesser than 5.4
sonar.metrics[0]=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,violations_density,sqale_index,test_success_density,test_failures,test_errors,tests
#for Sonar 5.4 and above
sonar.metrics[0]=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details

pls help me on this I'm struggling from last 2 days

I tried by giving aswell.
 sonar.username=
sonar.password= 

Thanks..!!!!

**Comment by vgandra** [comment]
Thanks for your quick turn.!!!

Here is my .properties file

dbname=dashboarddb
#dbusername=dashboarduser
#dbpassword=ENC(C9PLVDJ/1OfkT/3jvC/wEB20R1XPJtg9)
#dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
auth.ldapServerUrl=ldap://foo
auth.ldapUserDnPattern=uid={0}

sonar.cron=0 0/1 * * * *

sonar.servers[0]=http://19.68.11.15:9000

sonar.versions[0]=5.6.3

#Sonar versions lesser than 5.4
sonar.metrics[0]=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,violations_density,sqale_index,test_success_density,test_failures,test_errors,tests
#for Sonar 5.4 and above
sonar.metrics[0]=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details

pls help me on this I'm struggling from last 2 days

I tried by giving user name and pass aswell.
sonar.username=
sonar.password=

**Comment by willuk2010** [comment]
Im getting the same issue as the above.

2017-05-24 13:00:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2017-05-24 13:00:00,009 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at java.util.ArrayList.addAll(ArrayList.java:577) ~[na:1.8.0_111]
        at com.capitalone.dashboard.model.SonarCollector.prototype(SonarCollector.java:29) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.SonarCollectorTask.getCollector(SonarCollectorTask.java:57) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.SonarCollectorTask.getCollector(SonarCollectorTask.java:26) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:48) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by poloHex** [comment]
i also have such error. is there any one working on it?

**Comment by kavalpatel15** [comment]
Hey guys,

I had a similar issue when i was setting up my sonar collector but my issue with setting up the version numbers for each of my sonar servers. I had left the field completely blank because all my versions at the time were below 5.4 so it would throw me a null pointer but adding the server versions fixed my problem. Looking at your properties file that does not seem to be the issue for you. Sorry i couldnt help more.

**Comment by nitin1706** [comment]
this error is due to blank values in sonar properties. Please ensure values for below properties have been provided:
1.)  sonar.versions
2.)  sonar.metrics
3.)  sonar.servers

This has been fixed in latest codebase.

**Comment by Sbrenthughes** [comment]
Closing because fixed - https://github.com/capitalone/Hygieia/pull/1613
