### ISSUE TITLE
Not able to see Build Widget Section in the Dashboard

### ISSUE THREAD

**Issue by harish961** [capitalone/Hygieia#1425]
Hi,

I have built the Hygieia app with the instructions given. I'm not able to see the build widget section at all in the dashboard. It is missing. Can someone help. I'm seeing below errors in the console. Attached the screenshot. Also seeing that in src-->Components-->widgets folder of UI, build folder is missing.

TypeError: Cannot read property 'view' of undefined
    at link (http://localhost:3000/app/dashboard/directives/widget.js:49:64)
    at http://localhost:3000/bower_components/bower.js:9682:44
    at invokeLinkFn (http://localhost:3000/bower_components/bower.js:9688:9)
    at nodeLinkFn (http://localhost:3000/bower_components/bower.js:9198:11)
    at delayedNodeLinkFn (http://localhost:3000/bower_components/bower.js:9446:11)
    at compositeLinkFn (http://localhost:3000/bower_components/bower.js:8547:13)
    at compositeLinkFn (http://localhost:3000/bower_components/bower.js:8550:13)
    at compositeLinkFn (http://localhost:3000/bower_components/bower.js:8550:13)
    at nodeLinkFn (http://localhost:3000/bower_components/bower.js:9193:24)
    at compositeLinkFn (http://localhost:3000/bower_components/bower.js:8547:13) <widget name="build" class="ng-isolate-scope">

Thanks,
Harish.

![image](https://cloud.githubusercontent.com/assets/28887184/26499134/17db1e1a-424f-11e7-9dd6-7a77af72c24c.png)

**Comment by harish961** [comment]
Issue was with the base code.

**Comment by git4giri** [comment]
I think in the location 'UI\src\components\widgets' there should be the build dir for the build widget which is missing due to the .gitignore file in the root.
In that file line#18 has one entry 'build'... if you can remove that entry will solve the issue

**Comment by harish961** [comment]
Thank you so much, I have seen this after I put the query. Thanks again.

Thanks and Regards,
Venkata Harish Kumar Kasibhotla
DevOps, WFN, ADP India
Hyderabad @ Work:91 406 757 8045 Mobile: 9959972732
CM SD Ticket Link:  Click here<http://servicecatalog:8080/usm/wpf?Node=icguinode.catalogitemdetails&Args=10542&ObjectID=10542&NspPath=>
