### ISSUE TITLE
Product Dashboard Dexie Error

### ISSUE THREAD

**Issue by kavalpatel15** [capitalone/Hygieia#1432]
Hi all,

I have an issue with the product dashboard view. I have configured the Hygieia plugin for jenkins pre 2.0 and it is pushing build and deploy information however, it wont properly populate the information onto the product dashboard. (ScreenShot below). I placed a breakpoint on the link that throws the error and the stack trace is below. I tried to trace it back to to figure out why it is calling .filter from an undefined var but it just takes me throw the bower.js file. 

Thanks!

![productdashboardissue](https://cloud.githubusercontent.com/assets/11862646/26456628/ac74f632-413b-11e7-9b4a-ae61fa4c6f08.PNG)

"TypeError: Cannot read property 'filter' of undefined
    at http://dlsysadm-ap73:3000/components/widgets/product/js/commit-data.js:311:25
    at s (http://dlsysadm-ap73:3000/bower_components/bower.js:68837:36760)
    at t.b (http://dlsysadm-ap73:3000/bower_components/bower.js:68837:37841)
    at a (http://dlsysadm-ap73:3000/bower_components/bower.js:68837:37548)
    at http://dlsysadm-ap73:3000/bower_components/bower.js:68837:36478
    at u (http://dlsysadm-ap73:3000/bower_components/bower.js:68837:38081)
    at Object.<anonymous> (http://dlsysadm-ap73:3000/bower_components/bower.js:68837:9193)
    at Object.fire (http://dlsysadm-ap73:3000/bower_components/bower.js:68837:31321)
    at IDBTransaction.o.oncomplete (http://dlsysadm-ap73:3000/bower_components/bower.js:68837:19252)"

**Comment by xiaods** [comment]
@kavalpatel15 how do you setup the tools? could you please share some steps.

**Comment by kavalpatel15** [comment]
I am unsure of what you are looking for specifically but for the all the widgets besides Build and Deploy, I followed the guides for each of the collectors and for the Build and Deploy widgets I used the Hygieia-Jenkins-Plugin which does push data to the widgets. Using the data that was pushed i configured those widgets. I configured the piplelines in each team dashboard as well. Screenshots of the Build and Deploy widgets below as well as the team pipeline. 

![builddeploywidgets](https://user-images.githubusercontent.com/11862646/27136214-b83a626a-50e8-11e7-8bb0-80f1a65a6484.PNG)
![teampipeline](https://user-images.githubusercontent.com/11862646/27136215-b83c2532-50e8-11e7-821b-577ac4bdc378.PNG)

**Comment by willuk2010** [comment]
@kavalpatel15 exactly the same issue here, deploy widget, and pipeline tab are fine in the Team View, but in the Product view, the deployment box is blank. (using Jenkins Publish plugin)

**Comment by nireeshT** [comment]
@kavalpatel15  - Throw more light on -  "it wont properly populate the information onto the product dashboard." Do you have issue with the commits not showing up for a specific team dashboard ? I know the above error occurs when team dashboard does not have any commits, I can fix that. Want to understand your issue more in detail. 

@willuk2010  - COMMIT and BUILD stages are not showing any commits? share screenshot.

**Comment by willuk2010** [comment]
@nireeshT yeh, i have commits in the Commit and Build stages. ill get you a screen shot in a tick

**Comment by kavalpatel15** [comment]
hey @nireeshT the team dashboards do have commits on the build and commit widgets. Here is a screen shot of one of the team dashboards:

![teamdashboard](https://user-images.githubusercontent.com/11862646/27230749-4bf9a6d2-527e-11e7-963e-5089e2fe3c09.PNG)

**Comment by nireeshT** [comment]
@kavalpatel15  - I have fixed above issue in PR 1484. That occurs when your production stages did not have any commits. I see team dash "NDC API" is showing the commits moved to DEV, so product dash is showing the commits in environment stages. There is no prod stage , that is why the issue occurred. Set up a prod stage and you should see no of commits to prod.

**Comment by willuk2010** [comment]
@nireeshT 

Currently we do not have PRE/PRO deployments, just DEV for now.

Team Dashboard

![image](https://user-images.githubusercontent.com/1331751/27233542-ae8b82e2-52b1-11e7-80b7-332d092e5e6e.png)

Product Dashboard

![image](https://user-images.githubusercontent.com/1331751/27233492-84ac6e8c-52b1-11e7-8389-67b239a3d01b.png)

**Comment by kavalpatel15** [comment]
@nireeshT 
Another issue we are facing is the build block  does not show any other information besides the latest build status. I originally thought it was because of the Dixie error. Do you have any insight into what may be causing this?

**Comment by nireeshT** [comment]
@kavalpatel15  Commits move from "COMMIT" to "BUILD" stage when commits are build. Once the build artifacts are deployed in environments, commits will move from build stage to environments deployed. Transition seems like COMMIT -> BUILD-> DEV -> TEST -> PROD.
Once the commits move to later stages, they will disappear in early stages. In your case, if you see the commits moved to DEV, they should disappear in COMMIT and BUILD, unless you have different commits which are not deployed yet in DEV.

**Comment by kavalpatel15** [comment]
@nireeshT  We do have commits that are in build but have yet to be deployed into any other environment.

**Comment by nireeshT** [comment]
@kavalpatel15  - you can change cron settings of code repo collector to desired value. Product dashboard should not take time to refresh.

**Comment by willuk2010** [comment]
Any ideas with my product dashbaord @nireeshT ?

Cheers.

**Comment by Sbrenthughes** [comment]
@kavalpatel15 please reopen if you have anymore issue with this.

**Comment by jaigopinath528** [comment]
Hi  guys  tried to setup the hygieia  jenkins build collector


2020-09-29 04:28:00,001 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Getting Collector: Hudson
2020-09-29 04:28:00,006 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Starting Collector=Hudson
2020-09-29 04:28:00,011 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-09-29 04:28:00,012 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - http://user:token@localhost:9999/
2020-09-29 04:28:00,013 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-09-29 04:28:00,025 [taskScheduler-1] INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 0/4 pageSize 100...
2020-09-29 04:28:00,038 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2020-09-29 04:28:00,039 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2020-09-29 04:28:00,054 [taskScheduler-1] ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 404 Not Found. URL =http://localhost:9999/api/job/test3job/1/
2020-09-29 04:28:00,056 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2020-09-29 04:28:00,059 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New configs             0        0s
2020-09-29 04:28:00,060 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished                         0s
2020-09-29 04:28:00,060 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished running Collector=Hudson timeTaken=53 collectorItems=0
