### ISSUE TITLE
SonarQube collector not working

### ISSUE THREAD

**Issue by prvnsinghal** [capitalone/Hygieia#1434]
# application.propertis is given below :

dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
sonar.cron=0 0/1 * * * *
sonar.username=
sonar.password=
sonar.servers[0]=http://xyz:9000
sonar.metrics=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,sqale_index,test_success_density,test_failures,test_errors,tests

## but it is giving error

2017-05-31 08:12:07,963 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 4]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=315596}
2017-05-31 08:12:08,634 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2017-05-31 08:12:08,650 INFO  com.capitalone.dashboard.Application - Started Application in 4.92 seconds (JVM running for 5.739)
2017-05-31 08:13:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar

> 2017-05-31 08:13:00,021 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
> java.lang.NullPointerException:  null

        at java.util.ArrayList.addAll(ArrayList.java:577) ~[na:1.8.0_131]
        at com.capitalone.dashboard.model.SonarCollector.prototype(SonarCollector.java:29) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.SonarCollectorTask.getCollector(SonarCollectorTask.java:57) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.SonarCollectorTask.getCollector(SonarCollectorTask.java:26) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:48) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
2017-05-31 08:14:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2017-05-31 08:14:00,013 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null

**Comment by prvnsinghal** [comment]
yes I tried with that also

**Comment by Sbrenthughes** [comment]
Does your Sonar require authentication?

**Comment by satishc1** [comment]
@prvnsinghal paste your command that you are using to start the sonar collector along with the resulting full log.

**Comment by prvnsinghal** [comment]
@Sbrenthughes yes, It need authentication....but dont' know how to pass authentication values

**Comment by prvnsinghal** [comment]
@satishc1 sudo java -jar sonar-codequality-collector-2.0.5-SNAPSHOT.jar --spring.config.name=collectors --spring.config.location=/home/ubuntu/Hygieia/collectors/build/sonar/application.properties
this is my command

**Comment by prvnsinghal** [comment]
@Sbrenthughes @satishc1 do you guys have any solution??

**Comment by meet101** [comment]
Not sure which version of Sonar are you using. I have just configured sonar 5.6 with Hygieia. here is my .properties file. I don't see version "sonar.version[0]" in your .properties file. I am not sure it will fix your issue or not. You can give a try. 
sonar.properties
dbname=hygieiadb
dbhost=127.0.0.1
dbport=27017
dbusername=admin
dbpassword=admin
sonar.cron=0 0/5 * * * *
sonar.servers[0]=http://xxxxxxxxxxxxxx:9000/
**sonar.versions[0]=5.6**
#Sonar Metrics - Required.
#Sonar versions lesser than 5.4
#sonar.metrics[0]=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,violations_density,sqale_index,test_success_density,test_failures,test_errors,tests
#for Sonar 5.4 and above
**sonar.metrics[0]**=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,violations_density,sqale_index,test_success_density,test_failures,test_errors,tests

**Comment by satishc1** [comment]
@prvnsinghal The command you are using to launch the collector is wrong.
Use this
sudo java -jar <path to your jar file> --spring.config.name=sonar --spring.config.location=<path to your prop file>

**Comment by prvnsinghal** [comment]
Thankyou @satishc1, Now it is working for me.
