### ISSUE TITLE
Jira collector issue: Not showing any teams on UI Configure Feature Widget

### ISSUE THREAD

**Issue by meet101** [capitalone/Hygieia#1455]
Hi, I am trying to setup a Jira collector. I am trying on Jira cloud. When i try to configure it on UI. I don't see any teams. I can see only available projects but not teams as per image
![image](https://user-images.githubusercontent.com/17306302/26848022-12fca220-4acd-11e7-8631-5240b616d56b.png)
I don't see any error while running collector. here is the output from collector,
2017-06-06 19:31:00,005 INFO  c.c.d.collector.CollectorTask - https://agerodemo.atlassian.net/
2017-06-06 19:31:00,005 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-06 19:31:00,005 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2017-06-06 19:31:00,299 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2017-06-06 19:31:00,722 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 0
2017-06-06 19:31:00,722 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2017-06-06 19:31:00,723 INFO  c.c.d.collector.CollectorTask - Finished                         0s

here is my jira.properties file
dbname=hygieiadb
dbhost=127.0.0.1
dbport=27017
dbusername=admin
dbpassword=admin
logging.file=./logs/jira.log
feature.pageSize=100
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000
feature.cron=0 * * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.jiraBaseUrl=https://agerodemo.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=YWRtaW46YWRtaW4xMDE=
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10002
feature.jiraStoryPointsFieldName=customfield_10003
feature.jiraTeamFieldName=

Does anyone got this issue before? can someone please advice how to resolve this issue?

**Comment by irvingoe** [comment]
Don't you have to populate this setting?
feature.jiraTeamFieldName=

I do remember reading something about that

**Comment by irvingoe** [comment]
Check this out
https://github.com/capitalone/Hygieia/blob/eb0dfd7532c49c8222e83a55d1f5ebf4735811ee/collectors/feature/jira/src/main/java/com/capitalone/dashboard/client/DefaultJiraClient.java#L157

you see how is looking a value in that property, otherwise it just give you an empty array of results.

```
List<Team> result = new ArrayList<>();
	    if (StringUtils.isEmpty(featureSettings.getJiraTeamFieldName())) {
	        return result;
	    }
```

**Comment by meet101** [comment]
understood. I wrote a team name and put it like, feature.jiraTeamFieldName=Test
I got this error in collector,
2017-06-06 20:48:00,007 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-06 20:48:00,007 INFO  c.c.d.collector.CollectorTask - https://agerodemo.atlassian.net/
2017-06-06 20:48:00,007 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-06 20:48:00,499 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: https://agerodemo.atlassian.net/rest/tempo-teams/1/team
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872) ~[na:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_131]
        at java.net.URLConnection.getContent(URLConnection.java:739) ~[na:1.8.0_131]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:434) ~[na:1.8.0_131]
        at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJiraClient.java:196) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:57) [jira-feature-collector.jar                            !/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SN                            APSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNA                            PSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4                            .2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:                            4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]



I have created Test group in Jira as shown in image. I am new to Jira as well. I am trying it with free version. In new version of Jira cloud. i don't think they have a team. They replaced it with Groups.  is it correct or wrong? 
![image](https://user-images.githubusercontent.com/17306302/26851341-8b833f0a-4ad8-11e7-9787-b780cf71a750.png)

**Comment by irvingoe** [comment]
Try to get it following the instruction in the readme file

#############################################################################
# In Jira, your instance will have its own custom field created for "team"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# **https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]**
#############################################################################

I don't use Jira by the way, I just happened to dig into the code yesterday so I slightly remember the logic it is doing to get the data.

**Comment by sraghu-rs** [comment]
I am also facing similar problem in UI. I have also raised issue https://github.com/capitalone/Hygieia/issues/1456

Hopefully someone will suggest.

**Comment by nireeshT** [comment]
@meet101  @sraghu-rs  -Yes, Any should be one of the option. Working on it.

**Comment by meet101** [comment]
@nireshT - Thank you for looking into it.

**Comment by sraghu-rs** [comment]
@niresht - Thanks.

**Comment by nireeshT** [comment]
Refer #1458

**Comment by MarkRx** [comment]
If you are not using the tempo teams plugin then you need to keep the team field property blank

**Comment by nireeshT** [comment]
@meet101  @sraghu-rs  - update to latest code base. You should see option "Any" when you start typing in input field.

**Comment by meet101** [comment]
Thank you guys, I got it working. 
I have opened another issue in git hub before few a week ago. I am requesting you can someone please take a look and advice. It's about bitbucket. I am not able to setup bitbucket private repo. due to wrong URL as per me. I have described here #1418. 
Can someone please guide me. It would be great.  

Thank you, Appreciate your help!

**Comment by sachingupta771** [comment]
Hi All
I'm facing same problem. pls tell any solution that worked for any of you guys.

**Comment by meet101** [comment]
@sachingupta771  - If you get a latest code. You should not have same issue. If you still have same issue post error logs.

**Comment by tsr2017** [comment]
I am unable to see any option when I enter any in both team and project input field. 
Also I now I am unable to remove any from both input fields. Can anyone help me to fix this issue?

Thanks

**Comment by lenalevy** [comment]
Feature widget is showing in drop down only default "Any" in Team Name
What should be change in order to present list of teams ?

**Comment by nuttsky** [comment]
Even when the property feature.jiraTeamFieldName is set to the jira Team customfield name (i.e. customfield_10616) the Team name drop down only shows Any.  This looks to be broken.
