### ISSUE TITLE
Feature widget is not showing default "Any" Team Name

### ISSUE THREAD

**Issue by sraghu-rs** [capitalone/Hygieia#1456]
We are not using Temp Team plugin in JIRA cloud instance. JIRA collector is able to fetch all the project related information. However, when we try to configure feature dashboard, i do not see any drop down values in Team Name.

In the JIRA collector, we have not put any custom field against "feature.jiraTeamFieldName". Here is the snippet of the application properties.

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
feature.jiraTeamFieldName=

As per documentation, if we don't put any custom field name against "feature.jiraTeamFieldName", we should be able to get "Any" in the widget drop down.

![image](https://user-images.githubusercontent.com/27897251/26864109-e1eb45ae-4b73-11e7-8f31-24097dfc5669.png)

"Team Name" is a mandatory attribute in the widget hence we are not able to create dashboard at this moment.

A month back, in different instance, we were able to set up widget and there we received "Any" as Team Name (without Tempo plugin) but i see some changes to the config.html (compared with month old config.html code)

Can you please suggest?

Regards,
Raghav

**Comment by meet101** [comment]
@sraghu-rs  - Just for my info, 
1) Do we need to add below fields in .properties file? I don't find this filed in ReadME file anywhere.
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

2) For Jira cloud, Team it's similar as Group or it's different? I don't find anywhere teams in jira cloud.

**Comment by nireeshT** [comment]
@meet101 @sraghu-rs pull this or locally and test it out. I have added Any in drop down list. Type 'Any' in input field and you should be able to select. #1458

**Comment by meet101** [comment]
Thank you. Will test it and update here.

**Comment by sraghu-rs** [comment]
@nireeshT - I have pulled the latest code (entire Hygieia) and tested.

Below is my application.properties configuration. As mentioned, i have put 'Any' as field name in "feature.jiraTeamFieldName"

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

feature.jiraTeamFieldName=Any

After running the collector jar file, now it is looking for temp-team plug in and throwing ERROR message but it is proceeding.

Is this expected behavior? 
However, now i am able to get "Any" as Team name and able to display the dashboard. 

Thanks for quick assist.

Regards,
Raghav

2017-06-08 01:54:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2017-06-08 01:54:00,031 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-08 01:54:00,031 INFO  c.c.d.collector.CollectorTask - https://mycompany.jira.com/
2017-06-08 01:54:00,032 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-08 01:54:00,034 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2017-06-08 01:54:01,001 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: https://mycompany.jira.com/rest/tempo-teams/1/team
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_91]
	at java.net.URLConnection.getContent(Unknown Source) ~[na:1.8.0_91]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(Unknown Source) ~[na:1.8.0_91]
	at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJiraClient.java:196) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:57) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_91]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
2017-06-08 01:54:01,011 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2017-06-08 01:54:01,012 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2017-06-08 01:54:02,203 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 242
2017-06-08 01:54:02,551 INFO  c.c.d.collector.CollectorTask - Project Data          242        1s
2017-06-08 01:54:02,554 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2017-06-08 01:54:03,123 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2017-06-08 01:54:07,632 DEBUG c.c.d.client.DefaultJiraClient - Processing issues 0 - 99 out of 7495
2017-06-08 01:54:07,633 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 4509 ms
2017-06-08 01:54:07,634 DEBUG c.c.d.c.story.StoryDataClientImpl - Size of paged Jira response: 100

**Comment by MarkRx** [comment]
If you are not using the temp teams plugin then you have to keep the team field empty.

**Comment by willuk2010** [comment]
hey,

Im having a similar issue, "Search for a Project Name", and "Search for a Team Name", no matter what i put in, they return to blanks.. 

my config,

dbname=dashboard
dbhost=hygieia-mongodb
dbport=27017
dbusername=db
dbpassword=dbpass
feature.cron=0 * * * * *
feature.pageSize=1000
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
feature.jiraProxyUrl=
feature.jiraProxyPort=
feature.sprintDays=60
feature.sprintEndPrior=7
feature.scheduledPriorMin=2
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000
feature.jiraBaseUrl=https://uk-jira.almuk.xxxxxxxxxxxxx.corp
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
feature.jiraOauthAuthtoken=sdfghjkl==
feature.jiraOauthRefreshtoken=sdfagheh==
feature.jiraOauthRedirecturi=uri.this.is.test:uri
feature.jiraOauthExpiretime=234567890987
feature.deltaStartDate=2017-05-01T00:00:00.000000
feature.masterStartDate=2017-05-01T00:00:00.000000
feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10001
feature.jiraStoryPointsFieldName=customfield_10002
feature.jiraTeamFieldName=

jira log.

2017-06-08 14:18:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2017-06-08 14:18:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-08 14:18:00,008 INFO  c.c.d.collector.CollectorTask - https://uk-jira.almuk.xxxxxxxxxxx.corp
2017-06-08 14:18:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-08 14:18:00,009 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2017-06-08 14:18:00,196 INFO  c.c.d.collector.CollectorTask - Project Data            3        0s
2017-06-08 14:18:00,514 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 1
2017-06-08 14:18:00,515 INFO  c.c.d.collector.CollectorTask - Story Data              1        0s
2017-06-08 14:18:00,516 INFO  c.c.d.collector.CollectorTask - Finished                         0s

hygieia-jira-feature-collector is fresh 2.0.5 build from todays source code, and running in a docker container. Jira it self is a clean install, with just 3 test projects.

Cheers
Will

**Comment by irvingwa** [comment]
@willuk2010 I am seeing the same thing in docker. Before the latest build I was able to at least pull projects.

**Comment by willuk2010** [comment]
Also to add, i just noticed this in the UI logs.

10.0.0.11 - - [08/Jun/2017:14:22:00 +0000] "GET /api/scopecollector/page/5935830c6b661e00227fa930?page=0&search=ALMUK+Support&size=20&sort=description HTTP/1.1" **404** 163 "http://radiator.xxxxxxxxxxxx.corp/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36" "10.255.0.3"
10.0.0.11 - - [08/Jun/2017:14:22:00 +0000] "GET /api/teamcollector/page/5935830c6b661e00227fa930?page=0&search=&size=20&sort=description HTTP/1.1" **404** 162 "http://radiator.xxxxxxxxxxx.corp/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36" "10.255.0.3"
10.0.0.11 - - [08/Jun/2017:14:22:01 +0000] "GET /api/teamcollector/page/5935830c6b661e00227fa930?page=0&search=&size=20&sort=description HTTP/1.1" **404** 162 "http://radiator.xxxxxxxxxxx.corp/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36" "10.255.0.3"

404's when typing in the project name, or team name boxes..

**Comment by nireeshT** [comment]
@sraghu-rs @willuk2010  - update to latest code, you should see the option "Any" when yo start typing it in input field.

**Comment by willuk2010** [comment]
Hey @nireeshT mine is the latest, i pulled it about an hour ago mate.

**Comment by willuk2010** [comment]
@nireeshT seen as this is a platform i'm using to demo hygieia, i also just completely trashed my mongodb, and started all again fresh.. and i just cant enter anything into the Jira Project Name field, without it blanking out, none of my 3 projects are populated in the dropdown.

**Comment by irvingoe** [comment]
@willuk2010 could you try checking if this endpoint is returning any results for you? I'm working on a customization for a feature collector based on Jira but I can't get this endpoint to work or seems I don't understand it because it returns an empty array of 'scopes' aka projects.
http://API_URL/api/scopecollector/{JiraCollector_ID}
or try the swagger if it's better to try that endpoint
http://{API_URL}/api/swagger/index.html#/scope-controller

**Comment by willuk2010** [comment]
Ah, wait i only did the UI, and the Jira Collector, not the API... i have just re built and deployed the API and now i have projects in my project dropdown.

http://radiator.xxxxxxxxxxx.corp/api/scopecollector/page/59396274bfcbd80023d53f08? now returns project data.

[{"id":"59396274bfcbd80023d53f09","collectorId":"59396274bfcbd80023d53f08","pId":"10102","name":"ALMUK Support","projectPath":"ALMUK Support","beginDate":"","endDate":"","changeDate":"","assetState":"Active","isDeleted":"False"},{"id":"59396274bfcbd80023d53f0a","collectorId":"59396274bfcbd80023d53f08","pId":"10103","name":"Fake","projectPath":"Fake","beginDate":"","endDate":"","changeDate":"","assetState":"Active","isDeleted":"False"},{"id":"59396274bfcbd80023d53f0b","collectorId":"59396274bfcbd80023d53f08","pId":"10104","name":"Will Test","projectPath":"Will Test","beginDate":"","endDate":"","changeDate":"","assetState":"Active","isDeleted":"False"}]

However, the team box, doesn't give me "ANY",  and the endpoint for that returns an empty array.

http://radiator.xxxxxxxxxxxxxxxx.corp/api/teamcollector/page/59396274bfcbd80023d53f08?

returns []

Cheers
Will

**Comment by irvingoe** [comment]
oh I see, I'm glad the projects showed up at least :P 
It seems I need to update my API as well, my UI is pointing to the endpoint without 'page' on it.
Could you just confirm me if the other endpoint is working for you?
it'll be something like this
http://radiator.xxxxxxxxxxx.corp/api/scopecollector/59396274bfcbd80023d53f08?

Thanks in advance.

**Comment by willuk2010** [comment]
yep that endpoint works for me now.

returns,

[{"id":"59396274bfcbd80023d53f09","collectorId":"59396274bfcbd80023d53f08","pId":"10102","name":"ALMUK Support","projectPath":"ALMUK Support","beginDate":"","endDate":"","changeDate":"","assetState":"Active","isDeleted":"False"},{"id":"59396274bfcbd80023d53f0a","collectorId":"59396274bfcbd80023d53f08","pId":"10103","name":"Fake","projectPath":"Fake","beginDate":"","endDate":"","changeDate":"","assetState":"Active","isDeleted":"False"},{"id":"59396274bfcbd80023d53f0b","collectorId":"59396274bfcbd80023d53f08","pId":"10104","name":"Will Test","projectPath":"Will Test","beginDate":"","endDate":"","changeDate":"","assetState":"Active","isDeleted":"False"}]

**Comment by irvingoe** [comment]
Thanks Will! :+1:

**Comment by willuk2010** [comment]
No problem,

i still have the issue where Team Name box isnt populating the "ANY".

**Comment by irvingoe** [comment]
I'll be working on this after I get the latest code, if I notice something that could fix the team name box issue I'll let you know :zap:

**Comment by willuk2010** [comment]
Cheers dude

**Comment by nireeshT** [comment]
@willuk2010 try "Any"

**Comment by willuk2010** [comment]
@nireeshT tried that bud, but it just blanks out/removes the Any from the box.

**Comment by nireeshT** [comment]
@willuk2010  - so when you type 'Any', it is not showing the value in dropdown to select. I have made it mandatory to select the value from dropdown. So if you just type it and not select from dropdown, it will blank out. Can you share a screen shot of what you tried to do .

**Comment by willuk2010** [comment]
@nireeshT that's right, if I type Any, a drop-down doesn't appear like it does with the project box.. so I can't select anything (and I guess as you suggested it then blanks the box) I'll be dialling back into work later and I'll grab a screenshot for you.

**Comment by irvingoe** [comment]
I just fetched the latest code and @nireeshT instruction to type "Any" will get me this dropdown (Any got removed when I was trying to get the screenshot)
![image](https://user-images.githubusercontent.com/8560183/26942819-804e693c-4c51-11e7-8897-807f0d54f3a8.png)

**Comment by nireeshT** [comment]
@willuk2010  @irvingwa  what happened when you select Any with mouse cursor?

**Comment by irvingwa** [comment]
I was able to get the dropdown when I typed any.

**Comment by nireeshT** [comment]
@irvingwa were you able to select the value using mouse cursor

**Comment by irvingwa** [comment]
I was able to select it with the mouse cursor.

**Comment by satishc1** [comment]
Closed

**Comment by willuk2010** [comment]
Morning,

Yeh, mine does not give me a dropdown, if i enter "Any", no matter what.

Strange..

**Comment by willuk2010** [comment]
Ignore me! i deleted and re-created my dashboard, and Any is now available..

Cheers
Will

**Comment by sachingupta771** [comment]
Hi All
I'm facing same problem. pls tell any solution that worked for any of you guys.

**Comment by lenalevy** [comment]
Good morning 
I want to get list of team in dropdown instead of "Any"
Is it possible ?
