### ISSUE TITLE
error while running API "JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted."

### ISSUE THREAD

**Issue by meet101** [capitalone/Hygieia#1464]
Hi, 

can someone please help me to understand this error. 
```
2017-06-09 16:03:18,919 INFO  com.capitalone.dashboard.Application - Started Application in 53.586 seconds (JVM running for 64.541)
2017-06-09 16:04:15,613 INFO  o.a.c.c.C.[.[localhost].[/api] - Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-06-09 16:04:15,613 INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
2017-06-09 16:04:15,637 INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 24 ms
2017-06-09 16:04:15,760 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception
io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:342) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:458) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:518) ~[jjwt-0.6.0.jar!/:0.6.0]
        at com.capitalone.dashboard.auth.token.TokenAuthenticationServiceImpl.getAuthentication(TokenAuthenticationServiceImpl.java:59) ~[api.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.auth.token.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:28) ~[api.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RE
```
I am getting this error regarding key. I am not able to use the key which i got from core service as mentioned here https://github.com/capitalone/Hygieia/tree/master/UI#encryption-for-private-repos  
I got the key, I have copied into api.properties as well as bitbucket.properties (I am trying to use this with bitbucket) due to this, I am not able to authenticate bitbucket URL and it's giving me unauthorized as 
```
2017-06-08 20:34:00,086 ERROR c.c.d.c.DefaultBitbucketCloudClient - 401 Unauthorized:https://bitbucket.org/api/2.0/repositories/awsagero/testapi/commits?sha=master&since=2017-06-08T20:22Z2
```
before adding this key in api.properties i was not getting any error. But now i am getting this error even if i remove key form api.properties, can someone please help me with this issue.

Thank you

**Comment by irvingoe** [comment]
I got that issue yesterday when I fetch the latest changes.
The way I fixed it was running mvn clean package install again from Hygieia root folder, then I was also having problems specifically related to a dashboard I created "manually" in MongoDB, I created a new dashboard and then it was all good.
Another "hotfix" I did in my development was to make sure I was logged out before running 'gulp serve' again

**Comment by meet101** [comment]
I think for me it's because I had started a collector (bitbucket) where i am using that key before i run api. If i run API before running collector. it's not throwing error. 
I am having a really weird issue with bitbucket collector. if i pass my repo URL it's adding 'cket.org' in the URL. I have tried with private and public repo. both are having a same issue. 
@irvingoe  - have you ever configure Bitbucket on Hygieia? I really need a help to find solution. I explained issue here #1461 
Thanks

**Comment by nireeshT** [comment]
@meet101  - reopen issue if it is not fixed.

**Comment by smlcodes** [comment]
im also getting same issue
`io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:342) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:458) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:518) ~[jjwt-0.6.0.jar!/:0.6.0]
        at com.capitalone.dashboard.auth.token.TokenAuthenticationServiceImpl.getAuthentication(TokenAuthenticationServiceImpl.java:59) ~[api.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.auth.token.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:37) ~[api.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE] 
`

**Comment by preetcam** [comment]
Is this issue resolved. I am facing same error. I tried all the above steps.Nothing worked for me. Please guide.

2017-09-20 15:15:11,682 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception
io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:342) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:458) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:518) ~[jjwt-0.6.0.jar!/:0.6.0]
        at com.capitalone.dashboard.auth.token.TokenAuthenticationServiceImpl.getAuthentication(TokenAuthenticationServiceImpl.java:59) ~[api.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.auth.token.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:37) ~[api.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at com.capitalone.dashboard.auth.apitoken.ApiTokenRequestFilter.doFilter(ApiTokenRequestFilter.java:48) ~[api.jar!/:2.0.5-SNAPSHOT]

**Comment by Saurabbhh** [comment]
Hello Everyone, this issue can be solved by running gulp serve again without closing the previous one. By this, UI will run on a new port and run that url in incognito mode of your browser. There is some issue with the cache memory. Try this method, it worked for me

**Comment by cahi** [comment]
Easiest is to delete the cookie called JSESSIONID for <hygeiea-url>/api.

**Comment by JULIANCHO923** [comment]
> Easiest is to delete the cookie called JSESSIONID for /api.

Clear all cookies works to me :D

**Comment by minghungchen888** [comment]
> 這個問題解決了嗎。我面臨同樣的錯誤。我嘗試了上述所有步驟。沒有什麼對我有用。請指導。
![未命名](https://user-images.githubusercontent.com/76550533/157605373-f4f5c204-983d-4b46-a052-ce764c26a69b.jpg)

**Comment by minghungchen888** [comment]
這個問題解決了嗎。我面臨同樣的錯誤。我嘗試了上述所有步驟。沒有什麼對我有用。請指導。
Has this problem been resolved. I am facing the same error. I tried all the above steps. Nothing works for me. Please guide.
![Uploading 未命名.jpg…]()

**Comment by minghungchen888** [comment]
這個問題解決了嗎。我面臨同樣的錯誤。我嘗試了上述所有步驟。沒有什麼對我有用。請指導。
Has this problem been resolved. I am facing the same error. I tried all the above steps. Nothing works for me. Please guide.
![image](https://user-images.githubusercontent.com/76550533/157606183-234ccaca-d507-44d3-8592-8e47861be514.png)

**Comment by minghungchen888** [comment]
這個問題解決了嗎。我面臨同樣的錯誤。我嘗試了上述所有步驟。沒有什麼對我有用。請指導。
Has this problem been resolved. I am facing the same error. I tried all the above steps. Nothing works for me. Please guide.
![image](https://user-images.githubusercontent.com/76550533/157606424-7c129d9c-1649-43ac-ae53-4cbabbb17930.png)
