### ISSUE TITLE
Performance Collector NullPointer Exception

### ISSUE THREAD

**Issue by ganeshmuralidhar** [capitalone/Hygieia#1479]
Hi,

When I configured AppDYnamics collector with a dashboard configured for Node health metrics, I am getting a Nnullpointer Exception when I run the AppD collector and no data is reflecting on Hygieia Performance widget.

Is there a specific requirement for Dashboard content on AppD?

**Comment by nireeshT** [comment]
@ganeshmuralidhar  - share collector log.

**Comment by ganeshmuralidhar** [comment]
here it is . Also attached is the snapshot of my appdynamics.properties file.


INFO  c.c.d.collector.CollectorTask - Running Collector: Appdynamics
2017-06-16 09:37:01,009 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collector.AppdynamicsSettin
![untitled](https://user-images.githubusercontent.com/29456270/27211570-cbba9856-5277-11e7-9e7c-7097c3b39ca3.png)
gs.getInstanceUrlList(AppdynamicsSettings.java:38) ~[appdynamics-performance-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.model.AppdynamicsCollector.prototype(AppdynamicsCollector.java:31) ~[appdynamics-performance-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.getCollector(AppdynamicsCollectorTask.java:50) ~[appdynamics-performance-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.getCollector(AppdynamicsCollectorTask.java:20) ~[appdynamics-performance-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:48) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by nireeshT** [comment]
@ganeshmuralidhar   appdynamics.instanceUrl is incorrect, use below property name instead in your prop file. I will update Readme.

appdynamics.instanceUrls=

**Comment by ganeshmuralidhar** [comment]
Updated and now I am seeing a 401 Unauthorized error....

2017-06-16 22:07:01,199 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-16 22:07:01,375 ERROR c.c.d.c.DefaultAppdynamicsClient - client exception loading applications
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.makeRestCall(DefaultAppdynamicsClient.java:413) ~[appdynamics-performance-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.getApplications(DefaultAppdynamicsClient.java:89) ~[appdynamics-performance-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:79) [appdynamics-performance-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:20) [appdynamics-performance-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]

**Comment by nireeshT** [comment]
@ganeshmuralidhar - see if you were able to login to instance url from browser using the username and pwd given in prop file.

**Comment by nireeshT** [comment]
@ganeshmuralidhar  login to appdynamics -> settings -> license
check Account name - for me it is customer1 , check your account name and replace it as below. 
In you property file replace appdynamics.username = username@customer1  and run collector

**Comment by ganeshmuralidhar** [comment]
I am able to login for sure manually and hence I have this creds in the prop file. 

Now, when tried with your second option of username@customer .... This seems to be working... i can see the logs saying something like below.... 


2017-06-20 09:43:01,052 INFO  c.c.d.collector.CollectorTask - Fetched applications   1         0s
2017-06-20 09:43:01,052 INFO  c.c.d.collector.CollectorTask - New appplications:      0        0s
2017-06-20 09:43:01,054 INFO  c.c.d.collector.CollectorTask - Updated                 0        0s
2017-06-20 09:43:01,054 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-06-20 09:43:01,074 INFO  c.c.d.collector.CollectorTask - Fetched applications   1         0s
2017-06-20 09:43:01,075 INFO  c.c.d.collector.CollectorTask - New appplications:      0        0s
2017-06-20 09:43:01,077 INFO  c.c.d.collector.CollectorTask - Updated                 0        0s
2017-06-20 09:43:01,077 INFO  c.c.d.collector.CollectorTask - Finished                         0s

However, i don't see any stats on the Performance widget. Is there a specific metric I need to give on the AppD dashboard to get the values back on Hygieia?

**Comment by nireeshT** [comment]
@ganeshmuralidhar  give it some time to collect data and it should show up on the screen. You can also check MongoDB - performance collection to see appD data. You should see data similar to screenshot.  Reopen if issue is not resolved. 
<img width="718" alt="screen shot 2017-04-12 at 12 52 43 pm" src="https://user-images.githubusercontent.com/22962180/27467538-3a8f51e8-57b1-11e7-8768-669baa72b74f.png">

**Comment by ganeshmuralidhar** [comment]
I left it for more than 30 mins and still do not see any metrics. Consider this request and can you please provide me below data:
1. What are the metrics you have in your AppDynamics dashboard?
2. What is the URL you mentioned in your Appd.properties file? (if you share a screenshot with details masked, it will be helpful)

**Comment by narasimhacalsoft** [comment]
Hi Team,

Can you please explain how to configure appDynamics in Hygeiai dashboard and i am not install any appdynamic tool in my server.

Please explain step by step.
