### ISSUE TITLE
API throwing Exception After Configuring Jenkins: io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.

### ISSUE THREAD

**Issue by smlcodes** [capitalone/Hygieia#1518]
Iam able to see Jenkins Collector data in DB. but in dashboard it is showing all 0's. API is throwing io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted. Error.

Please find below Error log.

io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:342) ~[jjwt-0.6.0.jar!/:0.6.0]
at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:458) ~[jjwt-0.6.0.jar!/:0.6.0]
at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:518) ~[jjwt-0.6.0.jar!/:0.6.0]
at com.capitalone.dashboard.auth.token.TokenAuthenticationServiceImpl.getAuthentication(TokenAuthenticationServiceImpl.java:59) ~[api.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.auth.token.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:37) ~[api.jar!/:2.0.5-SNAPSHOT]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]

**Comment by sathishbob** [comment]
HI,

I am also facing the same, because of the same the loginpage is not coming .

Its just showing api connectivity green.

I pulled the latest code and also tried mvn clean package install still its not working.

Can you please advice.

**Comment by iglunev** [comment]
@sathishbob try clearing your dashboard cookies, that helped me

**Comment by sathishbob** [comment]
@iglunev , it helped me ..

Thanks

**Comment by Sbrenthughes** [comment]
@sathishbob - Please reopen if you have anymore issues with this.

**Comment by preetcam** [comment]
@sathishbob , could you please share steps to clear dashboard cookies. I cleared few stuff, issue still exists.

**Comment by Sbrenthughes** [comment]
Just clearing your cache and opening in incognito mode.

**Comment by magma7** [comment]
can you please suggest how to clean cache and cookies? which command to use?
