### ISSUE TITLE
Bitbucket collector is unable to collect commit 

### ISSUE THREAD

**Issue by kpal12** [capitalone/Hygieia#1522]
Hi , I getting the below error while running the bitbucket collector.. Please help..

2017-07-07 09:32:00,031 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2017-07-07 09:32:00,035 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2017-07-07 09:32:00,035 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-07-07 09:33:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2017-07-07 09:33:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-07-07 09:33:00,006 INFO  c.c.d.collector.CollectorTask - Starting...
2017-07-07 09:33:00,007 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-07-07 09:33:00,025 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from http://10.128.0.2:7990/rest/api/1.0/projects/demo4/repos/newproj/commits?until=master&limit=100
org.springframework.web.client.HttpClientErrorException: 401
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:235) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:90) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:132) [bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
2017-07-07 09:33:00,028 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2017-07-07 09:33:00,032 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2017-07-07 09:33:00,032 INFO  c.c.d.collector.CollectorTask - Finished                         0s

**********************************************************
My application properties contain 

dbname=dashboard
dbhost=localhost
dbport=27017
logging.file=./logs/bitbucket.log
git.cron=0 0/1 * * * *
git.host=http://10.128.0.2:7990
git.api=/rest/api/1.0/
git.key=nnmeAfQaOF7BARYWZ27yUW7391HaAvjs
git.commitThresholdDays=15
git.pageSize=25
git.product=server

I am also geeting password encryption error in the widget though i have added the key both in api and bitbucket app properties respectivly . Not sure whats wrong.. please help

**Comment by kpal12** [comment]
@tabladrum @satishc1
