### ISSUE TITLE
Stackoverflow error whiule running bamboo collector

### ISSUE THREAD

**Issue by kakumasn** [capitalone/Hygieia#1536]
Hi,

We have been using hygieia for a long time. Recently while running the bamboo collector , this error has occured. here are the logs

2017-07-10 02:28:06,613 INFO  com.capitalone.dashboard.Application - Started Application in 13.072 seconds (JVM running for 14.732)
2017-07-10 02:29:59,999 INFO  c.a.d.collector.CollectorTask - Running Collector: Bamboo
2017-07-10 02:30:58,225 INFO  c.a.d.collector.CollectorTask - -----------------------------------
2017-07-10 02:30:58,233 INFO  c.a.d.collector.CollectorTask - https://bamboo.xxx.com
2017-07-10 02:30:58,236 INFO  c.a.d.collector.CollectorTask - -----------------------------------
2017-07-10 02:59:46,023 INFO  c.a.d.collector.CollectorTask - Fetched jobs                  1786s
2017-07-10 02:59:47,122 INFO  c.a.d.collector.CollectorTask - New jobs              460        1s
2017-07-10 03:00:19,245 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.StackOverflowError: null
	at org.springframework.core.SerializableTypeWrapper.forTypeProvider(SerializableTypeWrapper.java:154) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.core.SerializableTypeWrapper.forGenericInterfaces(SerializableTypeWrapper.java:107) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.core.ResolvableType.getInterfaces(ResolvableType.java:403) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.core.ResolvableType.as(ResolvableType.java:365) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.core.ResolvableType.asCollection(ResolvableType.java:331) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.core.convert.TypeDescriptor.getElementTypeDescriptor(TypeDescriptor.java:329) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.core.convert.TypeDescriptor.equals(TypeDescriptor.java:495) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.util.ObjectUtils.nullSafeEquals(ObjectUtils.java:246) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService$ConverterCacheKey.equals(GenericConversionService.java:458) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:940) ~[na:1.8.0_91]
	at org.springframework.core.convert.support.GenericConversionService.getConverter(GenericConversionService.java:253) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:190) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:176) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:821) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readCollectionOrArray(MappingMongoConverter.java:888) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:213) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readMap(MappingMongoConverter.java:954) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:217) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1185) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.access$200(MappingMongoConverter.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1133) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getValueInternal(MappingMongoConverter.java:869) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$1.doWithPersistentProperty(MappingMongoConverter.java:282) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$1.doWithPersistentProperty(MappingMongoConverter.java:270) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:309) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:270) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:231) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readCollectionOrArray(MappingMongoConverter.java:906) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1183) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.access$200(MappingMongoConverter.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1133) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getValueInternal(MappingMongoConverter.java:869) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$1.doWithPersistentProperty(MappingMongoConverter.java:282) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$1.doWithPersistentProperty(MappingMongoConverter.java:270) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:309) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:270) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:231) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:191) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:187) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate$ReadDbObjectCallback.doWith(MongoTemplate.java:2206) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1884) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1707) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1690) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:602) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$Execution.readCollection(AbstractMongoQuery.java:170) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$CollectionExecution.execute(AbstractMongoQuery.java:193) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:104) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:454) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at com.sun.proxy.$Proxy50.findByApplicationComponentsIn(Unknown Source) ~[na:na]
	at **com.capitalone.dashboard.event.BuildEventListener.findAllDashboardsForBuild(BuildEventListener.java:195) ~[classes/:na]
	at com.capitalone.dashboard.event.BuildEventListener.processBuild(BuildEventListener.java:88) ~[classes/:na]
	at com.capitalone.dashboard.event.BuildEventListener.onAfterSave(BuildEventListener.java:60) ~[classes/:na]**
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:92) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:33) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.data.mongodb.core.MongoTemplate.maybeEmitEvent(MongoTemplate.java:1611) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doSave(MongoTemplate.java:978) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.save(MongoTemplate.java:921) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.save(SimpleMongoRepository.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:475) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at com.sun.proxy.$Proxy43.save(Unknown Source) ~[na:na]
	at com.capitalone.dashboard.event.BuildEventListener.processBuild(BuildEventListener.java:123) ~[classes/:na]
	at com.capitalone.dashboard.event.BuildEventListener.onAfterSave(BuildEventListener.java:60) ~[classes/:na]
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:92) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:33) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.data.mongodb.core.MongoTemplate.maybeEmitEvent(MongoTemplate.java:1611) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doSave(MongoTemplate.java:978) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.save(MongoTemplate.java:921) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.save(SimpleMongoRepository.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:475) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at com.sun.proxy.$Proxy43.save(Unknown Source) ~[na:na]
	**at com.capitalone.dashboard.event.BuildEventListener.processBuild(BuildEventListener.java:123) ~[classes/:na]
	at com.capitalone.dashboard.event.BuildEventListener.onAfterSave(BuildEventListener.java:60) ~[classes/:na]**
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:92) ~[spring-data-mongodb-1.8.0.RELEASE.jar:na]

**I did some debugging and found that this method  **onAfterSave(AfterSaveEvent<Build> event)** is getting called recursively**.
As in the class com.anthem.dashboard.event.BuildEventListener line no 122 we have this condition
if (hasFailedBuilds) {
                buildRepository.save(build);
}
So whenever build repository save happens, onAfterSave method is being called, and it is beiong called again and again.

I may be wrong, Any help would be appreciated.

**Comment by tabladrum** [comment]
Seen this before. And was reported by few others too - @MarkRx - never able to reproduce myself. I don't recognize this package though ``class com.anthem.dashboard.event`` unless you have refactored the package name internally. Let me check this once more. Stay tuned.

**Comment by kakumasn** [comment]
its com.capitalone.dashboard.event package and ya we did some customization to suit our requirementa

**Comment by tabladrum** [comment]
Are you using the Hygieia 2.0 Product Dashboard feature?

**Comment by kakumasn** [comment]
yes

**Comment by tabladrum** [comment]
This may fix it: check this branch https://github.com/capitalone/Hygieia/tree/eventlisternerFix. 
Will do PR after writing some tests. You may want to try it out before that.
@nireeshT can you pull this branch and test out the pipeline too?

**Comment by kakumasn** [comment]
Its fixed now. Thanks

**Comment by nireeshT** [comment]
@tabladrum  working on it
