### ISSUE TITLE
Api connectivity problem 

### ISSUE THREAD

**Issue by bseelam-hub** [capitalone/Hygieia#1546]
I have installed Hygieia, logged into the dashboards. created and  configuerd collectors  through UI . 

Suddenly getting this below error when i am trying to login into the Hygieia . 
![image](https://user-images.githubusercontent.com/26402613/28411620-ef0b8840-6d5e-11e7-9aec-7b3b7db1cab5.png)
 

i see the error in api service log 2017-07-20 05:48:45,765 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception
io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:342) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:458) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:518) ~[jjwt-0.6.0.jar!/:0.6.0]
        at com.capitalone.dashboard.auth.token.TokenAuthenticationServiceImpl.getAuthentication(TokenAuthenticationServiceImpl.java:59) ~[api.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.auth.token.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:37) ~[api.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]

what should i do to resolve this  ?

**Comment by bseelam-hub** [comment]
Update: Tried building the api again still facing the same problem

**Comment by nireeshT** [comment]
@bseelam-hub  use incognito

**Comment by satishc1** [comment]
@bseelam-hub check the api module readme and see if you have the following property set in properties file.
auth.authenticationProviders

**Comment by bseelam-hub** [comment]
Thanks satishc1
