### ISSUE TITLE
Jenkins-collector issue

### ISSUE THREAD

**Issue by DevOps575** [capitalone/Hygieia#1551]
Hi,

I am using Jenkins 2.x and trying to configure Hygieia to get the Jenkins jobs details in the dashboard. I am using Hygieia 2.0.4 release. I am able to fetch the total number of jobs in the Jenkins but when I select the build widget in the console and select a specific job to get the status I am getting below error:
ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL =http://localhost:8080/job/abc/10

This is the Jenkins properties file:

dbname=databasename
dbhost=localhost
dbport=27017
dbusername=databaseuser
dbpassword=databasepassword
jenkins.cron=0 * * * * *
jenkins.pageSize=1000
jenkins.folderDepth=10
jenkins.servers[0]=http://admin:d3d4248abd81ec6771ea7e6ba287e3f3@localhost:8080
logging.file=./logs/jenkins.log
jenkins.saveLog=true

What I am missing here?

Thanks

**Comment by golokeshpatra45** [comment]
The below properties file did work for me , compare and edit, try it out. If it doesnt work, give a shout.
# Database Name
dbname=dashboard

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
#dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=db

# Database Password - default is blank
dbpassword=dbpass

# Collector schedule (required)
jenkins.cron=0 0/5 * * * * 

# The page size
#Jenkins.pageSize=1000

# The folder depth - default is 10
#jenkins.folderDepth=10

# Jenkins server (required) - Can provide multiple
jenkins.servers[0]=http://localhost:8080

# If using username/token for api authentication
#   (required for Cloudbees Jenkins Ops Center) see sample
#jenkins.servers[1]=http://username:token@jenkins.company.com

# Another option: If using same user# Database Name
dbname=dashboard

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
#dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=db

# Database Password - default is blank
dbpassword=dbpass

# Collector schedule (required)
jenkins.cron=0 0/5 * * * * 

# The page size
#Jenkins.pageSize=1000

# The folder depth - default is 10
#jenkins.folderDepth=10

# Jenkins server (required) - Can provide multiple
jenkins.servers[0]=http://localhost:8080

# If using username/token for api authentication
#   (required for Cloudbees Jenkins Ops Center) see sample
#jenkins.servers[1]=http://username:token@jenkins.company.com

# Another option: If using same username/password Jenkins auth,
#   set username/apiKey to use HTTP Basic Auth (blank=no auth)
#jenkins.usernames=	
#jenkins.apiKeys=

# Determines if build console log is collected - defaults to false
jenkins.saveLog=true
name/password Jenkins auth,
#   set username/apiKey to use HTTP Basic Auth (blank=no auth)
jenkins.usernames=
jenkins.apiKeys=

# Determines if build console log is collected - defaults to false
jenkins.saveLog=true

**Comment by Ragavendira1** [comment]
@DevOps575 
looks like you missed below two lines in your code:
jenkins.usernames[0]=<username>
jenkins.apikeys[0]=<jenkins api key>

above statement, will resolve your 403 issue.

**Comment by Ragavendira1** [comment]
@DevOps575 
how are you generating jenkins api for the admin user?
looks like issue is with api key. 

Please check and let me know

**Comment by DevOps575** [comment]
Hi,

I am generating API Token from Jenkins console for admin user and using it in the property file. I also tried by adding the below keys in the property file:

jenkins.usernames[0]=admin
jenkins.apiKeys[0]=<JenkinsApiToken>

API Token seems to be fine as I am able to get the total number of jobs in Hygieia but not the details of individual job in dashboard after selecting the job name from dashboard.

2017-07-21 08:18:00,021 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-07-21 08:18:00,058 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2017-07-21 08:18:00,067 INFO  c.c.d.collector.CollectorTask - New jobs               17        0s
2017-07-21 08:18:00,082 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-07-21 08:18:00,082 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-07-21 08:19:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-07-21 08:19:00,018 INFO  c.c.d.collector.CollectorTask - -----------------------------------

On selecting job in the build widget in Hygieia console I am getting this error:

2017-07-21 08:23:00,029 ERROR c.c.d.collector.DefaultHudsonClient - Unknown error in getting build details. URL=http://localhost:8080/job/abc/10/
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getString(DefaultHudsonClient.java:370) ~[jenkins-collector.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.addChangeSets(DefaultHudsonClient.java:235) ~[jenkins-collector.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getBuildDetails(DefaultHudsonClient.java:188) ~[jenkins-collector.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.addNewBuilds(HudsonCollectorTask.java:193) [jenkins-collector.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:95) [jenkins-collector.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-collector.jar!/:2.0.4]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.4.jar!/:2.0.4]

Thanks

**Comment by DevOps575** [comment]
JFYI - In the above comment I forget to mention the apiKey value. This is what I set:

jenkins.usernames[0]=admin
jenkins.apiKeys[0]=1add7858efed99b86d21a5f2e23acc98

Thanks

**Comment by DevOps575** [comment]
I have taken the latest code from the master branch and it is working fine now.

**Comment by Sbrenthughes** [comment]
@DevOps575  - Please reopen if you have anymore issues.

**Comment by pasan96** [comment]
Same problem
