### ISSUE TITLE
Unable to authorize to jira

### ISSUE THREAD

**Issue by pallavi-d** [capitalone/Hygieia#1565]
We are unable to authorize to jira, follwed the steps mentioned for basic auth. Getting 401 everytime
For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
feature.jiraCredentials=dXNlcm5hbWU6cGFzc3dvcmQ= 

The jira url that we connect to is sso based. When we hit the jira url it redirects to another one and there the credentials are authenticated and then access to jira is provided. Will basic auth work in this case?

**Comment by htvan1** [comment]
Do you have control over your JIRA instance? We had an issue with the fact most of our company emails are set to google auth.  We learned, the authorization for the user used in the API call must be housed inside of JIRA.  We just made a "service user" with a different email account than the ones being filtered on to be redirected to google auth.  Than it worked fine for us.  Good luck!

**Comment by nb1706** [comment]
@pallavi-d : did you get it working? 
there maybe an issue in encoding credentials in case password has a special character. Refer #1549

**Comment by pallavi-d** [comment]
Not yet. I don't think there is any issue with the password. Moreover there is no special character in the password

**Comment by Sbrenthughes** [comment]
@pallavi-d can you paste the log?

**Comment by Sbrenthughes** [comment]
Closing due to inactivity. Reopen if the problem persist.

**Comment by pversteijnen** [comment]
I have a similar issue at the moment. We added a local user to Jira with a pasword without special characters. When I added this to the configuration it started working for the projects list. But when the status api is called I still get a 401. We made the user Admin. This resulted in more projects so that was prove it worked. But we still get the same error?

```
2018-02-08 08:40:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2018-02-08 08:40:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-08 08:40:00,009 INFO  c.c.d.collector.CollectorTask - https://jira.essent.nl/jira
2018-02-08 08:40:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-08 08:40:00,009 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2018-02-08 08:40:00,614 INFO  c.c.d.collector.CollectorTask - Project Data           92        0s
2018-02-08 08:40:00,735 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.IOException: Server returned HTTP response code: 401 for URL: https://jira.essent.nl/jira/rest/api/2/status/
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[na:1.8.0_151]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_151]
        at java.net.URLConnection.getContent(URLConnection.java:739) ~[na:1.8.0_151]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:443) ~[na:1.8.0_151]
        at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:442) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:750) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:154) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2018-02-08 08:40:00,942 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 2
2018-02-08 08:40:00,942 INFO  c.c.d.collector.CollectorTask - Story Data              2        0s
2018-02-08 08:40:00,942 INFO  c.c.d.collector.CollectorTask - Finished                         0s
``` 

Any thoughts on what can be done to get this working?
