### ISSUE TITLE
Getting Hygieia up and running with docker-compose

### ISSUE THREAD

**Issue by srinathanand** [capitalone/Hygieia#1623]
Hi All,

I am trying to get my Hygieia up and running with just one collector using the Docker Compose file and I am running into some errors. Here are the details:

docker -v
Docker version 17.05.0-ce, build 89658be

docker-compose.yml file attached (not much of a change from the source)
docker-compose.override.yml attached (trying to start off with just one collector)

Log - looks like authentication failed but I am using the defaults.

2017-08-15 18:38:20,845 INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongodb:27017
com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='db', source='dashboard', password=<hidden
>, mechanismProperties={}}
	at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:61) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99) ~[mongo-java-driver-
3.0.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44) ~[mongo-java-driver-3.0.2
.jar!/:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server mongodb:27017. The full response is { "o
k" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }
	at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:95) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:45) ~[mongo-java-driver-3.0.2.jar!/:na]
	... 5 common frames omitted

Can someone help?

Thanks

[docker-compose.pdf](https://github.com/capitalone/Hygieia/files/1226102/docker-compose.pdf)
[docker-compose.override.pdf](https://github.com/capitalone/Hygieia/files/1226103/docker-compose.override.pdf)

**Comment by srinathanand** [comment]
I am getting the same error when trying to run the API using the regular Docker build commands as outlined here -

https://github.com/capitalone/Hygieia/tree/master/api

The exact error is -

Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server <ip>:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }

I have MongoDB running in a container. Do I have to specify all the values in dashboard.properties such as the proxy even though I have set the http_proxy etc on my host?

Any help would be appreciated.

**Comment by srinathanand** [comment]
Found the solution here - https://github.com/capitalone/Hygieia/issues/999. 

Please update your documentation on how to run the API part of Hygieia. It doesn't work in a Docker container if you follow -

use db
db.createUser({user: "db", pwd: "dbpass", roles: [{role: "readWrite", db: "dashboard"}]})

I think the same problem will exist with Docker Compose as well. Closing this for now.
