### ISSUE TITLE
jenkins collector:::: unable to retrive data from Mongo DB

### ISSUE THREAD

**Issue by nag10** [capitalone/Hygieia#1640]
Am trying to publish the jenkins build data to the hygiea dashboard.

i could see the jobs are fetched during the build, but the jobs are not retriving from the DB.

Build log:
**********
Running com.capitalone.dashboard.collector.HudsonCollectorTaskTests
2017-08-18 09:38:11,965 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:11,966 INFO  c.c.d.collector.CollectorTask - server1
2017-08-18 09:38:11,967 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:11,973 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2017-08-18 09:38:11,973 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2017-08-18 09:38:11,973 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-08-18 09:38:11,974 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-08-18 09:38:11,978 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:11,979 INFO  c.c.d.collector.CollectorTask - server1
2017-08-18 09:38:11,984 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:11,985 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2017-08-18 09:38:11,985 INFO  c.c.d.collector.CollectorTask - New jobs                1        0s
2017-08-18 09:38:11,986 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-08-18 09:38:11,987 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-08-18 09:38:12,000 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:12,001 INFO  c.c.d.collector.CollectorTask - server1
2017-08-18 09:38:12,002 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:12,004 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2017-08-18 09:38:12,008 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2017-08-18 09:38:12,009 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-08-18 09:38:12,009 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-08-18 09:38:12,016 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:12,019 INFO  c.c.d.collector.CollectorTask - server1
2017-08-18 09:38:12,021 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:12,022 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2017-08-18 09:38:12,022 INFO  c.c.d.collector.CollectorTask - New jobs                1        0s
2017-08-18 09:38:12,022 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-08-18 09:38:12,023 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-08-18 09:38:12,030 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:12,032 INFO  c.c.d.collector.CollectorTask - server1
2017-08-18 09:38:12,034 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:12,034 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2017-08-18 09:38:12,037 INFO  c.c.d.collector.CollectorTask - New jobs                2        0s
2017-08-18 09:38:12,039 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-08-18 09:38:12,040 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-08-18 09:38:12,045 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:12,049 INFO  c.c.d.collector.CollectorTask - server1
2017-08-18 09:38:12,050 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:12,051 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2017-08-18 09:38:12,052 INFO  c.c.d.collector.CollectorTask - New jobs                1        0s
2017-08-18 09:38:12,056 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-08-18 09:38:12,060 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-08-18 09:38:12,065 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:12,068 INFO  c.c.d.collector.CollectorTask - server1
2017-08-18 09:38:12,069 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-18 09:38:12,073 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2017-08-18 09:38:12,077 INFO  c.c.d.collector.CollectorTask - New jobs                1        0s
2017-08-18 09:38:12,077 INFO  c.c.d.collector.CollectorTask - New builds              1        0s
2017-08-18 09:38:12,077 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-08-18 09:38:12,081 INFO  c.c.d.collector.CollectorTask - -----------------------------------

application.properties:
***********************
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
dbusername=dashboarduser
dbpassword=dashboardpassword
jenkins.cron=0 0/5 * * * *
jenkins.pageSize=1000
jenkins.folderDepth=10
jenkins.servers[0]=http://username:password@192.168.0.108:8080

Kindly provide inputs if anyone faced the error earlier.. thanks in advance..!!

**Comment by nag10** [comment]
Anyone  pls help  on this issue. This is a blocker for us.

Thanks in advance..!!

**Comment by nag10** [comment]
Getting the below error:

2017-08-21 13:55:04,969 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 11]}, minWireVersion=0, maxWireVersion=4, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=6049576}
2017-08-21 13:55:05,683 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2017-08-21 13:55:05,699 INFO  com.capitalone.dashboard.Application - Started Application in 7.166 seconds (JVM running for 8.307)
2017-08-21 13:56:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-08-21 13:56:00,043 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-21 13:56:00,044 INFO  c.c.d.collector.CollectorTask - http://192.168.0.105:8080/
2017-08-21 13:56:00,044 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-21 13:58:11,067 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://192.168.0.105:8080/api/json?tree=jobs[name,url,builds[number,url]]":Connection timed out (Connection timed out); nested exception is java.net.ConnectException: Connection timed out (Connection timed out)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:457) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:98) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) [jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
        at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_131]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_131]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_131]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_131]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_131]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_131]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202) ~[na:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[na:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[na:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966) ~[na:1.8.0_131]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:81) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:569) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 16 common frames omitted

**Comment by Sbrenthughes** [comment]
Can you verify you able to get to that url from the location of your collector?

**Comment by nag10** [comment]
@Sbrenthughes  i have verified the connectivity between two servers and is working fine...

**Comment by nitin1706** [comment]
can you try with the latest code using 2.0.5

**Comment by nireeshT** [comment]
@nag10  -  Update to latest code base and run jenkins collector.

**Comment by nag10** [comment]
with latest code am facing the below issue... login page not populating...


![image](https://user-images.githubusercontent.com/12077661/29872555-bbc6ea00-8dad-11e7-8dbc-f32f93c1e940.png)

**Comment by nitin1706** [comment]
as per this screen shot, its showing connectivity to your api is not successful. Do you see any error on api console or log file?

**Comment by nireeshT** [comment]
@nag10  - share api log, launch UI in incognito window

**Comment by nag10** [comment]
Thanks for the inputs. able to fetch data now..
