### ISSUE TITLE
Error running , jenkins-Codequality-collector

### ISSUE THREAD

**Issue by anuradha92** [capitalone/Hygieia#1645]
2017-08-22 11:10:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: JenkinsCodeQuality
2017-08-22 11:10:00,063 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at java.util.ArrayList.addAll(Unknown Source) ~[na:1.8.0_144]
        at com.capitalone.dashboard.collector.JenkinsCodeQualityCollector.prototype(JenkinsCodeQualityCollector.java:21) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTask.getCollector(JenkinsCodeQualityCollectorTask.java:47) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5
-SNAPSHOT]
        at com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTask.getCollector(JenkinsCodeQualityCollectorTask.java:23) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5
-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:52) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_144]

This is my properties file:

dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false 
dbhostport=localhost:27017,127.0.0.1:27017,ip-172-31-26-184:27017
dbusername=dashboarduser
dbpassword=dbpassword
jenkins-codequality.cron=0 0/1 * * * *
jenkins-codequality.servers[0]=http://jenkins
jenkins-codequality.artifactRegex.junit=TEST-.*\\.xml
jenkins-codequality.artifactRegex.findbugs=findbugsXml.xml
jenkins-codequality.artifactRegex.pmd=pmd.xml
jenkins-codequality.artifactRegex.checkstyle=checkstyle-result.xml
jenkins-codequality.artifactRegex.jacoco=jacoco.xml
jenkins-codequality.jobDepth=4

**Comment by pasan96** [comment]
Refer #1641

**Comment by nitin1706** [comment]
I can see the reason for error is 'jenkins-codequality.servers'.
Can you try again giving a complete server address instead of 'http://jenkins'.

**Comment by anuradha92** [comment]
java -jar jenkins-codequality-2.0.5-SNAPSHOT.jar --spring.config.location=..\quality.properties

**Comment by nitin1706** [comment]
try using giving your properties file name: jenkins-codequality.properties
and use this command with full path to your properties file:
 
`java -jar jenkins-codequality-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins-codequality --spring.config.location=/Path/to/properties/file/named/jenkins-codequality.properties`

**Comment by pasan96** [comment]
Do we have to provide the location of XML test files in the properties?

**Comment by anuradha92** [comment]
I'm change the my properties file name quality.properties to  jenkins-codequality.properties but i got the same error
this is my command:
java -jar jenkins-codequality-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins-codequality --spring.config.location=/C:/Users/anuradha92/Desktop/Newfolder/Hygieia/collectors/build/jenkins-codequality/jenkins-codequality.properties
this is my error:
2017-08-24 09:45:55,157 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.
cloud.context.properties:name=configurationPropertiesRebinder,context=72abb3a3,type=ConfigurationPropertiesRebinder]
2017-08-24 09:45:55,235 INFO  com.capitalone.dashboard.Application - Started Application in 11.15 seconds (JVM running for 12.981)
2017-08-24 09:46:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: JenkinsCodeQuality
2017-08-24 09:46:00,111 **ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.**
**org.springframework.web.client.HttpClientErrorException: 403 Forbidden**
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.HttpJenkinsClient.lambda$getJobs$0(HttpJenkinsClient.java:59) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_144]
        at com.capitalone.dashboard.collector.HttpJenkinsClient.getJobs(HttpJenkinsClient.java:41) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTask.collect(JenkinsCodeQualityCollectorTask.java:63) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAP
SHOT]
        at com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTask.collect(JenkinsCodeQualityCollectorTask.java:23) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAP
SHOT]

**Comment by anuradha92** [comment]
I'm change the my properties file name quality.properties to  jenkins-codequality.properties then NullPointerException is done but i got the 403 error
this is my command:
java -jar jenkins-codequality-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins-codequality --spring.config.location=/C:/Users/anuradha92/Desktop/Newfolder/Hygieia/collectors/build/jenkins-codequality/jenkins-codequality.properties
this is my error:
2017-08-24 09:45:55,157 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.
cloud.context.properties:name=configurationPropertiesRebinder,context=72abb3a3,type=ConfigurationPropertiesRebinder]
2017-08-24 09:45:55,235 INFO  com.capitalone.dashboard.Application - Started Application in 11.15 seconds (JVM running for 12.981)
2017-08-24 09:46:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: JenkinsCodeQuality
2017-08-24 09:46:00,111 **ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.**
**org.springframework.web.client.HttpClientErrorException: 403 Forbidden**
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.HttpJenkinsClient.lambda$getJobs$0(HttpJenkinsClient.java:59) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_144]
        at com.capitalone.dashboard.collector.HttpJenkinsClient.getJobs(HttpJenkinsClient.java:41) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTask.collect(JenkinsCodeQualityCollectorTask.java:63) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAP
SHOT]
        at com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTask.collect(JenkinsCodeQualityCollectorTask.java:23) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAP
SHOT]

**Comment by Sbrenthughes** [comment]
Try adding credentials.  
```
jenkins-codequality.username=
jenkins-codequality.apiKey=
```

**Comment by anuradha92** [comment]
I'm add the  jenkins-codequality.username= & jenkins-codequality.apiKey= to my properties file and run the same command then i got the same error "ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task." 
This is my properties file:
# Database Name
```
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false 
dbhostport=localhost:27017,127.0.0.1:27017,ip-172-31-26-184:27017

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Collector schedule (required)
jenkins-codequality.cron=0 0/1 * * * *

# Collector servers (required) - can be multiple
jenkins-codequality.servers[0]=http://admin:e1696630c52ad3b61e881e05416ac0d0@localhost:8090/jenkins
jenkins-codequality.username=admin
jenkins-codequality.apiKey=e1696630c52ad3b61e881e05416ac0d0
# Collector types (note not required, but the regex should be match only the type specified)

jenkins-codequality.artifactRegex.junit=TEST-.*\\.xml
jenkins-codequality.artifactRegex.findbugs=findbugsXml.xml
jenkins-codequality.artifactRegex.pmd=pmd.xml
jenkins-codequality.artifactRegex.checkstyle=checkstyle-result.xml
jenkins-codequality.artifactRegex.jacoco=jacoco.xml
# Collector job depth (required) should be set to at least 1, and more if you use folder jobs etc
jenkins-codequality.jobDepth=10
```
My Error:
```
        ... 22 common frames omitted
2017-08-25 10:01:00,007 INFO  c.c.d.collector.CollectorTask - Running Collector: JenkinsCodeQuality
2017-08-25 10:01:00,026 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: No suitable constructor found for type [simple type, class com.capitalone.dashboard.jen
kins.JobContainer]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: java.io.PushbackInputStream@54f3427b; line: 1, column: 2]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for t
ype [simple type, class com.capitalone.dashboard.jenkins.JobContainer]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable
type information?)
 at [Source: java.io.PushbackInputStream@54f3427b; line: 1, column: 2]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:225) ~[spring-web-4.2.5.RELEASE.jar!/
:4.2.5.RELEASE]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:209) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.R
ELEASE]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:95) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:835) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:819) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:599) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.HttpJenkinsClient.lambda$getJobs$0(HttpJenkinsClient.java:59) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_144]
        at com.capitalone.dashboard.collector.HttpJenkinsClient.getJobs(HttpJenkinsClient.java:41) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTask.collect(JenkinsCodeQualityCollectorTask.java:63) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAP
SHOT]
```

**Comment by stevegal** [comment]
The xml files must be archived in the job. When the collector polls Jenkins it gets the files from the archive for the job. Not sure about the 403...

**Comment by stevegal** [comment]
(As well as being configured for the file pattern for each type)

**Comment by stevegal** [comment]
Yeah. That's a bug re: collector. Looks like some tidy up code went wrong before I committed. I'll correct

**Comment by stevegal** [comment]
raised #1699 to correct

**Comment by pasan96** [comment]
@stevegal And also, setters should be added to the Artifact class, otherwise the artifact file name fileName won't be mapped correctly, it will be null, and that gives a regex exception in predicate.

**Comment by stevegal** [comment]
Hmm... fileName or filename... I'm not sure your root cause is right, but I need to check that casing. I'll update the conversion test and see...

**Comment by stevegal** [comment]
see #1700 for fix

**Comment by stevegal** [comment]
now that's merged, does it work for you @pasan96, @anuradha92 ?

**Comment by anuradha92** [comment]
yes. It's going to the db but it doesn't show up on the UI

**Comment by stevegal** [comment]
Did you see my comment there? Maybe the do has got a bit broken due to my broken collector.

**Comment by stevegal** [comment]
/s/ do/ ui

**Comment by pasan96** [comment]
Thank you @stevegal  the collector is working fine now. Is there any fix for the UI problem?

**Comment by pasan96** [comment]
@stevegal  Tried clearing both , no luck :/

**Comment by stevegal** [comment]
@pasan96 should be merged now

**Comment by stevegal** [comment]
@anuradha92 if you checkout the latest master, it should work for you.

**Comment by anuradha92** [comment]
@stevegal thanks now it's work.

**Comment by SNEHIL04** [comment]
hi , 

Running command:
sudo java -jar sonar-codequality-collector-2.0.5-SNAPSHOT.jar --spring.config.name=sonar --spring.config.location=/opt/hygieia/collectors/build/sonar/application.properties


and getting below error ,hence i am unable to integrate sonar in my hygieia dashboard:

2018-06-12 11:51:00,088 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_171]
        at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_171]
        at com.capitalone.dashboard.collector.SonarCollectorTask.collect(SonarCollectorTask.java:98) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.SonarCollectorTask.collect(SonarCollectorTask.java:36) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-06-12 11:52:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2018-06-12 11:52:00,019 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0



My application.properties file has this 

[ctier@blr-iae10 sonar]$ cat application.properties
dbname=test
dbhost=127.0.0.1
dbport=27017
dbreplicaset=false
dbhostport=127.0.0.1:27017
dbusername=username12
dbpassword=password
sonar.cron=0 0/1 * * * *
sonar.servers[0]=http://192.168.113.96:9000/
#sonar.versions[0]=7.0
sonar.metrics[0]=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details
sonar.username=admin
sonar.password=iaeadmin@iaedevops



Please advise .
