### ISSUE TITLE
Unable to get the data in Hygieia Pipleline - Error RunListener failed

### ISSUE THREAD

**Issue by akashnkgupta** [capitalone/Hygieia#1649]
HI Team,

I have configured Hygieia for multiple Jenkins instance. I am getting the required detail from 1 jenkins instance and able to get data in pipeline view for required environment. But Hygieia unable to get required data from another Jenkins instance in pipeline view. I found below mentioned error in Jenkins logs. Could you please provide help here or in case you require more information.

Dashboard - Hygieia(created on linux environment)

WARNING: RunListener failed
java.lang.UnsupportedClassVersionError: com/capitalone/dashboard/request/BuildDataCreateRequest
        at jenkins.plugins.hygieia.ActiveNotifier.getBuildData(ActiveNotifier.java:159)
        at jenkins.plugins.hygieia.ActiveNotifier.completed(ActiveNotifier.java:76)
        at jenkins.plugins.hygieia.HygieiaListener.onCompleted(HygieiaListener.java:27)
        at jenkins.plugins.hygieia.HygieiaListener.onCompleted(HygieiaListener.java:15)
        at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
        at hudson.model.Run.execute(Run.java:1786)
        at com.tikal.jenkins.plugins.multijob.MultiJobBuild.run(MultiJobBuild.java:73)
        at hudson.model.ResourceController.execute(ResourceController.java:98)
        at hudson.model.Executor.run(Executor.java:408)

**Comment by Sbrenthughes** [comment]
Are you using the plugin or the collector to get the data? If collector can you please post your properties file?

**Comment by akashnkgupta** [comment]
We are using customized Jenkins plugin - 

![image](https://user-images.githubusercontent.com/31215498/29657173-7578da0a-88d4-11e7-84ef-67b34f8ae682.png)

**Comment by nireeshT** [comment]
@akashnkgupta - Which version of jdk is used to compile & build hygieia plugin?

**Comment by akashnkgupta** [comment]
Hi @nireeshT  thanks for your reply.
we are using
java version "1.7.0_09-icedtea"
OpenJDK Runtime Environment (rhel-2.3.4.1.el6_3-x86_64)
OpenJDK 64-Bit Server VM (build 23.2-b09, mixed mode)

**Comment by nireeshT** [comment]
@akashnkgupta  try with jdk 1.8

**Comment by Sbrenthughes** [comment]
@akashnkgupta please reopen if this is still an issue
