### ISSUE TITLE
403 Forbidden error, Jenkins code quality collector 

### ISSUE THREAD

**Issue by pasan96** [capitalone/Hygieia#1659]
Getting the following error when running the code quality collector, jenkins is up and running on port 8080/jenkins .

```
09:48:39,983 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
09:48:39,985 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:48:39,992 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/C:/Users/psumanaratne/projects/Hygieia/collectors/buil
d/jenkins-codequality/target/jenkins-codequality-2.0.5-SNAPSHOT.jar!/logback.xml]
09:48:40,003 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
09:48:40,003 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Users/psumanaratne/projects/Hygieia/collectors/bui
ld/jenkins-codequality/target/jenkins-codequality-2.0.5-SNAPSHOT.jar!/lib/core-2.0.5-SNAPSHOT.jar!/logback.xml]
09:48:40,004 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Users/psumanaratne/projects/Hygieia/collectors/bui
ld/jenkins-codequality/target/jenkins-codequality-2.0.5-SNAPSHOT.jar!/logback.xml]
09:48:40,295 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@37734d65 - URL [jar:file:/C:/Users/psumanaratne/projects/Hygieia/collectors/build/jenkins-co
dequality/target/jenkins-codequality-2.0.5-SNAPSHOT.jar!/logback.xml] is not of type file
09:48:40,596 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
09:48:40,688 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:48:40,782 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
09:48:40,855 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encod
er] property
09:48:41,176 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
09:48:41,191 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ROLLING]
09:48:41,299 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
09:48:41,307 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/codequalitycollector-%d{yyyy-MM-dd}.%i.log for the active file
09:48:41,318 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@68e40327 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/codequalitycollector-%
d{yyyy-MM-dd}.%i.log'.
09:48:41,318 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@68e40327 - Roll-over at midnight.
09:48:41,321 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@68e40327 - Setting initial period to Thu Aug 24 09:48:41 IST 2017
09:48:41,333 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encod
er] property
09:48:41,334 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - Active log file name: logs/codequalitycollector-2017-08-24.0.log
09:48:41,334 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - File property is set to [null]
09:48:41,340 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
09:48:41,340 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ROLLING] to Logger[ROOT]
09:48:41,343 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
09:48:41,343 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:48:41,346 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@60cc5db1 - Registering current configuration as safe fallback point

2017-08-24 09:48:44,770 INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.2.Final
2017-08-24 09:48:45,139 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@67ed6b28
: startup date [Thu Aug 24 09:48:45 IST 2017]; root of context hierarchy
2017-08-24 09:48:46,545 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-24 09:48:47,193 INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'configurationPropertiesRebinderAutoConfiguration' of type [clas
s org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$8a37a7e2] is not eligible for getting processed by al
l BeanPostProcessors (for example: not eligible for auto-proxying)
 _   _             _      _                 ______           _      _____           _       _____             _ _ _         _____       _ _           _
| | | |           (_)    (_)                | ___ \         (_)    /  __ \         | |     |  _  |           | (_) |       /  __ \     | | |         | |
| |_| |_   _  __ _ _  ___ _  __ _   ______  | |_/ / __ _ ___ _  ___| /  \/ ___   __| | ___ | | | |_   _  __ _| |_| |_ _   _| /  \/ ___ | | | ___  ___| |_ ___  _ __
|  _  | | | |/ _` | |/ _ \ |/ _` | |______| | ___ \/ _` / __| |/ __| |    / _ \ / _` |/ _ \| | | | | | |/ _` | | | __| | | | |    / _ \| | |/ _ \/ __| __/ _ \| '__|
| | | | |_| | (_| | |  __/ | (_| |          | |_/ / (_| \__ \ | (__| \__/\ (_) | (_| |  __/\ \/' / |_| | (_| | | | |_| |_| | \__/\ (_) | | |  __/ (__| || (_) | |
\_| |_/\__, |\__, |_|\___|_|\__,_|          \____/ \__,_|___/_|\___|\____/\___/ \__,_|\___| \_/\_\\__,_|\__,_|_|_|\__|\__, |\____/\___/|_|_|\___|\___|\__\___/|_|
        __/ | __/ |                                                                                                    __/ |
       |___/ |___/                                                                                                    |___/

2017-08-24 09:48:48,359 INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://localhost:8888
2017-08-24 09:48:50,136 WARN  o.s.c.c.c.ConfigServicePropertySourceLocator - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/applic
ation/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2017-08-24 09:48:50,140 INFO  com.capitalone.dashboard.Application - No profiles are active
2017-08-24 09:48:50,176 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@49ae3298
: startup date [Thu Aug 24 09:48:50 IST 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@67ed6b28
2017-08-24 09:48:54,662 INFO  o.s.cloud.context.scope.GenericScope - BeanFactory id=11bf1126-0438-3945-aed1-8f8a22ef8e7f
2017-08-24 09:48:54,671 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Post-processing PropertySource instances
2017-08-24 09:48:54,694 INFO  c.u.j.c.StringEncryptorConfiguration - String Encryptor custom Bean not found with name 'jasyptStringEncryptor'. Initializing String Encry
ptor based on properties with name 'jasyptStringEncryptor'
2017-08-24 09:48:54,789 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleComman
dLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2017-08-24 09:48:54,792 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemProperties [org.springframework.core.env.MapProperty
Source] to EncryptableMapPropertySourceWrapper
2017-08-24 09:48:54,795 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemEnvironment [org.springframework.core.env.SystemEnvi
ronmentPropertySource] to EncryptableMapPropertySourceWrapper
2017-08-24 09:48:54,805 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource random [org.springframework.boot.context.config.RandomValu
ePropertySource] to EncryptablePropertySourceWrapper
2017-08-24 09:48:54,809 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource applicationConfig: [file:../jenkinsCQ.properties] [org.spr
ingframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2017-08-24 09:48:54,811 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.Ma
pPropertySource] to EncryptableMapPropertySourceWrapper
2017-08-24 09:48:54,818 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource defaultProperties [org.springframework.core.env.MapPropert
ySource] to EncryptableMapPropertySourceWrapper
2017-08-24 09:48:54,832 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-24 09:48:55,003 INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cloud.autoconfigure.ConfigurationProperties
RebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$8a37a7e2] is
not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-24 09:48:55,409 INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService  'taskScheduler'
2017-08-24 09:48:55,857 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2017-08-24 09:48:56,446 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2017-08-24 09:48:56,913 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelec
tionTimeout='30000 ms', maxWaitQueueSize=500}
2017-08-24 09:48:57,288 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, write
Concern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@cfc6fc98, minConnectionsPerHost=0, maxCon
nectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTim
e=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000,
minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.D
efaultDBDecoder$1@16c1bc44, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@51f71d07, socketFactory=javax.net.DefaultSocketFactory@17c81d48, cursorFinalizerEnabled=true
, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=6
0000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferS
ize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutM
S=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2017-08-24 09:48:59,570 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:7}] to localhost:27017
2017-08-24 09:48:59,605 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, t
ype=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 0]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, r
oundTripTimeNanos=24700849}
2017-08-24 09:49:00,562 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:8}] to localhost:27017
2017-08-24 09:49:02,092 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2017-08-24 09:49:02,095 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2017-08-24 09:49:02,100 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelec
tionTimeout='30000 ms', maxWaitQueueSize=500}
2017-08-24 09:49:02,105 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, write
Concern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@cfc6fc98, minConnectionsPerHost=0, maxCon
nectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTim
e=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000,
minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.D
efaultDBDecoder$1@16c1bc44, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@51f71d07, socketFactory=javax.net.DefaultSocketFactory@17c81d48, cursorFinalizerEnabled=true
, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=6
0000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferS
ize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutM
S=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2017-08-24 09:49:02,141 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:9}] to localhost:27017
2017-08-24 09:49:02,143 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, t
ype=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 0]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, r
oundTripTimeNanos=840301}
2017-08-24 09:49:02,178 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2017-08-24 09:49:02,184 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2017-08-24 09:49:02,187 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelec
tionTimeout='30000 ms', maxWaitQueueSize=500}
2017-08-24 09:49:02,191 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, write
Concern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@cfc6fc98, minConnectionsPerHost=0, maxCon
nectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTim
e=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000,
minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.D
efaultDBDecoder$1@16c1bc44, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@51f71d07, socketFactory=javax.net.DefaultSocketFactory@17c81d48, cursorFinalizerEnabled=true
, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=6
0000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferS
ize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutM
S=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2017-08-24 09:49:02,232 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:10}] to localhost:27017
2017-08-24 09:49:02,235 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, t
ype=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 0]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, r
oundTripTimeNanos=967807}
2017-08-24 09:49:03,097 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2017-08-24 09:49:03,100 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2017-08-24 09:49:03,107 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelec
tionTimeout='30000 ms', maxWaitQueueSize=500}
2017-08-24 09:49:03,127 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, write
Concern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@cfc6fc98, minConnectionsPerHost=0, maxCon
nectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTim
e=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000,
minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.D
efaultDBDecoder$1@16c1bc44, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@51f71d07, socketFactory=javax.net.DefaultSocketFactory@17c81d48, cursorFinalizerEnabled=true
, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=6
0000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferS
ize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutM
S=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2017-08-24 09:49:03,313 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:11}] to localhost:27017
2017-08-24 09:49:03,357 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, t
ype=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 0]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, r
oundTripTimeNanos=17348688}
2017-08-24 09:49:05,852 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2017-08-24 09:49:05,906 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2017-08-24 09:49:05,908 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'environmentManager' has been autodetected for JMX exposure
2017-08-24 09:49:05,911 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'refreshScope' has been autodetected for JMX exposure
2017-08-24 09:49:05,923 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.c
loud.context.environment:name=environmentManager,type=EnvironmentManager]
2017-08-24 09:49:06,016 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.c
ontext.scope.refresh:name=refreshScope,type=RefreshScope]
2017-08-24 09:49:06,061 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.spri
ngframework.cloud.context.properties:name=configurationPropertiesRebinder,context=49ae3298,type=ConfigurationPropertiesRebinder]
2017-08-24 09:49:06,160 INFO  com.capitalone.dashboard.Application - Started Application in 24.005 seconds (JVM running for 27.775)
2017-08-24 09:50:00,007 INFO  c.c.d.collector.CollectorTask - Running Collector: JenkinsCodeQuality
2017-08-24 09:50:00,243 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.HttpClientErrorException: 403 Forbidden
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.HttpJenkinsClient.lambda$getJobs$0(HttpJenkinsClient.java:59) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_131]
        at com.capitalone.dashboard.collector.HttpJenkinsClient.getJobs(HttpJenkinsClient.java:41) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTask.collect(JenkinsCodeQualityCollectorTask.java:63) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!
/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTask.collect(JenkinsCodeQualityCollectorTask.java:23) ~[jenkins-codequality-2.0.5-SNAPSHOT.jar!
/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.
5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]
```
Properties file - 

```
# Database Name
dbname=dashboarddb
# Database HostName - default is localhost
dbhost=localhost
# Database Port - default is 27017
dbport=27017
# MongoDB replicaset
dbreplicaset=false 
dbhostport=localhost:27017,127.0.0.1:27017,ip-172-31-26-184:27017
# Database Username - default is blank
dbusername=dashboarduser
# Database Password - default is blank
dbpassword=dbpassword
# Collector schedule (required)
jenkins-codequality.cron=0 0/1 * * * *
# Collector servers (required) - can be multiple
jenkins-codequality.servers[0]=http://psumanaratne:83212caf8b414b89a4f9c4fdf87d3711@localhost:8082/jenkins
#jenkins-codequality.servers[0]=http://localhost:8082/jenkins
# Collector types (note not required, but the regex should be match only the type specified)
jenkins-codequality.artifactRegex.junit=TEST-.*\\.xml
jenkins-codequality.artifactRegex.findbugs=findbugsXml.xml
jenkins-codequality.artifactRegex.pmd=pmd.xml
jenkins-codequality.artifactRegex.checkstyle=checkstyle-result.xml
jenkins-codequality.artifactRegex.jacoco=jacoco.xml
# Collector job depth (required) should be set to at least 1, and more if you use folder jobs etc
jenkins-codequality.jobDepth=4
```
Command - 

`java -jar jenkins-codequality-2.0.5-SNAPSHOT.jar --spring.config.location=..\jenkinsCQ.properties`
inside target folder.

I'm pretty sure it uses the properties file, since its connecting to the correct DB. So there's no problem with the command, must be something wrong with the properties file.

**Comment by anuradha92** [comment]
I got the same error
this is my properties file name : jenkins-codequality.properties and running command is java -jar jenkins-codequality-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins-codequality --spring.config.location=/C:/Users/anuradha92/Desktop/Newfolder/Hygieia/collectors/build/jenkins-codequality/jenkins-codequality.properties

**Comment by nitin1706** [comment]
Refer #1645 . you can try adding credentials as suggested by @Sbrenthughes
