### ISSUE TITLE
How  to start the UI in 2.0.4

### ISSUE THREAD

**Issue by yqbjtu** [capitalone/Hygieia#1668]
When I use Hygieia-2.0.2,  I start the UI by the following way.
export PATH=/home/qq/Downloads/Hygieia-2.0.2/UI/node:$PATH
source /etc/profile

root@yqubuntu:~/Downloads/Hygieia-2.0.2/UI/node_modules/gulp/bin$ node gulp serve

but for Hygieia-2.0.4. When I use the same way to start UI. it failed,
the error log:
[23:24:09] Working directory changed to /home/yangqian/Hygieia-2.0.4/UI
[23:24:10] Using gulpfile /home/yangqian/Hygieia-2.0.4/UI/gulpfile.js
[23:24:10] Starting 'build'...
[23:24:10] Starting 'clean'...
[23:24:10] Finished 'clean' after 45 ms
[23:24:10] Starting 'assets'...
[23:24:10] Starting 'themes'...
[23:24:10] Starting 'fonts'...
[23:24:10] Starting 'js'...
[23:24:10] Starting 'views'...
[23:24:10] Starting 'test-data'...
[23:24:10] Finished 'fonts' after 33 ms
[23:24:10] Finished 'themes' after 340 ms
[23:24:10] Finished 'assets' after 414 ms
[23:24:10] Finished 'test-data' after 413 ms
[23:24:10] Finished 'views' after 493 ms
[23:24:10] Finished 'js' after 552 ms
[23:24:10] Starting 'html'...
[23:24:10] 'html' errored after 7.29 ms
[23:24:10] Error: Error: Cannot find where you keep your Bower packages.
    at /home/yangqian/Hygieia-2.0.4/UI/node_modules/wiredep/wiredep.js:30:56
    at findBowerDirectory (/home/yangqian/Hygieia-2.0.4/UI/node_modules/wiredep/wiredep.js:108:27)
    at wiredep (/home/yangqian/Hygieia-2.0.4/UI/node_modules/wiredep/wiredep.js:37:43)
    at Gulp.<anonymous> (/home/yangqian/Hygieia-2.0.4/UI/gulpfile.js:255:13)
    at module.exports (/home/yangqian/Hygieia-2.0.4/UI/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/yangqian/Hygieia-2.0.4/UI/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/yangqian/Hygieia-2.0.4/UI/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/yangqian/Hygieia-2.0.4/UI/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/yangqian/Hygieia-2.0.4/UI/node_modules/run-sequence/index.js:88:16)
    at Gulp.onTaskEnd (/home/yangqian/Hygieia-2.0.4/UI/node_modules/run-sequence/index.js:77:5)
[23:24:10] 'build' errored after 631 ms
[23:24:10] Error in plugin 'run-sequence'
Message:
    An error occured in task 'html'.

According to the UI setup guide, 
### Running
"In terminal navigate to the project root and run ```gulp serve```. Should serve up on port 3000. "
I go to the /home/yangqian/Hygieia-2.0.4/, then execute "gulp serve" ,but still failed because can't find the module "/home/yangqian/Hygieia-2.0.4/gulp".

Thank you!

**Comment by yqbjtu** [comment]
I resolved this issue finally.
my solution is as following.
step1, use non-root user, to the project-root directory
 cd /home/yangqian/Hygieia-2.0.4
 sudo chmod -R 777 ./Hygieia-2.0.4
 then mvn clean package -pl UI docker:build
  results:the docker will failed, 

step2, go to /home/yangqian/Hygieia-2.0.4/UI/node_modules/gulp/bin
with root user
node gulp serve

result:server is up.

My questions:which use should we use to execute "mvn clean package -pl UI docker:build", where and which user should we use to execute "node gulp serve".

Thank you!

**Comment by arunbalajil** [comment]
Hi Team 

I am trying to implement Hygieia but resulting on this errors.

[INFO] --- frontend-maven-plugin:0.0.29:gulp (gulp build) @ UI ---
[INFO] Running 'gulp.js build' in /root/hygieia/UI
[ERROR]
[ERROR] assert.js:85
[ERROR]   throw new assert.AssertionError({
[ERROR]   ^
[ERROR] AssertionError: Task function must be specified
[ERROR]     at Gulp.set [as _setTask] (/root/hygieia/UI/node_modules/undertaker/lib/set-task.js:10:3)
[ERROR]     at Gulp.task (/root/hygieia/UI/node_modules/undertaker/lib/task.js:13:8)
[ERROR]     at Object.<anonymous> (/root/hygieia/UI/gulpfile.js:87:6)
[ERROR]     at Module._compile (module.js:570:32)
[ERROR]     at Object.Module._extensions..js (module.js:579:10)
[ERROR]     at Module.load (module.js:487:32)
[ERROR]     at tryModuleLoad (module.js:446:12)
[ERROR]     at Function.Module._load (module.js:438:3)
[ERROR]     at Module.require (module.js:497:17)
[ERROR]     at require (internal/module.js:20:19)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.824 s
[INFO] Finished at: 2018-09-27T22:50:38Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:gulp (gulp build) on project UI: Failed to run task: 'gulp.js build' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Please help on this.

Regards
Arun  Balaji

**Comment by Harika444** [comment]
how to solve that error

**Comment by Harika444** [comment]
assert.js:362
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Users\aharika\Desktop\hygieia\UI\node_modules\
undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Users\aharika\Desktop\hygieia\UI\node_modules\undertaker\li
b\task.js:13:8)
    at Object.<anonymous> (C:\Users\aharika\Desktop\hygieia\UI\gulpfile.js:88:6)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at execute (C:\Users\aharika\Desktop\hygieia\UI\node_modules\gulp-cli\lib\ve
rsioned\^4.0.0\index.js:36:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
 How to solve this.
