### ISSUE TITLE
JIRA Collector issue - No result was available from Jira unexpectedly - defaulting to blank response

### ISSUE THREAD

**Issue by tsr2017** [capitalone/Hygieia#1679]
No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(403), errorCollections=[]}
2017-08-28 15:34:00,738 INFO  c.c.d.collector.CollectorTask - Project Data            0        0s
2017-08-28 15:34:01,134 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.IOException: Server returned HTTP response code: 403 for URL: https://myjiraserver/rest/api/2/status/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[na:1.8.0_144]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_144]
	at java.net.URLConnection.getContent(URLConnection.java:739) ~[na:1.8.0_144]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:434) ~[na:1.8.0_144]
	at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:442) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:745) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:154) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2017-08-28 15:34:01,412 ERROR c.c.d.client.DefaultJiraClient - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(403), errorCollections=[]}

Below is my propery file - 
# Database Name
dbname=dashboard

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017,ip-172-31-26-184:27017

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2017-03-01T00:00:00.000000
feature.masterStartDate=2017-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2017-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
#In-built folder housing prepared REST queries (required)
feature.queryFolder=jiraapi-queries

feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

#feature.sprintDays=60
#feature.sprintEndPrior=7
#feature.scheduledPriorMin=2

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=http://proxy.com
#feature.jiraProxyPort=9000

feature.jiraBaseUrl=https://someserver.com/
feature.jiraQueryEndpoint=rest/api/2/

# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
feature.jiraCredentials=ZTcyNTA0Mzg6amZCMk8yMDE3

# OAuth is not fully implemented; please blank-out the OAuth values:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10002
feature.jiraStoryPointsFieldName=customfield_10003
feature.jiraTeamFieldName=

When I am trying to configure jira widget on dashboard I am unable to see any value for team name feild.

**Comment by tsr2017** [comment]
@satishc1 @tabladrum

**Comment by Sbrenthughes** [comment]
Try taking a look at https://github.com/capitalone/Hygieia/issues/335.

**Comment by tsr2017** [comment]
<img width="640" alt="screen shot 2017-08-29 at 4 32 50 pm" src="https://user-images.githubusercontent.com/31294059/29845352-1aaa867a-8cd8-11e7-8697-729660449958.png">
Also I am unable to change Any value for team and project name.
Before setting it to any, Whatever value I was giving for both of these feilds got disappear when I reponed it.
Do we need to explicitly specify project and team name here?

**Comment by tsr2017** [comment]
And what is the significance of **feature.pageSiz**e?

**Comment by tsr2017** [comment]
Now I am getting this
Server returned HTTP response code: 403 for URL: https://myjira.com/rest/api/2/status/

**Comment by MarkRx** [comment]
403 means unauthorized. Double check your credentials config

**Comment by tsr2017** [comment]
issue got resolve, was using wrong credentials
