### ISSUE TITLE
UI can't start

### ISSUE THREAD

**Issue by yqbjtu** [capitalone/Hygieia#1684]
I used master branch code and start ui  by node gulp serve  with root user under "/home/yangqian/Hygieia-master/UI/node_modules/gulp/bin"

I used ubuntu 16.04.3.

root@ubuntu:/home/yangqian/Hygieia-master/UI/node_modules/gulp/bin# **node gulp serve**
[02:37:31] Working directory changed to /home/yangqian/Hygieia-master/UI
[02:37:32] Using gulpfile /home/yangqian/Hygieia-master/UI/gulpfile.js
[02:37:32] Starting 'build'...
[02:37:32] Starting 'clean'...
[02:37:33] Finished 'clean' after 68 ms
[02:37:33] Starting 'assets'...
[02:37:33] Starting 'themes'...
[02:37:33] Starting 'fonts'...
[02:37:33] Starting 'js'...
[02:37:33] Starting 'views'...
[02:37:33] Starting 'test-data'...
[02:37:33] Finished 'fonts' after 31 ms
Error in plugin 'gulp-less'
Message:
    '../../../../bower_components/angular-ui-select/dist/select.css' wasn't found in file /home/yangqian/Hygieia-master/UI/src/components/widgets/deploy/view.less line no. 3
Details:
    type: File
    filename: /home/yangqian/Hygieia-master/UI/src/components/widgets/deploy/view.less
    index: 107
    line: 3
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: @import (reference) '../../../app/css/mixins.less';,@import (less)  '../../../../bower_components/angular-ui-select/dist/select.css';,
    lineNumber: 3
    fileName: /home/yangqian/Hygieia-master/UI/src/components/widgets/deploy/view.less
[02:37:33] Finished 'themes' after 427 ms
[02:37:33] Finished 'assets' after 489 ms
[02:37:33] Finished 'test-data' after 501 ms
[02:37:33] Finished 'views' after 592 ms
[02:37:33] Finished 'js' after 661 ms
[02:37:33] Starting 'html'...
[02:37:33] 'html' errored after 7.81 ms
[02:37:33] Error: Error: Cannot find where you keep your Bower packages.
    at /home/yangqian/Hygieia-master/UI/node_modules/wiredep/wiredep.js:30:56
    at findBowerDirectory (/home/yangqian/Hygieia-master/UI/node_modules/wiredep/wiredep.js:108:27)
    at wiredep (/home/yangqian/Hygieia-master/UI/node_modules/wiredep/wiredep.js:37:43)
    at Gulp.<anonymous> (/home/yangqian/Hygieia-master/UI/gulpfile.js:261:13)
    at module.exports (/home/yangqian/Hygieia-master/UI/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/yangqian/Hygieia-master/UI/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/yangqian/Hygieia-master/UI/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/yangqian/Hygieia-master/UI/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/yangqian/Hygieia-master/UI/node_modules/run-sequence/index.js:88:16)
    at Gulp.onTaskEnd (/home/yangqian/Hygieia-master/UI/node_modules/run-sequence/index.js:77:5)
[02:37:33] 'build' errored after 766 ms
[02:37:33] Error in plugin 'run-sequence'
Message:
    An error occured in task 'html'.

Ways I tried but did not resolve the issues
**1, I use root user to install bower**
   when running "npm install -g bower",  no effect 
   when running "npm install bower" under "/home/yangqian/Hygieia-master/UI", no effect

**2, I run the docker build command** 
   run "mvn clean package -pl UI docker:build" under "/home/yangqian/Hygieia-master"  with non-root user does not fix this issue.
 Notes:I executed the "chmod -R 777 /home/yangqian/Hygieia-master" to resolve the permission issue.
  
I also use root user, but have error:
![mvn_clean_package_-pl_ui_docker_build](https://user-images.githubusercontent.com/3291079/29815790-78917594-8ce4-11e7-9052-7ce61935e034.png)

yangqian@ubuntu:~/Hygieia-master$ mvn clean package -pl UI docker:build
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.capitalone.dashboard:api:jar:2.0.5-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.capitalone.dashboard:api-audit:jar:2.0.5-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (/home/yangqian/Hygieia-master/hygieia-jenkins-plugin/pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[WARNING] 'build.plugins.plugin.version' for org.jacoco:jacoco-maven-plugin is missing. @ line 214, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:UI 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UI ---
[INFO]
[INFO] >>> maven-pmd-plugin:3.6:check (default) > :pmd @ UI >>>
[INFO]
[INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ UI ---
[INFO]
[INFO] <<< maven-pmd-plugin:3.6:check (default) < :pmd @ UI <<<
[INFO]
[INFO]
[INFO] --- maven-pmd-plugin:3.6:check (default) @ UI ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:prepare-agent (default) @ UI ---
[INFO] argLine set to -javaagent:/home/yangqian/.m2/repository/org/jacoco/org.jacoco.agent/0.7.6.201602180812/org.jacoco.agent-0.7.6.201602180812-runtime.jar=destfile=/home/yangqian/Hygieia-master/UI/target/jacoco.exec
[INFO]
[INFO] --- frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) @ UI ---
[INFO] Found proxies: []
[INFO] Node v5.4.1 is already installed.
[INFO] NPM 2.14.15 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:0.0.29:npm (npm install) @ UI ---
[INFO] Found proxies: []
[INFO] Running 'npm install' in /home/yangqian/Hygieia-master/UI
[ERROR] npm ERR! Linux 4.10.0-32-generic
[ERROR] npm ERR! argv "/home/yangqian/Hygieia-master/UI/node/node" "/home/yangqian/Hygieia-master/UI/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v5.4.1
[ERROR] npm ERR! npm  v2.14.15
[ERROR] npm ERR! path /home/yangqian/Hygieia-master/UI/node_modules/mkdirp/bin/cmd.js
[ERROR] npm ERR! code EPERM
[ERROR] npm ERR! errno -1
[ERROR] npm ERR! syscall chmod
[ERROR]
[ERROR] npm ERR! Error: EPERM: operation not permitted, chmod '/home/yangqian/Hygieia-master/UI/node_modules/mkdirp/bin/cmd.js'
[ERROR] npm ERR!     at Error (native)
[ERROR] npm ERR!  { [Error: EPERM: operation not permitted, chmod '/home/yangqian/Hygieia-master/UI/node_modules/mkdirp/bin/cmd.js']
[ERROR] npm ERR!   errno: -1,
[ERROR] npm ERR!   code: 'EPERM',
[ERROR] npm ERR!   syscall: 'chmod',
[ERROR] npm ERR!   path: '/home/yangqian/Hygieia-master/UI/node_modules/mkdirp/bin/cmd.js' }
[ERROR] npm ERR!
[ERROR] npm ERR! Please try running this command again as root/Administrator.
[ERROR]
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/yangqian/Hygieia-master/UI/npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.427 s
[INFO] Finished at: 2017-08-29T02:30:57-07:00
[INFO] Final Memory: 42M/338M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:npm (npm install) on project UI: Failed to run task: '**npm install**' failed. (error code 255) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Could any one help me resolve this issue?   Or which user and command should I use?

Thank you very much!

**Comment by yqbjtu** [comment]
This issue is resolved today.

I add the "--allow-root" to the pom.xml under '/home/yangqian/Hygieia-master/UI/'.

          <execution>
            <id>bower install</id>
            <goals>
              <goal>bower</goal>
            </goals>
            <configuration>
              <arguments>install --allow-root</arguments>
            </configuration>
          </execution>
