### ISSUE TITLE
UI log in is not working

### ISSUE THREAD

**Issue by sachins50** [capitalone/Hygieia#1737]
This is my Dashboard properties file:

# dashboard.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
server.contextPath=/api
server.port=8080
logRequest=false
logSplunkRequest=false
corsEnabled=false

My API is started.. As I see true when I hit following URL: http://localhost:8080/api/ping

My UI is started as following:

C:\Hygieia-master\UI> gulp serve --local true
[13:44:07] Using gulpfile C:\Hygieia-master\UI\gulpfile.js
[13:44:07] Starting 'build'...
[13:44:07] Starting 'clean'...
[13:44:08] Finished 'clean' after 310 ms
[13:44:08] Starting 'assets'...
[13:44:08] Starting 'themes'...
[13:44:08] Starting 'fonts'...
[13:44:08] Starting 'js'...
[13:44:08] Starting 'views'...
[13:44:08] Starting 'test-data'...
[13:44:19] Finished 'assets' after 11 s
[13:44:19] Finished 'themes' after 11 s
[13:44:19] Finished 'test-data' after 12 s
[13:44:20] Finished 'views' after 12 s
[13:44:21] Finished 'js' after 13 s
[13:44:48] Finished 'fonts' after 41 s
[13:44:48] Starting 'html'...
[13:44:49] gulp-inject 1 files into index.html.
[13:44:49] gulp-inject 138 files into index.html.
[13:44:49] Finished 'html' after 819 ms
[13:44:49] Finished 'build' after 42 s
[13:44:49] Starting 'serve'...
[13:44:57] Finished 'serve' after 7.89 s
[BS] Local URL: http://localhost:3000
[BS] External URL: http://192.168.1.2:3000
[BS] Serving files from: dist/

![error1](https://user-images.githubusercontent.com/9337770/30761539-99f80042-9fac-11e7-95d0-a9bc5bc1abaa.jpg)

But when I try login - nothing happens. I stay on same page.
How do I login and resolve this issue?

Thanks,
SachinS

**Comment by nitin1706** [comment]
do you see any error in api logs.

**Comment by nitin1706** [comment]
do you see errors on api log? if so, share stack trace.

**Comment by sachins50** [comment]
[logs-api.txt](https://github.com/capitalone/Hygieia/files/1325732/logs-api.txt)


I am not seeing any error/exception. I am attaching logs with this ticket.

Thanks,
SachinS

**Comment by nitin1706** [comment]
I see a few exceptions in these logs. 
Here are the two highlighting:
2017-09-22 15:34:53,046 WARN  o.s.c.c.c.ConfigServicePropertySourceLocator - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect

2017-09-22 15:35:07,248 INFO  o.s.w.s.m.m.a.RequestMappingHandlerMapping - Mapped "{[/registerUser],methods=[POST],consumes=[application/json],produces=[application/json]}" onto public org.springframework.http.ResponseEntity<java.lang.Void> com.capitalone.dashboard.rest.AuthenticationController.registerUser(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,com.capitalone.dashboard.request.AuthenticationRequest) throws java.io.IOException,javax.servlet.ServletException

can you try again with full path to properties file

**Comment by sachins50** [comment]
Thanks Nitin.

I am running following command:
java -jar api.jar --spring.config.location=dashboard.properties -Djasypt.encryptor.password=hygieiasecret

Do I need to change anything in my command?

**Comment by nitin1706** [comment]
try with providing full path to properties file along with this:  --spring.config.name=dashboard

**Comment by sachins50** [comment]
[logs-api-2.txt](https://github.com/capitalone/Hygieia/files/1325919/logs-api-2.txt)

I tried 
java -jar api.jar --spring.config.location=dashboard.properties --spring.config.name=dashboard -Djasypt.encryptor.password=hygieiasecret

But still same issue is happening. No Login at UI.
I am attaching latest logs.

Thanks,
SachinS

**Comment by nitin1706** [comment]
where is your dashboard.properties file located? if it is at different location than tar, can you try with providing complete path from root?

**Comment by nitin1706** [comment]
also, can you try `http://localhost:8080/api/ping` to see what response you get?

**Comment by sachins50** [comment]
Hello,

I am running the command as below:-

_C:\Hygieia-master\api\target>java -jar api.jar --spring.config.location=dashboard.properties --spring.config.name=dashboard_


And I have dashboard.properties in the same directory:-

_C:\Hygieia-master\api\target>dir

Directory of C:\Hygieia-master\api\target

09/22/2017  02:57 PM    <DIR>          .
09/22/2017  02:57 PM    <DIR>          ..
09/12/2017  10:23 PM        56,793,166 api.jar
09/12/2017  10:23 PM         1,080,184 api.jar.original
09/12/2017  10:23 PM    <DIR>          classes
09/22/2017  03:34 PM             1,118 dashboard.properties
09/12/2017  10:23 PM    <DIR>          generated-sources
09/12/2017  10:23 PM    <DIR>          generated-test-sources
09/25/2017  08:51 AM    <DIR>          logs
09/12/2017  10:23 PM    <DIR>          maven-archiver
09/12/2017  10:23 PM    <DIR>          maven-status
09/12/2017  10:23 PM               107 pmd.xml
09/12/2017  10:23 PM    <DIR>          surefire-reports
09/12/2017  10:23 PM    <DIR>          test-classes_



When I tried to click to login via UI from this URL  http://localhost:3000/#/login :-
I see followig error in chrome browser tool:-

bower.js:25860 TypeError: response.headers is not a function
    
at processResponse (authService.js:15)
    
at processQueue (bower.js:28357)
    
at bower.js:28373
    
at Scope.$eval (bower.js:29655)
    
at Scope.$digest (bower.js:29469)
    
at Scope.$apply (bower.js:29763)
    
at done (bower.js:23743)
    
at completeRequest (bower.js:23952)
    
at XMLHttpRequest.requestLoaded (bower.js:23880)
(anonymous) 
@ bower.js:25860
(anonymous) 
@ bower.js:22368
processQueue 
@ bower.js:28365
(anonymous) 
@ bower.js:28373
$eval 
@ bower.js:29655
$digest 
@ bower.js:29469
$apply 
@ bower.js:29763
done 
@ bower.js:23743
completeRequest 
@ bower.js:23952
requestLoaded 
@ bower.js:23880
XMLHttpRequest.send (async)
(anonymous) 
@ bower.js:23926
sendReq 
@ bower.js:23688
serverRequest 
@ bower.js:23483
processQueue 
@ bower.js:28357
(anonymous) 
@ bower.js:28373
$eval 
@ bower.js:29655
$digest 
@ bower.js:29469
$apply 
@ bower.js:29763
(anonymous) 
@ bower.js:38258
dispatch 
@ bower.js:5206
elemData.handle 
@ bower.js:5014


I tried hitting ping url and I get 'true' in return.

Thanks,
SachinS

**Comment by sachins50** [comment]
Thanks I was able to login to dashboard now.

I am trying to use appDynamics performance collector.


But when I try to run the following command:

C:\Hygieia-master\collectors\performance\appdynamics\target>java -jar appdynamics-performance-collector-2.0.5-SNAPSHOT.jar --spring.config.name=appdynamics --spring.config.location="C:\Hygieia-master\collectors\performance\appdynamics\application.properties"


I am getting errors like -

2017-09-25 22:57:20,142 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeou
t=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@389871ab, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=
5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHost
NamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='n
ull', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@4b812102, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@1b15bdfc, socketFactory=javax.net.DefaultSocketFactory@256d7a12, cursorFinalizerEnabled=t
rue, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayM
S=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbe
atFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2017-09-25 22:57:20,263 INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboard', password=<hidden>, mechanismProperties={}}
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:61) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_144]
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "
code" : 18, "codeName" : "AuthenticationFailed" }
        at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:95) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:45) ~[mongo-java-driver-3.0.2.jar!/:na]
        ... 5 common frames omitted
2017-09-25 22:57:22,112 INFO  org.mongodb.driver.cluster - No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionM
ode=SINGLE, all=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1
, userName='dashboarduser', source='dashboard', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on serv
er localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }}}]}. Waiting for 30000 ms before timing out



Following is my appD prop file:


###Sample application.properties file

#Database Name
database=dashboarddb

#Database HostName - default is localhost
dbhost=localhost

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=dashboarduser

#Database Password - default is blank
dbpassword=dashboarduser

#Logging File
logging.file=./logs/appd-collector.log

#Collector schedule (required)
appdynamics.cron=1 * * * * *

#Appdynamics server (required)
appdynamics.instanceUrls=https://appdyn-gctpoc.nam.nsroot.net:8090/

#Appdynamics Username (required)
appdynamics.username=ss99083@customer1

#Appdynamics Password (required)
appdynamics.password=Welcome1

#Appdynamics Dashboard (required)
appdynamics.dashboardUrl=https://appdyn-gctpoc.nam.nsroot.net:8090/controller/#/location=APP_DASHBOARD&timeRange=last_15_minutes.BEFORE_NOW.-1.-1.15&application=53&dashboardMode=force



Following is mine API dashboard props file:

# dashboard.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
server.contextPath=/api
server.port=8080
logRequest=false
logSplunkRequest=false
corsEnabled=false
auth.authenticationProviders=STANDARD

#corsWhitelist=http://domain1.com:port,http://domain2.com:port
#version.number=@application.version.number@


# LDAP Server Url, including port of your LDAP server
#auth.ldapServerUrl=[ldap://company.com:389]

# If using standard ldap
# LDAP User Dn Pattern, where the username is replaced with '{0}'
#auth.ldapUserDnPattern=[uid={0},OU=Users,dc=your,dc=company,dc=com]

# If using ActiveDirectory
# This will be the domain part of your userPrincipalName
#auth.adDomain=[company.com]
# This will be your root dn
#auth.adRootDn=[dc=your,dc=company,dc=com]
# This will be your active directory url (required for AD)
#auth.adUrl=[Need an example]

#monitor.proxy.host=[hostname of proxy server]
#monitor.proxy.type=[http|socks|direct]
#monitor.proxy.port=[port enabled on proxy server]
#monitor.proxy.username=[proxy username]
#monitor.proxy.password=[proxy password]


Please can you share working props files from your side?
Also please let me know if the DBname/ DBuser and DBpasswd has to be same in both the files and also in the mongoDB. And if it is different in mongoDB - then how can I update/correct it?


Thanks a lot for your help,

SachinS

**Comment by nitin1706** [comment]
password and username in your appDynamics properties are same, Please update the password to correct, and it will be able to authenticate against DB.
`dbpassword=dashboarduser`

Open a new issue if you any error.

**Comment by vishnuvangala** [comment]
Hi @nitin1706 ,
I'm getting the same error. Looks like login seems to be not happening. Also I can see the same 2 exceptions in log file that you were mentioning above. I tried giving the full path to properties file and even added  --spring.config.name=dashboard.. still I see those 2 errors in log file. can you please help?

command I used:
I'm in ~/HYGIEIA/Hygieia/api/target: 

java -jar api.jar --spring.config.location=/home/XXXX/HYGIEIA/Hygieia/api/api.properties --spring.config.name=dashboard -Djasypt.encryptor.password=hygieiasecret

I don't see any other errors in api log also dont see anything in browser console.

**Comment by sundeepk1** [comment]
I am also getting the same error, @vishnuvangala were you able to fix this. If yes then can you please help me to fix this issue

**Comment by vishnuvangala** [comment]
@sundeepk1 
I'm not getting this error anymore. I have configured only minimum required properties in api and restarted it and I don't see any issue now.
One thing you need to note is.. whenever you restart api.. we should clear cache/history from browser and try to open the page again and relogin. otherwise.. you might see some errors in logs and you'll not be able to login.
Also, just check this property value.. it should be more otherwise its gets logged of frequently. auth.expirationTime=7200000

**Comment by sundeepk1** [comment]
thanks @vishnuvangala I will be checking it out today and confirm here
