### ISSUE TITLE
Latest version fails to build

### ISSUE THREAD

**Issue by clcain** [capitalone/Hygieia#1796]
I am trying to build Hygieia on an Ubuntu 16.04 machine. I have tried cloning the Hygieia repostory, ensuring that I am on the master branch and that everything is up to date, then running `mvn clean install package`. The build fails.

It gives the following error message:
```
Results :

Failed tests: 
  DefaultSecurityTest.registerUser:87 Status expected:<200> but was:<401>

Tests run: 287, Failures: 1, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  0.655 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 20.098 s]
[INFO] com.capitalone.dashboard:api ....................... FAILURE [ 11.775 s]
```

The machine is running the following software:
```
Apache Maven 3.5.2
Java version: 1.8.0_151, vendor: Oracle Corporation
```
I was expecting this to be a software version issue, or for there to be something missing from my system. However, as far as I can tell, the Hygieia documentation only states Java 1.8 as a requirement.

I can get the build to succeed if I check out the tag `Hygieia-2.0.4`, but not on master.

Am I missing something?

**Comment by nireeshT** [comment]
@clcain  current version on Hygieia is 2.0.5. You working on latest code base?

**Comment by crouchar** [comment]
Yea the latest is broken for me too. Tests fail on the API component.

**Comment by clcain** [comment]
@nireeshT I was running `mvn clean install package` while on the latest version of the `master` branch. At the time of posting, that was commit 817b176f0f40b04cc2ec229d4c4c182fb80a80f5.

I don't see a tag for 2.0.5, where can I get that version?

**Comment by clcain** [comment]
I tried again today, the build succeeds on `master` as of commit 4c7389513c023759a1513c5eb05d160425040744.

**Comment by crouchar** [comment]
The clean isn’t working right then. If you do a fresh git checkout and wipe out your .m2 repo you can replicate the test failure on HEAD of master

-----------------------------------
Alan R. Crouch

**Comment by clcain** [comment]
@crouchar The latest version works for me, even on a different machine with a fresh clone of the repository.

**Comment by ikfas** [comment]
I'm having the same problem. I tried multiple git clone but I'm still having the error.
 Did you discover what was the source of it ?

**Comment by crouchar** [comment]
My work around was to pull the tag for 2.0.4 and install that one.  Note
the only gotcha was that I had problems with some of the collectors on
2.0.4, but it looks like they are all dependency/timing issues.  If you do
a mvn install 2 or 3 times they will eventually resolve themselves and
compile.



*Alan R. Crouch **Account Manager (Federal Services) at Coveros
<http://www.coveros.com>*
*571.309.4561*
*www.twitter.com/RealAlanCrouch <http://www.twitter.com/RealAlanCrouch> *

**Comment by crouchar** [comment]
@clcain @ikfas, realistically i think this ticket should be reopened.  multiple people are reporting the exact same issue.

**Comment by nireeshT** [comment]
@crouchar @clcain @ikfas  - Please share error log

**Comment by ikfas** [comment]
`2017-11-07 11:09:18,878 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2017-11-07 11:09:19,014 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:42}] to localhost:27017
2017-11-07 11:09:19,016 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 10]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=713894}
2017-11-07 11:09:19,753 INFO  c.c.d.auth.DefaultSecurityTest - Started DefaultSecurityTest in 4.648 seconds (JVM running for 12.316)
2017-11-07 11:09:19,767 INFO  o.s.b.t.SpringBootMockServletContext - Initializing Spring FrameworkServlet ''
2017-11-07 11:09:19,767 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization started
2017-11-07 11:09:19,773 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization completed in 6 ms
2017-11-07 11:09:19,844 INFO  o.s.b.t.SpringBootMockServletContext - Initializing Spring FrameworkServlet ''
2017-11-07 11:09:19,844 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization started
2017-11-07 11:09:19,849 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization completed in 5 ms
2017-11-07 11:09:19,901 INFO  o.s.b.t.SpringBootMockServletContext - Initializing Spring FrameworkServlet ''
2017-11-07 11:09:19,902 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization started
2017-11-07 11:09:19,906 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization completed in 4 ms
2017-11-07 11:09:19,917 INFO  o.s.b.t.SpringBootMockServletContext - Initializing Spring FrameworkServlet ''
2017-11-07 11:09:19,917 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization started
2017-11-07 11:09:19,927 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization completed in 10 ms
2017-11-07 11:09:19,940 INFO  o.s.b.t.SpringBootMockServletContext - Initializing Spring FrameworkServlet ''
2017-11-07 11:09:19,940 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization started
2017-11-07 11:09:19,946 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization completed in 6 ms
2017-11-07 11:09:19,957 INFO  o.s.b.t.SpringBootMockServletContext - Initializing Spring FrameworkServlet ''
2017-11-07 11:09:19,958 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization started
2017-11-07 11:09:19,966 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization completed in 8 ms
2017-11-07 11:09:19,987 INFO  o.s.b.t.SpringBootMockServletContext - Initializing Spring FrameworkServlet ''
2017-11-07 11:09:19,987 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization started
2017-11-07 11:09:19,991 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization completed in 4 ms
2017-11-07 11:09:19,995 INFO  o.s.b.t.SpringBootMockServletContext - Initializing Spring FrameworkServlet ''
2017-11-07 11:09:19,995 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization started
2017-11-07 11:09:19,999 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization completed in 4 ms
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.949 sec <<< FAILURE! - in com.capitalone.dashboard.auth.DefaultSecurityTest
registerUser(com.capitalone.dashboard.auth.DefaultSecurityTest)  Time elapsed: 0.081 sec  <<< FAILURE!
java.lang.AssertionError: Status expected:<200> but was:<401>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:60)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:89)
	at org.springframework.test.web.servlet.result.StatusResultMatchers$10.match(StatusResultMatchers.java:655)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:171)
	at com.capitalone.dashboard.auth.DefaultSecurityTest.registerUser(DefaultSecurityTest.java:87)

Running com.capitalone.dashboard.auth.AuthenticationUtilTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.capitalone.dashboard.auth.AuthenticationUtilTest
Running com.capitalone.dashboard.auth.ldap.LdapAuthenticationDetailsSourceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.capitalone.dashboard.auth.ldap.LdapAuthenticationDetailsSourceTest
Running com.capitalone.dashboard.auth.ldap.LdapLoginRequestFilterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.capitalone.dashboard.auth.ldap.LdapLoginRequestFilterTest
Running com.capitalone.dashboard.config.monitor.ProxyAuthenticatorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.capitalone.dashboard.config.monitor.ProxyAuthenticatorTest
Running com.capitalone.dashboard.config.monitor.MonitorProxyConfigTest
Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.114 sec - in com.capitalone.dashboard.config.monitor.MonitorProxyConfigTest
Running com.capitalone.dashboard.util.URLConnectionFactoryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec - in com.capitalone.dashboard.util.URLConnectionFactoryTest
Running com.capitalone.dashboard.util.PaginationHeaderUtilityTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec - in com.capitalone.dashboard.util.PaginationHeaderUtilityTest
Running com.capitalone.dashboard.logging.LoggingFilterTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.041 sec - in com.capitalone.dashboard.logging.LoggingFilterTest
Running com.capitalone.dashboard.logging.KeyValueLoggingConditionTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec - in com.capitalone.dashboard.logging.KeyValueLoggingConditionTest
Running com.capitalone.dashboard.logging.KeyValueLoggingFilterTest
2017-11-07 11:09:20,389 INFO  c.c.d.logging.KeyValueLoggingFilter - REMOTE_ADDRESS="http://127.0.0.1" APPLICATION_NAME="appName" APPLICATION_VERSION="2.0.5-SNAPSHOT" REQUEST_URL="http://127.0.0.1/api" REQUEST_METHOD="POST" STATUS_CODE="200" SESSION_ID="sessionId" USER_NAME="username" USER_DETAILS="details" USER_AUTHORITIES="[ROLE_ADMIN]"
2017-11-07 11:09:20,391 INFO  c.c.d.logging.KeyValueLoggingFilter - REMOTE_ADDRESS="http://127.0.0.1" APPLICATION_NAME="appName" APPLICATION_VERSION="2.0.5-SNAPSHOT" REQUEST_URL="http://127.0.0.1/api" REQUEST_METHOD="POST" STATUS_CODE="200" USER_NAME="username" USER_DETAILS="details" USER_AUTHORITIES="[ROLE_ADMIN]"
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in com.capitalone.dashboard.logging.KeyValueLoggingFilterTest
Running com.capitalone.dashboard.logging.DatabaseLoggingConditionTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.capitalone.dashboard.logging.DatabaseLoggingConditionTest
Running com.capitalone.dashboard.service.UserInfoServiceImplTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in com.capitalone.dashboard.service.UserInfoServiceImplTest
Running com.capitalone.dashboard.service.MaturityModelServiceImplTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.capitalone.dashboard.service.MaturityModelServiceImplTest
Running com.capitalone.dashboard.service.TeamServiceImplTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec - in com.capitalone.dashboard.service.TeamServiceImplTest
Running com.capitalone.dashboard.service.DashboardRemoteServiceTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec - in com.capitalone.dashboard.service.DashboardRemoteServiceTest
Running com.capitalone.dashboard.service.DeployServiceTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.083 sec - in com.capitalone.dashboard.service.DeployServiceTest
Running com.capitalone.dashboard.service.BuildServiceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.107 sec - in com.capitalone.dashboard.service.BuildServiceTest
Running com.capitalone.dashboard.service.CloudInstanceServiceImplTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.059 sec - in com.capitalone.dashboard.service.CloudInstanceServiceImplTest
Running com.capitalone.dashboard.service.BinaryArtifactServiceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec - in com.capitalone.dashboard.service.BinaryArtifactServiceTest
Running com.capitalone.dashboard.service.TemplateServiceTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in com.capitalone.dashboard.service.TemplateServiceTest
Running com.capitalone.dashboard.service.CloudSubnetServiceImplTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec - in com.capitalone.dashboard.service.CloudSubnetServiceImplTest
Running com.capitalone.dashboard.service.DashboardServiceTest
Tests run: 28, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.959 sec - in com.capitalone.dashboard.service.DashboardServiceTest
Running com.capitalone.dashboard.service.DynamicPipelineServiceImplTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.051 sec - in com.capitalone.dashboard.service.DynamicPipelineServiceImplTest
Running com.capitalone.dashboard.service.PipelineServiceTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 0.005 sec - in com.capitalone.dashboard.service.PipelineServiceTest
Running com.capitalone.dashboard.service.CollectorServiceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.capitalone.dashboard.service.CollectorServiceTest
Running com.capitalone.dashboard.service.ServiceServiceTest
2017-11-07 11:09:21,807 ERROR c.c.d.model.monitor.MonitorService - dashboardId: 5a0186515d616b4ff3a4f3a9 http://some.url failed with protocol doesn't support input
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 sec - in com.capitalone.dashboard.service.ServiceServiceTest
Running com.capitalone.dashboard.service.AuthenticationServiceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.capitalone.dashboard.service.AuthenticationServiceTest
Running com.capitalone.dashboard.service.FeatureServiceImplTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 sec - in com.capitalone.dashboard.service.FeatureServiceImplTest
Running com.capitalone.dashboard.service.ApiTokenServiceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.capitalone.dashboard.service.ApiTokenServiceTest
Running com.capitalone.dashboard.model.MonitorServiceTest
2017-11-07 11:09:21,841 ERROR c.c.d.model.monitor.MonitorService - dashboardId: 5a0186515d616b4ff3a4f3d4 http://www.google.com failed with null
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.capitalone.dashboard.model.MonitorServiceTest
Running com.capitalone.dashboard.model.ServiceStatusTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.capitalone.dashboard.model.ServiceStatusTest
2017-11-07 11:09:21,858 INFO  o.s.w.c.s.GenericWebApplicationContext - Closing org.springframework.web.context.support.GenericWebApplicationContext@69e153c5: startup date [Tue Nov 07 11:09:08 CET 2017]; root of context hierarchy
2017-11-07 11:09:21,866 INFO  o.s.w.c.s.GenericWebApplicationContext - Closing org.springframework.web.context.support.GenericWebApplicationContext@2d913116: startup date [Tue Nov 07 11:09:15 CET 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@60c96eb4
2017-11-07 11:09:21,867 INFO  o.s.w.c.s.GenericWebApplicationContext - Closing org.springframework.web.context.support.GenericWebApplicationContext@3dc95b8b: startup date [Tue Nov 07 11:09:13 CET 2017]; root of context hierarchy

Results :

Failed tests: 
  DefaultSecurityTest.registerUser:87 Status expected:<200> but was:<401>

Tests run: 289, Failures: 1, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia .................. SUCCESS [  1.305 s]
[INFO] com.capitalone.dashboard:core ..................... SUCCESS [ 27.427 s]
[INFO] com.capitalone.dashboard:api ...................... FAILURE [ 19.638 s]
[INFO] com.capitalone.dashboard:api-audit ................ SKIPPED
[INFO] com.capitalone.dashboard:artifactory-artifact-collector  SKIPPED
[INFO] com.capitalone.dashboard:bamboo-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-build-collector .. SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector  SKIPPED
[INFO] com.capitalone.dashboard:jenkins-codequality ...... SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector  SKIPPED
[INFO] com.capitalone.dashboard:aws-cloud-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector  SKIPPED
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector  SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector ... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector  SKIPPED
[INFO] com.capitalone.dashboard:gitlab-feature-collector . SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:appdynamics-performance-collector  SKIPPED
[INFO] com.capitalone.dashboard:bitbucket-scm-collector .. SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ..... SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ..... SKIPPED
[INFO] com.capitalone.dashboard:gitlab-scm-collector ..... SKIPPED
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:nexus-iq-collector ....... SKIPPED
[INFO] Hygieia Publisher Plugin .......................... SKIPPED
[INFO] com.capitalone.dashboard:UI ....................... SKIPPED
[INFO] com.capitalone.dashboard:ui-tests ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.000 s
[INFO] Finished at: 2017-11-07T11:09:21+01:00
[INFO] Final Memory: 71M/681M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project api: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/john/Desktop/ji/Hygieia/api/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :api `

@crouchar @clcain @nireeshT - Here is the error I get

**Comment by crouchar** [comment]
[hygieia.log](https://github.com/capitalone/Hygieia/files/1450680/hygieia.log)

**Comment by subodhbattina** [comment]
Regarding this test failure: "DefaultSecurityTest.registerUser":
Please include this property shown below in the "test.properties" file, and re-run the build with -X option (mvn -X clean install).

**auth.expirationTime=120000**

Let us know if this solves the problem. Thanks.

**Comment by subodhbattina** [comment]
@ikfas:
Wanted to touch base and check if you were able to update your "test.properties" file and re-run the build. You could set  **auth.expirationTime** to higher value like may be **1200,000**, and try again. So **auth.expirationTime=1200000**. Please let me know when you get a chance where you stand with this? Thanks !

**Comment by subodhbattina** [comment]
@ikfas: Since we didn't hear back from you, assuming this issue was resolved based on the latest suggestions posted. Closing this issue. Thanks !
