### ISSUE TITLE
Jenkins collector not starting up throws error "Error getting jobs for"

### ISSUE THREAD

**Issue by abhishek789** [capitalone/Hygieia#1804]
Hi Team

@amitmawkin 
@tabladrum 

I am not able to run jenkins collector.
It gives following output-

C:\Hygieia_code\Hygieia\collectors\build\jenkins\target>java -jar jenkins-build-collector-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins --spring.config.location=C:\Hygieia_code\Hygieia\collectors\build\jenkins\jenkins.properties
11:48:45,952 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:48:45,953 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:48:45,953 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/C:/Hygieia_code/Hygieia/collectors/build/jenkins/target/jenkins-build-collector-2.0.5-SNAPSHOT.jar!/logback.xml]
11:48:45,954 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
11:48:45,954 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Hygieia_code/Hygieia/collectors/build/jenkins/target/jenkins-build-collector-2.0.5-SNAPSHOT.jar!/logback.xml]
11:48:45,954 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Hygieia_code/Hygieia/collectors/build/jenkins/target/jenkins-build-collector-2.0.5-SNAPSHOT.jar!/lib/core-2.0.5-SNAPSHOT.jar!/logback.xml]
11:48:45,983 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@43b1dd0c - URL [jar:file:/C:/Hygieia_code/Hygieia/collectors/build/jenkins/target/jenkins-build-collector-2.0.5-SNAPSHOT.jar!/logback.xml] is not of type file
11:48:46,065 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:48:46,075 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:48:46,088 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
11:48:46,123 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:48:46,223 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:48:46,226 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ROLLING]
11:48:46,274 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
11:48:46,276 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/buildcollector-%d{yyyy-MM-dd}.%i.log for the active file
11:48:46,279 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@59d1c5b7 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/buildcollector-%d{yyyy-MM-dd}.%i.log'.
11:48:46,279 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@59d1c5b7 - Roll-over at midnight.
11:48:46,282 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@59d1c5b7 - Setting initial period to Mon Oct 30 11:48:46 UTC 2017
11:48:46,284 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:48:46,285 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - Active log file name: logs/buildcollector-2017-10-30.0.log
11:48:46,285 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - File property is set to [null]
11:48:46,286 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:48:46,286 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ROLLING] to Logger[ROOT]
11:48:46,287 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
11:48:46,287 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:48:46,287 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6e1b0a47 - Registering current configuration as safe fallback point

2017-10-30 11:48:47,310 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@77f94a93: startup date [Mon Oct 30 11:48:47 UTC 2017]; root of context hierarchy
2017-10-30 11:48:47,590 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-10-30 11:48:47,697 INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'configurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$4b540f1a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
_   _             _      _             ______       _ _     _        _____       _ _           _
| | | |           (_)    (_)            | ___ \     (_) |   | |      /  __ \     | | |         | |
| |_| |_   _  __ _ _  ___ _  __ _ ______| |_/ /_   _ _| | __| |______| /  \/ ___ | | | ___  ___| |_ ___  _ __
|  _  | | | |/ _` | |/ _ \ |/ _` |______| ___ \ | | | | |/ _` |______| |    / _ \| | |/ _ \/ __| __/ _ \| '__|
| | | | |_| | (_| | |  __/ | (_| |      | |_/ / |_| | | | (_| |      | \__/\ (_) | | |  __/ (__| || (_) | |
\_| |_/\__, |\__, |_|\___|_|\__,_|      \____/ \__,_|_|_|\__,_|       \____/\___/|_|_|\___|\___|\__\___/|_|
        __/ | __/ |
       |___/ |___/

2017-10-30 11:48:48,153 INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://localhost:8888
2017-10-30 11:48:49,260 WARN  o.s.c.c.c.ConfigServicePropertySourceLocator - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2017-10-30 11:48:49,264 INFO  com.capitalone.dashboard.Application - No profiles are active
2017-10-30 11:48:49,295 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@51e57f27: startup date [Mon Oct 30 11:48:49 UTC 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@77f94a93
2017-10-30 11:48:50,738 INFO  o.s.cloud.context.scope.GenericScope - BeanFactory id=b1c495d1-a7f7-3ceb-9446-61a55758b526
2017-10-30 11:48:50,748 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Post-processing PropertySource instances
2017-10-30 11:48:50,771 INFO  c.u.j.c.StringEncryptorConfiguration - String Encryptor custom Bean not found with name 'jasyptStringEncryptor'. Initializing String Encryptor based on properties with name 'jasyptStringEncryptor'
2017-10-30 11:48:50,786 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2017-10-30 11:48:50,787 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2017-10-30 11:48:50,787 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemEnvironment [org.springframework.core.env.SystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
2017-10-30 11:48:50,788 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource random [org.springframework.boot.context.config.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2017-10-30 11:48:50,789 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource applicationConfig: [file:C:/Hygieia_code/Hygieia/collectors/build/jenkins/jenkins.properties] [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2017-10-30 11:48:50,791 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2017-10-30 11:48:50,792 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource defaultProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2017-10-30 11:48:50,807 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-10-30 11:48:50,844 INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$4b540f1a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-10-30 11:48:50,925 INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService  'taskScheduler'
2017-10-30 11:48:51,001 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2017-10-30 11:48:51,069 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2017-10-30 11:48:51,191 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2017-10-30 11:48:51,254 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@ed16bf34, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@f2f6a2e, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@3bf4eab8, socketFactory=javax.net.DefaultSocketFactory@59d731c1, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2017-10-30 11:48:51,723 INFO  org.mongodb.driver.cluster - No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
2017-10-30 11:48:52,181 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:82}] to localhost:27017
2017-10-30 11:48:52,185 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 10]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=2325500}
2017-10-30 11:48:52,213 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:83}] to localhost:27017
2017-10-30 11:48:52,601 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2017-10-30 11:48:52,601 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2017-10-30 11:48:52,604 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2017-10-30 11:48:52,605 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@ed16bf34, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@f2f6a2e, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@3bf4eab8, socketFactory=javax.net.DefaultSocketFactory@59d731c1, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2017-10-30 11:48:52,617 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2017-10-30 11:48:52,618 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2017-10-30 11:48:52,619 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2017-10-30 11:48:52,620 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@ed16bf34, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@f2f6a2e, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@3bf4eab8, socketFactory=javax.net.DefaultSocketFactory@59d731c1, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2017-10-30 11:48:52,736 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:84}] to localhost:27017
2017-10-30 11:48:52,737 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 10]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=331400}
2017-10-30 11:48:53,149 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2017-10-30 11:48:53,160 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2017-10-30 11:48:53,177 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2017-10-30 11:48:53,179 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@ed16bf34, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@f2f6a2e, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@3bf4eab8, socketFactory=javax.net.DefaultSocketFactory@59d731c1, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2017-10-30 11:48:53,955 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2017-10-30 11:48:53,968 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2017-10-30 11:48:53,983 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'environmentManager' has been autodetected for JMX exposure
2017-10-30 11:48:53,984 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'refreshScope' has been autodetected for JMX exposure
2017-10-30 11:48:53,989 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2017-10-30 11:48:54,010 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2017-10-30 11:48:54,018 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=51e57f27,type=ConfigurationPropertiesRebinder]
2017-10-30 11:48:54,077 INFO  com.capitalone.dashboard.Application - Started Application in 7.652 seconds (JVM running for 8.503)
2017-10-30 11:48:54,095 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:86}] to localhost:27017
2017-10-30 11:48:54,096 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 10]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=580700}
2017-10-30 11:48:54,098 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:85}] to localhost:27017
2017-10-30 11:48:54,099 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 10]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=336400}
2017-10-30 11:49:00,004 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-10-30 11:49:00,033 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-10-30 11:49:00,035 INFO  c.c.d.collector.CollectorTask - http://localhost:9001
2017-10-30 11:49:00,038 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-10-30 11:49:00,069 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 403 Forbidden
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:655) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:192) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:110) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:99) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:37) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
2017-10-30 11:49:00,073 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://localhost:9001 0s

PFB my properties file-

#Database Name 
dbname=hellodb
 
#Database HostName - default is localhost
dbhost=localhost
 
#Database Port - default is 27017
dbport=27017
 
#Database Username - default is blank
dbusername=abhi
 
#Database Password - default is blank
dbpassword=abhi123
 
# Collector schedule (required)
jenkins.cron=0 0/1 * * * *

# The page size
jenkins.pageSize=1000

# The folder depth - default is 10
jenkins.folderDepth=10

jenkins.servers[0]=http://localhost:9001
 
#Jenkins server (required) - Can provide multiple
 
#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
#jenkins.servers[1]=http://username:token@jenkins.company.com
#jenkins.servers[1]=http://admin1:da4879810be2f040ec0930346973e3af@localhost:9000/
#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)

jenkins.username=jenkinsuser
jenkins.apiKey=76f6a6fb168c7b4f423cbf03a2eb443d
 
#Determines if build console log is collected - defaults to false
jenkins.saveLog=false

Could you please let me know what am i missing here?
I have been trying this for a week now.
I am able to configure github collector but jenkins collector throws this error.

**Comment by nireeshT** [comment]
change below properties and restart collector
jenkins.servers[0]=http://localhost:9001/
jenkins.usernames[0]=jenkins username
jenkins.apiKeys[0]= password

**Comment by nireeshT** [comment]
@abhishek789  you got issue resolved?

**Comment by Sbrenthughes** [comment]
Closing because duplicate.. https://github.com/capitalone/Hygieia/issues/1793
