### ISSUE TITLE
ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits

### ISSUE THREAD

**Issue by rtemzare** [capitalone/Hygieia#1828]
I am getting below error:

ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from http://localhost:7990/rest/api/1.0/projects/hdd/repos/com.hygieia.demo.test/commits?until=master&limit=25
org.springframework.web.client.HttpClientErrorException: 401
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RE
LEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:235) ~[bitbucket-scm-collector-2.0.5-S
NAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:90) ~[bitbucket-scm-collector-2.0.5-SNAP
SHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:148) [bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar
!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_144]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_144]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_144]
2017-11-08 17:25:00,071 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2017-11-08 17:25:00,072 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2017-11-08 17:25:00,073 INFO  c.c.d.collector.CollectorTask - Finished                         0s

Property file:
dbname=dashboard

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

logging.file=C:/logs/bitbucket.log

# Collector schedule (required)
git.cron=0 0/5 * * * *

# Mandatory parameters
git.host=http://localhost:7990
git.api=/rest/api/1.0/

# Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

# Page size for rest calls
#   Only applicable to Bitbucket Server.
#   Only applicable to Bitbucket Cloud.
git.pageSize=25

# Bitbucket product
#   Set to 'cloud' to use Bitbucket Cloud (formerly known as Bitbucket)
#   Set to 'server' to use Bitbucket Server (formerly known as Stash)
#   More information can be found here:	
#https://github.com/capitalone/Hygieia/issues/609
git.product=server

and entry of bitbucket.key also there in dashboard.properties file.
In attached image you can see yellow ball where it tool tip the pending data collection message.

![capture](https:// collecuser-images.githubusercontent.com/33485094/32550148-0be49c9a-c4b2-11e7-8ce5-6fe7a56e2bf3.PNG)

**Comment by nireeshT** [comment]
@rtemzare  - try passing username and password in git.host=http://localhost:7990

**Comment by rvema** [comment]
@rtemzare closing due to inactivity, please reopen is this is still happening.
