### ISSUE TITLE
JIRA Collector not showing status correctly

### ISSUE THREAD

**Issue by mcahill7** [capitalone/Hygieia#1838]
Currently the JIRA widget shows all items as open, even closed/resolved/in progress items.
This the log of the container

`2017-11-14 18:45:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2017-11-14 18:45:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-11-14 18:45:00,004 INFO  c.c.d.collector.CollectorTask - 
2017-11-14 18:45:00,004 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-11-14 18:45:00,004 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2017-11-14 18:45:00,909 INFO  c.c.d.collector.CollectorTask - Project Data           14        0s
2017-11-14 18:45:01,650 ERROR c.c.d.client.DefaultJiraClient - Parser exception when parsing statuses
org.json.simple.parser.ParseException: null
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
	at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:365) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:727) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:152) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2017-11-14 18:45:01,835 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 0
2017-11-14 18:45:01,835 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2017-11-14 18:45:01,835 INFO  c.c.d.collector.CollectorTask - Finished                         1s
`
Jira section of compose file: 
`  hygieia-jira:
    image: hygieia-jira-feature-collector
    container_name: hygieia-jira
    environment:
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE=dashboarddb
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME=xxxx
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD=xxxx
      - SPRING_DATA_MONGODB_HOST=172.17.0.1
      - SPRING_DATA_MONGODB_PORT=27017
      - MONGO_PORT=tcp://172.17.0.1:27017
      - JIRA_BASE_URL=https://xxxx
      - JIRA_URL=https://xxxxx
      - JIRA_CREDENTIALS=xxxx
      - JIRA_PAGE_SIZE=100
      - JIRA_QUERY_ENDPOINT=-rest/api/2/
      - JIRA_ISSUE_TYPE_NAMES=Sub-task
      - JIRA_BOARD_AS_TEAM=false
      - JIRA_TEAM_FIELD_NAME=
      - JIRA_STORY_POINTS_FIELD_NAME=
      - JIRA_EPIC_FIELD_NAME=
      - JIRA_SPRINT_DATA_FIELD_NAME=
      - JIRA_DELTA_COLLECTOR_ITEM_START_DATE:-2008-01-01T00:00:00.000000
    restart: always
    network_mode: "host"`

Properties file as it is in the container:

`#Database Name
dbname=dashboarddb
dbhost=172.17.0.1
dbport=27017
dbusername=xxx
dbpassword=xxx
feature.cron=0 * * * * *
feature.pageSize=100
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
feature.jiraProxyUrl=
feature.jiraProxyPort=
feature.sprintDays=60
feature.sprintEndPrior=7
feature.scheduledPriorMin=2
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000
feature.jiraBaseUrl=https://api-sharedservices.dhs.gov/jira
feature.jiraUrl=https://sharedservices.dhs.gov/jira
feature.jiraQueryEndpoint=-rest/api/2/
feature.jiraCredentials=
feature.jiraOauthAuthtoken=sdfghjkl==
feature.jiraOauthRefreshtoken=sdfagheh==
feature.jiraOauthRedirecturi=uri.this.is.test:uri
feature.jiraOauthExpiretime=234567890987
feature.deltaStartDate=2015-03-01T00:00:00.000000
feature.masterStartDate=2008-01-01T00:00:00.000000
feature.jiraIssueTypeNames=Sub-task
feature.jiraSprintDataFieldName=customfield_10007
feature.jiraEpicIdFieldName=customfield_10400
feature.jiraStoryPointsFieldName=customfield_10002
feature.jiraTeamFieldName=
`

**Comment by subodhbattina** [comment]
Hi @mcahill7:
Looks like the status information coming back your JIRA endpoint may not be a valid JSON.

Based on the properties file you shared, please go to this URL below and check what your are getting is a valid JSON or not:

https://api-sharedservices.dhs.gov/jira/rest/api/2/status/.

Thanks !

**Comment by subodhbattina** [comment]
@mcahill7: Since we didn't hear back from you on where you stand on this issue based on the latest comments/suggestions made on the issue, we are going ahead and closing this out for now. Thanks !
