### ISSUE TITLE
AWS Collector Null Pointer Exceptions

### ISSUE THREAD

**Issue by yks0000** [capitalone/Hygieia#1852]
Hygieia Team,

Seeing NPE while starting AWS Collector. Could you please help as what is missing?

Command to Start:

`Path: collectors/cloud/aws/target/`

`java -jar aws-cloud-collector-2.0.5-SNAPSHOT.jar --spring.config.name=aws --spring.config.location=application.properties`

Property File:

> dbname=dashboarddb
> dbhost=127.0.0.1
> dbport=27017
> dbusername=dashboarduser
> dbpassword=dbpassword
> logging.file=./logs/cloud.log
> aws.cron=0 0/1 * * * *
> aws.validTagKey[0]=Name
> aws.validTagKey[1]=Project
> aws.profile=default

Error:

```
2017-11-20 13:43:15,407 INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://localhost:8888
2017-11-20 13:43:15,543 WARN  o.s.c.c.c.ConfigServicePropertySourceLocator - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default":Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
2017-11-20 13:43:15,544 INFO  com.capitalone.dashboard.Application - No profiles are active

2017-11-20 13:43:17,126 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AWSCloudCollectorTask' defined in URL [jar:file:/usr/local/src/Hygieia/collectors/cloud/aws/target/aws-cloud-collector-2.0.5-SNAPSHOT.jar!/com/capitalone/dashboard/collector/AWSCloudCollectorTask.class]: Unsatisfied dependency expressed through constructor argument with index 3 of type [com.capitalone.dashboard.collector.AWSCloudClient]: Error creating bean with name 'defaultAWSCloudClient' defined in URL [jar:file:/usr/local/src/Hygieia/collectors/cloud/aws/target/aws-cloud-collector-2.0.5-SNAPSHOT.jar!/com/capitalone/dashboard/collector/DefaultAWSCloudClient.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.capitalone.dashboard.collector.DefaultAWSCloudClient]: Constructor threw exception; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultAWSCloudClient' defined in URL [jar:file:/usr/local/src/Hygieia/collectors/cloud/aws/target/aws-cloud-collector-2.0.5-SNAPSHOT.jar!/com/capitalone/dashboard/collector/DefaultAWSCloudClient.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.capitalone.dashboard.collector.DefaultAWSCloudClient]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at com.capitalone.dashboard.Application.main(Application.java:38) [aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultAWSCloudClient' defined in URL [jar:file:/usr/local/src/Hygieia/collectors/cloud/aws/target/aws-cloud-collector-2.0.5-SNAPSHOT.jar!/com/capitalone/dashboard/collector/DefaultAWSCloudClient.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.capitalone.dashboard.collector.DefaultAWSCloudClient]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	... 24 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.capitalone.dashboard.collector.DefaultAWSCloudClient]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	... 37 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:460) ~[na:1.8.0_151]
	at com.capitalone.dashboard.collector.DefaultAWSCloudClient.setClients(DefaultAWSCloudClient.java:76) ~[aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultAWSCloudClient.<init>(DefaultAWSCloudClient.java:67) ~[aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_151]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	... 39 common frames omitted
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AWSCloudCollectorTask' defined in URL [jar:file:/usr/local/src/Hygieia/collectors/cloud/aws/target/aws-cloud-collector-2.0.5-SNAPSHOT.jar!/com/capitalone/dashboard/collector/AWSCloudCollectorTask.class]: Unsatisfied dependency expressed through constructor argument with index 3 of type [com.capitalone.dashboard.collector.AWSCloudClient]: Error creating bean with name 'defaultAWSCloudClient' defined in URL [jar:file:/usr/local/src/Hygieia/collectors/cloud/aws/target/aws-cloud-collector-2.0.5-SNAPSHOT.jar!/com/capitalone/dashboard/collector/DefaultAWSCloudClient.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.capitalone.dashboard.collector.DefaultAWSCloudClient]: Constructor threw exception; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultAWSCloudClient' defined in URL [jar:file:/usr/local/src/Hygieia/collectors/cloud/aws/target/aws-cloud-collector-2.0.5-SNAPSHOT.jar!/com/capitalone/dashboard/collector/DefaultAWSCloudClient.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.capitalone.dashboard.collector.DefaultAWSCloudClient]: Constructor threw exception; nested exception is java.lang.NullPointerException
```

**Comment by Sbrenthughes** [comment]
Is `spring.config.location=application.properties` the correct path to your properties file?

**Comment by yks0000** [comment]
@Sbrenthughes Yes, `spring.config.location=application.properties` is correct location.


> # cd hygieia/collectors/cloud/aws/target/
> [root@ip-172-31-26-211 target]# ls -lhrt
> total 66M
> drwxr-xr-x 3 root root  35 Nov 20 13:05 maven-status
> drwxr-xr-x 3 root root  25 Nov 20 13:05 generated-sources
> drwxr-xr-x 3 root root  54 Nov 20 13:05 classes
> drwxr-xr-x 2 root root 240 Nov 20 13:05 test-classes
> drwxr-xr-x 2 root root  28 Nov 20 13:05 maven-archiver
> drwxr-xr-x 2 root root  50 Nov 20 13:31 logs
> -rw-r--r-- 1 root root 104 Nov 20 13:40 pmd.xml
> -rw-r--r-- 1 root root 21K Nov 20 13:40 aws-cloud-collector-2.0.5-SNAPSHOT.jar.original
> -rw-r--r-- 1 root root 66M Nov 20 13:40 aws-cloud-collector-2.0.5-SNAPSHOT.jar
> -rw-r--r-- 1 root root 457 Nov 20 13:43 application.properties

**Comment by yks0000** [comment]
So, there is a hard dependency on all the config property, If I pass all (mainly proxy) with dummy value and other with actual value (those of need), it works. Ideally it should not be, proxy values should not be mandatory.

> # AWS Proxy Host
> aws.proxyHost=localhost
> 
> # AWS Proxy Port
> aws.proxyPort=3333
> 
> # AWS Non Proxy
> aws.nonProxy=xxx.xxx.xxx.xxx

**Comment by yks0000** [comment]
I installed Apache Forward Proxy to get this going, but facing another issue as it picks us-east-1 region only. Is there any way to define aws region to pick?

**Comment by yks0000** [comment]
I made fix to my local by changing code as follows.

At `line number 78, 81, and 83` I changed `ec2Client, cloudWatchClient and autoScalingClient` as follows:

        ```
ec2Client = new AmazonEC2Client(new AWSCredentialsProviderChain(new ProfileCredentialsProvider(settings.getProfile()),
                new InstanceProfileCredentialsProvider())).withRegion(Regions.US_WEST_2);

        cloudWatchClient = new AmazonCloudWatchClient(new AWSCredentialsProviderChain(new ProfileCredentialsProvider(settings.getProfile()),
                new InstanceProfileCredentialsProvider())).withRegion(Regions.US_WEST_2);
        autoScalingClient = new AmazonAutoScalingClient(new AWSCredentialsProviderChain(new ProfileCredentialsProvider(settings.getProfile()),
                new InstanceProfileCredentialsProvider())).withRegion(Regions.US_WEST_2);
```

Seems like you might need to add a property For eg: `aws.region=xxxx` and have it called here.

**Comment by rohit0503** [comment]
After making the changes to the code, I am getting the below error while running mvn install :
`[ec2-user@ip-10-218-22-60 aws]$ mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:aws-cloud-collector 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-pmd-plugin:3.6:check (default) > :pmd @ aws-cloud-collector >>>
[INFO]
[INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ aws-cloud-collector ---
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO]
[INFO] <<< maven-pmd-plugin:3.6:check (default) < :pmd @ aws-cloud-collector <<<
[INFO]
[INFO] --- maven-pmd-plugin:3.6:check (default) @ aws-cloud-collector ---
[INFO]
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ aws-cloud-collector ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ aws-cloud-collector ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /home/ec2-user/Hygieia/collectors/cloud/aws/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/ec2-user/Hygieia/collectors/cloud/aws/src/main/java/com/capitalone/dashboard/collector/DefaultAWSCloudClient.java:[79,71] cannot find symbol
  symbol:   variable Regions
  location: class com.capitalone.dashboard.collector.DefaultAWSCloudClient
[ERROR] /home/ec2-user/Hygieia/collectors/cloud/aws/src/main/java/com/capitalone/dashboard/collector/DefaultAWSCloudClient.java:[84,71] cannot find symbol
  symbol:   variable Regions
  location: class com.capitalone.dashboard.collector.DefaultAWSCloudClient
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.644 s
[INFO] Finished at: 2017-11-29T14:55:38+00:00
[INFO] Final Memory: 52M/600M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project aws-cloud-collector: Compilation failure: Compilation failure:
[ERROR] /home/ec2-user/Hygieia/collectors/cloud/aws/src/main/java/com/capitalone/dashboard/collector/DefaultAWSCloudClient.java:[79,71] cannot find symbol
[ERROR] symbol:   variable Regions
[ERROR] location: class com.capitalone.dashboard.collector.DefaultAWSCloudClient
[ERROR] /home/ec2-user/Hygieia/collectors/cloud/aws/src/main/java/com/capitalone/dashboard/collector/DefaultAWSCloudClient.java:[84,71] cannot find symbol
[ERROR] symbol:   variable Regions
[ERROR] location: class com.capitalone.dashboard.collector.DefaultAWSCloudClient
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

Please help.

**Comment by yks0000** [comment]
Seems like Error in your update. `/home/ec2-user/Hygieia/collectors/cloud/aws/src/main/java/com/capitalone/dashboard/collector/DefaultAWSCloudClient.java:[79,71] cannot find symbol [ERROR] symbol: variable Regions [ERROR] location: class`

Not sure  how you made the change. I would prefer replacing `DefaultAWSCloudClient.java` with https://gist.github.com/yks0000/d2ff8f3f6d8e6074cf584da7fc49fd9d and then `mvn install` from `collectors/cloud/aws`

**Comment by rohit0503** [comment]
Hi,
Finally after replacing the file it worked. Thanks for the Help. I appreciate.
I have one more Question : 
If i need to include more regions, can i do that also?

**Comment by matthewbeasley** [comment]
@yks0000, @rohit0503 - Running the aws collector cross-region isn't recommended. You should instead have separate instances of Hygieia for each region.

**Comment by yks0000** [comment]
@matthewbeasley how to set region property for aws collector, I don't see any?

**Comment by matthewbeasley** [comment]
@yks0000 - there isn't a property for this as the aws collector isn't intended work across regions. It is intended to collect data for the region it is deployed. In order to collect data from a region other than us-east-1 simply deploy the collector in the region for which you would like to collect data. As this isn't an issue per se I'm going to close this, but please feel free to continue the discussion.

**Comment by yks0000** [comment]
@matthewbeasley I am running collector in us-west-2 region but it collects data for us-east-1 only. If this has to collect for Home region then ideally it should collect for us-west-2 instead of us-east-1. Please suggest.

**Comment by syedafirdaus** [comment]
@yks0000 did you get any solution? I copied your file from https://gist.github.com/yks0000/d2ff8f3f6d8e6074cf584da7fc49fd9d but still maven throws error.

i have raised a new request here . Please advise 
https://github.com/Hygieia/Hygieia/issues/2774

**Comment by zerolaser** [comment]
@yks0000 How did you got the aws proxy settings work for you. 
I tried setting the dummy values as you did but still running into `Unable to execute HTTP request: Connection refused (Connection refused)`
any help here is appreciated.
