### ISSUE TITLE
Jenkins Collectorr

### ISSUE THREAD

**Issue by Dhruva231** [capitalone/Hygieia#1858]
@tabladrum @satishc1 

Getting below error message, while running Jenkins collector, also not able to view "Create Widget" in my hygieia dashboard.

Is it possible to have teleconference.

I am also facing same issue, is it possible to have screen share

2017-11-20 22:50:00,008 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
 java.lang.NullPointerException: null
 at java.util.ArrayList.addAll(ArrayList.java:581) ~[na:1.8.0_151]
 at com.capitalone.dashboard.model.HudsonCollector.prototype(HudsonCollec tor.java:49) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
 at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(H udsonCollectorTask.java:69) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5 -SNAPSHOT]
 at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(H udsonCollectorTask.java:37) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5 -SNAPSHOT]
 at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.ja va:48) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
 at org.springframework.scheduling.support.DelegatingErrorHandlingRunnabl e.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.ja r!/:4.2.5.RELEASE]
 at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(Re schedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51 1) [na:1.8.0_151]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_15 1]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask. access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask. run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor. java:1149) [na:1.8.0_151]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor .java:624) [na:1.8.0_151]
 at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
 2017-11-20 22:55:00,000 INFO c.c.d.collector.CollectorTask - Running Collector: Hudson
 2017-11-20 22:55:00,002 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
 java.lang.NullPointerException: null
 at java.util.ArrayList.addAll(ArrayList.java:581) ~[na:1.8.0_151]
 at com.capitalone.dashboard.model.HudsonCollector.prototype(HudsonCollector.java:49) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
 at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:69) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
 at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:37) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
 at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:48) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
 at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
 at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
 at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by Dhruva231** [comment]
@Sbrenthughes , I am using java -jar Jen.jar --spring.config.name=jekins --spring.config.location=<path to application.properties>

we have production deployment on coming Monday, please can some one help me via screen sharing.

Your help is much appreciated

**Comment by Dhruva231** [comment]
please help me to fix this issue, we have prod deployment scheduled for sunday

**Comment by Dhruva231** [comment]
also  I am getting below error in api module
DefaultSecurityTest.registerUser:87 Status expected:<200> but was:<401>

**Comment by Dhruva231** [comment]
we have prod deployment, please help me

**Comment by Dhruva231** [comment]
This is my application.properties file content

dbusername=
dbpassword=
dbhost=localhost
dbport-27017
dbreplicateset=false
dbhostport=localhost:27017,127.0.0.1:27017,ip-172-31-26-184:27017
jenkins.cron=0 0/5 * * * *
jenkins.pageSize=1000
jenkins.folderDepth:10
jenkins.server[0]=http://admin:<token>@<hostname>:9090/jenkins
jenkins.slaveLog=false

**Comment by Sbrenthughes** [comment]
I have made some corrections to your command. The` config.name` was misspelled and make sure the `config.location` is <path_to_prop_file>/prop_file
`java -jar Jen.jar --spring.config.name=jenkins --spring.config.location=<path_to_prop_file>`

**Comment by Dhruva231** [comment]
@Sbrenthughes 

I am running below command
java -jar jenkins-build-collector-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins --spring.config.location=/data/Hygieia-master/collectors/build/jenkins/application.properties

2017-11-23 04:10:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-11-23 04:10:00,015 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at java.util.ArrayList.addAll(ArrayList.java:581) ~[na:1.8.0_151]
        at com.capitalone.dashboard.model.HudsonCollector.prototype(HudsonCollector.java:49) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:69) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:37) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:48) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
**2017-11-23 04:15:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson**
2017-11-23 04:15:00,004 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at java.util.ArrayList.addAll(ArrayList.java:581) ~[na:1.8.0_151]
        at com.capitalone.dashboard.model.HudsonCollector.prototype(HudsonCollector.java:49) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:69) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:37) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:48) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2017-11-23 04:20:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-11-23 04:20:00,004 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at java.util.ArrayList.addAll(ArrayList.java:581) ~[na:1.8.0_151]
        at com.capitalone.dashboard.model.HudsonCollector.prototype(HudsonCollector.java:49) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:69) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:37) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:48) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by Sbrenthughes** [comment]
Are you passing in the token here?
`jenkins.server[0]=http://admin:@:9090/jenkins`

**Comment by Sbrenthughes** [comment]
`dbport-27017`
should be
`dbport=27017`
