### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:bower (bower install) on project UI: Failed to run task: 'bower install --allow-root' failed.

### ISSUE THREAD

**Issue by nkarra08** [capitalone/Hygieia#1877]
[INFO] bower@1.8.2 node_modules/bower
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.29:bower (bower install) @ UI ---
[DEBUG] Configuring mojo com.github.eirslett:frontend-maven-plugin:0.0.29:bower from plugin realm ClassRealm[plugin>com.github.eirslett:frontend-maven-plugin:0.0.29, parent: sun.misc.Launcher$AppClassLoader@4e25154f]
[DEBUG] Configuring mojo 'com.github.eirslett:frontend-maven-plugin:0.0.29:bower' with basic configurator -->
[DEBUG]   (f) arguments = install --allow-root
[DEBUG]   (f) project = MavenProject: com.capitalone.dashboard:UI:2.0.5-SNAPSHOT @ /opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI/pom.xml
[DEBUG]   (f) repositorySystemSession = org.eclipse.aether.DefaultRepositorySystemSession@6403e24c
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@2f236de0
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipTests = true
[DEBUG]   (f) workingDirectory = /opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI
[DEBUG]   (f) execution = com.github.eirslett:frontend-maven-plugin:0.0.29:bower {execution: bower install}
[DEBUG] -- end configuration --
[INFO] Found proxies: []
[INFO] Running 'bower install --allow-root' in /opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI
[ERROR] /opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI/node_modules/bower/lib/node_modules/bower-config/lib/util/rc.js:71
[ERROR]         throw error;
[ERROR]         ^
[ERROR] 
[ERROR] Error: Unable to parse /opt/homes/EntDevOps/.bowerrc: Unexpected token : in JSON at position 44
[ERROR]     at parse (/opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI/node_modules/bower/lib/node_modules/bower-config/lib/util/rc.js:64:21)
[ERROR]     at json (/opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI/node_modules/bower/lib/node_modules/bower-config/lib/util/rc.js:84:16)
[ERROR]     at rc (/opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI/node_modules/bower/lib/node_modules/bower-config/lib/util/rc.js:32:26)
[ERROR]     at Config.load (/opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI/node_modules/bower/lib/node_modules/bower-config/lib/Config.js:16:20)
[ERROR]     at readCachedConfig (/opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI/node_modules/bower/lib/config.js:15:39)
[ERROR]     at defaultConfig (/opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI/node_modules/bower/lib/config.js:11:12)
[ERROR]     at Object.<anonymous> (/opt/apps/partitioned-Slaves/partition-1/fc77c055/workspace/AA-DevOps/EIS-DevOps/Dev/EDT-Development/UI/node_modules/bower/lib/index.js:16:32)
[ERROR]     at Module._compile (module.js:570:32)
[ERROR]     at Object.Module._extensions..js (module.js:579:10)
[ERROR]     at Module.load (module.js:487:32)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:35 min
[INFO] Finished at: 2017-12-01T15:30:44-06:00
[INFO] Final Memory: 24M/285M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:bower (bower install) on project UI: Failed to run task: 'bower install --allow-root' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:bower (bower install) on project UI: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'bower install --allow-root' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60)
	at com.github.eirslett.maven.plugins.frontend.mojo.BowerMojo.execute(BowerMojo.java:42)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89)
	... 22 more
[ERROR]

**Comment by matthewbeasley** [comment]
Hi nkarra08. This line is your biggest hint. There seems to be an issue with the JSON in your .bowerrc
[ERROR] Error: Unable to parse /opt/homes/EntDevOps/.bowerrc: Unexpected token : in JSON at position 44
Please verify the contents of the this file. Use [this](https://jsonlint.com/) or something similar to validate your bower settings and try again.

**Comment by matthewbeasley** [comment]
@nkarra08 - I'm sorry that I didn't use the @ notation so that you would receive a notification for the previous comment. Can you please take a look at my response?

**Comment by matthewbeasley** [comment]
@nkarra08 - closing this due to inactivity.
