### ISSUE TITLE
Error encrypting password since Update

### ISSUE THREAD

**Issue by hrushie** [capitalone/Hygieia#1904]
we have perfect Hygieia setup since last 4 months and since last update I am getting error encrypting password error while entering bitbucket credentials. previously I have created encryption key and was using it without any issues, this time as well I have created the encryption key and entered it in the Api and Bitbucket properties file still I am getting the error. 

Recently I have noticed that you guys have removed the documentation for creating a encryption key for private repos, do I have to use another technique to get access to my SCM data? I look forward to hear back from you guys.
My Properties file is as below - 

dbname=dashboard
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017,ip-
logging.file=./logs/bitbucket.log
git.cron=0 0/5 * * * *
git.host=repo link 
git.api=/rest/api/1.0/
github.UserId=username
github.key=key
git.key=key
bitbucket.key=key
git.commitThresholdDays=15
git.pageSize=25
git.product=server

Thanks,
Rushikesh

@nireeshT

**Comment by matthewbeasley** [comment]
@hrushie - I'm currently looking into this issue. We have not removed the documentation for creating an encryption key. You can find that [here](http://www.capitalone.io/Hygieia/setup.html)

**Comment by matthewbeasley** [comment]
@hrushie - can you please provide additional details on the error you are receiving? A screenshot of your logs with your personal info redacted would be best.

**Comment by matthewbeasley** [comment]
@hrushie - also check [here](http://www.capitalone.io/Hygieia/troubleshoot.html) for more info on github encryption for private repos

**Comment by hrushie** [comment]
[
<img width="598" alt="screen shot 2017-12-18 at 3 53 50 pm" src="https://user-images.githubusercontent.com/585126/34303829-0babd21e-e6ec-11e7-8242-3555477c190d.png">
Hi @matthewbeasley this is the error I am getting

**Comment by matthewbeasley** [comment]
@hrushie - Can you please provide the logs of the API when the error occurs. That is where the valuable information is.

**Comment by hrushie** [comment]
Hi @matthewbeasley there are no errors only this msg pops up.

2017-12-26 13:45:00,100 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2017-12-26T13:45:00.102-0800 I NETWORK  [listener] connection accepted from 127.0.0.1:55408 #146 (13 connections now open)
2017-12-26T13:45:00.130-0800 I ACCESS   [conn146] Successfully authenticated as principal dashboarduser on dashboard
2017-12-26 13:45:00,131 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:115, serverValue:146}] to localhost:27017
2017-12-26 13:45:00,134 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-12-26 13:45:00,134 INFO  c.c.d.collector.CollectorTask - Starting...
2017-12-26 13:45:00,134 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-12-26 13:45:00,137 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2017-12-26 13:45:00,141 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2017-12-26 13:45:00,141 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-12-26 13:46:55,459 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:115, serverValue:146}] to localhost:27017 because it is past its maximum allowed idle time.
2017-12-26T13:46:55.466-0800 I NETWORK  [conn146] end connection 127.0.0.1:55408 (12 connections now open)

**Comment by matthewbeasley** [comment]
@hrushie - hmm. what about the console logs in your browser?

**Comment by hrushie** [comment]
Hi @matthewbeasley ,

here are the log from my web console

dashboard.js:38 Dashboard Object
:3000/api/encrypt/ Failed to load resource: the server responded with a status of 401 (Unauthorized)
api-status.js:16 appinfo:2.0.5-SNAPSHOT
:3000/#/login:1 [DOM] Found 2 elements with non-unique id #lg: (More info: https://goo.gl/9p2vKq) <form class=​"col-xs-10 col-xs-push-1 col-sm-8 col-sm-push-2 ng-dirty ng-valid ng-submitted ng-valid-invalid-username-password-remove ng-valid-parse-remove ng-valid-required-remove" id=​"lg" name=​"lg" ng-submit=​"login(username, password)​" role=​"form" novalidate style>​…​</form>​ <form class=​"col-xs-10 col-xs-push-1 col-sm-8 col-sm-push-2 ng-pristine ng-valid-add ng-invalid-remove ng-invalid-required-remove ng-valid" id=​"lg" name=​"lg" ng-submit=​"login(username, password)​" role=​"form" novalidate>​…​</form>​
:3000/api/encrypt/ Failed to load resource: the server responded with a status of 401 (Unauthorized)
dashboard.js:38 Dashboard Object

**Comment by matthewbeasley** [comment]
@hrushie - in your api.properties file what do you have set for `auth.expirationTime`?

**Comment by hrushie** [comment]
1000000

**Comment by hrushie** [comment]
<img width="551" alt="screen shot 2017-12-29 at 9 06 17 am" src="https://user-images.githubusercontent.com/585126/34442538-9b9f48ac-ec77-11e7-9411-fd26bdc72fe4.png">

**Comment by hrushie** [comment]
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:235) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:90) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:148) [bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

**Comment by hrushie** [comment]
@matthewbeasley

**Comment by hrushie** [comment]
My api.properties file 

# Database Name
dbname=dashboard

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017,ip-172-31-26-184:27017

server.contextPath=/api
server.port=8084
corsEnabled=false
#corsWhitelist=http://domain1.com:port,http://domain2.com:port
#version.number=@application.version.number@

auth.expirationTime=1000000


key=HF6RYpGwfM4qbtVMNONYbXDWqEUERXXx

@matthewbeasley

**Comment by alexandruivan** [comment]
I was trying to use the bitbucket collector and I can confirm the same issue.

**Comment by rodrigocmn** [comment]
+1

**Comment by rodrigocmn** [comment]
Ok! I've managed to find what was wrong on my side...

@hrushie 
In my case, I made a mistake in the command that starts the API layer and didn't point to the right api.properties file. As I copied the command from the installation webpage, I didn't realise that it was a windows command and forgot to replace the backslash to forward slash (I'm running Hytgieia on RHEL). So it would be good for you to double check your start command.

@alexandruivan 
Looking at the source code, I realised that you need to add the following property to your bitbucket properties file:

git.key=<same key you've used for api.properties key>

I believe that [this documentation](http://www.capitalone.io/Hygieia/setup.html#encryption-for-private-repos) is wrong, as it says we should use the respective repo name as the prefix for the key property (i.e. github.key, bitbucket.key).

Hope it helps!

**Comment by matthewbeasley** [comment]
@rodrigocmn - thank you so much for this comment. You are right that the documentation is wrong in those two places. We will update it very soon. Also, thank you for sharing what you did to fix the issue on your end as this is very valuable information to us and the community at large.

**Comment by rodrigocmn** [comment]
@matthewbeasley my pleasure!

**Comment by matthewbeasley** [comment]
@hrushie, @alexandruivan - since @rodrigocmn was able to successfully set up his collector I believe this issue should be closed. If either of you still have issues please reach out to me at our [gitter.im](https://gitter.im/capitalone/Hygieia) channel. I look forward to talking to you there.

**Comment by rodrigocmn** [comment]
@matthewbeasley just one last comment... even when I was getting the encryption error, the api layer was not throwing any error. I believe that is because the catch block in the EncryptionServiceImpl is using logger at debug level.

```
public String encrypt(String message) {
        String key = apiSettings.getKey();
        String returnString = "ERROR";
        if (!"".equals(key)) {
            try {
                returnString = Encryption.encryptString(message, key);
            } catch (EncryptionException ignored) {
                LOGGER.debug("Caught encryption exception", ignored);
            }
        }
        return returnString;
    }
```

**Comment by matthewbeasley** [comment]
@rodrigocmn - good catch, I think it should probably be `LOGGER.error()` or at least `LOGGER.warning()`. I'm going to submit a PR for this.
