### ISSUE TITLE
Bamboo configure

### ISSUE THREAD

**Issue by sachingupta771** [capitalone/Hygieia#1912]
Hi i'm trying to configure bamboo in hygieia but unable to do so,

someone pls share some sample application.properties file for bamboo and explicitly how can we connect to bamboo, do we need the api token key or password should work.
i have tried several ways pls help me asap.

attached logs :

nder]
2017-12-22 17:04:56,260 INFO  com.capitalone.dashboard.Application - Started Application in 10.159 seconds (JVM running for 11.304)
2017-12-22 17:05:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Bamboo
2017-12-22 17:05:00,101 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-12-22 17:05:00,102 INFO  c.c.d.collector.CollectorTask - https://qa.tools.sapient.com/bamboo
2017-12-22 17:05:00,102 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-12-22 17:05:01,212 ERROR c.c.d.collector.DefaultBambooClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultBambooClient.makeRestCall(DefaultBambooClient.java:381) ~[bamboo-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultBambooClient.getInstanceJobs(DefaultBambooClient.java:67) ~[bamboo-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.BambooCollectorTask.collect(BambooCollectorTask.java:94) [bamboo-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.BambooCollectorTask.collect(BambooCollectorTask.java:34) [bamboo-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]

**Comment by Sbrenthughes** [comment]
Can you scrub and post your properties file?

**Comment by sachingupta771** [comment]
## MongoDB related properties
dbport=27017
dbname=demodb
dbhost=localhost
dbusername=demo
dbpassword=demo@123

dbreplicaset=false
bamboo.saveLog=true
bamboo.cron=0 0/1 * * * *
bamboo.servers[0]=https://bamboo server url
bamboo.username=demouser
bamboo.apiKey=fbc5069b-1dw6-4c4c-46d0-5e363c4ded85 < this is sample api key>

pls see my properties file. i have been using it and it gives me above written error.
pls help asap

**Comment by Sbrenthughes** [comment]
`bamboo.servers[1]=http://username:token@bamboo.company.com` from the documentation, you will need to pass in the apikey and username
