### ISSUE TITLE
Hygiea Jenkins plugin Pipeline code issue 

### ISSUE THREAD

**Issue by chaitu-papa** [capitalone/Hygieia#1938]
Hi Team,

 I am getting following error when trying to trigger  Jenkins pipeline build . We are using hygieia-jenkins-plugin 

The pipeline works fine through post build event configuration when using Jenkins job type: freestyle project .  

But it fails when using Jenkins job type : Pipeline 

This is piece of pipeline code I am trying to use .. Please suggest

Pipeline code snippet -
 stage('compile-unit-test') {
      // Run the gradle build
      if (isUnix()) {
        
         sh 'chmod +x gradlew'
         sh "./gradlew clean build"
         hygieiaBuildPublishStep([buildStatus: 'Success'])
      }   }
Error --- 
[Pipeline] hygieiaBuildPublishStep
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.NullPointerException
	at hygieia.utils.HygieiaUtils.getGitHubRepoBranch(HygieiaUtils.java:275)
	at hygieia.utils.HygieiaUtils.getRepoBranchFromScmObject(HygieiaUtils.java:258)
	at hygieia.utils.HygieiaUtils.getRepoBranch(HygieiaUtils.java:247)
	at hygieia.builder.BuildBuilder.createBuildRequestFromRun(BuildBuilder.java:78)
	at hygieia.builder.BuildBuilder.<init>(BuildBuilder.java:59)
	at jenkins.plugins.hygieia.workflow.HygieiaBuildPublishStep$HygieiaBuildPublishStepExecution.run(HygieiaBuildPublishStep.java:108)
	at jenkins.plugins.hygieia.workflow.HygieiaBuildPublishStep$HygieiaBuildPublishStepExecution.run(HygieiaBuildPublishStep.java:78)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE

**Comment by chaitu-papa** [comment]
Hi Team 
Request to help in this regard

**Comment by chaitu-papa** [comment]
Hello @nireeshT @tabladrum @satishc1 @nitin1706 @MarkRx @rob-miller-777 - Kindly help

**Comment by Sbrenthughes** [comment]
Try this:
` hygieiaBuildPublishStep buildStatus: 'Success'`

**Comment by chaitu-papa** [comment]
I am had found the problem and is with hygieiaDeployPublishStep step... it is not able find artifact in the workspace ... post fixing this issue ... I am able get application & environments details ...but it is showing failure even after deployment is successful..pls suggest

**Comment by rvema** [comment]
closing due to inactivity, please reopen is this is still happening.
