### ISSUE TITLE
Failed to obtain commits from bitbucket

### ISSUE THREAD

**Issue by nehatan** [capitalone/Hygieia#1946]
Hi, I am using below properties:
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
dbusername=dashboarduser
dbpassword=dbpassword
logging.file=./logs/bitbucket.log
git.cron=0 0/1 * * * *
git.host=https://xxxx@//bitbucket.org/
git.api=/rest/api/1.0/
git.commitThresholdDays=15
git.pageSize=25
git.product=server
bitbucket.key=XXXXXXXXXXXXXXXXXXXXXX
git.key=XXXXXXXXXXXXXXXXXXXXXX
logging.level.com.capitalone.dashboard=DEBUG
logging.level.com.capitalone.dashboard.collector=DEBUG

And getting the following error:
2018-01-18 11:51:00,021 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-01-18 11:51:00,160 DEBUG c.c.d.collector.GitCollectorTask - {password=G6/Bu3ZU+kLUEpcP9LeZjg==, scm=Bitbucket, branch=master, userID=xxxxxx, url=https://xxxxx@bitbucket.org/xxxxx/cou
n, lastUpdate=Thu Jan 18 11:49:00 EST 2018}::master
2018-01-18 11:51:00,237 DEBUG c.c.d.c.DefaultBitbucketServerClient - Rest Url: https://bitbucket.org/rest/api/1.0/projects/xxxxx/repos/coupon/commits?until=master&limit=25
2018-01-18 11:51:02,771 DEBUG c.c.d.c.DefaultBitbucketServerClient - GET https://bitbucket.org/rest/api/1.0/projects/xxxxx/repos/coupon/commits?until=master&limit=25
2018-01-18 11:51:03,906 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https://bitbucket.org/rest/api/1.0/projects/xxxxx/repos/coupon/commits?until=master&limit=25
org.springframework.web.client.HttpClientErrorException: 404 Not Found
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:230) ~[bitbucket-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:90) ~[bitbucket-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:148) [bitbucket-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
2018-01-18 11:51:03,916 INFO  c.c.d.collector.CollectorTask - Repo Count              1        3s
2018-01-18 11:51:03,917 INFO  c.c.d.collector.CollectorTask - New Commits             0        3s
2018-01-18 11:51:03,917 INFO  c.c.d.collector.CollectorTask - Finished                         3s

I tried with and without username/password while creating the widget.
I tried my repository as public/private

Also, I am not able to even access the link https://bitbucket.org/rest/api/1.0/projects/xxxx/repos/coupon/commits?until=master&limit=25 from browser.

I did went through some of the already opened similar tickets but could not find a solution. Any help would be appreciated

**Comment by pversteijnen** [comment]
@nehatan what do you use to run the collector? Do you use Docker images?

Is there a proxy being used in the company? Make sure this is setup. I also have a ticket open about the bitbucket collector not using the proxy settings. #1975

**Comment by nehatan** [comment]
Thanks for your response @pversteijnen 

No, I am not using docker and don't have a proxy too.
I changed the git.product to cloud and made required changes in the Repo URL, and its working good!
