### ISSUE TITLE
Bitbucket collector not using proxy settings

### ISSUE THREAD

**Issue by pversteijnen** [capitalone/Hygieia#1975]
Is it a correct assumption that the Bitbucket collector is not using the Proxy settings?

In my company environment I have to configure the proxy to connect to Bitbucket using the docker container.

When I create the same setup locally it works. But within the company network I keep getting a timeout. After viewing the code it seems that the proxy is never configured in the bitbucket collector.

```
  hygieia-bitbucket-scm-collector:
    environment:
    #mandatory
      - BITBUCKET_HOST=https://url/
      - BITBUCKET_API=/rest/api/1.0/
      - BITBUCKET_CRON=0 0/5 * * * *
      - BITBUCKET_PRODUCT=server
      - BITBUCKET_KEY=UVZObXlsaG56VUp6TXZaVUJmVWxwcE50
    #Maximum number of days to go back in time when fetching commits. Only applicable to Bitbucket Cloud.
    #  - BITBUCKET_COMMIT_THRESHOLD_DAYS=15
    #Page size for rest calls. Only applicable to Bitbucket Server.
      - BITBUCKET_PAGE_SIZE=10
      - MONGO_PORT=tcp:://mongodb:27017
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE=dashboard
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME=db
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD=dbpass
      - JAVA_OPTS='-Dhttp.proxyHost=http://proxy -Dhttp.proxyPort=<port> -Dhttps.proxyHost=http://proxy -Dhttps.proxyPort=<port>'
      - http_proxy=http://proxy:<port>
      - https_proxy=http://proxy:<port>
```
Error in the Docker logs: in line with this blog http://roufid.com/proxy-in-spring-resttemplate/
```
2018-01-31 07:40:00,083 INFO  c.c.d.collector.CollectorTask - Starting...
2018-01-31 07:40:00,083 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-01-31 07:41:28,969 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:406, serverValue:5067}] to mongodb:27017 because it is past its maximum allowed idle time.
2018-01-31 07:42:00,213 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https://git.essent.nl/rest/api/1.0/projects/feapp/repos/regelneef/commits?until=development&limit=10
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://git.essent.nl/rest/api/1.0/projects/feapp/repos/regelneef/commits?until=development&limit=10": Connect to git.essent.nl:443 [git.essent.nl/52.29.100.27, git.essent.nl/18.194.52.115] failed: connect timed out; nested exception is org.apache.http.conn.ConnectTimeoutException: Connect to git.essent.nl:443 [git.essent.nl/52.29.100.27, git.essent.nl/18.194.52.115] failed: connect timed out
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:230) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:90) ~[bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:148) [bitbucket-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to git.essent.nl:443 [git.essent.nl/52.29.100.27, git.essent.nl/18.194.52.115] failed: connect timed out
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:143) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        ... 15 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_151]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_151]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_151]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar!/:4.5.1]
        ... 28 common frames omitted
2018-01-31 07:42:00,230 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:407, serverValue:5069}] to mongodb:27017
2018-01-31 07:42:00,231 INFO  c.c.d.collector.CollectorTask - Repo Count              1      120s
2018-01-31 07:42:00,231 INFO  c.c.d.collector.CollectorTask - New Commits             0      120s
2018-01-31 07:42:00,231 INFO  c.c.d.collector.CollectorTask - Finished                       120s
2018-01-31 07:43:28,969 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:407, serverValue:5069}] to mongodb:27017 because it is past its maximum allowed idle time.
```

**Comment by pversteijnen** [comment]
For now the problem is fixed for me. I added a docker container that deals with all proxy traffic. So I configured the proxy in one place and now I do not have to worry about proxy issues on collector level

```
  # Proxy
  transparent-proxy:
    image: fengzhou/transparent-proxy
    privileged: true
    network_mode: "host"
    environment:
      #This is upstream proxy, should support "CONNECT" HTTP method (Usually it is http proxy for HTTPS).
      - HTTP_PROXY=<proxy>:<port>
      #This is optional value to by pass network address without go through upstream proxy.
      #- NO_PROXY=
      #This is optional value and it can be any open port. Default value is "3129".
      #- LISTEN_PORT=
      #This is optional value, and should be different with other mark value used in iptables. Default value is "5".
      #- IPTABLE_MASK=
      #This is optional value for ports that can be transparent to proxy. The default value is "80,443".
      - PROXY_PORTS=80,443,22
      #This is optional value to start DNS proxy to help advanced filter by DNS. Default value is "53". To disable it use "0".
      #- DNS_PORT=
      #This is optional value to use advanced proxy routing configuration file. Default value is disabled.
      #- PROXY_CONFIG_FILE=
```
