### ISSUE TITLE
Sonar Collector issue Property referenced in indexed property path 'metrics[0]' is neither an array nor a List nor a Map; returned value was []

### ISSUE THREAD

**Issue by harishgu** [capitalone/Hygieia#1976]
Hi,
When i try to invoke sonar collector i am getting below error message

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sonarSettings': Could not bind properties to [unkno
wn] (target=sonar, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.I
nvalidPropertyException: Invalid property 'metrics[0]' of bean class [com.capitalone.dashboard.collector.SonarSettings]: Property referenced in indexe
d property path 'metrics[0]' is neither an array nor a List nor a Map; returned value was []
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationProper
tiesBindingPostProcessor.java:303)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationProper
tiesBindingPostProcessor.java:250)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCa
pableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 23 more
Caused by: org.springframework.beans.InvalidPropertyException: Invalid property 'metrics[0]' of bean class [com.capitalone.dashboard.collector.SonarSe
ttings]: Property referenced in indexed property path 'metrics[0]' is neither an array nor a List nor a Map; returned value was []
        at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:1056)
        at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:927)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95)
        at org.springframework.validation.DataBinder.applyPropertyValues(DataBinder.java:750)
        at org.springframework.validation.DataBinder.doBind(DataBinder.java:646)
        at org.springframework.boot.bind.RelaxedDataBinder.doBind(RelaxedDataBinder.java:123)
        at org.springframework.validation.DataBinder.bind(DataBinder.java:631)
        at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:253)
        at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:227)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationProper
tiesBindingPostProcessor.java:296)
        ... 37 more
below are the my property file detilas

dbname=dashboard

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=

# Database Password - default is blank
dbpassword=

# Collector schedule (required)
sonar.cron=0 0/1 * * * *

# Sonar server(s) (required) - Can provide multiple
sonar.servers[0]=http://cdletimesonar.es.ad.adp.com:9000/

sonar.versions[0]=6.7

# Sonar Metrics - Required. 

sonar.metrics[0]=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details 

Could any one suggest what could be the issue.if i remove the [0] for sonar.metrics jvm is getting started but it is not fetching any data.

Thanks,

**Comment by nireeshT** [comment]
@harishgu - are you working on latest code base.

**Comment by Sbrenthughes** [comment]
@harishgu  Please rebase with master and try again. If the issue persist please reopen this issue.
