### ISSUE TITLE
Jira collector throws 401 on status call

### ISSUE THREAD

**Issue by pversteijnen** [capitalone/Hygieia#1999]
I have a similar issue as #1565 at the moment. We added a local user to Jira with a password without special characters. When I added this to the configuration it started working for the projects list. But when the status api is called I still get a 401. We made the user Admin. This resulted in more projects so that was prove it worked. But we still get the same error?

```
2018-02-08 08:40:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2018-02-08 08:40:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-08 08:40:00,009 INFO  c.c.d.collector.CollectorTask - https://jira.essent.nl/jira
2018-02-08 08:40:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-08 08:40:00,009 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2018-02-08 08:40:00,614 INFO  c.c.d.collector.CollectorTask - Project Data           92        0s
2018-02-08 08:40:00,735 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.IOException: Server returned HTTP response code: 401 for URL: https://jira.essent.nl/jira/rest/api/2/status/
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[na:1.8.0_151]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_151]
        at java.net.URLConnection.getContent(URLConnection.java:739) ~[na:1.8.0_151]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:443) ~[na:1.8.0_151]
        at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:442) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:750) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:154) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2018-02-08 08:40:00,942 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 2
2018-02-08 08:40:00,942 INFO  c.c.d.collector.CollectorTask - Story Data              2        0s
2018-02-08 08:40:00,942 INFO  c.c.d.collector.CollectorTask - Finished                         0s
``` 

Any thoughts on what can be done to get this working?
 Jira version 7.6.1 is used

**Comment by pversteijnen** [comment]
Using Postman I recreated the call to the status page. I saw a different base64 encoded string there. When I used this one it worked. Still not getting teams in. Not sure why this is failing. Will post a new issue when I cannot figure this out.
