### ISSUE TITLE
Doesn't work out of the box?

### ISSUE THREAD

**Issue by ianrossi** [capitalone/Hygieia#2013]
Hi there, this project seems promising, but I'm having a really difficult time getting it set up using the docker-compose method. I have encountered several typos and unexpected errors along the way.

Particularly, the username and password used to setup Mongo and then access it from the API and from the Jenkins build collector don't seem to match up. Is the master branch supposed to work out of the box? I looked at and followed the documentation multiple times. Any help is appreciated.

Just for a start, I'm trying to get Hygieia running with just Jenkins, but the Jenkins container keeps complaining about Mongo auth failing. It appears that Mongo installs and runs with no blank username and password by default. But the `config/hygieia-jenkins-build-collector.properties` file was using a password. I have confirmed Mongo isn't using a password by trying to log into the Mongo container with a username and password, and it's denied. In the above mentioned file, I have tried blank creds:
```
#Database Username - default is blank
dbusername=''

#Database Password - default is blank
dbpassword=''
```
and also just commented out the fields
```
#Database Username - default is blank
#dbusername=''

#Database Password - default is blank
#dbpassword=''
```
but to no avail.

If anyone can share a link to a "working" branch, it would be much appreciated.

**Comment by matthewbeasley** [comment]
@ianrossi - the username and password that is set up when creating the db can be found [here](https://github.com/capitalone/Hygieia/blob/master/db/db-setup.js), this is reflected in the docs. In order to run the jenkins collector, rename this [file](https://github.com/capitalone/Hygieia/blob/master/docker-compose.override.example.yml) to docker-compose.override.yml and add the environment vars for the collectors you want to run (jenkins-build for example). You can find the env vars available to you [here](https://github.com/capitalone/Hygieia/blob/master/collectors/build/jenkins/docker/jenkins-build-properties-builder.sh). Our docker setup is currently a work in progress and you can expect it to change in the near future.

**Comment by matthewbeasley** [comment]
@ianrossi - if this solves your problem to your satisfaction, please close this issue.

**Comment by ianrossi** [comment]
@matthewbeasley This doesn't solve my problem. For now, I have left the docker-compose setup behind and have built the JARs on a Virtualbox VM and am running each individual process. I now have Mongo running, the API, gulp serve (UI) and the Jenkins build collector (against a local Dockerized Jenkins with 2 jobs) running and all logs seem to be running with no errors.

However, I can't get anything to show up in the dashboard. I'm stuck on this:
![screen shot 2018-02-13 at 10 18 56 am](https://user-images.githubusercontent.com/103247/36157395-b0a6b3f8-10a7-11e8-9f91-aea2c086545a.png)

First, **what does the format `<Server Name> : <Job Name>` mean?** I don't see any info in the docs about this. The gentlemen that posted [this video](https://youtu.be/Iq8M3llEp0k?t=1239) (over a year ago) doesn't show any special format for the job names, it's just the Jenkins job names. 
The logs for the build collector show this:
```
2018-02-13 10:24:00,024 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 0/2 pageSize 1000...
2018-02-13 10:24:00,035 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2018-02-13 10:24:00,036 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2018-02-13 10:24:00,044 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2018-02-13 10:24:00,051 INFO  c.c.d.collector.CollectorTask - New configs             0        0s
2018-02-13 10:24:00,052 INFO  c.c.d.collector.CollectorTask - Finished                         0s
```
Previous reports like this showed when the `New jobs` were added. But what does this mean? The jobs should now be discoverable? Because they don't come up when I search in the above screenshot. 

I also keep on getting the [JWT error](https://github.com/capitalone/Hygieia/issues/1564) which makes things more difficult.

Can anyone point me a to a known working walkthrough of how to get Hygieia set up in its current state? I have implemented a whole lot of different open source project from Chef to Sensu to Kubernetes and I'm kind of surprised that a project like Hygieia with Cap One behind it does not have better documentation.

However, this is just an observation. Based what I've seen in screenshots, Hygieia looks to be a fantastic tools with lots to offer. Any help is very much appreciated.

**Comment by matthewbeasley** [comment]
@ianrossi - can you be more specific as to how what I said doesn't solve your problem? The ui, api and mongo should start up with just `docker-compose up -d`. If this isn't the case please let me know.

The JWT error is more than likely a cookie issue. If using chrome: go to [cookies](chrome://settings/siteData), search your cookies for localhost and delete that cookie. Should be good to go. This will happen when you go from the docker setup to running the jars AND your jwt has expired. If that doesn't solve your JWT issue then you need increase your jwt expiration time in your api settings. It's not clear to me exactly which issue you are experiencing but I'm confident that one of these two things will fix you up.

`<Server Name> : <Job Name>` corresponds to your jenkins server and the name of the job you are trying to track.

**Comment by matthewbeasley** [comment]
@ianrossi - also as far as the docs go -- hang tight. We are working to improve them. If you have specific suggestions then please air them out here as we'd love to hear your feedback.

**Comment by matthewbeasley** [comment]
@ianrossi - actually don't air them out here lol. If you have the time and have specific suggestions, open a new issue.

**Comment by ianrossi** [comment]
@matthewbeasley Thanks. I know how to solve the JWT issue, I was just sharing the observation because it makes things difficult.

About the server name, I still need more clarification.

> <Server Name> : <Job Name> corresponds to your jenkins server and the name of the job you are trying to track, respectively.

What does "jenkins server" mean? Is this the DNS name/address of the Jenkins server? If you can give an example, that would be great. Thanks.

**Comment by matthewbeasley** [comment]
@ianrossi - if you know how to solve the JWT issue then you shouldn't be seeing it. "jenkins server" does mean DNS name / address. If you are running jenkins locally in docker and exposing the appropriate port (8080 for instance) then Server name is `localhost:8080`. This should be available to you as a dropdown item though. Can you post your jenkins collector property file? It seems that you don't have that correctly configured.

**Comment by nireeshT** [comment]
@ianrossi  - You can assign nickname or nicename for jenkins instances so that when data is collected from multiple instances, you will know the jenkins instance - job relation. You can do it in 2 ways.
1)  You can set below values in jenkins.properties  (pull-based mechanism) 
jenkins.servers[0]=http://localhost:8080/
jenkins.niceNames[0]= give some nick name for 8080 - lets call it **ianrossi8080**
You can specify multiple server instances and nicenames with index.
2) If you have Hygieia jenkins plugin installed on your jenkins instance you will see Global Hygieia settings under - Jenkins -> Manage Jenkins -> configure system -> Global Hygieia Publisher Settings (Push-based mechanism)  
<img width="1264" alt="screen shot 2018-02-13 at 12 00 00 pm" src="https://user-images.githubusercontent.com/22962180/36163136-7580ebe0-10b6-11e8-87b5-c82a5f99cf80.png">

You can refer https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/hygieia-jenkins-plugin/hygieia-jenkins-plugin.md on how to build *.hpi file (Hygieia Jenkins Plugin) and install plugin to Jenkins instance. 

Pull based mechanism - When you start running Jenkins collector, jobs/build information is pulled to Hygieia and you should be able to search basing on 
1) job name only  ( here my job name is HygieiaPublic) 
<img width="541" alt="screen shot 2018-02-13 at 12 15 02 pm" src="https://user-images.githubusercontent.com/22962180/36163500-92585374-10b7-11e8-88f4-7f2829d35366.png">
 
2) nicename :  jobname ( Eg - nireesh : hyg) - it should match on partial search. We used ':' as a delimiter for nicename and job name. So if you want to search on both, make you include : in 
<img width="539" alt="screen shot 2018-02-13 at 12 17 02 pm" src="https://user-images.githubusercontent.com/22962180/36163693-24d031f4-10b8-11e8-805c-4ac14f7f095d.png">
between.

**Comment by ianrossi** [comment]
Hi @nireeshT CC @matthewbeasley 
Thanks for this info. Is the Jenkins / Hygieia plugin required for the Jenkins build collector to work? From your post, it almost looks like the "nice names" cannot be used without the plugin. I'm working on getting the plugin working with my local Jenkins.

**Comment by nireeshT** [comment]
@ianrossi you can either use Jenkins build collector or hygieia plugin. Just a matter of how you want to collect data.

**Comment by matthewbeasley** [comment]
@ianrossi - Tomorrow we will close this issue due to inactivity. Is everything good for you?

**Comment by ianrossi** [comment]
@matthewbeasley I'm all set. Thx.

**Comment by ianrossi** [comment]
@matthewbeasley @nireeshT There is still a problem with the Jenkins build collector. I'm seeing this error:
```
2018-02-23 13:44:44,308 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: https://build.as-crdbi-dev.com 584s
2018-02-23 13:45:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2018-02-23 13:45:00,270 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-23 13:45:00,270 INFO  c.c.d.collector.CollectorTask - https://build.as-crdbi-dev.com
2018-02-23 13:45:00,270 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-23 13:45:08,609 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 0/116 pageSize 500...
2018-02-23 13:54:52,578 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs details
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://build.as-crdbi-dev.com/api/json?tree=jobs[name,url,builds[number,url],lastSuccessfulBuild[timestamp,builtOn],lastBuild
[timestamp,builtOn],actions[jobConfigHistory[currentName,date,hasConfig,job,oldName,operation,user,userID]],jobs[name,url,builds[number,url],lastSuccessfulBuild[timestamp,builtOn],lastBuild[timestamp,builtOn],act
ions[jobConfigHistory[currentName,date,hasConfig,job,oldName,operation,user,userID]],jobs[name,url,builds[number,url],lastSuccessfulBuild[timestamp,builtOn],lastBuild[timestamp,builtOn],actions[jobConfigHistory[c
urrentName,date,hasConfig,job,oldName,operation,user,userID]],jobs[name,url,builds[number,url],lastSuccessfulBuild[timestamp,builtOn],lastBuild[timestamp,builtOn],actions[jobConfigHistory[currentName,date,hasConf
ig,job,oldName,operation,user,userID]],jobs[name,url,builds[number,url],lastSuccessfulBuild[timestamp,builtOn],lastBuild[timestamp,builtOn],actions[jobConfigHistory[currentName,date,hasConfig,job,oldName,operatio
n,user,userID]],jobs[name,url,builds[number,url],lastSuccessfulBuild[timestamp,builtOn],lastBuild[timestamp,builtOn],actions[jobConfigHistory[currentName,date,hasConfig,job,oldName,operation,user,userID]],jobs[na
me,url,builds[number,url],lastSuccessfulBuild[timestamp,builtOn],lastBuild[timestamp,builtOn],actions[jobConfigHistory[currentName,date,hasConfig,job,oldName,operation,user,userID]],jobs[name,url,builds[number,ur
l],lastSuccessfulBuild[timestamp,builtOn],lastBuild[timestamp,builtOn],actions[jobConfigHistory[currentName,date,hasConfig,job,oldName,operation,user,userID]],jobs[name,url,builds[number,url],lastSuccessfulBuild[
timestamp,builtOn],lastBuild[timestamp,builtOn],actions[jobConfigHistory[currentName,date,hasConfig,job,oldName,operation,user,userID]],jobs[name,url,builds[number,url],lastSuccessfulBuild[timestamp,builtOn],last
Build[timestamp,builtOn],actions[jobConfigHistory[currentName,date,hasConfig,job,oldName,operation,user,userID]]]]]]]]]]]]%7B0%2C500%7D": Premature EOF; nested exception is java.io.IOException: Premature EOF
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:650) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:126) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:101) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:39) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: java.io.IOException: Premature EOF
```
What does this mean? Does this mean that the collector was not able to load the entire request? Because I am able to put the request into a browser and it loads all of the data to the browser. So there is something on the Hygieia side that is a problem. Please help, thanks.

**Comment by ianrossi** [comment]
@matthewbeasley @nireeshT I'm also experiencing another issue with BItbucket. I'm getting this error and there is no actionable message in the server logs. But the JS console does show a 404 not found error. Can you help?
![screen shot 2018-02-23 at 9 52 04 am](https://user-images.githubusercontent.com/103247/36600062-3fd7b41c-187f-11e8-8f2e-ce7d99f70a4c.png)

**Comment by satishc1** [comment]
@ianrossi can you try setting ```jenkins.pageSize=10``` in your props and running the collector.

**Comment by satishc1** [comment]
@ianrossi for the "error encrypting password" refer to https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/setup.md#encryption-for-private-repos

**Comment by ianrossi** [comment]
@satishc1 In setting up the Bitbucket collector I had already generated the encrypted password with those instructions and I'm still getting that error message "Error encrypting password" in the UI.

Here is the properties file:
```
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=

# Database Password - default is blank
dbpassword=

# Logging File location
logging.file=./logs/bitbucket.log

# Collector schedule (required)
git.cron=0 0/5 * * * *

# Mandatory parameters
git.host=https://sourcecode.jnj.com/
git.api=/rest/api/1.0/

# Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

# Page size for rest calls
#   Only applicable to Bitbucket Server.
#   Only applicable to Bitbucket Cloud.
git.pageSize=25

# Bitbucket product
#   Set to 'cloud' to use Bitbucket Cloud (formerly known as Bitbucket)
#   Set to 'server' to use Bitbucket Server (formerly known as Stash)
#   More information can be found here: https://github.com/capitalone/Hygieia/issues/609
git.product=server

# Bitbucket key for private repos
bitbucket.key=redacted
```

**Comment by ianrossi** [comment]
@satishc1 Can you help me with the above question? I have already encrypted the password, but I continue to get the error in the screenshot you can see above.

**Comment by ianrossi** [comment]
@satishc1 @matthewbeasley I'm also trying to get the Sonar collector to work. It is acting very strangely. The first time I loaded it, I was able to see a dropdown list of Sonar projects in the search field of the settings window, but now none show up. When I manually enter the name of the project and save it, nothing happens in the UI, but I get the following error in the API log. Can you please help?
```
2018-02-28 14:44:12,620 ERROR c.c.d.rest.RestApiExceptionHandler - The given id must not be null!
java.lang.IllegalArgumentException: The given id must not be null!
        at org.springframework.util.Assert.notNull(Assert.java:115) ~[spring-core-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findOne(SimpleMongoRepository.java:118) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:475) ~[spring-data-commons-1.11.0.RELEASE.jar!/:
na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.sun.proxy.$Proxy94.findOne(Unknown Source) ~[na:na]
        at com.capitalone.dashboard.service.DashboardServiceImpl.associateCollectorToComponent(DashboardServiceImpl.java:255) ~[api.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.rest.DashboardController.addWidget(DashboardController.java:168) ~[api.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.rest.DashboardController$$FastClassBySpringCGLIB$$857f1c73.invoke(<generated>) ~[api.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:68) ~[spring-security-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.rest.DashboardController$$EnhancerBySpringCGLIB$$8ed61416.addWidget(<generated>) ~[api.jar!/:2.0.5-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
```

**Comment by satishc1** [comment]
@matthewbeasley can you setup a time with @ianrossi on gitter.im or google hangout and help with some of the issues. You can include me in the call if needed. Thanks.

**Comment by matthewbeasley** [comment]
@ianrossi - I will message you directly on gitter.im to coordinate a meeting.

**Comment by ianrossi** [comment]
@matthewbeasley Yes, I'm on gitter.im, thanks.

**Comment by matthewbeasley** [comment]
@ianrossi - can you reach out to me there in a one-to-one conversation when you get a chance? I'm available any time.

**Comment by ianrossi** [comment]
I searched for you but didn't find you. Perhaps you can reach out to me.
