### ISSUE TITLE
Jira collector is run with errors

### ISSUE THREAD

**Issue by magma7** [capitalone/Hygieia#2031]
Hi,
I've created Jira application properties with following data.
After API was running, I got errors. 
Could my user role permissions of Jira have caused this? 
Could you advice what's wrong?

Error:

2018-02-13 22:04:05,570 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 1
2018-02-13 22:04:05,573 INFO  c.c.d.collector.CollectorTask - Story Data              1        2s
2018-02-13 22:04:05,574 INFO  c.c.d.collector.CollectorTask - Finished                         5s
2018-02-13 22:05:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2018-02-13 22:05:00,060 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-13 22:05:00,070 INFO  c.c.d.collector.CollectorTask - http://jira/
2018-02-13 22:05:00,072 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-13 22:05:00,590 ERROR c.c.d.client.DefaultJiraClient - Parser exception when parsing teams
org.json.simple.parser.ParseException: null
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
	at com.capitalone.dashboard.client.DefaultJiraClient.getBoards(DefaultJiraClient.java:206) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:62) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2018-02-13 22:05:00,597 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2018-02-13 22:05:01,676 INFO  c.c.d.collector.CollectorTask - Project Data           39        1s
2018-02-13 22:05:01,937 ERROR c.c.d.client.DefaultJiraClient - Parser exception when parsing statuses
org.json.simple.parser.ParseException: null
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
	at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:453) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:750) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:154) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2018-02-13 22:05:03,069 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 1
2018-02-13 22:05:03,069 INFO  c.c.d.collector.CollectorTask - Story Data              1        1s
2018-02-13 22:05:03,070 INFO  c.c.d.collector.CollectorTask - Finished       

############################################################################

Application Properties:

    feature.pageSize=50
    dbname=dashboarddb
    dbhost=localhost
    dbport=27017
    dbusername=dashboarduser
    dbpassword=dbpassword
    logging.file=./logs/jira.log
    feature.deltaStartDate=2016-03-01T00:00:00.000000
    feature.masterStartDate=2016-03-01T00:00:00.000000
    feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000
    feature.cron=0 * * * * *
    feature.queryFolder=jiraapi-queries
    feature.storyQuery=story
    feature.epicQuery=epic
    feature.projectQuery=projectinfo
    feature.teamQuery=teaminfo
    feature.sprintQuery=sprintinfo
    feature.jiraBaseUrl=http://jira/
    feature.jiraQueryEndpoint=rest/api/2/
    feature.jiraCredentials=YW5uYW1hbHQ6UWFhbWRvY3MxNTE1MTUh

   # OAuth is not fully implemented; please blank-out the OAuth values:
   feature.jiraOauthAuthtoken=
   feature.jiraOauthRefreshtoken=
   feature.jiraOauthRedirecturi=
   feature.jiraOauthExpiretime=

############################################################################
 feature.jiraIssueTypeNames=Story
 feature.jiraSprintDataFieldName=customfield_10004
 feature.jiraEpicIdFieldName=customfield_10005
 feature.jiraStoryPointsFieldName=customfield_10002
 feature.jiraTeamFieldName=customfield_10112
 feature.jiraBoardAsTeam=true

**Comment by pversteijnen** [comment]
#2022 The config in this issue might help?

**Comment by magma7** [comment]
it didn't help :(

2018-02-21 19:05:00,003 INFO  c.c.d.collector.CollectorTask - http://jira/
2018-02-21 19:05:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-21 19:05:00,705 ERROR c.c.d.client.DefaultJiraClient - Parser exception when parsing teams
org.json.simple.parser.ParseException: null
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
        at com.capitalone.dashboard.client.DefaultJiraClient.getBoards(DefaultJiraClient.java:206) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:62) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
2018-02-21 19:05:00,705 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2018-02-21 19:05:01,323 INFO  c.c.d.collector.CollectorTask - Project Data          105        0s
2018-02-21 19:05:01,602 ERROR c.c.d.client.DefaultJiraClient - Parser exception when parsing statuses
org.json.simple.parser.ParseException: null
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
        at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:453) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:750) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:154) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
2018-02-21 19:05:02,280 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 1

**Comment by pversteijnen** [comment]
This is what I use setting up the Docker container.

```
  hygieia-jira-feature-collector:
    environment:
      - MONGO_PORT=tcp:://mongodb:27017
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE=dashboard
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME=db
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD=dbpass
        # you can override these by creating a docker-compose.overider.yml and put in entries like this:
        #REQUIRED Entries
      - JIRA_BASE_URL=**<your jira instance>**
        #64-bit encoded credentials with the pattern username:password
        #on a mac you can create them with : echo "username:password" | base64
        #reference:  https://www.base64decode.org/
      - JIRA_CREDENTIALS=**<your base64 encoded string>**

        #OPTIONAL - you may want to tweek these
      - JIRA_CRON=0 0/5 * * * *
        #Start dates from which to begin collector data, if no other data is present - usually, a month back is appropriate (required)
#      - JIRA_DELTA_START_DATE=2015-03-01T00:00:00.000000
#      - JIRA_MASTER_START_DATE=2008-01-01T00:00:00.000000

        #OPTIONAL Overrides if you need them
        #Page size for data calls (Jira maxes at 1000)
#      - JIRA_PAGE_SIZE=1000
        #Jira Connection Details
#      - JIRA_PROXY_URL=http://proxy.int.essent.rwe.com
#      - JIRA_PROXY_PORT=3128
        # Trending Query:  Number of days in a sprint (not-required)
#      - JIRA_SPRINT_DAYS=60
        # Trending Query:  Length of sprint week (not-required)
#      - JIRA_SPRINT_END_PRIOR=7
        #Scheduled Job prior minutes to recover data created during execution time (usually, 2 minutes is enough)
#      - JIRA_SCHEDULED_PRIOR_MIN=2
        #Delta change date that modulates the collector item task - should be about as far back as possible, in ISO format (required)
#      - JIRA_DELTA_COLLECTOR_ITEM_START_DATE=2008-01-01T00:00:00.000000
        #Jira Connection Details
      - JIRA_QUERY_ENDPOINT=rest/api/2/

        #OAuth2.0 token credentials (currently not supported in this version)
#      - JIRA_OAUTH_AUTH_TOKEN=sdfghjkl==
#      - JIRA_OAUTH_REFRESH_TOKEN=sdfagheh==
#      - JIRA_OAUTH_REDIRECT_URL=uri.this.is.test:uri
#      - JIRA_OAUTH_EXPIRE_TIME=234567890987

      - JIRA_ISSUE_TYPE_NAMES=Story
      - JIRA_SPRINT_DATA_FIELD_NAME=customfield_10007
      - JIRA_EPIC_FIELD_NAME=customfield_10003
      - JIRA_STORY_POINTS_FIELD_NAME=customfield_10004
      - JIRA_TEAM_FIELD_NAME=customfield_11248
      - JIRA_BOARD_AS_TEAM=true
```

**Comment by Sbrenthughes** [comment]
@magma7 did you get this resolved?

**Comment by Sbrenthughes** [comment]
Please reopen if this did not resolve the issue
