### ISSUE TITLE
Jenkins build collector Root Certificate challenge

### ISSUE THREAD

**Issue by pversteijnen** [capitalone/Hygieia#2032]
Keep getting a certifcate error when connecting to our Jenkins server. Jenkins is signed with an internal certificate so I try to add the root CA to the docker container to fix this issue but every solution I found online seems to be failing.

```
2018-02-15 08:50:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2018-02-15 08:50:00,010 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-15 08:50:00,011 INFO  c.c.d.collector.CollectorTask - https://ourjenkinsserver.com
2018-02-15 08:50:00,011 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-15 08:50:00,032 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://ourjenkinsserver.com/api/json?tree=jobs":sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:592) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:166) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:101) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_151]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959) ~[na:1.8.0_151]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[na:1.8.0_151]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_151]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514) ~[na:1.8.0_151]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[na:1.8.0_151]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026) ~[na:1.8.0_151]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:961) ~[na:1.8.0_151]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[na:1.8.0_151]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[na:1.8.0_151]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[na:1.8.0_151]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[na:1.8.0_151]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_151]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_151]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162) ~[na:1.8.0_151]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:81) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:569) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 17 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397) ~[na:1.8.0_151]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[na:1.8.0_151]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_151]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_151]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_151]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[na:1.8.0_151]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496) ~[na:1.8.0_151]
        ... 31 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[na:1.8.0_151]
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[na:1.8.0_151]
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_151]
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392) ~[na:1.8.0_151]
        ... 37 common frames omitted
2018-02-15 08:50:00,036 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: https://ourjenkinsserver.com 0s
```

I did this to try and get it working. After opening bash shell on the jenkins collector docker image:
```
cp /hygieia/logs/RootCertificate_RWE_base64.cer /docker-java-home/jre/lib/security/
cd /docker-java-home/jre/lib/security/
keytool -keystore jks-keystore -importcert -alias rootcarwe -trustcacerts -file RootCertificate_RWE_base64.cer -storepass changeit -noprompt
keytool -keystore cacerts -importcert -alias rootcarwe -trustcacerts -file RootCertificate_RWE_base64.cer -storepass changeit -noprompt
update-ca-certificates

cp /hygieia/logs/RootCertificate_RWE_base64.pem /etc/ssl/certs
cp /hygieia/logs/RootCertificate_RWE_base64.cer /etc/ssl/certs
cd /etc/ssl/certs
update-ca-certificates

cp /hygieia/logs/RootCertificate_RWE_base64.pem /etc/ca-certificates/update.d
cp /hygieia/logs/RootCertificate_RWE_base64.cer /etc/ca-certificates/update.d
cd /etc/ca-certificates/update.d
update-ca-certificates

cp /hygieia/logs/RootCertificate_RWE_base64.pem /usr/local/share/ca-certificates
cp /hygieia/logs/RootCertificate_RWE_base64.cer /usr/local/share/ca-certificates
cd /usr/local/share/ca-certificates
update-ca-certificates
```

If I look at the error it is a Java Keystore issue. But the collector is not using the CA certificate somehow? Any help on this would be great.

**Comment by satishc1** [comment]
@pversteijnen Interesting. Can you try this on a non-docker jenkins collector. Alternately, check the java home(s) in your docker setup. Perhaps the collector is using a different jdk / jre than the one you are importing the cert into.

**Comment by pversteijnen** [comment]
@satishc1 I have checked the Java_Home
```
root@2ba5ef71ef07:/hygieia# echo $JAVA_HOME
/docker-java-home/jre
```
Imported the certificate again:
```
root@2ba5ef71ef07:/docker-java-home/jre/lib/security# keytool -import -alias rootcarwe -trustcacerts -file /hygieia/RootCertificate_RWE_base64.cer -keystore jks-keystore -storepass changeit -noprompt
keytool error: java.lang.Exception: Certificate not imported, alias <rootcarwe> already exists
root@2ba5ef71ef07:/docker-java-home/jre/lib/security# keytool -import -alias rootcarwe -trustcacerts -file /hygieia/RootCertificate_RWE_base64.cer -keystore cacerts -storepass changeit -noprompt
keytool error: java.lang.Exception: Certificate not imported, alias <rootcarwe> already exists
```
No change and still the certificate error. Not not familier with Java and I have the Docker setup so starting the collector without Docker is a challenge. But looking back at all the issues I have getting Hygieia up and running is nog giving me much confidence for the future.

**Comment by pversteijnen** [comment]
Solved it by creating my own docker image based on the hygieia source code. Added the certificates to a folder in the source tree and copy them to the container using the Dockerfile

```
FROM docker.io/openjdk:8-jre

MAINTAINER Hygieia@capitalone.com

RUN mkdir /hygieia /hygieia/config

COPY *.jar /hygieia/
COPY jenkins-build-properties-builder.sh /hygieia/

COPY certificates/ /usr/local/share/ca-certificates/
RUN update-ca-certificates && \
    ls -1 /usr/local/share/ca-certificates | while read cert; do \
        openssl x509 -outform der -in /usr/local/share/ca-certificates/$cert -out $cert.der; \
        keytool -import -alias $cert -keystore $JAVA_HOME/lib/security/cacerts -trustcacerts -file $cert.der -storepass changeit -noprompt; \
        rm $cert.der; \
    done

WORKDIR /hygieia/
RUN chmod -R a+x /hygieia && \
    sed -i -e 's/\r$//' ./jenkins-build-properties-builder.sh

VOLUME ["/hygieia/logs"]

CMD ./jenkins-build-properties-builder.sh && \
  java -jar jenkins-build-collector*.jar --spring.config.location=/hygieia/config/hygieia-jenkins-build-collector.properties
```

Big difference is that the certificates are changed to a der format. I think did was what I missed.
