### ISSUE TITLE
 JWT signature does not match locally computed signature

### ISSUE THREAD

**Issue by magma7** [capitalone/Hygieia#2057]
Hello,
after I'm running api i'm getting this error:

maybe you can advice how i can clean api cache and cookies? which command do i need to use?
thanks

2018-02-27 13:45:50,843 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception
io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:342) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:458) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:518) ~[jjwt-0.6.0.jar!/:0.6.0]
        at com.capitalone.dashboard.auth.token.TokenAuthenticationServiceImpl.getAuthentication(TokenAuthenticationServiceImpl.java:59) ~[api.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.auth.token.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:37) ~[api.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.

**Comment by Sbrenthughes** [comment]
Can you post your properties file? If your properties file is correct then you can try cleaning your browser cache or opening the browser in incognito mode.

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/issues/1564, or https://github.com/capitalone/Hygieia/issues/1464

**Comment by fidelcoria-aa** [comment]
Clearing the cache or using incognito mode is not an acceptable solution. When I try to login tomorrow I will have the same problem. Would you ask people to clear their cache before logging into capitalone.com? 
@Sbrenthughes, I have not been setting any value for auth.secret. I am giving a value now. It's been working today, will check again tomorrow. Is that the missing piece? Only one of the issues mentions this property specifically?

**Comment by fidelcoria-aa** [comment]
Well, once we set `auth.secret` we are not seeing this problem anymore. Documentation implies this property is optional... should be updated I think.

**Comment by adhish70** [comment]
@fidelcoria-aa Can you help with what did you set as the auth.secret?

**Comment by fidelcoria-aa** [comment]
value does not matter. any alphanumeric string should work. I would avoid using special characters just in case.
Note: If you have multiple API instances make sure they all have the same auth.secret value.
