### ISSUE TITLE
UI Docker Build Fails

### ISSUE THREAD

**Issue by txappmkr** [capitalone/Hygieia#207]
UI Docker build fails on Ubuntu LTS.
Fails for "lstat html: no such file or directory"
```
INFO] Copying /home/swa/cap/hygieia/UI/docker/Dockerfile -> /home/swa/cap/hygieia/UI/target/docker/Dockerfile
[INFO] Copying /home/swa/cap/hygieia/UI/docker/default.conf -> /home/swa/cap/hygieia/UI/target/docker/default.conf
[INFO] Copying /home/swa/cap/hygieia/UI/docker/conf-builder.sh -> /home/swa/cap/hygieia/UI/target/docker/conf-builder.sh
[INFO] Building image hygieia-ui
[DEBUG] Auth Config null
[DEBUG] Registry Config Json {"configs":{"":{"serveraddress":"","password":"","auth":"","email":"","username":""}}}
[DEBUG] Registry Config Encoded 
Step 1 : FROM docker.io/nginx:latest
---> b4c1ea3cfac2
Step 2 : MAINTAINER Hygieia@capitalone.com
---> Using cache
---> f800e6948674
Step 3 : COPY default.conf /etc/nginx/conf.d/default.conf.templ
---> Using cache
---> 6b9b3bc9b1b5
Step 4 : COPY conf-builder.sh /usr/bin/conf-builder.sh
---> Using cache
---> 7722d5e18935
Step 5 : COPY html /usr/share/nginx/html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.044 s
[INFO] Finished at: 2015-12-10T19:58:50-06:00
[INFO] Final Memory: 24M/57M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.3:build (default-cli) on project UI: Exception caught: lstat html: no such file or directory -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.3.3:build (default-cli) on project UI: Exception caught
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
    at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:95)
    at com.spotify.docker.BuildMojo.execute(BuildMojo.java:79)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: com.spotify.docker.client.DockerException: lstat html: no such file or directory
    at com.spotify.docker.client.AnsiProgressHandler.progress(AnsiProgressHandler.java:51)
    at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:840)
    at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:789)
    at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:517)
    at com.spotify.docker.BuildMojo.execute(BuildMojo.java:307)
    at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:93)
    ... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by mrpudn** [comment]
Old issue - please open a new one if the problem persists with the latest codebase
