### ISSUE TITLE
hygieia-github-scm-collector

### ISSUE THREAD

**Issue by 2804337402** [capitalone/Hygieia#2076]
![1521012430 1](https://user-images.githubusercontent.com/25359798/37388479-b7d2b3f6-279b-11e8-96f4-751bea062598.jpg)

2018-03-14 03:42:00,051 INFO  c.c.d.collector.GitHubCollectorTask - Starting collection: 1 of 1: https://github.com/capitalone/Hygieia/tree/master
2018-03-14 03:42:00,534 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/capitalone/Hygieia
org.springframework.web.client.HttpClientErrorException: 404 Not Found
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCallPost(DefaultGitHubClient.java:926) ~[github-graphql-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.getRateLimit(DefaultGitHubClient.java:835) ~[github-graphql-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitHubCollectorTask.isUnderRateLimit(GitHubCollectorTask.java:258) ~[github-graphql-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:166) ~[github-graphql-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2018-03-14 03:42:00,537 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2018-03-14 03:42:00,537 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2018-03-14 03:42:00,537 INFO  c.c.d.collector.CollectorTask - New Pulls               0        0s
2018-03-14 03:42:00,537 INFO  c.c.d.collector.CollectorTask - New Issues              0        0s
2018-03-14 03:42:00,537 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-03-14 03:43:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2018-03-14 03:43:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-03-14 03:43:00,006 INFO  c.c.d.collector.CollectorTask - Starting...
2018-03-14 03:43:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-03-14 03:43:00,066 INFO  c.c.d.collector.GitHubCollectorTask - Starting collection: 1 of 1: https://github.com/capitalone/Hygieia/tree/master
2018-03-14 03:43:00,067 INFO  c.c.d.collector.GitHubCollectorTask - {password=, scm=Github, branch=master, userID=, url=https://github.com/capitalone/Hygieia}::master:: errorThreshold exceeded

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/issues/1904 check here about how to create an encryption key.
