### ISSUE TITLE
Gitlab Repo Type doesn't appear in Configure Code Repo Widget dropdown

### ISSUE THREAD

**Issue by thadguidry** [capitalone/Hygieia#2078]
Using latest build from master.
I have correctly configured gitlab-scm-collector (but doesn't appear to be retrieving anything). Repo Count shows 0  0s  on the logs.

I also don't see Gitlab as a repo type in the dropdown for Code Repo widget ?
Any idea on how to further troubleshoot ?  Turn on advanced debug logs somewhere ?

I see the network response from the GET to
```
http://127.0.0.1:8088/api/collector/type/scm
```
showing
```
"name":"Gitlab","collectorType":"SCM","enabled":"true"
``` 
yet the dropdown only shows Github and Subversion.

**Comment by shantanub0** [comment]
Hi, Thad Guidry
did you find any solution?
I am also facing the same issue

**Comment by thadguidry** [comment]
@shantanub0 Nope, no solution.  We have dropped worrying about Hygieia for now until the gitlab-scm-collector can be given more love from the community.

**Comment by tabladrum** [comment]
@nireeshT please take a look.

**Comment by tabladrum** [comment]
@shantanub0 will checkout today or tomorrow.

**Comment by shantanub0** [comment]
Thanx @thadguidry @tabladrum for the quick response
In the dropdown list, I am not able to see any RepoType except bitbucket

**Comment by rvema** [comment]
@thadguidry @shantanub0 closing due to inactivity, please reopen is this is still happening.

**Comment by lyndomiao** [comment]
@thadguidry did you solve this issue?

**Comment by thadguidry** [comment]
No.  Gitlab has improved in many areas.  We have moved on to Gitlab Premium and incorporating Sensu, Prometheus, etc.  which offers all that Hygieia was trying to solve.

**Comment by lyndomiao** [comment]
@Sbrenthughes this is my docker-compose.yml
hygieia-api:
  image: docker.io/capitalone/hygieia-api:latest
  container_name: hygieia-api
  volumes:
  - ./hygieia-api/logs:/hygieia/logs
  - ./hygieia-api/conf:/hygieia/config
  environment:
    - jasypt.encryptor.password=hygieiasecret
    - SPRING_DATA_MONGODB_DATABASE=dashboarddb
    - SPRING_DATA_MONGODB_HOST=mongo
    - SPRING_DATA_MONGODB_PORT=27017
    - SPRING_DATA_MONGODB_USERNAME=dashboarduser
    - SPRING_DATA_MONGODB_PASSWORD=dbpassword
    - FEATURE_DYNAMIC_PIPELINE=enabled
    - AUTH_EXPIRATION_TIME=3600000
    - AUTH_SECRET=hygieiasecret
    - SKIP_PROPERTIES_BUILDER=false
  links:
  - mongodb:mongo
  ports:
  - "9090:8080"
hygieia-ui:
  image: docker.io/capitalone/hygieia-ui:latest
  container_name: hygieia-ui
  ports:
  - "8900:80"
  links:
  - hygieia-api:hygieia-api
  environment:
  - jasypt.encryptor.password=hygieiasecret
  - API_HOST=hygieia-api
  - API_PORT=8080
  - AUTH_EXPIRATION_TIME=3600000
  - AUTH_SECRET=hygieiasecret
 
hygieia-gitlab-scm-collector:
  image: hygieia-gitlab-scm-collector:latest
  container_name: hygieia-gitlab
  volumes:
  - ./hygieia-gitlab-scm-collector/logs:/hygieia/logs
  - ./hygieia-gitlab-scm-collector/conf:/hygieia/config
  links:
  - mongodb:mongodb
  - hygieia-api
  environment:
  - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE=dashboarddb
  - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME=dashboarduser
  - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD=dbpassword
  - MONGODB_HOST=mongodb
  - MONGODB_PORT=27017
  - GITLAB_HOST=10.140.8.53
  - GITLAB_PROTOCOL=http
  - GITLAB_PORT=80
  - GITLAB_CRON=0 */15 * * * *
  - GITLAB_API_TOKEN=_enNsNR9FBhzaz9QX77N
  - GITLAB_COMMIT_THRESHOLD_DAYS=20
  - SKIP_PROPERTIES_BUILDER=false

**Comment by lyndomiao** [comment]
@Sbrenthughes this is my docker-compose.yml
hygieia-api:
image: docker.io/capitalone/hygieia-api:latest
container_name: hygieia-api
volumes:

./hygieia-api/logs:/hygieia/logs
./hygieia-api/conf:/hygieia/config
environment:
jasypt.encryptor.password=hygieiasecret
SPRING_DATA_MONGODB_DATABASE=dashboarddb
SPRING_DATA_MONGODB_HOST=mongo
SPRING_DATA_MONGODB_PORT=27017
SPRING_DATA_MONGODB_USERNAME=dashboarduser
SPRING_DATA_MONGODB_PASSWORD=dbpassword
FEATURE_DYNAMIC_PIPELINE=enabled
AUTH_EXPIRATION_TIME=3600000
AUTH_SECRET=hygieiasecret
SKIP_PROPERTIES_BUILDER=false
links:
mongodb:mongo
ports:
"9090:8080"
hygieia-ui:
image: docker.io/capitalone/hygieia-ui:latest
container_name: hygieia-ui
ports:
"8900:80"
links:
hygieia-api:hygieia-api
environment:
jasypt.encryptor.password=hygieiasecret
API_HOST=hygieia-api
API_PORT=8080
AUTH_EXPIRATION_TIME=3600000
AUTH_SECRET=hygieiasecret
hygieia-gitlab-scm-collector:
image: hygieia-gitlab-scm-collector:latest
container_name: hygieia-gitlab
volumes:

./hygieia-gitlab-scm-collector/logs:/hygieia/logs
./hygieia-gitlab-scm-collector/conf:/hygieia/config
links:
mongodb:mongodb
hygieia-api
environment:
HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE=dashboarddb
HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME=dashboarduser
HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD=dbpassword
MONGODB_HOST=mongodb
MONGODB_PORT=27017
GITLAB_HOST=xxxx
GITLAB_PROTOCOL=http
GITLAB_PORT=80
GITLAB_CRON=0 */15 * * * *
GITLAB_API_TOKEN=xxxxx
GITLAB_COMMIT_THRESHOLD_DAYS=20
SKIP_PROPERTIES_BUILDER=false

**Comment by Sbrenthughes** [comment]
When running the API can you go to http://localhost:8080/api/collector/type/scm and let me know the response?

**Comment by rishi-mukherjee** [comment]
I am seeing empty array []
log showing 
2019-02-06 11:50:00,011 INFO  c.c.d.collector.CollectorTask - Starting...
2019-02-06 11:50:00,011 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-06 11:50:00,016 INFO  c.c.d.collector.CollectorTask - Issues Added/Updated    0        0s
2019-02-06 11:50:00,016 INFO  c.c.d.collector.CollectorTask - Issues Deleted          0        0s

**Comment by krishna59** [comment]
Hi, am unable to deploy the SCM-gitlab. I have done with all the steps required to bring up the Hygieia dashboard. 

Command used to delpoy :  **java -jar gitlab-scm-collector-3.0.1.jar --spring.config.name=scm --spring.config.location=C:\Hygieia\Hygieia-master\collectors\scm\gitlab\application.properties**

Output I receive:    

ERROR o.s.boot.SpringApplication-Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitlabGitCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at com.capitalone.dashboard.Application.main(Application.java:16) [gitlab-scm-collector-3.0.1.jar!/:3.0.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [gitlab-scm-collector-3.0.1.jar!/:3.0.1]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.NullPointerException: null
        at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73) ~[core-3.0.4.jar!/:3.0.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        ... 23 common frames omitted
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitlabGitCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101)
        at com.capitalone.dashboard.Application.main(Application.java:16)
        ... 6 more
Caused by: java.lang.NullPointerException
        at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265)
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95)
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82)
        at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44)
        at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
        ... 23 more.

Can anyone please help me with this?

**Comment by arunmk108** [comment]
> Using latest build from master.
> I have correctly configured gitlab-scm-collector (but doesn't appear to be retrieving anything). Repo Count shows 0 0s on the logs.
> 
> I also don't see Gitlab as a repo type in the dropdown for Code Repo widget ?
> Any idea on how to further troubleshoot ? Turn on advanced debug logs somewhere ?
> 
> I see the network response from the GET to
> 
> ```
> http://127.0.0.1:8088/api/collector/type/scm
> ```
> showing
> 
> ```
> "name":"Gitlab","collectorType":"SCM","enabled":"true"
> ```
> yet the dropdown only shows Github and Subversion.

Hi Thadguidry, 
Did you find any solution? 
I am also facing the same issue for gitlab in code repo widget(only listing github not gitlab in dropdown) when i created dashboard with docker-compose file.
