### ISSUE TITLE
Which version of Jira have been tested>

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#209]
We are trying to integrate Jira and are running into lot of issues... in collector runtime... we are using 6.x

**Comment by softwareklinic** [comment]
ERROR c.c.d.d.j.s.c.GetResponseBuilderImpl - There was a problem connecting to Jira with a given query:
null
java.lang.NullPointerException: null
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191) ~[google-http-client-1.14.1-beta.jar!/:1.14.1-beta]
	at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:127) ~[google-http-client-1.14.1-beta.jar!/:1.14.1-beta]
	at com.google.api.client.http.GenericUrl.buildAuthority(GenericUrl.java:322) ~[google-http-client-1.14.1-beta.jar!/:1.14.1-beta]
	at com.google.api.client.http.GenericUrl.build(GenericUrl.java:303) ~[google-http-client-1.14.1-beta.jar!/:1.14.1-beta]
	at com.google.api.client.http.GenericUrl.toString(GenericUrl.java:178) ~[google-http-client-1.14.1-beta.jar!/:1.14.1-beta]
	at java.lang.String.valueOf(String.java:2847) ~[na:1.7.0_65]
	at java.lang.StringBuilder.append(StringBuilder.java:128) ~[na:1.7.0_65]
	at com.capitalone.dashboard.datafactory.jira.sdk.connector.GetResponseBuilderImpl.getResponseArray(GetResponseBuilderImpl.java:101) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.datafactory.jira.JiraDataFactoryImpl.getArrayQueryResponse(JiraDataFactoryImpl.java:213) [jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.client.team.TeamDataClientSetupImpl.updateObjectInformation(TeamDataClientSetupImpl.java:89) [jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:116) [jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:97) [jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:24) [jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]

**Comment by softwareklinic** [comment]
Never mind - we fixed this issue, but now we are seeing some issue while querying Mongo db... and its breaking there.. not providing data to dashboard for Jira... will ping the error message tomorrow.. good enough for today...

**Comment by tabladrum** [comment]
What was the fix?

**Comment by softwareklinic** [comment]
We forgot to add / at the end of the jira instance URL



Regards,
Keyur

On Dec 11, 2015, at 7:54 AM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


What was the fix?

**Comment by amitmawkin** [comment]
:)

**Comment by softwareklinic** [comment]
Probably code should take care of trailing / if missing



Regards,
Keyur

On Dec 11, 2015, at 8:13 AM, Amit Mawkin <notifications@github.com<mailto:notifications@github.com>> wrote:


:)

**Comment by amitmawkin** [comment]
Can you open a new issue with specific request, I will mark it as a bug and get our documentation updated as well get a developer to fix it

**Comment by amitmawkin** [comment]
I will close this issue

**Comment by softwareklinic** [comment]
Yes



Regards,
Keyur

On Dec 11, 2015, at 8:18 AM, Amit Mawkin <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you open a new issue with specific request, I will mark it as a bug and get our documentation updated as well get a developer to fix it
