### ISSUE TITLE
issue with aws collector - connection refused all the time for http request

### ISSUE THREAD

**Issue by harisvu9** [capitalone/Hygieia#2139]
```I have followed the steps provided in the following document```

```https://github.com/capitalone/Hygieia/issues/1852```

```ERROR MESSAGE```
```2018-04-12 01:51:03,897 INFO  com.capitalone.dashboard.Application - Started Application in 6.128 seconds (JVM running for 6.94)
2018-04-12 01:52:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: AWSCloud
2018-04-12 01:52:00,007 INFO  c.c.d.collector.CollectorTask - Starting AWS collection...
2018-04-12 01:52:00,007 INFO  c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...
2018-04-12 01:52:00,135 INFO  com.amazonaws.http.AmazonHttpClient - Unable to execute HTTP request: Connection refused (Connection refused)
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_161]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_161]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_161]
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:822) [aws-java-sdk-core-1.10.46.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576) [aws-java-sdk-core-1.10.46.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362) [aws-java-sdk-core-1.10.46.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328) [aws-java-sdk-core-1.10.46.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307) [aws-java-sdk-core-1.10.46.jar!/:na]
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:12792) [aws-java-sdk-ec2-1.10.46.jar!/:na]
	at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:8865) [aws-java-sdk-ec2-1.10.46.jar!/:na]
	at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:12330) [aws-java-sdk-ec2-1.10.46.jar!/:na]
	at com.capitalone.dashboard.collector.DefaultAWSCloudClient.getCloudInstances(DefaultAWSCloudClient.java:95) [aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.AWSCloudCollectorTask.collectInstances(AWSCloudCollectorTask.java:137) [aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.AWSCloudCollectorTask.collect(AWSCloudCollectorTask.java:122) [aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.AWSCloudCollectorTask.collect(AWSCloudCollectorTask.java:51) [aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```

**Comment by nireeshT** [comment]
@harisvu9  check this out - https://github.com/capitalone/Hygieia/issues/649

**Comment by harisvu9** [comment]
I have come across this. I have set up IAM role for my Hygieia running on EC2.Now the issue is collector is not able to hit aws http api.Connection refused error.

**Comment by nireeshT** [comment]
@harisvu9  I have to check that ..will hit back soon

**Comment by rvema** [comment]
closing due to inactivity, please reopen is this is still happening.
