### ISSUE TITLE
Jira collector - Parser exception when parsing teams -- Tried everything :-(

### ISSUE THREAD

**Issue by email2niranjan** [capitalone/Hygieia#2146]
[debugcustometeam.log](https://github.com/capitalone/Hygieia/files/1915793/debugcustometeam.log)
Hi,

I am getting the error "Parser exception when parsing teams".
I am not sure where the problem is. But I went through all the already reported issues in forums and was able to do some steps to debug. 

    Below are the some additional details;
-- **LOOKS GOOD:** **CONNECTION** with JIRA **working OK**. No issues with my authentication. I verified.
-- **LOOKS GOOD:** I added the below DEBUG properties and **AM ABLE TO SEE** all my JIRA stories and their details are coming up **in the output file** that I directed the output to. 
        logging.level.com.capitalone.dashboard=DEBUG
        logging.level.com.capitalone.dashboard.collector=DEBUG
        logging.level.com.atlassian.jira=INFO
-- **LOOKS GOOD:** I verified the **custom field ID numbers** by doing a export as xml and my team names, story points, Sprint data field custom names **are proper/correct**.
-- **BUT STILL NOT WORKING:** But for some reason, **collector is not able to parse** any of those details!
-- I tried all possible combinations below  
        team data field name = blank and Boardasteam=true
        team data field name = blank and Boardasteam=false
        team data field name = proper custom field value and Boardasteam=true
        team data field name = proper custom field value and Boardasteam=false
        (for the sake of trying... :-) , tried the below as well)
        team data field name = proper custom field value and Boardasteam=(blank)
        team data field name = blank and Boardasteam=(blank)

Please help fix this problem.

2018-04-14 10:39:20,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2018-04-14 10:39:20,024 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-04-14 10:39:20,025 INFO  c.c.d.collector.CollectorTask - https://adlm.dummy.com/jira/projects/XXXP/
2018-04-14 10:39:20,026 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-04-14 10:39:20,028 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2018-04-14 10:39:20,036 DEBUG c.c.d.client.DefaultJiraClient - startAt 0
2018-04-14 10:39:25,219 ERROR c.c.d.client.DefaultJiraClient - Parser exception when parsing teams
org.json.simple.parser.ParseException: null
	at org.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
	at com.capitalone.dashboard.client.DefaultJiraClient.getBoards(DefaultJiraClient.java:206) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:62) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_161]
2018-04-14 10:39:25,234 INFO  c.c.d.collector.CollectorTask - Team Data               0        5s
2018-04-14 10:39:25,235 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2018-04-14 10:39:28,910 ERROR c.c.d.client.DefaultJiraClient - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.absent(), errorCollections=[]}
2018-04-14 10:39:28,912 DEBUG c.c.d.client.DefaultJiraClient - Exception
com.atlassian.jira.rest.client.api.RestClientException: org.codehaus.jettison.json.JSONException: A JSONArray text must start with '[' at character 2 of 
<!DOCTYPE html>
<html lang="en">
<head>

**Comment by email2niranjan** [comment]
any help would be much appreciated :-)

**Comment by nireeshT** [comment]
@email2niranjan  refer https://github.com/capitalone/Hygieia/issues/2142 . Use jira props which I uploaded there

**Comment by email2niranjan** [comment]
I just tried...But same result :-(

**props i changed:**
feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10007
feature.jiraEpicIdFieldName=customfield_10003
feature.jiraStoryPointsFieldName=customfield_10004
feature.jiraTeamFieldName=customfield_11248
feature.jiraBoardAsTeam=true

**Result:**

2018-04-16 11:37:25,382 ERROR c.c.d.client.DefaultJiraClient - **Parser exception when parsing teams
org.json.simple.parser.ParseException: null**
	at org.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
	at com.capitalone.dashboard.client.DefaultJiraClient.getBoards(DefaultJiraClient.java:206) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:62) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_161]
2018-04-16 11:37:25,395 INFO  c.c.d.collector.CollectorTask - Team Data               0        5s
2018-04-16 11:37:25,397 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2018-04-16 11:37:30,135 ERROR c.c.d.client.DefaultJiraClient - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.absent(), errorCollections=[]}
2018-04-16 11:37:30,137 DEBUG c.c.d.client.DefaultJiraClient - Exception
com.atlassian.jira.rest.client.api.RestClientException: org.codehaus.jettison.json.JSONException: A JSONArray text must start with '[' at character 2 of

**Comment by email2niranjan** [comment]
to add...
i also tried increasing/expanding the pagesize to a very high value,
with my original props  and your recommended jira props .. both resulted in same result .. 

what else can I try? Pls help

**Comment by email2niranjan** [comment]
I am starting to believe that the response that am getting back is probably not JSON, really.
And am suspecting if its due to the JIRA URL connection details. Below are the details am giving... 
Can I really give /projects/<PROEJCTID> as baseUrl?
(As mentioned before, am getting data in the logs but they start with some htm tags before the json response)

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
feature.jiraProxyUrl=
feature.jiraProxyPort=
feature.jiraBaseUrl=https://adlm.dummy.com/jira/projects/XXXXP/
feature.jiraQueryEndpoint=rest/api/2/

**Comment by email2niranjan** [comment]
Closing this as I resolved it by properly giving the base URL details

**Comment by prk-fad** [comment]
Can you please provide details on the base URL. I am still seeing this issue
