### ISSUE TITLE
user already exists : not allowing admin: Error while logging in

### ISSUE THREAD

**Issue by email2niranjan** [capitalone/Hygieia#2160]
First time am trying to signup **admin** user and it says user already exists (please see screenshot)
I tried multiple times, by even deleting the authentication document in mongoDB, then restarting the api.
I also tried setting the auth.expirationTime=6000000 like mentioned in other issues. Nothing helps!
Please help.
**additional info:** There is no document in **authentication** table to begin with, but the moment I hit **SIGNUP** button after entering admin details, it says user already exists and the record gets added. I am not able to login using the details i entered though! :-(

![image](https://user-images.githubusercontent.com/38367179/38955827-c28b3db0-4323-11e8-91d0-3c6107861ee0.png)

API properties file:

# api.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=
# This will be your root dn
server.contextPath=/api
server.port=8080
logRequest=false
logSplunkRequest=false
corsEnabled=false
corsWhitelist=
version.number=@application.version.number@

auth.expirationTime=6000000
auth.secret=
auth.authenticationProviders=

# LDAP Server URL, including port of your LDAP server
auth.ldapServerUrl=

# If using standard LDAP
# LDAP User Dn Pattern, where the username is replaced with '{0}'
auth.ldapUserDnPattern=

# If using ActiveDirectory
# This will be the domain part of your userPrincipalName
auth.adDomain=
auth.adRootDn=
# This will be your active directory URL (required for AD)
auth.adUrl=

monitor.proxy.host=
monitor.proxy.type=
monitor.proxy.port=8080
monitor.proxy.username=
monitor.proxy.password=

# This will be the page size for pagination on Hygieia landing page. If this property is not set, the default value is set to 10.
pageSize=10

# API token generated for basic authentication to secure APIs.
key=

# SSO properties with header values from UI layer
auth.userEid=
auth.userEmail=
auth.userFirstName=
auth.userLastName=
auth.userMiddelInitials=
auth.userDisplayName=

**Comment by email2niranjan** [comment]
Actually... when i try logging in using the details I gave (when it thre 'user already exists error'), am getting the below error in api logs.. but nothing happens in the login screen

2018-04-18 16:23:54,550 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.serv
ice() for servlet [dispatcherServlet] in context with path [/api] threw exceptio
n
java.lang.IllegalArgumentException: base64-encoded secret key cannot be null or
empty.
        at io.jsonwebtoken.lang.Assert.hasText(Assert.java:130) ~[jjwt-0.6.0.jar
!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.jav
a:104) ~[jjwt-0.6.0.jar!/:0.6.0]
        at com.capitalone.dashboard.auth.token.TokenAuthenticationServiceImpl.ad
dAuthentication(TokenAuthenticationServiceImpl.java:47) ~[api.jar!/:2.0.5-SNAPSH
OT]
        at com.capitalone.dashboard.auth.DefaultAuthenticationResponseService.ha
ndle(DefaultAuthenticationResponseService.java:73) ~[api.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.auth.AuthenticationResultHandler.onAuthentic
ationSuccess(AuthenticationResultHandler.java:22) ~[api.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.security.web.authentication.AbstractAuthenticatio
nProcessingFilter.successfulAuthentication(AbstractAuthenticationProcessingFilte
r.java:331) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.security.web.authentication.AbstractAuthenticatio
nProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:245) ~[sp
ring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.
0.3.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.d
oFilter(LogoutFilter.java:120) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.R
ELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.
0.3.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterIn
ternal(HeaderWriterFilter.java:64) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0
.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.
0.3.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFi
lter.doFilter(SecurityContextPersistenceFilter.java:91) ~[spring-security-web-4.
0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.
0.3.RELEASE]
        at org.springframework.security.web.context.request.async.WebAsyncManage
rIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53) ~[
spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.
0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(Fi
lterChainProxy.java:213) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE
]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChai
nProxy.java:176) ~[spring-security-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(D
elegatingFilterProxy.java:346) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(Delegat
ingFilterProxy.java:262) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterIntern
al(CharacterEncodingFilter.java:121) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELE
ASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:217) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:106) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:502) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:142) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:79) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:88) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:518) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp
11Processor.java:1091) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(
AbstractProtocol.java:673) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1500) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoin
t.java:1456) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:624) [na:1.8.0_151]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by email2niranjan** [comment]
solved it by giving auth.secret
