### ISSUE TITLE
Github collector unauthorized for public repos!

### ISSUE THREAD

**Issue by michaelreda** [capitalone/Hygieia#2172]
**I get this error for any repo!**

```
{password=, personalAccessToken=, branch=master, userID=, url=https://github.com/scottschiller/SoundManager2}::master:: get commits
2018-04-25 08:40:00,236 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/scottschiller/SoundManager2/commits?sha=master&since=2018-04-11T08:40Z
2018-04-25 08:40:00,259 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2018-04-25 08:40:01,180 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/scottschiller/SoundManager2
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:587) ~[github-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:97) ~[github-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:177) ~[github-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2018-04-25 08:40:01,200 INFO  c.c.d.collector.CollectorTask - Repo Count              4        1s
2018-04-25 08:40:01,201 INFO  c.c.d.collector.CollectorTask - New Commits             0        1s
2018-04-25 08:40:01,203 INFO  c.c.d.collector.CollectorTask - New Pulls               0        1s
2018-04-25 08:40:01,204 INFO  c.c.d.collector.CollectorTask - New Issues              0        1s
2018-04-25 08:40:01,205 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2018-04-25 08:41:03,238 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:7, serverValue:98}] to localhost:27017 because it is past its maximum allowed idle time.
```

**## and this is my github properties file:**

```

		# dashboard.properties
		# Database Name
		dbname=dashboard

		# Database HostName - default is localhost
		dbhost=10.0.0.0

		# Database Port - default is 27017
		dbport=27017

		# MongoDB replicaset
		dbreplicaset=true
		#dbhostport= [host1:port1,host2:port2,host3:port3]

		# Database Username - default is blank
		dbusername=dashboarduser

		# Database Password - default is blank
		dbpassword=dbpassword

		# Logging File location
		logging.file=./logs/github.log

		# Collector schedule (required)
		github.cron=0 0/5 *

		github.host=github.com

		# Maximum number of previous days from current date, when fetching commits
		github.commitThresholdDays=300

    # Optional: Error threshold count after which collector stops collecting for a collector item. Default is 2.
    github.errorThreshold=2

    # This is the key generated using the Encryption class in core
    #github.key=<your-generated-key>

    # Personal access token generated from github and used for making authentiated calls
    github.personalAccessToken=and here is my personal access token

```

**## and this is how i run the collector**

`java -jar github-scm-collector-2.0.5-SNAPSHOT.jar --spring.config.name=github --spring.config.location= full path/github.properties `

**Comment by michaelreda** [comment]
Already set that I got an error for every new repo whether it's a public one or private:

```

2018-04-26 07:41:00,181 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/michaelreda/botify-android-app/commits?sha=master&since=2018-04-12T07:41Z
2018-04-26 07:41:00,377 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message,
 encypted Message: <My personal access token>  key: <my generated key>    [This line i logged it for debugging ]
**Input length must be multiple of 8 when decrypting with padded cipher**
2018-04-26 07:41:01,934 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/michaelreda/botify-android-app
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
```

**Comment by michaelreda** [comment]
solved it by adding the following at line: 95 (before decrypting) at DefaultGithubClient.java file:

```
try{
        settings.setPersonalAccessToken(Encryption.encryptString(settings.getPersonalAccessToken(),settings.getKey()));
       }catch(Exception e){
           LOG.info(e.getMessage());
       }
```

**Comment by ssyzyg** [comment]
> solved it by adding the following at line: 95 (before decrypting) at DefaultGithubClient.java file:
> 
> ```
> try{
>         settings.setPersonalAccessToken(Encryption.encryptString(settings.getPersonalAccessToken(),settings.getKey()));
>        }catch(Exception e){
>            LOG.info(e.getMessage());
>        }
> ```

I  tried to edit several places in DefaultGithubClient.java and rebuild the jar. but still no lucky to resolve the problem.  Did you change anything else for this issue?

**Comment by ysnoussi** [comment]
@ssyzyg 
you can try this out simply put decryptedPersonalAccessToken = settings.getPersonalAccessToken()

@michaelreda you are encrypting the access_key then decrypting  again :)
