### ISSUE TITLE
MongoDB query error

### ISSUE THREAD

**Issue by vtaneeru** [capitalone/Hygieia#218]
When I'm running Jira collector, I'm getting below MonogoDB query error. I see same error in mongodb console when Jira widget from dashboard is trying to get data

org.springframework.data.mongodb.UncategorizedMongoDbException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue unknown top level operator: $query' on server localhost:27017; nested exception is com.mongodb.MongoQueryException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue unknown top level operator: $query' on server localhost:27017
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:101) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2013) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1896) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1707) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1690) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:602) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$Execution.readCollection(AbstractMongoQuery.java:170) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$CollectionExecution.execute(AbstractMongoQuery.java:193) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:104) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:454) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]

My MonogoDB verison is 3.0.6

Is there any version issue here?

**Comment by amp5208** [comment]
There is an issue here:  Thank you for bringing this to our attention.  I am currently working towards a fix with this issue, which actually affects both existing feature collectors.  So far, we have have determined that this issue arose when Java 1.8 was established as the runtime version for Hygieia, and we have a relatively clear path towards a fix.  Please stay tuned for a fix to be pushed in the next two weeks.

**Comment by vtaneeru** [comment]
@amp5208 did you get a chance to work on this issue. Can you please let us know if there is fix/update

**Comment by amp5208** [comment]
@vtaneeru , thank you for following-up.  I have submitted a pull request to have this issue fixed that is currently being evaluated and functionally tested.  Once validated fully, the pull request will be added to Master.  Here is that pull request:  https://github.com/capitalone/Hygieia/pull/253

**Comment by vtaneeru** [comment]
@amp5208 Thank you. Once it is merged, will get the latest and try it out.

**Comment by oshingc** [comment]
@amp5208  I have a question, is this issue solved?

**Comment by amp5208** [comment]
@oshingc , I apologize for the delay - we had several, minor post-implementation bugs that were found after the main fix was implemented that needed to be resolved.  The pull request will likely be ready to be merged with master by EOB today (EST)

**Comment by amp5208** [comment]
Fix is ready for this issue - pending merge of #253 pull request before closing this issue. Once merged, please pull from master and use any new property file settings noted in the Feature content read-me's.

**Comment by amp5208** [comment]
This issue has been fixed.  @tabladrum or @amitmawkin , Please feel free to close this issue.
