### ISSUE TITLE
GitLab SCM collector does not pickup dbhost

### ISSUE THREAD

**Issue by pversteijnen** [capitalone/Hygieia#2203]
Somehow the GitLab SCM collector does not pickup the mongodb settings anymore?
The properties file seems to be correct

Properties file:
```
#Database Name
dbname=dashboard

#Database HostName - default is localhost
dbhost=db

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=db

#Database Password - default is blank
dbpassword=dbpass

#Collector schedule (required)
gitlab.cron=0 0/1 * * * *

#Gitlab host (optional, defaults to "gitlab.com")
gitlab.host=gitlab.company.nl

#Gitlab protocol (optional, defaults to "http")
gitlab.protocol=https

#Gitlab port (optional, defaults to protocol default port)
gitlab.port=443

#Gitlab path (optional, defaults to no path)
gitlab.path=

#Gitlab API Token (required, access token can be retrieved through gitlab, collector will have the permissions of the user associated to the token)
gitlab.apiToken=XXXXXXXXXXXXXX

#Maximum number of days to go back in time when fetching commits
gitlab.commitThresholdDays=15

#Gitlab Instance using self signed certificate
gitlab.selfSignedCertificate=false

#Gitlab API Version (optional, defaults to current version of 4)
gitlab.apiVersion=4

```
In the logs I can see that the collector is trying to connect to localhost:27017 instead of using the dbhost setting from the properties file.
Log:
```
  _    ___     _______ _____ ______ _____                _____ _____ _______ _               ____         _____ ____  _      _      ______ _____ _______ ____  _____
 | |  | \ \   / / ____|_   _|  ____|_   _|   /\         / ____|_   _|__   __| |       /\    |  _ \       / ____/ __ \| |    | |    |  ____/ ____|__   __/ __ \|  __ \
 | |__| |\ \_/ / |  __  | | | |__    | |    /  \ ______| |  __  | |    | |  | |      /  \   | (_) |_____| |   | |  | | |    | |    | |__ | |       | | | |  | | |__) |
 |  __  | \   /| | |_ | | | |  __|   | |   / /\ \______| | |_ | | |    | |  | |     / /\ \  |  _ < _____| |   | |  | | |    | |    |  __|| |       | | | |  | |  _  /
 | |  | |  | | | |__| |_| |_| |____ _| |_ / ____ \     | |__| |_| |_   | |  | |__  / ____ \ | (_) |     | |___| |__| | |____| |____| |___| |____   | | | |__| | | \ \
 |_|  |_|  |_|  \_____|_____|______|_____/_/    \_\     \_____|_____|  |_|  |____|/_/    \_\|____/       \_____\____/|______|______|______\_____|  |_|  \____/|_|  \_\



2018-05-15 08:16:43,454 INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://localhost:8888
2018-05-15 08:16:43,799 WARN  o.s.c.c.c.ConfigServicePropertySourceLocator - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
2018-05-15 08:16:43,808 INFO  com.capitalone.dashboard.Application - No profiles are active
2018-05-15 08:16:43,851 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@699b639d: startup date [Tue May 15 08:16:43 UTC 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@8be1e70
2018-05-15 08:16:46,397 INFO  o.s.cloud.context.scope.GenericScope - BeanFactory id=e3a9cd83-8bc1-37e6-98b3-1670910e7db1
2018-05-15 08:16:46,409 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Post-processing PropertySource instances
2018-05-15 08:16:46,429 INFO  c.u.j.c.StringEncryptorConfiguration - String Encryptor custom Bean not found with name 'jasyptStringEncryptor'. Initializing String Encryptor based on properties with name 'jasyptStringEncryptor'
2018-05-15 08:16:46,444 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2018-05-15 08:16:46,452 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2018-05-15 08:16:46,452 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemEnvironment [org.springframework.core.env.SystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
2018-05-15 08:16:46,453 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource random [org.springframework.boot.context.config.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2018-05-15 08:16:46,453 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2018-05-15 08:16:46,453 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource defaultProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2018-05-15 08:16:46,466 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-05-15 08:16:46,536 INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$b734ec80] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-05-15 08:16:46,638 INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService  'taskScheduler'
2018-05-15 08:16:46,784 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2018-05-15 08:16:46,937 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2018-05-15 08:16:47,001 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2018-05-15 08:16:47,160 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@d4006cf7, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@56d99403, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@c721ef6, socketFactory=javax.net.DefaultSocketFactory@31349b93, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2018-05-15 08:16:47,190 INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_162]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_162]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_162]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_162]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_162]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_162]
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.0.2.jar!/:na]
        ... 3 common frames omitted

```

Any ideas on how to solve this?

**Comment by Sbrenthughes** [comment]
Can you try looking at https://github.com/capitalone/Hygieia/issues/2097 or https://github.com/capitalone/Hygieia/issues/489

**Comment by pversteijnen** [comment]
Yes this fixed my problem thank you.
I do find it stange that you want to get rid of the properties file. In light of Infrastructure as Code it is great to set these variables using a docker-compose file. All I need is a docker-compose file and then I can restart my entire Hygieia environment from scratch in a few seconds. Only thing I need is a decent database backup or cluster.
