### ISSUE TITLE
Authentication failed for mongodb

### ISSUE THREAD

**Issue by trinathtiru** [capitalone/Hygieia#2205]
Hello All,

I have installed hygieia & mongodb successfully in my ubuntu machine. 

After installing i am trying to connect the database and establish the connection between Hygiea api and database using below command:

 java -jar api.jar --spring.config.location=/usr/Hygieia/api/dashboard.properties -Djasypt.encryptor.password=hygieiasecret

After executing the above command. i am facing the below error.

com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboarddb', password=<hidden>, mechanismProperties={}}
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:61) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }
        at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SaslAuthenticator.sendSaslContinue(SaslAuthenticator.java:99) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:58) ~[mongo-java-driver-3.0.2.jar!/:na]
   
Can someone help me. how to rid out of this?

Regards
Seenu

**Comment by trinathtiru** [comment]
Hi @Sbrenthughes 

can you please help on this

**Comment by nireeshT** [comment]
@trinathtiru  share api prop file . Remove "-Djasypt.encryptor.password=hygieiasecret" from command and try

**Comment by trinathtiru** [comment]
Hi @nireeshT 
thanks for the information. the issue got resolved with the port number.
