### ISSUE TITLE
Jenkins collector giving error

### ISSUE THREAD

**Issue by sushmaharish** [capitalone/Hygieia#2233]
I tried multiple solutions mentioned in this portal . nothing is working for me. Please suggest how to fix this issue....

I tried 2 different URLS they are giving different errors 

1.

ontext.scope.refresh:name=refreshScope,type=RefreshScope]
2018-05-23 13:07:57,466 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=282f1c66,type=ConfigurationPropertiesRebinder]
2018-05-23 13:07:57,523 INFO  com.capitalone.dashboard.Application - Started Application in 6.559 seconds (JVM running for 7.561)
2018-05-23 13:08:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2018-05-23 13:08:00,056 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-23 13:08:00,057 INFO  c.c.d.collector.CollectorTask - https://wipro-codereviewserver-devops.bos.infocrossing.com/jenkins
2018-05-23 13:08:00,057 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-23 13:09:03,917 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://wipro-codereviewserver-devops.bos.infocrossing.com/jenkins/api/json?tree=jobs": Connection timed out (Connection timed out); nested exception is java.net.ConnectException: Connection timed out (Connection timed out)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:655) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]

2.  I tried IP address also like below 👎 
This time I am getting parser error - json parser

2018-05-23 13:12:37,378 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=282f1c66,type=ConfigurationPropertiesRebinder]
2018-05-23 13:12:37,433 INFO  com.capitalone.dashboard.Application - Started Application in 6.301 seconds (JVM running for 7.208)
2018-05-23 13:13:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2018-05-23 13:13:00,072 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-23 13:13:00,072 INFO  c.c.d.collector.CollectorTask - http://10.32.66.161/jenkins
2018-05-23 13:13:00,072 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-23 13:13:00,098 ERROR c.c.d.collector.DefaultHudsonClient - returned json:
2018-05-23 13:13:00,108 ERROR c.c.d.collector.DefaultHudsonClient - Parsing jobs on instance: http://10.32.66.161/jenkins
org.json.simple.parser.ParseException: null
        at org.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:204) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:113) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:127) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:42) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/issues/2226

**Comment by matthewbeasley** [comment]
@sushmaharish - please take a look at the referenced issue. If this does not solve you problem please say so.

**Comment by matthewbeasley** [comment]
@sushmaharish @Sbrenthughes - closing due to inactivity.
