### ISSUE TITLE
hygieia-appdynamics error

### ISSUE THREAD

**Issue by anayyadav** [capitalone/Hygieia#2237]
my application.prop file is 👍 

#Database Name
database=dashboarddb

#Database HostName - default is localhost
dbhost=localhost

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=

#Database Password - default is blank
dbpassword=

#Logging File
logging.file=./logs/appd-collector.log

#Collector schedule (required)
appdynamics.cron=1 * * * * *

#AppDynamics server (required)(controller server )
appdynamics.instanceUrls=http://ipaddress:8090

#AppDynamics Username (required)
appdynamics.username=admin

#AppDynamics Password (required)
appdynamics.password=admin

#AppDynamics Dashboard (required)
appdynamics.dashboardUrls=http://ipaddress:8090/controller/#/location=AD_HOME_OVERVIEW&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60#%2Flocation=AD_HOME_OVERVIEW&timeRange=last_5_minutes.BEFORE_NOW.-1.-1.5

and i'm getting an error which is: 

2018-05-24 16:09:01,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Appdynamics
2018-05-24 16:09:01,010 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-24 16:09:01,011 INFO  c.c.d.collector.CollectorTask - Instance 0: http://ipaddress:8090
2018-05-24 16:09:01,013 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-24 16:09:01,140 ERROR c.c.d.c.DefaultAppdynamicsClient - client exception loading applications
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.makeRestCall(DefaultAppdynamicsClient.java:418) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.getApplications(DefaultAppdynamicsClient.java:90) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:79) [appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:20) [appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_171]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_171]
2018-05-24 16:09:01,146 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.makeRestCall(DefaultAppdynamicsClient.java:418) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.getApplications(DefaultAppdynamicsClient.java:90) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:79) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:20) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_171]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_171]

**Comment by Sbrenthughes** [comment]
What command are you using to run the collector ?

**Comment by anayyadav** [comment]
my application.prop file is +1

#Database Name
database=dashboarddb

#Database HostName - default is localhost
dbhost=localhost

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=

#Database Password - default is blank
dbpassword=

#Logging File
logging.file=./logs/appd-collector.log

#Collector schedule (required)
appdynamics.cron=1 * * * * *

#AppDynamics server (required)(controller server )
appdynamics.instanceUrls=http://localhost:8090

#AppDynamics Username (required)
appdynamics.username=admin

#AppDynamics Password (required)
appdynamics.password=admin

#AppDynamics Dashboard (required)
appdynamics.dashboardUrls=http://localhost:8090/controller/#/location=AD_HOME_OVERVIEW&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60#%2Flocation=AD_HOME_OVERVIEW&timeRange=last_5_minutes.BEFORE_NOW.-1.-1.5

and i'm getting an error which is:

2018-05-24 16:09:01,001 INFO c.c.d.collector.CollectorTask - Running Collector: Appdynamics
2018-05-24 16:09:01,010 INFO c.c.d.collector.CollectorTask - -----------------------------------
2018-05-24 16:09:01,011 INFO c.c.d.collector.CollectorTask - Instance 0: http://localhost:8090
2018-05-24 16:09:01,013 INFO c.c.d.collector.CollectorTask - -----------------------------------
2018-05-24 16:09:01,140 ERROR c.c.d.c.DefaultAppdynamicsClient - client exception loading applications
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.makeRestCall(DefaultAppdynamicsClient.java:418) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.getApplications(DefaultAppdynamicsClient.java:90) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:79) [appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:20) [appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_171]
at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_171]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_171]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_171]
at java.lang.Thread.run(Unknown Source) [na:1.8.0_171]
2018-05-24 16:09:01,146 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.makeRestCall(DefaultAppdynamicsClient.java:418) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.getApplications(DefaultAppdynamicsClient.java:90) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:79) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:20) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_171]
at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_171]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_171]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_171]
at java.lang.Thread.run(Unknown Source) [na:1.8.0_171]

**Comment by anayyadav** [comment]
I resolved that error but now I cant see any data on my hygieia dashboard .

my collector logs are ::

2018-05-25 14:27:01,123 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-25 14:27:01,124 INFO  c.c.d.collector.CollectorTask - Instance 0: http://168.62.166.66:8090
2018-05-25 14:27:01,049 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2018-05-25 14:27:01,128 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-25 14:27:01,129 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@b103666e, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@311bffa4, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@5d44e1d2, socketFactory=javax.net.DefaultSocketFactory@36ba76b1, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2018-05-25 14:27:01,189 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:80}] to localhost:27017
2018-05-25 14:27:01,193 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 6, 3]}, minWireVersion=0, maxWireVersion=6, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=856300}
2018-05-25 14:27:02,053 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2018-05-25 14:27:02,106 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2018-05-25 14:27:02,139 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2018-05-25 14:27:02,143 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@b103666e, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@311bffa4, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@5d44e1d2, socketFactory=javax.net.DefaultSocketFactory@36ba76b1, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2018-05-25 14:27:02,728 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:81}] to localhost:27017
2018-05-25 14:27:02,813 INFO  c.c.d.collector.CollectorTask - Fetched applications   1         1s
2018-05-25 14:27:03,859 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 6, 3]}, minWireVersion=0, maxWireVersion=6, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=1641800}
2018-05-25 14:27:04,390 INFO  c.c.d.collector.CollectorTask - New appplications:      0        0s
2018-05-25 14:27:04,413 INFO  c.c.d.collector.CollectorTask - Updated                 0        0s
2018-05-25 14:27:04,414 INFO  c.c.d.collector.CollectorTask - Finished                         3s
2018-05-25 14:27:04,725 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2018-05-25 14:27:04,769 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2018-05-25 14:27:04,773 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'environmentManager' has been autodetected for JMX exposure
2018-05-25 14:27:04,787 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'refreshScope' has been autodetected for JMX exposure
2018-05-25 14:27:04,793 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2018-05-25 14:27:04,832 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2018-05-25 14:27:04,880 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=54d7b16d,type=ConfigurationPropertiesRebinder]
2018-05-25 14:27:04,981 INFO  com.capitalone.dashboard.Application - Started Application in 15.362 seconds (JVM running for 17.095)
2018-05-25 14:28:01,007 INFO  c.c.d.collector.CollectorTask - Running Collector: Appdynamics
2018-05-25 14:28:01,026 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-25 14:28:01,050 INFO  c.c.d.collector.CollectorTask - Instance 0: http://168.62.166.66:8090
2018-05-25 14:28:01,053 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-25 14:28:01,401 INFO  c.c.d.collector.CollectorTask - Fetched applications   1         0s
2018-05-25 14:28:01,490 INFO  c.c.d.collector.CollectorTask - New appplications:      0        0s
2018-05-25 14:28:01,502 INFO  c.c.d.collector.CollectorTask - Updated                 0        0s
2018-05-25 14:28:01,504 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-05-25 14:29:01,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Appdynamics


and the UI looks like this : 
![1](https://user-images.githubusercontent.com/22302511/40536275-37cbea80-6029-11e8-857b-a0f245ed29a4.PNG)

Help me to resolve this issue

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/issues/1745. Can you check this out?

**Comment by matthewbeasley** [comment]
@anayyadav - closing this to inactivity. If your issue persists, please respond to the above comment and reopen the issue.

**Comment by anayyadav** [comment]
Still getting this issue. Please help me to fix this issue.

**Comment by Rishikeshpal** [comment]
@anayyadav  how did u resolve 401 error at the first place? Does your appD is saml authenticated?
