### ISSUE TITLE
Hygieia Hygieia Publisher Plugin Build Issue

### ISSUE THREAD

**Issue by mprabhat** [capitalone/Hygieia#2261]
Unable to build Hygieia on my machine. It is throwing java.lang.ArrayIndexOutOfBoundsException: 15669

OS: Windows 10
JDK: 1.8.0_161"

Stacktrace: 

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  0.689 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 26.537 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 23.002 s]
[INFO] com.capitalone.dashboard:api-audit ................. SUCCESS [  8.726 s]
[INFO] com.capitalone.dashboard:rally-collector ........... SUCCESS [  3.819 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SUCCESS [  3.481 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SUCCESS [  3.637 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  5.495 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  3.422 s]
[INFO] com.capitalone.dashboard:jenkins-codequality ....... SUCCESS [  5.520 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  3.918 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SUCCESS [  1.267 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  3.403 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SUCCESS [  3.803 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [  7.408 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  3.220 s]
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SUCCESS [  4.906 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  1.092 s]
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SUCCESS [  2.923 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SUCCESS [  3.813 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  3.487 s]
[INFO] com.capitalone.dashboard:github-graphql-scm-collector SUCCESS [  4.154 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  1.215 s]
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SUCCESS [  4.064 s]
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SUCCESS [  4.326 s]
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SUCCESS [  2.924 s]
[INFO] com.capitalone.dashboard:score-collector ........... SUCCESS [  5.193 s]
[INFO] Hygieia Publisher Plugin ........................... FAILURE [  0.187 s]
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] com.capitalone.dashboard:ui-tests .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:27 min
[INFO] Finished at: 2018-06-04T12:09:09+08:00
[INFO] Final Memory: 151M/1528M
[INFO] ------------------------------------------------------------------------
[ERROR] 15669
java.lang.ArrayIndexOutOfBoundsException: 15669
        at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2502)
        at org.codehaus.plexus.util.xml.pull.MXParser.parseEpilog(MXParser.java:1604)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1434)
        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3856)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:109)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:82)
        at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:81)
        at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:535)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1097)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:829)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:331)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:321)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:199)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:544)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:528)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:418)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:513)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:467)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:513)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:467)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:263)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:325)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:169)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:246)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
```

**Comment by mprabhat** [comment]
Well, it seems it has nothing to do with Hygieia rather my local m2 repository. I cleaned my repo and then did another install and it worked.
