### ISSUE TITLE
Jenkins build collector 

### ISSUE THREAD

**Issue by 0-d** [capitalone/Hygieia#2271]
I have a following error running jenkins collector:
```java
2018-06-07 11:45:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2018-06-07 11:45:00,040 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:17481}] to 127.0.0.1:27017
2018-06-07 11:45:00,092 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:87) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:42) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:52) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_171]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_171]
```

My `jenkins.properties`:
```properties
[Database]
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017

[Jenkins]
jenkins.cron=0 0/5 * * * *
jenkins.pageSize=25
jenkins.folderDepth=5
jenkins.servers[0]=https://user:apikey@jenkins-host.org
```

5 days ago it was working fine. Today I discovered that my dashboard build widget updated 5 days ago and I cant collect data from jenkins anymore. I haven't changed properties, dashboard configs -- nothing. Haven't even touch the server where Hygieia runs. All other collectors (jira, bitbucket, sonarqube) works as expected.

Jenkins server version 2.107.3

**Comment by subodhbattina** [comment]
@0-d : 
Based on the log you shared, it is a NullPointerException: at HudsonCollectorTask.java:87

lang.NullPointerException: null
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:87) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]

Line # 87 is "hudsonSettings.getUsernames().clear();", it seems to be going into the "else" block.

Are you able to go into the debug mode on your IDE, or print some logs and make sure your servers are being set appropriately. Basically ensure "hudsonSettings.getServers()" is returning a non null value?

**Comment by 0-d** [comment]
@subodhbattina I am not a java programmer and does not have a java IDE (only VSCode). If you could explain me how to do it in VSCode I'll try.

**Comment by MAH6146** [comment]
I need some help, error at Jenkins Build Collector - 

```
Caused by: java.lang.NullPointerException: null
	at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT] 
```

jenkins.properties file looks like below:

```
# Database
dbname=dashboarddb
dbhost=localhost
dbport=20217
dbreplicaset=false
dbhostport=localhost:20217
dbusername=dashboarduser
dbpassword=<mypassword>

#Jenkins
jenkins.cron=0 0/5 * * * *
jenkins.pageSize=1000
jenkins.folderDepth=10
jenkins.servers[0]=http://mah6146:023efc5c8f1d87965aa49178680b387d@172.30.32.55:8080

```
http://localhost:8080/api/dashboard output looks like below
`[{"id":"5b1aa4f3c49d052e2ccdcd64","template":"capone","title":"Product Dashboard","widgets":[{"id":"5b1ab8aec49d052e2ccdcd69","name":"build","componentId":"5b1aa4f3c49d052e2ccdcd63","options":{"id":"build0","buildDurationThreshold":3,"consecutiveFailureThreshold":5}}],"owners":[{"username":"fldrewards","authType":"STANDARD"}],"type":"Team","application":{"name":"Lanister","components":[{"id":"5b1aa4f3c49d052e2ccdcd63","name":"Lanister","collectorItems":{}}]},"validServiceName":false,"validAppName":false,"remoteCreated":false,"scoreEnabled":true,"scoreDisplay":"HEADER","errorCode":0}]`

**Comment by 0-d** [comment]
For some reason it started to work again after I changed this:
```properties
jenkins.servers[0]=https://user:apikey@jenkins-host.org
```

to

```properties
jenkins.servers[0]=https://jenkins-host.org
jenkins.usernames[0]=user
jenkins.apiKeys[0]=apikey
```

**Comment by IkaroSales** [comment]
I make this alteration, but don't work

**Comment by MousomGITHub** [comment]
hey, i am in process of setting up the Hygieia dashboard and collectors.
i can get these working - 
however i am not able to see any thing on the dashboard from collectors...

http://10.39.159.118:8080/api/dashboard - returning empty - []
i can see in the jenkins collector logs (in debug mode) - the jobs names and etc, however i am not able to understand why these are not showing up in the dashboard.
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient -  buildNumber: 3
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient -  Adding Build: http://jenkins.ibr.extnp.national.com.au/job/wrapper_deploy_docker_st/3/
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient -  buildNumber: 2
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient -  Adding Build: http://jenkins.ibr.extnp.national.com.au/job/wrapper_deploy_docker_st/2/
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient -  buildNumber: 1
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient -  Adding Build: http://jenkins.ibr.extnp.national.com.au/job/wrapper_deploy_docker_st/1/
2018-10-15 17:15:03,509 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     3s
2018-10-15 17:15:03,552 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2018-10-15 17:15:03,555 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2018-10-15 17:15:03,558 INFO  c.c.d.collector.CollectorTask - New configs             0        0s
2018-10-15 17:15:03,558 INFO  c.c.d.collector.CollectorTask - Finished                         3s


Please note that i have not set up any ldap authentication, i am using standard authentication post sign up.

sonar collector issue:
018-10-15 17:15:00,252 WARN  o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: AWSALB=MLAAhi0tymi5qD+JZmgWXZCasXhU0diqdRDgHHcsA2/C38Kxm8EtbklCVXhk8dDrRSPjVrZJxoZDDGbj1nNK3DAC86FVaCWdKrXT1iTaEmDrjzkAJYe3psBQQstE; Expires=Mon, 22 Oct 2018 06:15:00 GMT; Path=/". Invalid 'expires' attribute: Mon, 22 Oct 2018 06:15:00 GMT
2018-10-15 17:15:00,252 ERROR c.c.d.collector.DefaultSonar6Client - org.springframework.web.client.HttpClientErrorException: 404
2018-10-15 17:15:00,252 INFO  c.c.d.collector.CollectorTask - Fetched projects   0             0s
2018-10-15 17:15:00,252 INFO  c.c.d.collector.CollectorTask - New projects            0        0s
2018-10-15 17:15:00,254 INFO  c.c.d.collector.CollectorTask - Updated                 0        0s

Dashboard - 
2018-10-15 16:30:35,878 ERROR c.c.d.rest.RestApiExceptionHandler - An Authentication object was not found in the SecurityContext

Really appreaciate if someone helps here.
