### ISSUE TITLE
Jenkins Build collector - error

### ISSUE THREAD

**Issue by MAH6146** [capitalone/Hygieia#2277]
Hi, my UI and api are up and running. But while running jenkins build collector, i am struggling with  MondoDB connection error. I have used the same db properties to run api but no error there.
```
2018-06-11 09:57:08,937 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hudsonCollectorTask': Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:20217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:20217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	...
Caused by: org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:20217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:20217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:75) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	... 23 common frames omitted
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:20217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:370) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:166) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:394) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:57) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.Mongo.execute(Mongo.java:738) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.Mongo$2.execute(Mongo.java:725) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.DBCollection.findOne(DBCollection.java:737) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.DBCollection.findOne(DBCollection.java:710) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.DBCollection.findOne(DBCollection.java:657) ~[mongo-java-driver-3.0.2.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:2080) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:2064) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:1839) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	... 45 common frames omitted
```
jenkins.properties look like below.
```
# Database
dbname=dashboarddb
dbhost=localhost
dbport=20217
dbreplicaset=false
dbhostport=localhost:20217
dbusername=dashboarduser
dbpassword=<mypassword>


# Jenkins server (required) - Can provide multiple
jenkins.servers[0]=https://fldrewards.jenkins.nml.com/
jenkins.usernames[0]=<myusername>
jenkins.apiKeys[0]=<myapikey>
jenkins.cron=0 0/5 * * * *
jenkins.pageSize=1000
jenkins.folderDepth=10
```

**Comment by nireeshT** [comment]
@MAH6146  share run command to start jenkins collector

**Comment by MAH6146** [comment]
used below command to run jenkins collector
`D:\Hygieia\collectors\build\jenkins\target>java -jar jenkins-build-collector-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins --spring.config.location=D:\Hygieia\collectors\build\jenkins\jenkins.properties`

Yes, mongodb is up and api is connected to mongo

**Comment by stangem** [comment]
Was this ever solved? I am having the same problem.
