### ISSUE TITLE
JIRA Collector NullPointerException

### ISSUE THREAD

**Issue by Prodesire** [capitalone/Hygieia#2291]
JIRA Version： 7.10.1
Hygieia Commit ID: 996ec6b93c924ebe43efc61345f2448798e9d1ad (very new)
Error:

> 2018-06-15 11:06:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2018-06-15 11:06:00,019 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-06-15 11:06:00,021 INFO  c.c.d.collector.CollectorTask - http://10.1.60.117:8080/
2018-06-15 11:06:00,021 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-06-15 11:06:00,023 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2018-06-15 11:06:00,038 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2018-06-15 11:06:00,040 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2018-06-15 11:06:00,302 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1
2018-06-15 11:06:00,336 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2018-06-15 11:06:00,339 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2018-06-15 11:06:00,405 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2018-06-15 11:06:00,491 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
        at com.capitalone.dashboard.util.FeatureWidgetQueries.getStoryQuery(FeatureWidgetQueries.java:111) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.DefaultJiraClient.getIssues(DefaultJiraClient.java:95) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:162) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]

Collector Properties (note: the value of feature.jiraIssueTypeName is chinese character):

> dbname=dashboarddb
dbhost=localhost
dbport=27017
dbusername=dashboarduser
dbpassword=dbpassword
logging.file=/opt/Hygieia/logs/jira.log
feature.pageSize=100
feature.deltaStartDate=2018-01-01T00:00:00.000000
feature.masterStartDate=2018-01-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2018-01-01T00:00:00.000000
feature.cron=0 0/1 * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.jiraBaseUrl=http://10.1.60.117:8080/
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=YWRtaW46MTIzNDU2
feature.jiraIssueTypeName=故事
feature.jiraSprintDataFieldName=customfield_10101
feature.jiraEpicIdFieldName=customfield_10102
feature.jiraStoryPointsFieldName=customfield_10106
feature.jiraTeamFieldName=
feature.jiraBoardAsTeam=false
logging.level.com.capitalone.dashboard=DEBUG
logging.level.com.capitalone.dashboard.collector=DEBUG
logging.level.com.atlassian.jira=DEBUG

Hope for your help! Thanks!

**Comment by Prodesire** [comment]
Well, after serval times trying, I solved the problem.

1. `feature.jiraIssueTypeName` should be `feature.jiraIssueTypeNames`. I missed `s`
2. The value of `feature.jiraIssueTypeNames` can't be `故事`, otherwise JIRA can't find this issue type. Actually, we should assign `Story` to `feature.jiraIssueTypeNames` what ever language you set in JIRA.

Now, when running `jira collector`, we could see these logs:

> 

> 2018-06-15 11:56:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2018-06-15 11:56:00,016 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-06-15 11:56:00,016 INFO  c.c.d.collector.CollectorTask - http://10.1.60.117:8080/
2018-06-15 11:56:00,016 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-06-15 11:56:00,016 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2018-06-15 11:56:00,016 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2018-06-15 11:56:00,016 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2018-06-15 11:56:00,057 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1
2018-06-15 11:56:00,062 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2018-06-15 11:56:00,062 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2018-06-15 11:56:00,096 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2018-06-15 11:56:00,179 DEBUG c.c.d.client.DefaultJiraClient - Processing issues 0 - 6 out of 6
2018-06-15 11:56:00,179 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 82 ms
2018-06-15 11:56:00,179 DEBUG c.c.d.c.story.StoryDataClientImpl - Size of paged Jira response: 6
2018-06-15 11:56:00,196 DEBUG c.c.d.c.story.StoryDataClientImpl - Processing epic data
2018-06-15 11:56:00,197 DEBUG c.c.d.c.story.StoryDataClientImpl - Processing epic data took 0 ms
2018-06-15 11:56:00,197 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 6
2018-06-15 11:56:00,197 INFO  c.c.d.collector.CollectorTask - Story Data              6        0s
2018-06-15 11:56:00,197 INFO  c.c.d.collector.CollectorTask - Finished                         0s

Unfortunately, the Feature Widget still shows no data. I am trying to figure it out.

**Comment by No6-start** [comment]
我遇到了和你一样的问题，这个问题是如何解决的呢？jiraIssueTypeNames这个值我设定了，但是可惜还是报错
