### ISSUE TITLE
VersionOne Collector MongoDB Query Issue

### ISSUE THREAD

**Issue by aniketvsawant** [capitalone/Hygieia#231]
When I'm running VersionOne collector, I'm getting below MonogoDB query error. I see the same error on mongodb console when VersionOne widget from dashboard is trying to get data

-----------------------------------------------------------------------------------------------------
org.springframework.data.mongodb.UncategorizedMongoDbException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue unknown top level operator: $query' on server localhost:27017; nest
        at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:101) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2013) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1896) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1707) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1690) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:602) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$Execution.readCollection(AbstractMongoQuery.java:170) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$CollectionExecution.execute(AbstractMongoQuery.java:193) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:104) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:454) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.sun.proxy.$Proxy38.getFeatureIdById(Unknown Source) ~[na:na]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.removeExistingEntity(StoryDataClientImpl.java:389) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateMongoInfo(StoryDataClientImpl.java:82) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.story.FeatureDataClientSetupImpl.updateObjectInformation(FeatureDataClientSetupImpl.java:82) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:374) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:115) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_66]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_66]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_66]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_66]
Caused by: com.mongodb.MongoQueryException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue unknown top level operator: $query' on server localhost:27017
        at com.mongodb.connection.ProtocolHelper.getQueryFailureException(ProtocolHelper.java:93) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.QueryProtocol.receiveMessage(QueryProtocol.java:288) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:229) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:38) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:155) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:219) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:166) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:397) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:394) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:195) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:394) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:57) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.Mongo.execute(Mongo.java:738) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.Mongo$2.execute(Mongo.java:725) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBCursor.initializeCursor(DBCursor.java:815) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBCursor.hasNext(DBCursor.java:149) ~[mongo-java-driver-3.0.2.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1882) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        ... 31 common frames omitted
2015-12-17 13:49:09,070 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Process took :7.949508804 seconds to update
2015-12-17 13:49:09,070 INFO  c.c.d.collector.FeatureCollectorTask - Feature Data Collection Finished
-------------------------------------------------------------------------------------------------------

**Comment by softwareklinic** [comment]
There are about 4 files where the Jira feature collector is using $query which it probably should not... and needs little tweaks in theJSON itself... but looks like those changes are not in master... Diane did put those changes in but didn't make it to master as far as we see... 

so, I'm assuming similar would be the case with VersionOne as well...

**Comment by aniketvsawant** [comment]
Thanks @softwareklinic. So when can we expect Diane to put those changes in to the master ?

**Comment by softwareklinic** [comment]
I’m not sure… but that particular build failed at that point in time from what I see in the history.. So, maybe we can get some inputs from Amit & team…

**Comment by amp5208** [comment]
The changes are not yet in master, but are coming - I am providing additional defect fixes in addition to this one, and is only pending internal validation before being merged to master.  I apologize for the delay.

**Comment by oshingc** [comment]
I see this issue as open. @amp5208 Is this issue solved?

**Comment by amp5208** [comment]
@oshingc , Very close - we are finalizing testing now.  we should be able to merge the fixes to master this morning, EST.

**Comment by amp5208** [comment]
@oshingc , This issue was resolved with the newest merge to master, as mentioned in https://github.com/capitalone/Hygieia/issues/224.  Both issues should be able to be closed.  Let me know if you have any questions.

**Comment by oshingc** [comment]
@amp5208 I see the change is already at master.Thank you for the answer.

**Comment by amp5208** [comment]
@tabladrum , This issue can be closed, as customer is no longer having related problem since previous merge.
