### ISSUE TITLE
Jenkins collector issue

### ISSUE THREAD

**Issue by lakshmipgudipati** [capitalone/Hygieia#2310]
2018-06-20 09:53:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2018-06-20 09:53:00,027 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-06-20 09:53:00,027 INFO  c.c.d.collector.CollectorTask - null
2018-06-20 09:53:00,027 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-06-20 09:53:00,028 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at java.lang.StringBuilder.<init>(StringBuilder.java:112) ~[na:1.8.0_91]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.joinURL(DefaultHudsonClient.java:692) ~[hudson-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:192) ~[hudson-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:113) ~[hudson-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:127) ~[hudson-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:42) ~[hudson-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by lakshmipgudipati** [comment]
while executing the jar file in jenkins/target i got this error. Please help me out. Thank you!

**Comment by rvema** [comment]
please provide the execution command (java -jar etc..) and your properties file to debug this issue better.

**Comment by lakshmipgudipati** [comment]
@rvema 
jar file:
java -jar hudson-collector-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins --spring.config.location=/apps/mst/dashboard/Hygieia-master/api/src/main/resources/application.properties

application.properties:
#Database Name
dbname=dashboard

# Database HostName - default is localh:ost
dbhost=localhost

# Database Port - default is 27017
dbport=23456

# MongoDB replicaset
dbreplicaset=false
dbhostport=localhost:23456

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=**********

# Collector schedule (required)
jenkins.cron=*/15 * * * * *

# The page size
jenkins.pageSize=1000

# The folder depth - default is 10
jenkins.folderDepth=20

# Jenkins server (required) - Can provide multiple
jenkins.servers[0]=(jenkins url)

# If using username/token for API authentication
# (required for Cloudbees Jenkins Ops Center) For example,
#jenkins.servers[1]=http://username:token@jenkins.company.com
# Another option: If using same username/password Jenkins auth,
# set username/apiKey to use HTTP Basic Auth (blank=no auth)
jenkins.usernames[0]=*********
jenkins.apiKeys[0]=*********

# Determines if build console log is collected - defaults to false
jenkins.saveLog=true

# Search criteria enabled via properties (max search criteria = 2)
jenkins.searchFields[0]= options.jobName
jenkins.searchFields[1]= niceName

**Comment by rvema** [comment]
per the error seems your jenkins server configuration especially the url is empty can you check the same in your properties file( jenkins.servers array property)

**Comment by lakshmipgudipati** [comment]
@rvema i have given my company's jenkins url in jenkins.servers[0]=(jenkins url)

**Comment by rvema** [comment]
@lakshmipgudipati is it in the format jenkins.servers[0]=http://username:token@jenkins.company.com ?

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/collectors/build/jenkins.md. Per the documentation you should be able to do it either way but not both. If the first way doesn't work try the second way.

**Comment by Sbrenthughes** [comment]
Closing for inactivity
