### ISSUE TITLE
Artifactory collector throwing 415 error while executing AQL query

### ISSUE THREAD

**Issue by jagadeeshchirasani** [capitalone/Hygieia#2317]
2018-06-22 13:25:02,780 INFO  c.c.d.collector.CollectorTask - Fetched repos                    2s
2018-06-22 13:25:02,780 INFO  c.c.d.collector.CollectorTask - New repos               0        0s
2018-06-22 14:14:24,578 ERROR c.c.d.c.DefaultArtifactoryClient - Error with REST url: http://XXXXXXXXXXX:8081/artifactory/api/search/aql
2018-06-22 14:14:24,579 ERROR c.c.d.c.DefaultArtifactoryClient - 415 Unsupported Media Type
2018-06-22 14:14:24,589 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at com.capitalone.dashboard.collector.DefaultArtifactoryClient.getArtifacts(Unknown Source) ~[classes/:na]
	at com.capitalone.dashboard.collector.ArtifactoryCollectorTask.addNewArtifacts(ArtifactoryCollectorTask.java:181) ~

**Comment by subodhbattina** [comment]
@jagadeeshchirasani : looks like the REST url: http://XXXXXXXXXXX:8081/artifactory/api/search/aql
is expecting a different Content-Type. I am looking at the code base, and the content type being set is "text/plain". I will have to check what content-type is expecting and get back to you. In the meanwhile, if you are able to install "Fiddler", please do that. This will allow you to inspect the network traffic. And form there, please share the header information for this url. Thanks !

**Comment by subodhbattina** [comment]
@jagadeeshchirasani : I just checked, and the api does expect "text/plain". Please do confirm what you are seeing on Fiddler, share the headers and the pay load. Thanks !

**Comment by subodhbattina** [comment]
@jagadeeshchirasani My apologies for not having followed up on this.

The error is being thrown in the method "makeRestPost()" in the class "DefaultArtifactoryClient".
If you are able to put log statements in that method, and print out the "body" (Payload) of the post rest call being made, we can figure out if there is something wrong with the message. It has to be in text/plain format. Thanks.

**Comment by subodhbattina** [comment]
@jagadeeshchirasani Any updates on this at all?

**Comment by battinasubodh** [comment]
@jagadeeshchirasani Wanted to check one last time, if you have any updates on this at all? Thanks.

**Comment by subodhbattina** [comment]
@jagadeeshchirasani Since we didn't hear back from you, I am assuming this issue is resolved at your end, and so closing this issue. Thanks !
