### ISSUE TITLE
Code Repo - Bitbucket Collector - Save button not working

### ISSUE THREAD

**Issue by baitiandi** [capitalone/Hygieia#2319]
there are the below errors once Save button in brower. can you please help me.

TypeError: Object doesn't support property or method 'endsWith'
   at removeGit (http://server:3000/components/widgets/repo/config.js:142:4)
   at getOptions (http://server:3000/components/widgets/repo/config.js:148:4)
   at createCollectorItem (http://server:3000/components/widgets/repo/config.js:176:5)
   at submitForm (http://server:3000/components/widgets/repo/config.js:124:6)
   at fn (Function code:2:368)
   at expensiveCheckFn (http://server:3000/bower_components/bower.js:27985:11)
   at callback (http://server:3000/bower_components/bower.js:38364:17)
   at Scope.prototype.$eval (http://server:3000/bower_components/bower.js:29766:9)
   at Scope.prototype.$apply (http://server:3000/bower_components/bower.js:29866:13)
   at Anonymous function (http://server:3000/bower_components/bower.js:38369:17)

**Comment by subodhbattina** [comment]
@baitiandi: In your widget configuration, please check if you have provided the repoUrl correctly. From the exception it looks like the repoUrl may be missing.

**Comment by baitiandi** [comment]
@subodhbattina 
could you please provide a correctly repo URL templete. i config the URL like https://server/scm/project_name/xxx.git

**Comment by baitiandi** [comment]
Hi @subodhbattina 
thank your support, i changed git URL, but still not work, and no any errors in logs once click save botton.could you please give me some suggestion to fix it.

**Comment by baitiandi** [comment]
maybe this issues root case is IE11.

**Comment by subodhbattina** [comment]
@baitiandi : Glad we got over the error at least. Now, when you say "still not working", what is the behavior you are seeing, could you please provide more info, may be a screen shot of your widget?

**Comment by baitiandi** [comment]
@subodhbattina 
thanks for your support, it is fine with chrome brower.

**Comment by subodhbattina** [comment]
@baitiandi: Awesome, thanks for the update, I will go ahead and close this issue.
