### ISSUE TITLE
ALM Jenkins collector: Parse job details error, reported: ERROR c.c.d.collector.DefaultHudsonClient, org.json.simple.parser.ParseException: null

### ISSUE THREAD

**Issue by yuhong02** [capitalone/Hygieia#2327]
Can fetch all jobs information, but, when parse job details info, reported error:
2018-06-29 15:38:13,064 ERROR c.c.d.collector.DefaultHudsonClient - Parsing build: http://hudsonci.oraclecorp.com/jenkins/oardc-jenkins/job/auto_ui_develop_qa/1/
org.json.simple.parser.ParseException: null.

On the UI, I can see the jenkins job, but, no job details. Please help check, thanks a lot.

The log is as following: 
2018-06-29 15:37:46,404 INFO  c.c.d.collector.CollectorTask - Fetched jobs                    46s
2018-06-29 15:37:46,404 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2018-06-29 15:37:46,407 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2018-06-29 15:37:46,408 INFO  c.c.d.collector.CollectorTask - New configs             0        0s
2018-06-29 15:37:46,408 INFO  c.c.d.collector.CollectorTask - Finished                        46s
2018-06-29 15:38:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2018-06-29 15:38:00,084 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-06-29 15:38:00,084 INFO  c.c.d.collector.CollectorTask - http://s***.company.com:8114/jenkins/bu-jenkins
2018-06-29 15:38:00,084 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-06-29 15:38:00,707 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 0/278 pageSize 1000...
2018-06-29 15:38:12,432 INFO  c.c.d.collector.CollectorTask - Fetched jobs                    12s
2018-06-29 15:38:12,440 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2018-06-29 15:38:13,064 ERROR c.c.d.collector.DefaultHudsonClient - Parsing build: http://hudsonci.company.com/jenkins/bu-jenkins/job/auto_ui_develop_qa/1/
org.json.simple.parser.ParseException: null
        at org.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getBuildDetails(DefaultHudsonClient.java:321) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.addNewBuilds(HudsonCollectorTask.java:242) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:131) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:42) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-06-29 15:38:13,483 ERROR c.c.d.collector.DefaultHudsonClient - Parsing build: http://hudsonci.company.com/jenkins/bu-jenkins/job/auto_ui_develop_qa/2/
org.json.simple.parser.ParseException: null
        at org.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getBuildDetails(DefaultHudsonClient.java:321) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.addNewBuilds(HudsonCollectorTask.java:242) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:131) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:42) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

**Comment by yuhong02** [comment]
For the url http://hudsonci.oraclecorp.com/jenkins/oardc-jenkins/job/auto_ui_develop_qa/1/, I can see info after inputting my SSO credential(username and password).

**Comment by yuhong02** [comment]
The properties file is:
dbname=dashboarddb
dbhost=127.0.0.1
dbport=27017
dbreplicaset=false
dbhostport=[host1:port1,host2:port2,host3:port3]
dbusername=admin
dbpassword=welcome1
jenkins.cron=0 0/1 * * * *
jenkins.pageSize=1000
jenkins.folderDepth=10

jenkins.servers[0]=http://slc******.company.com:8114/jenkins/oardc-jenkins
jenkins.servers[1]=http://hud*******.company.com/jenkins/oardc-jenkins
jenkins.usernames[0]=y****.m@oracle.com
jenkins.apiKeys[0]=cf******************************5
jenkins.usernames[1]=y****.m@oracle.com
jenkins.apiKeys[1]=cf******************************5
jenkins.saveLog=true

**Comment by yuhong02** [comment]
I figured out my issue related to SSO. So, I close it.
