### ISSUE TITLE
Unable to start jenkins collector ( ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs org.springframework.web.client.HttpClientErrorException: 403 Forbidden)

### ISSUE THREAD

**Issue by prithvibv** [capitalone/Hygieia#2329]
config file:
#Database Name 
dbname=dashboarddb
 
#Database HostName - default is localhost
#dbhost=localhost
 
#Database Port - default is 27017
#dbport=27017
 
#Database Username - default is blank
#dbusername=databaseuser
 
#Database Password - default is blank
#dbpassword=databaseuser123
 
#jenkins.servers[0]=https://xxxx-jenkins-2.xx.xxx.xxxxxx.com/view/xxxxx(xxxxx)
#Collector schedule (required)
jenkins.cron=0 0/1 * * * *
 
#Jenkins server (required) - Can provide multiple
 
#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
jenkins.servers[1]=https://xxxx:xxxxxxxxxx@xxxx-jenkins-2.xx.xx.xxxx.com/view/xxxxx(xxxxx)
 
#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
#jenkins.username=xxxxxxxx
#jenkins.apiKey=xxxxxxxxxxxxxxxxx

Jenkins.saveLog=false

Exception:
2018-07-02 12:07:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2018-07-02 12:07:00,016 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-07-02 12:07:00,016 INFO  c.c.d.collector.CollectorTask - https://xxx-jenkins-2.xxx.xxx.xxxxx.com/view/xxxxxx(xxxxxx)
2018-07-02 12:07:00,016 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-07-02 12:07:00,443 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 403 Forbidden
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:461) ~[classes/:na]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:98) ~[classes/:na]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) [classes/:na]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:1) [classes/:na]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [classes/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_171]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_171]

Run:
Built the project , right click application.java and in run configurations arguments used --spring.config.name=jenkins --spring.config.location=C:\DevOps\Hygieia\collectors\build\jenkins\application.properties

**Comment by prithvibv** [comment]
Update config file from 
jenkins.servers[1]=https://xxxx:xxxxxxxxxx@xxxx-jenkins-2.xx.xx.xxxx.com/view/xxxxx(xxxxx)
to
jenkins.servers**[0]**=https://xxxx:xxxxxxxxxx@xxxx-jenkins-2.xx.xx.xxxx.com/view/xxxxx(xxxxx)
fixed the issue

**Comment by chenthilan** [comment]
Get the same error (403 forbidden error) with :-

jenkins.servers[0]=_jenkinsendpoint_
jenkins.usernames[0]=_username_
jenkins.apiKeys[0]=_jenkinskey_
