### ISSUE TITLE
Issue with UI

### ISSUE THREAD

**Issue by monikanaagar** [capitalone/Hygieia#2353]
While running UI , I am getting this error after some time.

can anyone help me to resolve this ?

[BS] Serving files from: dist/
_http_outgoing.js:491
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.writeHead (_http_server.js:215:21)
    at ProxyServer.<anonymous> (C:\Users\C57920\Hygieia-master\UI\gulpfile.js:11
0:15)
    at ProxyServer.emit (C:\Users\C57920\Hygieia-master\UI\node_modules\eventemi
tter3\index.js:100:27)
    at ClientRequest.proxyError (C:\Users\C57920\Hygieia-master\UI\node_modules\
http-proxy\lib\http-proxy\passes\web-incoming.js:139:16)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnData (_http_client.js:445:9)
    at emitOne (events.js:116:13)

**Comment by monikanaagar** [comment]
can anyone help ?

**Comment by monikanaagar** [comment]
Yes,locally

**Comment by monikanaagar** [comment]
@Sbrenthughes  any update ?

**Comment by Sbrenthughes** [comment]
Are you seeing any error in the API logs?

**Comment by monikanaagar** [comment]
No , error in api logs .

**Comment by ham5768** [comment]
@monikanaagar : Just need information on ldap integration. Is LDAP stepup is working for you ? Sorry this thread is not for ldap, but i am not getting support on ldap issue thought of asking some one who active recently. Please share if you have any

**Comment by Sbrenthughes** [comment]
@monikanaagar did you get this resolved ?

**Comment by monikanaagar** [comment]
Not able to resolve

**Comment by Sbrenthughes** [comment]
This error causes you to not be able to use the UI? I cannot recreate this error.

**Comment by monikanaagar** [comment]
yes, I am not able to use UI

**Comment by Sbrenthughes** [comment]
I will message you directly in gitter

**Comment by Sbrenthughes** [comment]
@monikanaagar did you ever resolve this? From our last talk it seemed to be a proxy issue.
