### ISSUE TITLE
Artifactory collector Error

### ISSUE THREAD

**Issue by stangem** [capitalone/Hygieia#2362]
When trying to run the Artifactory collector, I come across this error.

sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2018-07-16 14:53:00,210 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at com.capitalone.dashboard.collector.DefaultArtifactoryClient.getRepos(DefaultArtifactoryClient.java:80) ~[artifactory-artifact-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.ArtifactoryCollectorTask.collect(ArtifactoryCollectorTask.java:84) ~[artifactory-artifact-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.ArtifactoryCollectorTask.collect(ArtifactoryCollectorTask.java:27) ~[artifactory-artifact-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
^C2018-07-16 14:53:52,072 INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@2138ca5d: startup date [Mon Jul 16 14:52:55 EDT 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@7c9adc56
2018-07-16 14:53:52,078 INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2018-07-16 14:53:52,078 INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans
2018-07-16 14:53:52,100 INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'

Here are my Properties:

dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
dbusername=dashboarduser
dbpassword=dbpassword
artifactory.cron=0 0/1 * * * *
artifactory.servers[0]= https://www.artifacts.company.com/
#artifactory.usernames[0]="myusername"
artifactory.apiKeys[0]="myApikey"
artifactory.repos[0]=prerelease,release
artifactory.endpoint=artifactory/
artifactory.patterns[0]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<artifact>\\k<module>)-\\k<version>(-(?<classifier>[^\\.]+))?(\\.(?<ext>.+))?
artifactory.patterns[1]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<artifact>ivy)-\\k<version>(-(?<classifier>[^\\.]+))?\\.(?<ext>xml)
artifactory.patterns[2]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<type>[^/]+)/(?<artifact>[^\\.-/]+)-\\k<version>(-(?<classifier>[^\\.]+))?(\\.(?<ext>.+))?

Here is the command I'm using to run the collector

java -jar artifactory-artifact-collector-2.0.5-SNAPSHOT.jar --spring.config.name=artifactory --spring.config.location=/Users/stangem/Hygieia-master/collectors/artifact/artifactory/target/artifactory.properties

**Comment by subodhbattina** [comment]
@stangem : This looks like and SSLHandshakeException.

1. Obtain the certificate from the target server: "https://www.artifacts.company.com".
You could do this by contacting somebody or just putting that URL on your browser and clicking on the  "Not Secure" or the Lock sign in front of the URL on the browser, and download the certificate.

2. Now you need to add this to your JVM trust store:
$JAVA_HOME/jre/lib/security/ for JREs or $JAVA_HOME/lib/security for JDKs, there is file called cacerts.

3. Import the new cert use the below command:
keytool -import -file <the certificate file> -alias <some meaningful name> -keystore <path to cacerts file>

Hope this helps. Thanks.

**Comment by stangem** [comment]
Awesome that fixed the error, Thank you!
