### ISSUE TITLE
Jenkins build collector

### ISSUE THREAD

**Issue by IkaroSales** [capitalone/Hygieia#2368]
I have a following error running jenkins collector:
I'm using docker to run Hygieia and when I run the jenkins collector container it can not connect to the mongo container.
I have other containers and the connection usually occurs only from Jenkins that this error occurs

```
2018-07-20 14:59:26,412 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2018-07-20 14:59:26,749 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@a11d91f6, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@1aa1105a, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@31f9a64f, socketFactory=javax.net.DefaultSocketFactory@2e41d7bf, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2018-07-20 14:59:26,806 INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
    at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
    at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_171]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_171]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_171]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_171]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_171]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_171]
    at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.0.2.jar!/:na]
    ... 3 common frames omitted
```

**docker-compose.yml**
```
version: '3'

services:
  db:
    image: japm/mongodb:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=dashboarduser
      - MONGODB_PASSWORD=dbpassword
      - MONGODB_DATABASE=dashboarddb

  api:
      image: japm/hygieia-api
      links:
        - db
      ports:
        - "8080:8080"

  ui:
    image: japm/hygieia-ui
    depends_on:
      - api
    ports:
      - "80:80"

  phabricator-collector:
     image: japm/hygieia-phabricator-scm-collector
     depends_on:
       - db
     environment:
       - PHABRICATOR_HOST=pb-dc.alm-latam.accenture.com
       - PHABRICATOR_TOKEN=api-ddh64pznhpx2wqgjluhgm5cedbvv
       - MONGO_PORT=tcp://db:27017

  jenkins-build-collector:
      image: japm/jenkins-build-collector
      links:
        - db
      environment:
        - JENKINS_CRON=0 * * * * *
        - JENKINS_MASTER=https://addresstes.com
        - JENKINS_USERNAME=admin
        - JENKINS_API_KEY=fi2de3adp985b1b94a4f2sd4cd772mwe
        - MONGO_PORT=tcp://db:27017
        - DOCKER_LOCALHOST=db

```

**Comment by rvema** [comment]
What OS are you running this on?

**Comment by matthewbeasley** [comment]
@IkaroSales - these are not the official images for Hygieia. Therefore we do not support them. Please clone the project and run `mvn clean install; docker-compose up -d`

**Comment by IkaroSales** [comment]
I tried this command but still dont working.
