### ISSUE TITLE
API and UI is failing to start

### ISSUE THREAD

**Issue by gangadharahn** [capitalone/Hygieia#250]
Could yo please help to solve this issue. The build is successful and when i run the java - jar on api it works fine but when hit the localhost:8080 i am getting the following error

2015-12-22 05:12:52,853 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception [Reque
st processing failed; nested exception is java.lang.IllegalStateException: A RequestDispatcher could not be located for the default servlet 'api'] with root cause
java.lang.IllegalStateException: A RequestDispatcher could not be located for the default servlet 'api'
        at org.springframework.web.servlet.resource.DefaultServletHttpRequestHandler.handleRequest(DefaultServletHttpRequestHandler.java:119) ~[spring-webmvc-4.1.7.RELE
ASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) ~[tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_65]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_65]

Issue2:

When i run the gulp serve command i am getting the following error.

[04:49:32] Finished 'scripts' after 13 s
[04:49:32] Starting 'injector:js'...
[04:49:33] gulp-inject 67 files into index.html.
[04:49:33] Finished 'injector:js' after 563 ms
[04:49:33] Starting 'watch'...
[04:49:34] Finished 'watch' after 983 ms
[04:49:34] Starting 'serve'...
[04:49:34] Finished 'serve' after 336 ms
[BS] Local URL: http://localhost:3000/
[BS] External URL: http://xx.xx.xxx.XXX:3000/
[BS] Serving files from: .tmp
[BS] Serving files from: src
[BS] Watching files...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:855:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)

**Comment by gitfan89** [comment]
@gangadharahn  : any luck with the API error ? me too facing the same issue .

**Comment by gangadharahn** [comment]
After pointing to "dashboard" database it started working!

**Comment by roykaushik07** [comment]
I am also facing the same issue, though my db is correct. Any suggestions?

**Comment by tabladrum** [comment]
@roykaushik07 can you paste your command line and also the api properties file and location?

**Comment by tabladrum** [comment]
The content looks good. Are you running from 8081 for a reason?
Also, can you paste the command that you are executing ... java -jar .etc.

**Comment by roykaushik07** [comment]
Thanks for the reply. I am using port 8081 because 8080 is being used by another application. Following is the command I am executing: 
java -jar api.jar --spring.config.name=api --spring.config.location=dashboard.properties --debug

I am executing it from the location where dashboard.prop file is present. 

What are the prerequisite for getting dashboard running? I am doing installation on Linux server.

**Comment by hygieia** [comment]
can you run the command http://<hostname:8081/api/dashboard and paste the output.

**Comment by roykaushik07** [comment]
I am getting a epmty json response.

**Comment by azedu** [comment]
same for me, empty json response. Any updates on this?

**Comment by tabladrum** [comment]
An empty json is a good sign IF you do not have ANY dashboard configured yet. 
It means your API is running.

**Comment by tabladrum** [comment]
You can change the default api port in gulpfile.js
