### ISSUE TITLE
Git collector fails of you put in a ssh spec instead of https

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#301]
I accidentally entered an ssh path "git@github.com:capitalone/Hygieia" instead of the https url in one dashboard and they all stopped updating as the collector failed and did not run the other dashboards.

We should consider:
1. Skipping a dashboard on failure and update the others
2. validate in the UI the URL to block the bad input.

2016-02-01 20:02:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2016-02-01 20:02:00,022 INFO  c.c.d.collector.CollectorTask - ------------------------------
2016-02-01 20:02:00,023 INFO  c.c.d.collector.CollectorTask - Starting...
2016-02-01 20:02:00,023 INFO  c.c.d.collector.CollectorTask - ------------------------------
2016-02-01 20:02:00,155 ERROR c.c.d.collector.DefaultGitHubClient - no protocol: git@github.com:capitalone/Hygieia
2016-02-01 20:02:00,168 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.

java.lang.IllegalStateException: Could not create URI object: Expected scheme name at index 0: ://api/v3/repos/github.com:capitalone/Hygieia/commits?sha=master&since=2016-02-01T19:52Z
	at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:416) ~[spring-web-4.1.0.RELEASE.jar!/:4.1.0.RELEASE]
	at org.springframework.web.util.UriTemplate.expand(UriTemplate.java:121) ~[spring-web-4.1.0.RELEASE.jar!/:4.1.0.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:520) ~[spring-web-4.1.0.RELEASE.jar!/:4.1.0.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:439) ~[spring-web-4.1.0.RELEASE.jar!/:4.1.0.RELEASE]
	at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:200) ~[github-scm-collector-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:129) ~[github-scm-collector-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:135) ~[github-scm-collector-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_66-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66-internal]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_66-internal]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
Caused by: java.net.URISyntaxException: Expected scheme name at index 0: ://api/v3/repos/github.com:capitalone/Hygieia/commits?sha=master&since=2016-02-01T19:52Z
	at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_66-internal]
	at java.net.URI$Parser.failExpecting(URI.java:2854) ~[na:1.8.0_66-internal]
	at java.net.URI$Parser.parse(URI.java:3046) ~[na:1.8.0_66-internal]
	at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_66-internal]
	at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:401) ~[spring-web-4.1.0.RELEASE.jar!/:4.1.0.RELEASE]
	... 16 common frames omitted

**Comment by smsuresh** [comment]
Please fix this ASAP, This is exactly we also missing!!

**Comment by vishalbisa** [comment]
Hi @jimzucker / @smsuresh 

As a work around you can import jsch package and change the code to connect, hope it works.

please find below sample code .

`int assigned_port;   
    int local_port=3309;

    // Remote host and port
    int remote_port=3306;
    String remote_host = "<SSH host goes here>";
    String login = "<SSH login goes here>";
    String password = "<SSH password goes here>";

    try {
        JSch jsch = new JSch(); 

        // Create SSH session.  Port 22 is your SSH port which
        // is open in your firewall setup.
        Session session = jsch.getSession(login, remote_host, 22);
        session.setPassword(password);

        // Additional SSH options.  See your ssh_config manual for
        // more options.  Set options according to your requirements.
        java.util.Properties config = new java.util.Properties();
        config.put("StrictHostKeyChecking", "no");
        config.put("Compression", "yes");
        config.put("ConnectionAttempts","2");

        session.setConfig(config);

        // Connect
        session.connect();            

        // Create the tunnel through port forwarding.  
        // This is basically instructing jsch session to send 
        // data received from local_port in the local machine to 
        // remote_port of the remote_host
        // assigned_port is the port assigned by jsch for use,
        // it may not always be the same as
        // local_port.

        assigned_port = session.setPortForwardingL(local_port, 
                remote_host, remote_port);

    } catch (JSchException e) {            
        System.out.println("JSch:" + e.getMessage());
        return;
    }

    if (assigned_port == 0) {
        System.out.println("Port forwarding failed!"); 
        return;
    }

`
Thanks,
Vishal

**Comment by tabladrum** [comment]
@jimzucker @smsuresh Fixed. Please test:

![image](https://cloud.githubusercontent.com/assets/6014941/13907531/c284281c-eec6-11e5-8e45-0ef0d7d4608a.png)

**Comment by jimzucker** [comment]
@tabladrum - works OK, closing it.
