### ISSUE TITLE
Authorization and HTTPs error for collectors 

### ISSUE THREAD

**Issue by vignesh89** [capitalone/Hygieia#312]
Hi ,

Is it possible to use the https protocol for the collectors because I don’t see any information has been shared on the same. If it is possible please share the steps to achieve the same.

As of now while I’m trying to connect or use  Hygieia with my organization’s Jenkins , sonarqube and SVN, I’m facing **authentication** error and **certificate** error. Below are the error messages.

**Jenkins :**

2016-02-04 12:03:23,612 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 1]}, minWireVersion=0, maxWireVersion=4, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=1075647}
2016-02-04 12:03:24,915 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2016-02-04 12:03:24,930 INFO  com.capitalone.dashboard.Application - Started Application in 7.67 seconds (JVM running for 9.467)
2016-02-04 12:05:00,007 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2016-02-04 12:05:00,062 INFO  c.c.d.collector.CollectorTask - ------------------------------
2016-02-04 12:05:00,064 INFO  c.c.d.collector.CollectorTask -** https://XXXXXXXXX**
2016-02-04 12:05:00,067 INFO  c.c.d.collector.CollectorTask - ------------------------------
2016-02-04 12:05:01,228 ERROR c.c.d.collector.DefaultHudsonClient -** client exception loading jobs
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://XXXXXXXXXX/api/json?**tree=jobs[name,url,builds[number,url]]":sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:324) ~[jenkins-build-collector-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:88) ~[jenkins-build-collector-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:90) [jenkins-build-collector-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:31) [jenkins-build-collector-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_71]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_71]

**Subversion :**

2016-02-04 17:05:00,869 INFO  c.c.d.collector.CollectorTask - Repo Count         1        0s
2016-02-04 17:05:00,869 INFO  c.c.d.collector.CollectorTask - New Commits        0        0s
2016-02-04 17:05:00,869 INFO  c.c.d.collector.CollectorTask - Finished                    0s
2016-02-04 17:10:00,020 INFO  c.c.d.collector.CollectorTask - Running Collector: Subversion
2016-02-04 17:10:00,028 INFO  c.c.d.collector.CollectorTask - ------------------------------
2016-02-04 17:10:00,029 INFO  c.c.d.collector.CollectorTask - Starting...
2016-02-04 17:10:00,029 INFO  c.c.d.collector.CollectorTask - ------------------------------
2016-02-04 17:10:00,137 ERROR c.c.d.c.DefaultSubversionClient - Subversion repo: https://svn.xxxxx.com/corresponding/ branch/name
org.tmatesoft.svn.core.SVNAuthenticationException: svn: E170001: **Authentication required fo**r '**<https://svn.xxxx.com:443>** THD Subversion Repository'
	at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.authenticationFailed(SVNErrorManager.java:47) ~[svnkit-1.8.7.jar!/:na]
	at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.authenticationFailed(SVNErrorManager.java:41) ~[svnkit-1.8.7.jar!/:na]
	at org.tmatesoft.svn.core.internal.wc.DefaultSVNAuthenticationManager.getNextAuthentication(DefaultSVNAuthenticationManager.java:218) ~[svnkit-1.8.7.jar!/:na]
	at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:696) ~[svnkit-1.8.7.jar!/:na]
	at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:375) ~[svnkit-1.8.7.jar!/:na]
	at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:363) ~[svnkit-1.8.7.jar!/:na]
	at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.performHttpRequest(DAVConnection.java:710) ~[svnkit-1.8.7.jar!/:na]
	at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.exchangeCapabilities(DAVConnection.java:627) ~[svnkit-1.8.7.jar!/:na]
	at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.open(DAVConnection.java:102) ~[svnkit-1.8.7.jar!/:na]
	at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.openConnection(DAVRepository.java:1032) ~[svnkit-1.8.7.jar!/:na]
	at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.getDatedRevision(DAVRepository.java:191) ~[svnkit-1.8.7.jar!/:na]
	at com.capitalone.dashboard.collector.DefaultSubversionClient.getRevisionClosestTo(DefaultSubversionClient.java:59) ~[subversion-collector-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.SubversionCollectorTask.startRevision(SubversionCollectorTask.java:146) [subversion-collector-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.SubversionCollectorTask.collect(SubversionCollectorTask.java:121) [subversion-collector-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_71]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_71]

**SonarQube :**

2016-02-04 13:46:24,889 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:203}] to localhost:27017
2016-02-04 13:46:24,896 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 1]}, minWireVersion=0, maxWireVersion=4, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=3967460}
2016-02-04 13:46:25,457 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2016-02-04 13:46:25,471 INFO  com.capitalone.dashboard.Application - Started Application in 4.903 seconds (JVM running for 5.821)
2016-02-04 13:46:59,999 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2016-02-04 13:47:00,058 INFO  c.c.d.collector.CollectorTask - ------------------------------
2016-02-04 13:47:00,059 INFO  c.c.d.collector.CollectorTask -** https//xxxxxxxxxx**
2016-02-04 13:47:00,059 INFO  c.c.d.collector.CollectorTask - ------------------------------
2016-02-04 13:47:00,757 ERROR c.c.d.collector.DefaultSonarClient - org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://xxxxxxxx/api/resources?format=json":sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2016-02-04 13:47:00,761 INFO  c.c.d.collector.CollectorTask - Fetched projects   0        0s
2016-02-04 13:47:00,769 INFO  c.c.d.collector.CollectorTask - New projects       0        0s
2016-02-04 13:47:00,785 INFO  c.c.d.collector.CollectorTask - Updated            0        0s
2016-02-04 13:47:00,786 INFO  c.c.d.collector.CollectorTask - Finished                    0s
2016-02-04 13:48:00,017 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2016-02-04 13:48:00,040 INFO  c.c.d.collector.CollectorTask - ------------------------------
2016-02-04 13:48:00,041 INFO  c.c.d.collector.CollectorTask - **https://xxxxxxxxxx**
2016-02-04 13:48:00,042 INFO  c.c.d.collector.CollectorTask - ------------------------------
2016-02-04 13:48:00,173 ERROR c.c.d.collector.DefaultSonarClient - org.springframework.web.client.ResourceAccessException: I/O error on GET request for " https://xxxxxxxx/api/resources?=json":sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed:

Thanks for any help !

**Comment by amitmawkin** [comment]
For Jenkins &  Sonarqube Your organization is using self signed certificate which java does not trust , you would have to use the java keytool to import the certificate into your jdk default truststore.

Subversion is getting an authentication error , please check the credentials used

**Comment by dkpurushothaman** [comment]
Subversion is getting an authentication error , same credentials used in eclipse for checkout the source code its working fine

**Comment by JustLeo** [comment]
What happened with this problem? is it resolved? how? please share... Thanks

**Comment by saurav126** [comment]
Having the same problem. Please help. Credentials working in eclipse and browser.

**Comment by ajasonwang** [comment]
Have used the java keytool to import the certificate into jdk default truststore under JAVA_HOME/jre/lib/security/cacerts, and it works when using browser to login urbancode deploy site with https, but running the plugin still get the error: "c.c.d.collector.DefaultUDeployClient - Error with REST url: https://x.x.x.x:443/rest/deploy/application". please advise, thanks.
