### ISSUE TITLE
Maven build error in UI while building from root

### ISSUE THREAD

**Issue by BeenaMP** [capitalone/Hygieia#366]
I have done a "mvn clean install package" from root and got the build error.I can see issue no 192 may be similar.But unable to understand the term "Please run this without root as a user "

]Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:gulp (gulp build) on project UI: Failed to run task: 'gulp.js build --no-color' failed. (error code 1) -> [Help 1]

Build stacktrace:
```
[INFO] Building com.capitalone.dashboard:UI 1.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UI ---
[INFO]
[INFO] >>> maven-pmd-plugin:3.5:check (default) > :pmd @ UI >>>
[INFO]
[INFO] --- maven-pmd-plugin:3.5:pmd (pmd) @ UI ---
[INFO]
[INFO] <<< maven-pmd-plugin:3.5:check (default) < :pmd @ UI <<<
[INFO]
[INFO] --- maven-pmd-plugin:3.5:check (default) @ UI ---
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:install-node-and-npm (install node and npm) @ UI ---
[INFO] Node v0.12.0 is already installed.
[INFO] Found NPM version 2.7.1
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:npm (npm install) @ UI ---
[INFO] Running 'npm install --color=false --proxy=http://cts%5C468683:***@proxy.cognizant.com:6050' in C:\Users\468683\workspace\DE_Hygieia\UI
[ERROR] npm WARN package.json callsite@1.0.0 No repository field.
[ERROR] npm WARN package.json colorspace@1.0.1 No repository field.
[ERROR] npm WARN package.json css-parse@1.0.4 No repository field.
[ERROR] npm WARN package.json css@1.0.8 No repository field.
[ERROR] npm WARN package.json css-stringify@1.0.5 No repository field.
[ERROR] npm WARN package.json has-binary@0.1.7 No repository field.
[ERROR] npm WARN package.json indexof@0.0.1 No repository field.
[ERROR] npm WARN package.json object-component@0.0.3 No repository field.
[ERROR] npm WARN package.json parsejson@0.0.1 No repository field.
[ERROR] npm WARN package.json parseqs@0.0.2 No repository field.
[ERROR] npm WARN package.json path@0.12.7 path is also the name of a node core module.
[ERROR] npm WARN package.json string_decoder@0.10.31 string_decoder is also the name of a node core module.
[ERROR] npm WARN package.json util@0.10.3 util is also the name of a node core module.
[INFO]
[INFO] > gifsicle@3.0.3 postinstall C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\gifsicle
[INFO] > node lib/install.js
[INFO]
[ERROR]   ΓÇ╝ tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 6050
[ERROR]   ΓÇ╝ gifsicle pre-build test failed
[ERROR]   i compiling from source
[ERROR]   ├ù RequestError: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 6050
[ERROR]     at ClientRequest.<anonymous> (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\got\index.js:68:21)
[ERROR]     at ClientRequest.g (events.js:199:16)
[ERROR]     at ClientRequest.emit (events.js:107:17)
[ERROR]     at ClientRequest.onError (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\tunnel-agent\index.js:178:21)
[ERROR]     at ClientRequest.g (events.js:199:16)
[ERROR]     at ClientRequest.emit (events.js:107:17)
[ERROR]     at Socket.socketErrorListener (_http_client.js:272:9)
[ERROR]     at Socket.emit (events.js:107:17)
[ERROR]     at net.js:923:16
[ERROR]     at process._tickCallback (node.js:355:11)
[INFO]
[INFO] > jpegtran-bin@3.0.6 postinstall C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\jpegtran-bin
[INFO] > node lib/install.js
[INFO]
[ERROR]   ΓÇ╝ tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 6050
[ERROR]   ΓÇ╝ jpegtran pre-build test failed
[ERROR]   i compiling from source
[ERROR]   ├ù RequestError: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 6050
[ERROR]     at ClientRequest.<anonymous> (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\got\index.js:68:21)
[ERROR]     at ClientRequest.g (events.js:199:16)
[ERROR]     at ClientRequest.emit (events.js:107:17)
[ERROR]     at ClientRequest.onError (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\tunnel-agent\index.js:178:21)
[ERROR]     at ClientRequest.g (events.js:199:16)
[ERROR]     at ClientRequest.emit (events.js:107:17)
[ERROR]     at Socket.socketErrorListener (_http_client.js:272:9)
[ERROR]     at Socket.emit (events.js:107:17)
[ERROR]     at net.js:923:16
[ERROR]     at process._tickCallback (node.js:355:11)
[ERROR] npm WARN prefer global jshint@2.9.1 should be installed with -g
[INFO]
[INFO] > optipng-bin@3.1.0 postinstall C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\optipng-bin
[INFO] > node lib/install.js
[INFO]
[ERROR]   ΓÇ╝ tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 6050
[ERROR]   ΓÇ╝ optipng pre-build test failed
[ERROR]   i compiling from source
[ERROR]   ├ù RequestError: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 6050
[ERROR]     at ClientRequest.<anonymous> (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\got\index.js:68:21)
[ERROR]     at ClientRequest.g (events.js:199:16)
[ERROR]     at ClientRequest.emit (events.js:107:17)
[ERROR]     at ClientRequest.onError (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\tunnel-agent\index.js:178:21)
[ERROR]     at ClientRequest.g (events.js:199:16)
[ERROR]     at ClientRequest.emit (events.js:107:17)
[ERROR]     at Socket.socketErrorListener (_http_client.js:272:9)
[ERROR]     at Socket.emit (events.js:107:17)
[ERROR]     at net.js:923:16
[ERROR]     at process._tickCallback (node.js:355:11)
[INFO]
[INFO] > phantomjs@1.9.19 install C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\phantomjs
[INFO] > node install.js
[INFO]
[INFO] PhantomJS is previously installed at phantom\phantomjs.exe
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:bower (bower install) @ UI ---
[INFO] Running 'bower install' in C:\Users\468683\workspace\DE_Hygieia\UI
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:gulp (gulp build) @ UI ---
[INFO] Running 'gulp.js build --no-color' in C:\Users\468683\workspace\DE_Hygieia\UI
[INFO] [12:14:28] Using gulpfile ~\workspace\DE_Hygieia\UI\gulpfile.js
[INFO] [12:14:28] Starting 'wiredep'...
[INFO] [12:14:28] Starting 'injector:css:preprocessor'...
[INFO] [12:14:28] Starting 'local-testing'...
[INFO] [12:14:29] Starting 'scripts'...
[INFO] [12:14:35] Starting 'consolidate:jade:app'...
[INFO] [12:14:40] Starting 'consolidate:jade:components'...
[INFO] [12:14:40] Starting 'images'...
[INFO] [12:14:40] Starting 'fonts'...
[INFO] [12:14:43] Starting 'misc'...
[ERROR] events.js:85
[ERROR]       throw er; // Unhandled 'error' event
[ERROR]             ^
[ERROR] Error: Error: modernizr is not installed. Try running `bower install`.
[ERROR]     at C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\wiredep\wiredep.js:30:56
[ERROR]     at C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\wiredep\lib\detect-dependencies.js:145:29
[ERROR]     at forOwn (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\lodash\dist\lodash.js:2106:15)
[ERROR]     at Function.forEach (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\lodash\dist\lodash.js:3303:9)
[ERROR]     at detectDependencies (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\wiredep\lib\detect-dependencies.js:34:7)
[ERROR]     at wiredep (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\wiredep\wiredep.js:70:39)
[ERROR]     at DestroyableTransform._transform (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\wiredep\wiredep.js:135:34)
[ERROR]     at DestroyableTransform.Transform._read (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\wiredep\node_modules\readable-stream\lib_stream_transform.js:18
[ERROR]     at DestroyableTransform.Transform._write (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\wiredep\node_modules\readable-stream\lib_stream_transform.js:1
[ERROR]     at doWrite (C:\Users\468683\workspace\DE_Hygieia\UI\node_modules\wiredep\node_modules\readable-stream\lib_stream_writable.js:237:10)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  1.825 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [  3.133 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [  2.306 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [  4.804 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [12:17 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:29 min
[INFO] Finished at: 2016-02-25T12:14:44+05:30
[INFO] Final Memory: 38M/92M
[INFO] ------------------------------------------------------------------------
 [ERROR]Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:gulp (gulp build) on project UI: Failed to run task: 'gulp.js build --no-color' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:gulp (gulp build) on project UI: Failed to run task
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:66)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'gulp.js build --no-color' failed. (error code 1)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:59)
        at com.github.eirslett.maven.plugins.frontend.mojo.GulpMojo.execute(GulpMojo.java:64)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:64)
        ... 22 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI
```

**Comment by BeenaMP** [comment]
Can I get any resolution for the above issue?

**Comment by tabladrum** [comment]
@BeenaMP See this issue: https://github.com/capitalone/Hygieia/issues/280
