### ISSUE TITLE
Failure in core tests with proxy without user info

### ISSUE THREAD

**Issue by RichSteele** [capitalone/Hygieia#369]
Maven build fails with:

15:39:35.202 [main] DEBUG d.f.e.p.store.ArtifactStoreBuilder - Build ArtifactStore(useCache: true)
Download PRODUCTION:Linux:B64 START
15:39:35.269 [main] ERROR c.c.d.repository.EmbeddedMongoDBRule - Unexpectedly, something in your proxy configuration was blank or misreferenced for com.capitalone.dashboard.repository.EmbeddedMongoDBRule$SystemProxy
java.lang.NullPointerException: null
        at com.capitalone.dashboard.repository.EmbeddedMongoDBRule$SystemProxy.createProxy(EmbeddedMongoDBRule.java:58) ~[test-classes/:na]
        at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:111) [de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69) [de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66) [de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.store.CachingArtifactStore.checkDistribution(CachingArtifactStore.java:62) [de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:55) [de.flapdoodle.embed.process-1.50.0.jar:na]
        at com.capitalone.dashboard.repository.EmbeddedMongoDBRule.before(EmbeddedMongoDBRule.java:136) [test-classes/:na]
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46) [junit-4.11.jar:na]
        at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.11.jar:na]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163) [spring-test-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264) [surefire-junit4-2.17.jar:2.17]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.17.jar:2.17]
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124) [surefire-junit4-2.17.jar:2.17]
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200) [surefire-booter-2.17.jar:2.17]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) [surefire-booter-2.17.jar:2.17]
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.17.jar:2.17]

This is caused by an assumption in EmbeddedMongoDBRule.java that assumes the HTTP_PROXY URL has a userinfo portion:

				URL proxyUrl = new URL(proxy);

				// Case for Proxy authentication required
				try {
					StringTokenizer tokenizedUrl = new StringTokenizer(proxyUrl
							.**getUserInfo**().toString(), ":");
					if (tokenizedUrl.hasMoreTokens()) {

The userinfo portion of the proxy URL is optional, so without it we pop the NPE.

**Comment by satishc1** [comment]
Fixed.
