### ISSUE TITLE
Sonar disabled for github and stash collectors - SonarQube is unable to analyze file

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#370]
Currently  <sonar.skip>true</sonar.skip> is set on these 2 projects and we get the error below in both projects.  It took a while (1.5d to figure out all of the other sonar/eclipse compatibly issues and I wasn't able to solve this last one, more research needed.

Sonar Version: 5.3
Sonar Plugin: 3.0.1
Jacob Plugin: 0.7.4.201502262128

github-scm-collector: 
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.1:sonar (default-cli) on project Hygieia: SonarQube is unable to analyze file : '/Users/jaz/work/Hygieia/github-scm-collector/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java': index (1) must be less than size (1) -> [Help 1]

stash-scm-collector:
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.1:sonar (default-cli) on project Hygieia: SonarQube is unable to analyze file : '/Users/jaz/work/Hygieia/stash-scm-collector/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketClient.java': index (1) must be less than size (1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.1:sonar (default-cli) on project Hygieia: SonarQube is unable to analyze file : '/Users/jaz/work/Hygieia/stash-scm-collector/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketClient.java'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: SonarQube is unable to analyze file : '/Users/jaz/work/Hygieia/stash-scm-collector/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketClient.java'
	at org.sonarsource.scanner.maven.bootstrap.ExceptionHandling.handle(ExceptionHandling.java:36)
	at org.sonarsource.scanner.maven.bootstrap.RunnerBootstrapper.execute(RunnerBootstrapper.java:81)
	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:112)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.sonar.squidbridge.api.AnalysisException: SonarQube is unable to analyze file : '/Users/jaz/work/Hygieia/stash-scm-collector/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketClient.java'
	at org.sonar.java.ast.JavaAstScanner.simpleScan(JavaAstScanner.java:105)
	at org.sonar.java.ast.JavaAstScanner.scan(JavaAstScanner.java:77)
	at org.sonar.java.JavaSquid.scanSources(JavaSquid.java:130)
	at org.sonar.java.JavaSquid.scan(JavaSquid.java:123)
	at org.sonar.plugins.java.JavaSquidSensor.analyse(JavaSquidSensor.java:90)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:98)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:243)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:238)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:228)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
	at com.sun.proxy.$Proxy23.execute(Unknown Source)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
	at org.sonarsource.scanner.maven.bootstrap.RunnerBootstrapper.execute(RunnerBootstrapper.java:78)
	... 23 more
Caused by: java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:301)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:280)
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:91)
	at org.sonar.java.checks.PrintfCheck.verifyParameters(PrintfCheck.java:173)
	at org.sonar.java.checks.PrintfCheck.onMethodInvocationFound(PrintfCheck.java:112)
	at org.sonar.java.checks.methods.AbstractMethodDetection.checkInvocation(AbstractMethodDetection.java:52)
	at org.sonar.java.checks.methods.AbstractMethodDetection.visitNode(AbstractMethodDetection.java:43)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:89)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:115)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:91)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:115)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:91)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:115)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:91)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:115)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:91)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:115)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:91)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.scanTree(SubscriptionVisitor.java:72)
	at org.sonar.java.ast.visitors.SubscriptionVisitor.scanFile(SubscriptionVisitor.java:65)
	at org.sonar.java.checks.SubscriptionBaseVisitor.scanFile(SubscriptionBaseVisitor.java:33)
	at org.sonar.java.model.InternalVisitorsBridge.visitFile(InternalVisitorsBridge.java:111)
	at org.sonar.java.ast.JavaAstScanner.simpleScan(JavaAstScanner.java:97)
	... 56 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by amitmawkin** [comment]
Just exclude all the github, stash  files from sonar analysis. I suspect that they have a special character  > which causes issues with Sonar 5.3

**Comment by jimzucker** [comment]
Note: I have to submit a pull req for #363 before this will be visible to everyone else.

**Comment by jimzucker** [comment]
I did set it to skip these 2 projects, let me re-type the @suppress line it is complaining about.
