### ISSUE TITLE
Now you can use Jenkins Plugin and Github Webhook

### ISSUE THREAD

**Issue by tabladrum** [capitalone/Hygieia#378]
With Hygieia 2.0, you can publish Build, Sonar Analysis, Artifact Info, Deployment (if using Jenkins to deploy), Cucumber Test Results from Jenkins to Hygieia. Use the latest Jenkins Plugin (https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin).

For Github webhook, the  payload url should be set to: http://hygieia-base-url/api/commit/github/v3
Select to publish just the "push" events. 

With the above two new features, you will not need to run github collector, jenkins build collector, sonar collector and jenkins cucumber test collector.

**Comment by softwareklinic** [comment]
So we need API, mongodb, and UI with Jenkins plugin?

Sent from my iPhone

On Feb 29, 2016, at 10:01 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


With Hygieia 2.0, you can publish Build, Sonar Analysis, Artifact Info, Deployment (if using Jenkins to deploy), Cucumber Test Results from Jenkins to Hygieia. Use the latest Jenkins Plugin (https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin).

For Github webhook, the payload url should be set to: http://hygieia-base-url/api/commit/github/v3
Select to publish just the "push" events.

With the above two new features, you will not need to run github collector, jenkins build collector, sonar collector and jenkins cucumber test collector.

**Comment by indrgun** [comment]
i am still getting this NPE:

2017-02-02 15:06:01,308 ERROR c.c.d.rest.RestApiExceptionHandler - null
java.lang.NullPointerException: null
	at com.capitalone.dashboard.service.CommitServiceImpl$GitHubv3.buildCommits(CommitServiceImpl.java:186) ~[api.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.service.CommitServiceImpl$GitHubv3.<init>(CommitServiceImpl.java:140) ~[api.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.service.CommitServiceImpl.createFromGitHubv3(CommitServiceImpl.java:92) ~[api.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.rest.ZCommitController.createGitHubv3(ZCommitController.java:44) ~[api.jar!/:2.0.5-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor379.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at com.capitalone.dashboard.config.LoggingFilter.doFilter(LoggingFilter.java:111) [api.jar!/:2.0.5-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85) [spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

**Comment by jiamengyu** [comment]
I am getting the same issue.  But noticed that our GitHub Enterprise instance is v2.8.  I guess it is not supported by Hygieia, anyone can confirm?  What is the alternative way to integrate?  Will SCM-Github Collector have similar issue?

**Comment by indrgun** [comment]
This is not an issue.  We have github enterprise 2.8 as well and webhook
works fine.  Please ignore the test of webhook.  Set it up and try pushing
a commit; you shall see the commit on hygieia.

**Comment by jiamengyu** [comment]
@indrgun Thanks for the hints.  You are right,  the webhook actually worked even the Ping failed with errors.  I can see the commits per day from Code Repo Widget. 👍

**Comment by satishc1** [comment]
Closed.

**Comment by hammad-bbc** [comment]
> So we need API, mongodb, and UI with Jenkins plugin?
> 
> Sent from my iPhone
> 
> On Feb 29, 2016, at 10:01 PM, tabladrum <[notifications@github.com](mailto:notifications@github.com)[mailto:notifications@github.com](mailto:notifications@github.com)> wrote:
> 
> With Hygieia 2.0, you can publish Build, Sonar Analysis, Artifact Info, Deployment (if using Jenkins to deploy), Cucumber Test Results from Jenkins to Hygieia. Use the latest Jenkins Plugin (https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin).
> 
> For Github webhook, the payload url should be set to: http://hygieia-base-url/api/commit/github/v3
> Select to publish just the "push" events.
> 
> With the above two new features, you will not need to run github collector, jenkins build collector, sonar collector and jenkins cucumber test collector.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/[/issues/378](https://github.com/Hygieia/Hygieia/issues/378).

I am trying to use github web hook but hygieia expects the authorization token and api User. How can I pass that as part of github web hook. There is no option in github webhook ui to do that? What is the work around?
