### ISSUE TITLE
Build & Running on Windows environment

### ISSUE THREAD

**Issue by deepakasa** [capitalone/Hygieia#416]
I am facing issues while building code. I have commented bower and gulp sections from UI pom.xml and able to successfully build the application. While trying to run the application also am getting errors. 

Do you any documentation which explains how to build and run the application on windows environment?

**Comment by tabladrum** [comment]
Can you paste the error log? Thanks

**Comment by deepakasa** [comment]
Thanks, The build errors are as follows

[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  3.174 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  3.795 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  6.831 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  4.911 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [ 12.630 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  4.613 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  3.296 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [ 12.257 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:56 min
[INFO] Finished at: 2016-03-11T09:45:55-05:00
[INFO] Final Memory: 200M/1414M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:bower (bower install) on project UI: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:bower (bower install) on project UI: Failed to run task
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:69)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 27 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'bower install' failed. (error code 1)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:59)
        at com.github.eirslett.maven.plugins.frontend.mojo.BowerMojo.execute(BowerMojo.java:42)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:67)
        ... 29 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI

Command used for build is 

mvnw clean install package -X

**Comment by tabladrum** [comment]
Looks like bower does not have permission to write. Not very familiar with Windows. I will look around. Hold tight.

**Comment by ashnaa** [comment]
I am also facing this issue . Any help is appreciated

**Comment by camify** [comment]
Any update on this?

**Comment by mrpudn** [comment]
Do you have [`bower`](https://bower.io/) installed?

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:bower
  (bower install) on project UI: Failed to run task: 'bower install' failed.
  (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal 
  com.github.eirslett:frontend-maven-plugin:0.0.27:bower (bower install) on project UI:
  Failed to run task
```

**Comment by amitmawkin** [comment]
No reply, assuming this issue was resolved for user , closing this issue for now. If still an issue please  open a new one

**Comment by jaypillai** [comment]
what is the solution for this ?

**Comment by satishc1** [comment]
@jaypillai Run the build on a network not restricted by proxy.

**Comment by mrpudn** [comment]
@jaypillai make sure you have the `HTTP_PROXY` and `HTTPS_PROXY` environment variables set - most tools should honor them.

It looks like the problem that @deepakasa was facing was that he did not have `bower` installed.

**Comment by MarkRx** [comment]
You can also use cntlm.

**Comment by tabladrum** [comment]
love cntlm.

**Comment by camify** [comment]
Think you have the wrong “Moore” added Casey Moore <CMoore@nvidia.com> rather than Cam Moore <camm@nvidia.com>
