### ISSUE TITLE
Can't get UI working

### ISSUE THREAD

**Issue by emoshaya-cognito** [capitalone/Hygieia#478]
API is up and running but I can't get to the UI for some reason. Here's output of running gulp serve:

[centos@ip-10-255-36-170 ui]$ sudo gulp serve
[17:05:30] Warning: gulp version mismatch:
[17:05:30] Global gulp is 3.9.1
[17:05:30] Local gulp is 3.8.11
[17:05:50] Using gulpfile /opt/hygieia/bin/ui/gulpfile.js
[17:05:50] Starting 'build'...
[17:05:50] Starting 'clean'...
[17:05:51] Finished 'clean' after 510 ms
[17:05:51] Starting 'assets'...
[17:05:51] Starting 'themes'...
[17:05:51] Starting 'fonts'...
[17:05:51] Starting 'js'...
[17:05:51] Starting 'views'...
[17:05:51] Starting 'test-data'...
[17:06:39] Finished 'test-data' after 49 s
[17:07:01] Finished 'assets' after 1.15 min
[17:07:15] Finished 'themes' after 1.4 min
[17:07:16] Finished 'views' after 1.42 min
[17:07:17] Finished 'js' after 1.42 min
[17:07:18] Finished 'fonts' after 1.45 min
[17:07:18] Starting 'html'...
[17:07:20] gulp-inject 1 files into index.html.
[17:07:20] gulp-inject 89 files into index.html.
[17:07:20] Finished 'html' after 1.54 s
[17:07:20] Finished 'build' after 1.48 min
[17:07:20] Starting 'serve'...
[17:07:22] Finished 'serve' after 2.43 s
[BS] Local URL: http://localhost:3001
[BS] External URL: http://10.255.36.170:3001
[BS] Serving files from: dist/

**Comment by tabladrum** [comment]
Looks ok to me! what do you see when you point your browser to localhost:3001?

**Comment by emoshaya-cognito** [comment]
Absolutely nothing.. This is running on AWS EC2 instance

**Comment by tabladrum** [comment]
@amitmawkin can you check this out? We run this on EC2 too.

**Comment by jimzucker** [comment]
Can you provide the output of theses actions

Are you connecting from the same ec2 i stance or a different one?

0. Try this in the browser:
http://10.255.36.170:3001/

1. Ping localhost
2. Ping 10.255.36.170
3. Telnet 10.255.36.170 3001

**Comment by amitmawkin** [comment]
Also make sure  your aws ec2 security group allows traffic on ports above

**Comment by emoshaya-cognito** [comment]
I started again today on a clean ec2 instance and now I can't even get the api up. 

2016-04-01 11:02:54,591 INFO  com.capitalone.dashboard.Application - Starting Application v2.0.0-SNAPSHOT on ip-10-255-36-106 with PID 1805 (/opt/hygieia/bin/api/api.jar started by root in /)
2016-04-01 11:02:54,655 INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2cf0ec: startup date [Fri Apr 01 11:02:54 BST 2016]; root of context hierarchy
2016-04-01 11:02:56,375 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-04-01 11:02:56,448 INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
2016-04-01 11:02:56,888 INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat initialized with port(s): 8080 (http)
2016-04-01 11:02:57,044 INFO  o.a.catalina.core.StandardService - Starting service Tomcat
2016-04-01 11:02:57,048 INFO  o.a.catalina.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.0.23
2016-04-01 11:02:57,274 INFO  o.a.c.c.C.[.[localhost].[/api] - Initializing Spring embedded WebApplicationContext
2016-04-01 11:02:57,278 INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 2623 ms
2016-04-01 11:02:57,467 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: 127.0.0.1:27017
2016-04-01 11:02:57,525 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2016-04-01 11:02:57,560 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@d10bcbf4, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@39c58181, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@23dd607, socketFactory=javax.net.DefaultSocketFactory@7c5dab2d, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2016-04-01 11:02:57,637 INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server 127.0.0.1:27017
com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='db', source='dashboard', password=<hidden>, mechanismProperties={}}
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:61) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: com.mongodb.MongoCommandException: Command failed with error 59: 'no such cmd: saslStart' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "no such cmd: saslStart", "code" : 59, "bad cmd" : { "saslStart" : 1, "mechanism" : "SCRAM-SHA-1", "payload" : { "$binary" : "biwsbj1kYixyPVBjTm4mJylJQVRZZTJSSFJEe2lnPW5LVw==", "$type" : "0" } } }
        at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:95) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:45) ~[mongo-java-driver-3.0.2.jar!/:na]
        ... 5 common frames omitted
2016-04-01 11:02:57,880 INFO  o.s.b.c.e.ServletRegistrationBean - Mapping servlet: 'dispatcherServlet' to [/]
2016-04-01 11:02:57,889 INFO  o.s.b.c.e.FilterRegistrationBean - Mapping filter: 'characterEncodingFilter' to: [/*]
2016-04-01 11:02:57,893 INFO  o.s.b.c.e.FilterRegistrationBean - Mapping filter: 'loggingFilter' to: [/*]
2016-04-01 11:02:58,226 INFO  org.mongodb.driver.cluster - No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='db', source='dashboard', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 59: 'no such cmd: saslStart' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "no such cmd: saslStart", "code" : 59, "bad cmd" : { "saslStart" : 1, "mechanism" : "SCRAM-SHA-1", "payload" : { "$binary" : "biwsbj1kYixyPVBjTm4mJylJQVRZZTJSSFJEe2lnPW5LVw==", "$type" : "0" } } }}}]}. Waiting for 30000 ms before timing out
2016-04-01 11:03:28,230 WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt

**Comment by emoshaya-cognito** [comment]
and before you ask yes I've created the dashboard db in mongodb set the default username to db and password to dbpass... I've got the spring config set as 

dbname=dashboard
dbusername=db
dbpassword=dbpass
dbhost=127.0.0.1
dbport=27017
server.contextPath=/api
server.port=8080

**Comment by emoshaya-cognito** [comment]
I got this working in the end

**Comment by AdonisCelestine** [comment]
How did you get this working...I have the exact same issue...I am running it in windows
[23:29:56] Starting 'build'...
[23:29:56] Starting 'clean'...
[23:29:57] Finished 'clean' after 117 ms
[23:29:57] Starting 'assets'...
[23:29:57] Starting 'themes'...
[23:29:57] Starting 'fonts'...
[23:29:57] Starting 'js'...
[23:29:57] Starting 'views'...
[23:29:57] Starting 'test-data'...
[23:30:05] Finished 'test-data' after 8.67 s
[23:30:08] Finished 'themes' after 11 s
[23:30:08] Finished 'assets' after 11 s
[23:30:08] Finished 'views' after 11 s
[23:30:08] Finished 'js' after 11 s
[23:30:08] Finished 'fonts' after 12 s
[23:30:08] Starting 'html'...
[23:30:09] Finished 'html' after 213 ms
[23:30:09] Finished 'build' after 12 s
[23:30:09] Starting 'serve'...
[23:30:09] Finished 'serve' after 667 ms
[BS] Local URL: http://localhost:3000
[BS] External URL: http://10.246.27.241:3000
[BS] Serving files from: dist/

I see nothing in the browser....

Had no problems with earlier versions of Hygieia..

**Comment by AdonisCelestine** [comment]
May be this helps

The connection to ws://localhost:3000/browser-sync/socket.io/?EIO=3&transport=websocket&sid=qpjdc2EqcZItKEiWAAAO was interrupted while the page was loading. browser-sync-client.1.7.3.js:3:884
ReferenceError: config is not defined
 localhost:3000:10:30
ReferenceError: angular is not defined
 template-cache.js:1:1

**Comment by amitmawkin** [comment]
i suggest that you clean up and start afresh, looks like your setup is corrupted.
