### ISSUE TITLE
Property file for JIRA collector

### ISSUE THREAD

**Issue by aryasunny** [capitalone/Hygieia#497]
Need help with figuring these properties
# Jira API Query file names (String template requires the files to have .st extension) (required)

feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

What I am able to understand is that JIRA collector requires --> 
story.st, epic.st, projectinfo.st, memberinfo.st, sprintinfo.st, teaminfo.st, trendinginfo.st

And in each of these files, it requires a query. What kind of query is needed in each of these files.

Thanks

**Comment by aryasunny** [comment]
@tabladrum can you please guide here ?

**Comment by amp5208** [comment]
@aryasunny , I will be able to provide guidance; I will reach out tomorrow via this issue with help.  Tagging myself for awareness:  @amp5208

**Comment by aryasunny** [comment]
@amp5208  Arnold, were you able to find some time to look into this ??

Thanks

**Comment by aryasunny** [comment]
@amp5208 
Arnold, need some help here.

I am using proxy.But there is no specific proxy URL for JIRA. It's just that all traffic goes through a proxy.

 And this is the error I am getting

2016-04-15 13:23:00,073 ERROR c.c.d.d.jira.JiraDataFactoryImpl - There was a problem parsing or reading the proxy configuration settings during openning a Jira connection
. Defaulting to a non-proxy URI.
2016-04-15 13:23:05,539 WARN  c.c.d.d.jira.JiraDataFactoryImpl - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault
is the following:java.net.SocketTimeoutException
2016-04-15 13:23:05,542 ERROR c.c.d.c.team.TeamDataClientSetupImpl - The response from Jira was blank or non existant - please check your property configurations
2016-04-15 13:23:05,553 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Process took :5.495936217 seconds to update

P.S- I am giving the IP address in the property feature.jiraProxyUrl. I understand that it is expecting proxy URL in this format --> http://JIRAPROXY.com...But how to implement proxy if I am just behind a proxy and have nothing like JIRA proxy URL

**Comment by aryasunny** [comment]
finally I am able to pass through the proxy and all. But I am ending up getting the below error.

@amp5208 @tabladrum any guidance from here ??

2016-04-15 15:21:06,524 ERROR o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-14 [ACTIVE] HTTP protocol exception: An existing connection was forcibly closed by the re
mote host
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_77]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_77]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_77]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_77]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_77]
        at org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSLIOSession.java:340) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:366) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:118) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:160) [httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:342) [httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:320) [httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) [httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106) [httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:604) [httpcore-nio-4.2.2.jar!/:4.2.2]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
2016-04-15 15:21:06,528 WARN  c.c.d.d.jira.JiraDataFactoryImpl - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault
is the following:java.io.IOException: An existing connection was forcibly closed by the remote host
2016-04-15 15:21:06,531 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Process took :2.228149612 seconds to update
2016-04-15 15:21:06,534 INFO  c.c.d.collector.FeatureCollectorTask - Feature Data Collection Finished
2016-04-15 15:21:50,336 INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7711ed23: sta
rtup date [Fri Apr 15 15:16:07 CDT 2016]; root of context hierarchy
2016-04-15 15:21:50,344 INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2016-04-15 15:21:50,377 INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'

**Comment by amp5208** [comment]
@aryasunny, Thank you for following-up with your connection issues to Jira via Hygieia.  However, the error you are getting I have never seen during use of our collectors; it would seem to me that Jira (the remote host) or some abstraction infrastructure layer within your company (e.g., an API gateway) is rejecting your request for some reason.  Please validate the following, assuming that your properties are correctly configured:

 - Ensure that you have your remote Jira web certificate installed on your JDK's keystore; _Note:_  If you are deploying to a non-production region that is blocked from communicating to production domains, you will not be able to communication to that Jira instance; ask your Jira admin for a non-production instance of Jira.
 - Ensure that your Jira admin has configured Jira to accept basic authentication (e.g., nosso)
 - Ensure that your Jira admin is not disallowing API connectivity from end-users
 - Validate with your Jira admin the state of your Jira Sessions as they come in from Hygieia
 - If you have an abstracted infrastructure layer (e.g., an API gateway), please validate you are meeting that layer's communication contract (e.g. header, WSDL, WADL, API, etc.).  You may have to even transform the messages coming out of Hygieia to meet your company's transaction requirements through that abstracted layer.

After validating these things, please reply with your findings/status, and I can provide more assistance.

**Comment by satishc1** [comment]
@aryasunny Refer to https://github.com/capitalone/Hygieia/blob/master/collectors/feature/jira/README.md
