### ISSUE TITLE
Docker configuration Error - HTTP 404 Not Found | TCP protocol not supported

### ISSUE THREAD

**Issue by raviAmlani** [capitalone/Hygieia#500]
Hi Team,

I am trying to install Hygieia on my windows machine, starting from cloning the Github repo to Mvn install it worked. Though got some error but those got resolved. Then I am able to run the api also. 

Now as per the set up instruction,  I am trying to build the docker image. Using `mvn docker:build` command which is failing. I am pasting the stack trace below.

> [INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  1.107 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [  0.016 s]
[INFO] com.capitalone.dashboard:api ....................... FAILURE [  2.889 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:stash-scm-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.672 s
[INFO] Finished at: 2016-04-12T15:39:41+01:00
[INFO] Final Memory: 33M/277M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.0:build (default-cli) on project api: Exception caught: Request error: GE
T http://127.0.0.1:8080/version: 404: HTTP 404 Not Found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.0:build (default-cli) on
project api: Exception caught
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:115)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:82)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.spotify.docker.client.DockerRequestException: Request error: GET http://127.0.0.1:8080/version: 404
        at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1306)
        at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1255)
        at com.spotify.docker.client.DefaultDockerClient.version(DefaultDockerClient.java:337)
        at com.spotify.docker.client.DefaultDockerClient.authRegistryHeader(DefaultDockerClient.java:1353)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:925)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:884)
        at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:546)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:331)
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:113)
        ... 23 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.NotFoundException: HTTP 404 Not Found
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
        at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
        at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
        at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
        at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
        at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
        at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :api

What I've done in order to resolve this. 

I put following properties in api POM.xml file:

><dockerHost>${docker.host}</dockerHost> - http://127.0.0.1:8080
<dockerMachineName>${docker.machine.name}</dockerMachineName> - default
<dockerTlsVerify>${docker.tls.verify}</dockerTlsVerify> - 1
<dockerToolboxInstallPath>${docker.toolbox.install.path}</dockerToolboxInstallPath> - C:\Program Files\Docker Toolbox
<dockerCertPath>${docker.cert.path}</dockerCertPath> - C:\Users\96446.docker\machine\machines\default

In the docker host, first I had put the `tcp` protocol which usually I find on the internet people asking to put, but for that I'm getting an error like 
`Unsupported protocol tcp. `

Hence I changed to `http`. And for http also, if I use any other port except `8080` then it gives me: 
`Connection refused`

So by putting `http` and port `8080` I think I am one step closer. 

Can you do let me know how to proceed from this error? 

Thanks,
Ravi

**Comment by jdamick** [comment]
you shouldnt have to change the pom, did you source your dockermachine env?

**Comment by raviAmlani** [comment]
Hi @jdamick 

I didn't create the env variable `dockermachine` instead I made one entry in POM configuration only for `<dockerMachineName>default</dockerMachineName>`

Should I remove these entries from config? 

But by doing so it tries to connect to 127.0.0.1 & 0.0.0.0 which again gives `Connection refused` error.

**Comment by tabladrum** [comment]
@jdamick can you see this?

**Comment by jdamick** [comment]
does your docker machine work from cmd line? did you source in your docker-machine env to your shell?

**Comment by satishc1** [comment]
Closing this. Reopen if still an issue.
