### ISSUE TITLE
Jenkins-cucumber-test-collector  unable to start collector

### ISSUE THREAD

**Issue by sibaom** [capitalone/Hygieia#507]
Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)

2016-04-20 17:23:05,793 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jenkinsCucumberTestCollectorTask': Invocation of init method f
ailed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBe
anPostProcessor.java:136) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCa
pableBeanFactory.java:408) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566) ~
[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[sp
ring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spri
ng-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:
4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4
.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.
1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.
7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring
-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[sprin
g-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.7.RELEASE.
jar!/:4.1.7.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at com.capitalone.dashboard.Application.main(Application.java:13) [jenkins-cucumber-test-collector-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_91]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [jenkins-cucumber-test-collector-2.0.0-SNAPSHOT.jar!/:2.0.0-
SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
Caused by: java.lang.NullPointerException: null
        at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265) ~[spring-context-4.1.7.RELEASE.jar!/:4.1
.7.RELEASE]
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95) ~[spring-context-4.1.7.RELEASE.jar!/:4.1
.7.RELEASE]
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82) ~[spring-context-4.1.7.RELEASE.jar!/:4.1
.7.RELEASE]
        at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73) ~[core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_91]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostPr
ocessor.java:349) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotati
onBeanPostProcessor.java:300) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBe
anPostProcessor.java:133) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 22 common frames omitted
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jenkinsCucumberTestCollectorTask': Invocation of in
it method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBe
anPostProcessor.java:136)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCa
pableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        at com.capitalone.dashboard.Application.main(Application.java:13)
        ... 6 more
Caused by: java.lang.NullPointerException
        at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265)
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95)
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82)
        at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44)
        at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostPr
ocessor.java:349)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotati
onBeanPostProcessor.java:300)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBe
anPostProcessor.java:133)
        ... 22 more

**Comment by sibaom** [comment]
Hi,
please help me to solve this issue.Its urgent

**Comment by tabladrum** [comment]
I think you are not passing in properties correctly or your properties file is missing cron value.

Please paste the properties and the command line you are using.

**Comment by sibaom** [comment]
#Database Name 
dbname=dashboard

#Database HostName - default is localhost
dbhost=localhost

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=

#Database Password - default is blank
dbpassword=

#Collector schedule (required)
jenkins.cron=0 0/5 * * * *

#Jenkins server (required) - Can provide multiple
jenkins.servers[0]=
#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
#jenkins.servers[1]=#

#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
jenkins.username=
jenkins.apiKey=

#Determines if build console log is collected - defaults to false
jenkins.saveLog=true

**Comment by sibaom** [comment]
this is my property file and i am giving username and key there..and running the command 
java -jar jenkins-cucumber-test-collector-2.0.0-SNAPSHOT.jar  --spring.config.location=application.properties

**Comment by sibaom** [comment]
But still its showing error
Error creating bean with name 'jenkinsCucumberTestCollectorTask': Invocation of init method f
ailed; nested exception is java.lang.NullPointerExceptionwing

**Comment by tabladrum** [comment]
You are using Jenkins collector properties for Jenkins cucumber. Change the properties to "jenkins-cucumber"

**Comment by sibaom** [comment]
please say what information should i put for jenkins-cucumber.properties

**Comment by sibaom** [comment]
#Database Name 
dbname=dashboard

#Database HostName - default is localhost
dbhost=localhost

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=

#Database Password - default is blank
dbpassword=

#Collector schedule (required)
jenkins-cucumber.cron=0 0/5 * * * *

#Jenkins server (required) - Can provide multiple
jenkins-cucumber.servers[0]=

#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
#jenkins.servers[1]=#

#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
jenkins-cucumber.username=
jenkins-cucumber.apiKey=
#Determines if build console log is collected - defaults to false
jenkins-cucumber.saveLog=true




this is my new jenkins-cucumber.propertyfile with valid user name and token   But still i am getting the error

**Comment by sibaom** [comment]
Thanks for the information @tabladrum 
now the collector is running but showing warning as bellow 
WARNING: No Enabled Jobs found with artifacts pattern: cucumber.json 
what goal should i set for  Archive the artifacts and how to
set the files to archive to the root  directory tree

**Comment by jimzucker** [comment]
Hi,  you can look at the example jenkins server and cucumber job under test servers.


Jim

Sent from my iPhone

On Apr 21, 2016, at 05:16, sibaom <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the information @tabladrum<https://github.com/tabladrum>
now the collector is running but showing warning as bellow
WARNING: No Enabled Jobs found with artifacts pattern: cucumber.json
what goal should i set for Archive the artifacts and how to
set the files to archive to the root directory tree

-

**Comment by sibaom** [comment]
Thanks @tabladrum and @jimzucker
