### ISSUE TITLE
hygieia-api docker container : Exited after 30s

### ISSUE THREAD

**Issue by benathmane** [capitalone/Hygieia#520]
====>  sudo docker ps -a

CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                      PORTS                         NAMES
5261ee77ef8c        hygieia-ui               "/bin/sh -c 'conf-bui"   20 minutes ago      Up 20 minutes               0.0.0.0:80->80/tcp, 443/tcp   hygieia-ui
96dbae7409fd        knickers/mongo-express   "tini -- node app"       20 minutes ago      Up 20 minutes               0.0.0.0:8081->8081/tcp        mongo-express
3f5b4b1c3a79        hygieia-api              "/bin/sh -c './proper"   20 minutes ago      Exited (1) 11 minutes ago                                 hygieia-api
475ebee3b9a3        mongo:latest             "/entrypoint.sh mongo"   20 minutes ago      Up 20 minutes               0.0.0.0:27017->27017/tcp      mongodb

====>  sudo docker logs 3f5b4b1c3a79 

Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches PrimaryServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.17.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='db', source='dashboard', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server 172.17.0.1:27017. The full response is { "ok" : 0.0, "code" : 18, "errmsg" : "Authentication failed." }}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:370)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getWriteConnectionSource(ClusterBinding.java:68)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:175)
	at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:111)
	at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:66)
	at com.mongodb.Mongo.execute(Mongo.java:747)
	at com.mongodb.Mongo$2.execute(Mongo.java:730)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:1492)
	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:142)
	... 67 more

**Comment by tabladrum** [comment]
@jimzucker or @jdamick can you take a look at this?

**Comment by jimzucker** [comment]
@benathmane @tabladrum - I checkout master and ran the containers today w/no issue. 

1.  Please confirm you setup the db id/pwd per the setup instructions: https://github.com/capitalone/Hygieia/blob/master/Setup.md  

2. Did you try restarting using the docker-compose file ?  `docker-compose restart`

**Comment by benathmane** [comment]
@jimzucker Thank you, my problem is solved :)
