### ISSUE TITLE
Error when i run docker jenkins-build-collector docker's

### ISSUE THREAD

**Issue by benathmane** [capitalone/Hygieia#582]
```
2016-05-20 12:52:07,567 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.StackOverflowError: null
    at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3797) ~[na:1.8.0_91]
    at java.util.regex.Pattern$Curly.match(Pattern.java:4227) ~[na:1.8.0_91]
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658) ~[na:1.8.0_91]
    at java.util.regex.Pattern$Branch.match(Pattern.java:4604) ~[na:1.8.0_91]
    at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568) ~[na:1.8.0_91]
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717) ~[na:1.8.0_91]
    at java.util.regex.Pattern$Curly.match0(Pattern.java:4279) ~[na:1.8.0_91]
    at java.util.regex.Pattern$Curly.match(Pattern.java:4234) ~[na:1.8.0_91]
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658) ~[na:1.8.0_91]
    at java.util.regex.Pattern$Branch.match(Pattern.java:4604) ~[na:1.8.0_91]
    at java.util.regex.Pattern$Branch.match(Pattern.java:4602) ~[na:1.8.0_91]
    at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798) ~[na:1.8.0_91]
    at java.util.regex.Pattern$Start.match(Pattern.java:3461) ~[na:1.8.0_91]
    at java.util.regex.Matcher.search(Matcher.java:1248) ~[na:1.8.0_91]
    at java.util.regex.Matcher.find(Matcher.java:664) ~[na:1.8.0_91]
    at java.util.Formatter.parse(Formatter.java:2549) ~[na:1.8.0_91]
    at java.util.Formatter.format(Formatter.java:2501) ~[na:1.8.0_91]
    at java.util.Formatter.format(Formatter.java:2455) ~[na:1.8.0_91]
    at java.lang.String.format(String.java:2940) ~[na:1.8.0_91]
    at com.mongodb.connection.DefaultConnectionPool.getPooledConnection(DefaultConnectionPool.java:249) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:90) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:80) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.connection.DefaultServer.getConnection(DefaultServer.java:69) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:86) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:193) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.operation.FindOperation.execute(FindOperation.java:394) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.operation.FindOperation.execute(FindOperation.java:57) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.Mongo.execute(Mongo.java:738) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.Mongo$2.execute(Mongo.java:725) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.DBCollection.findOne(DBCollection.java:737) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.DBCollection.findOne(DBCollection.java:710) ~[mongo-java-driver-3.0.2.jar!/:na]
    at com.mongodb.DBCollection.findOne(DBCollection.java:657) ~[mongo-java-driver-3.0.2.jar!/:na]
    at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:2080) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:2064) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:1839) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at org.springframework.data.mongodb.core.MongoTemplate.doFindOne(MongoTemplate.java:1656) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at org.springframework.data.mongodb.core.MongoTemplate.findById(MongoTemplate.java:614) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findOne(SimpleMongoRepository.java:119) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:475) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at com.sun.proxy.$Proxy47.findOne(Unknown Source) ~[na:na]
    at com.capitalone.dashboard.event.BuildEventListener.findAllDashboardsForBuild(BuildEventListener.java:118) ~[core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
    at com.capitalone.dashboard.event.BuildEventListener.processBuild(BuildEventListener.java:63) ~[core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
    at com.capitalone.dashboard.event.BuildEventListener.onAfterSave(BuildEventListener.java:36) ~[core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
    at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:92) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:33) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.data.mongodb.core.MongoTemplate.maybeEmitEvent(MongoTemplate.java:1611) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at org.springframework.data.mongodb.core.MongoTemplate.doSave(MongoTemplate.java:978) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at org.springframework.data.mongodb.core.MongoTemplate.save(MongoTemplate.java:921) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.save(SimpleMongoRepository.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
    at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:475) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
    at com.sun.proxy.$Proxy42.save(Unknown Source) ~[na:na]
```

**Comment by continuum-prateek-agarwal** [comment]
Can anyone please update on this..i am also facing the same issue while starting jenkins build collector on Hygieia2.5 version
