### ISSUE TITLE
Bower errors in UI

### ISSUE THREAD

**Issue by cloudsan42** [capitalone/Hygieia#584]
ERROR] npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
[ERROR] npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
[ERROR] npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
[ERROR] npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
[ERROR] npm WARN enoent ENOENT: no such file or directory, open '/home/vagrant/test/Hygieia/UI/node_modules/npm/package.json'
[ERROR] npm WARN bl@0.7.0 requires a peer of stream-browserify@* but none was installed.
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.27:bower (bower install) @ UI ---
[INFO] Found proxies: []
[INFO] Running 'bower install' in /home/vagrant/test/Hygieia/UI
[INFO] bower modernizr#~2.8.3      not-cached https://github.com/Modernizr/Modernizr.git#~2.8.3
[INFO] bower modernizr#~2.8.3         resolve https://github.com/Modernizr/Modernizr.git#~2.8.3
[INFO] bower angular-animate#~1.3.4       not-cached https://github.com/angular/bower-angular-animate.git#~1.3.4
[INFO] bower angular-animate#~1.3.4          resolve https://github.com/angular/bower-angular-animate.git#~1.3.4
[INFO] bower angular-sanitize#~1.3.4      not-cached https://github.com/angular/bower-angular-sanitize.git#~1.3.4
[INFO] bower angular-sanitize#~1.3.4         resolve https://github.com/angular/bower-angular-sanitize.git#~1.3.4
[INFO] bower angular-route#~1.3.4         not-cached https://github.com/angular/bower-angular-route.git#~1.3.4
[INFO] bower angular-route#~1.3.4            resolve https://github.com/angular/bower-angular-route.git#~1.3.4
[INFO] bower angular-cookies#~1.3.4       not-cached https://github.com/angular/bower-angular-cookies.git#~1.3.4
[INFO] bower angular-cookies#~1.3.4          resolve https://github.com/angular/bower-angular-cookies.git#~1.3.4
[INFO] bower angular#~1.3.4               not-cached https://github.com/angular/bower-angular.git#~1.3.4
[INFO] bower angular#~1.3.4                  resolve https://github.com/angular/bower-angular.git#~1.3.4
[INFO] bower angular-ui-router#~0.2.13    not-cached https://github.com/angular-ui/angular-ui-router-bower.git#~0.2.13
[INFO] bower angular-ui-router#~0.2.13       resolve https://github.com/angular-ui/angular-ui-router-bower.git#~0.2.13
[INFO] bower angular-bootstrap#~0.12.0    not-cached https://github.com/angular-ui/bootstrap-bower.git#~0.12.0
[INFO] bower angular-bootstrap#~0.12.0       resolve https://github.com/angular-ui/bootstrap-bower.git#~0.12.0
[INFO] bower angular-validation-match#~1.5.0       not-cached https://github.com/TheSharpieOne/angular-validation-match.git#~1.5.0
[INFO] bower angular-validation-match#~1.5.0          resolve https://github.com/TheSharpieOne/angular-validation-match.git#~1.5.0
[INFO] bower bootstrap-sweetalert#~0.4.5           not-cached https://github.com/lipis/bootstrap-sweetalert.git#~0.4.5
[INFO] bower bootstrap-sweetalert#~0.4.5              resolve https://github.com/lipis/bootstrap-sweetalert.git#~0.4.5
[INFO] bower operative#~0.4.4                      not-cached https://github.com/padolsey/operative.git#~0.4.4
[INFO] bower operative#~0.4.4                         resolve https://github.com/padolsey/operative.git#~0.4.4
[INFO] bower angular-chartist.js#~3.3.13           not-cached https://github.com/paradox41/angular-chartist.js.git#~3.3.13
[INFO] bower angular-chartist.js#~3.3.13              resolve https://github.com/paradox41/angular-chartist.js.git#~3.3.13
[INFO] bower chartist#~0.9.5                       not-cached https://github.com/gionkunz/chartist-js.git#~0.9.5
[INFO] bower chartist#~0.9.5                          resolve https://github.com/gionkunz/chartist-js.git#~0.9.5
[INFO] bower moment#~2.9.0                         not-cached https://github.com/moment/moment.git#~2.9.0
[INFO] bower moment#~2.9.0                            resolve https://github.com/moment/moment.git#~2.9.0
[INFO] bower lodash#~2.4.1                         not-cached https://github.com/lodash/lodash.git#~2.4.1
[INFO] bower lodash#~2.4.1                            resolve https://github.com/lodash/lodash.git#~2.4.1
[INFO] bower components-font-awesome#~4.2.0        not-cached https://github.com/components/font-awesome.git#~4.2.0
[INFO] bower components-font-awesome#~4.2.0           resolve https://github.com/components/font-awesome.git#~4.2.0
[INFO] bower bootstrap#~3.3.2                      not-cached https://github.com/twbs/bootstrap.git#~3.3.2
[INFO] bower bootstrap#~3.3.2                         resolve https://github.com/twbs/bootstrap.git#~3.3.2
[INFO] bower hygieia-jstz-detect#~1.0.5            not-cached https://github.com/amitmawkin/bower-jstz.git#~1.0.5
[INFO] bower hygieia-jstz-detect#~1.0.5               resolve https://github.com/amitmawkin/bower-jstz.git#~1.0.5
[INFO] bower dexie#~1.2.0                          not-cached https://github.com/dfahlander/dexie.js.git#~1.2.0
[INFO] bower dexie#~1.2.0                             resolve https://github.com/dfahlander/dexie.js.git#~1.2.0
[INFO] bower ng-sortable#~1.3.2                    not-cached https://github.com/a5hik/ng-sortable.git#~1.3.2
[INFO] bower ng-sortable#~1.3.2                       resolve https://github.com/a5hik/ng-sortable.git#~1.3.2
[INFO] bower regression-js#~1.3.0                  not-cached https://github.com/Tom-Alexander/regression-js.git#~1.3.0
[INFO] bower regression-js#~1.3.0                     resolve https://github.com/Tom-Alexander/regression-js.git#~1.3.0
[INFO] bower angular-mocks#~1.3.4                  not-cached https://github.com/angular/bower-angular-mocks.git#~1.3.4
[INFO] bower angular-mocks#~1.3.4                     resolve https://github.com/angular/bower-angular-mocks.git#~1.3.4
[ERROR] bower modernizr#~2.8.3                           error cmd(...).spread is not a function
[ERROR] 
[ERROR] Stack trace:
[ERROR] TypeError: cmd(...).spread is not a function
[ERROR]     at Function.GitRemoteResolver.refs (/home/vagrant/test/Hygieia/UI/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:254:6)
[ERROR]     at Function.GitResolver.tags (/home/vagrant/test/Hygieia/UI/node_modules/bower/lib/core/resolvers/GitResolver.js:299:18)
[ERROR]     at Function.GitResolver.versions (/home/vagrant/test/Hygieia/UI/node_modules/bower/lib/core/resolvers/GitResolver.js:259:18)
[ERROR]     at GitHubResolver.GitResolver._findResolution (/home/vagrant/test/Hygieia/UI/node_modules/bower/lib/core/resolvers/GitResolver.js:108:21)
[ERROR]     at GitHubResolver.GitRemoteResolver._findResolution (/home/vagrant/test/Hygieia/UI/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:98:50)
[ERROR]     at GitHubResolver.GitResolver._resolve (/home/vagrant/test/Hygieia/UI/node_modules/bower/lib/core/resolvers/GitResolver.js:67:17)
[ERROR]     at _fulfilled (/home/vagrant/test/Hygieia/UI/node_modules/q/q.js:834:54)
[ERROR]     at self.promiseDispatch.done (/home/vagrant/test/Hygieia/UI/node_modules/q/q.js:863:30)
[ERROR]     at Promise.promise.promiseDispatch (/home/vagrant/test/Hygieia/UI/node_modules/q/q.js:796:13)
[ERROR]     at /home/vagrant/test/Hygieia/UI/node_modules/q/q.js:604:44
[ERROR] 
[ERROR] Console trace:
[ERROR] Error
[ERROR]     at StandardRenderer.error (/home/vagrant/test/Hygieia/UI/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
[ERROR]     at Logger.<anonymous> (/home/vagrant/test/Hygieia/UI/node_modules/bower/lib/bin/bower.js:110:26)
[ERROR]     at emitOne (events.js:77:13)
[ERROR]     at Logger.emit (events.js:169:7)
[ERROR]     at Logger.emit (/home/vagrant/test/Hygieia/UI/node_modules/bower-logger/lib/Logger.js:29:39)
[ERROR]     at /home/vagrant/test/Hygieia/UI/node_modules/bower/lib/commands/index.js:48:20
[ERROR]     at _rejected (/home/vagrant/test/Hygieia/UI/node_modules/q/q.js:844:24)
[ERROR]     at /home/vagrant/test/Hygieia/UI/node_modules/q/q.js:870:30
[ERROR]     at Promise.when (/home/vagrant/test/Hygieia/UI/node_modules/q/q.js:1122:31)
[ERROR]     at Promise.promise.promiseDispatch (/home/vagrant/test/Hygieia/UI/node_modules/q/q.js:788:41)
[ERROR] System info:
[ERROR] Bower version: 1.7.9
[ERROR] Node version: 5.4.1
[ERROR] OS: Linux 3.10.0-327.18.2.el7.x86_64 x64
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.294 s
[INFO] Finished at: 2016-05-20T08:57:25+00:00
[INFO] Final Memory: 18M/43M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:bower (bower install) on project UI: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Hi I'm getting this issue when running maven on UI.

**Comment by amitmawkin** [comment]
looks like you are running it inside a vagrant box, make sure the vagrant box can connect out to internet. If connectivity is not an issue I will clean and start again
