### ISSUE TITLE
ERROR c.c.d.repository.EmbeddedMongoDBRule - Malformed HTTP

### ISSUE THREAD

**Issue by bimalvv** [capitalone/Hygieia#628]
Hi,
When I try to build the proj, I am getting the following error

`08:28:51.868 [main] ERROR c.c.d.repository.EmbeddedMongoDBRule - Malformed HTTP
Proxy for com.capitalone.dashboard.repository.EmbeddedMongoDBRule$SystemProxy
java.net.MalformedURLException: null
        at java.net.URL.<init>(URL.java:620) ~[na:1.8.0_25]
        at java.net.URL.<init>(URL.java:483) ~[na:1.8.0_25]
        at java.net.URL.<init>(URL.java:432) ~[na:1.8.0_25]
        at com.capitalone.dashboard.repository.EmbeddedMongoDBRule$SystemProxy.c
reateProxy(EmbeddedMongoDBRule.java:53) ~[test-classes/:na]
        at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Down
loader.java:111) [de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java
:69) [de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(Art
ifactStore.java:66) [de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.store.CachingArtifactStore.checkDistribut
ion(CachingArtifactStore.java:62) [de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:55)
[de.flapdoodle.embed.process-1.50.0.jar:na]
        at com.capitalone.dashboard.repository.EmbeddedMongoDBRule.before(Embedd
edMongoDBRule.java:140) [test-classes/:na]
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
 [junit-4.11.jar:na]
        at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.11.jar:n
a]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11
.jar:na]
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(S
pringJUnit4ClassRunner.java:163) [spring-test-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:264) [surefire-junit4-2.17.jar:2.17]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:153) [surefire-junit4-2.17.jar:2.17]
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:124) [surefire-junit4-2.17.jar:2.17]
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
ssLoader(ForkedBooter.java:200) [surefire-booter-2.17.jar:2.17]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:153) [surefire-booter-2.17.jar:2.17]
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
103) [surefire-booter-2.17.jar:2.17]
Caused by: java.lang.NullPointerException: null
        at java.net.URL.<init>(URL.java:525) ~[na:1.8.0_25]
        ... 19 common frames omitted
08:28:51.899 [main] ERROR d.f.embed.process.runtime.Starter - prepare executable

java.io.IOException: Could not open inputStream for http://downloads.mongodb.org
/win32/mongodb-win32-x86_64-2008plus-3.0.5.zip with proxy DIRECT
        at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Down
loader.java:131) ~[de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java
:69) ~[de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(Art
ifactStore.java:66) ~[de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.store.CachingArtifactStore.checkDistribut
ion(CachingArtifactStore.java:62) ~[de.flapdoodle.embed.process-1.50.0.jar:na]
        at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:55)
~[de.flapdoodle.embed.process-1.50.0.jar:na]
        at com.capitalone.dashboard.repository.EmbeddedMongoDBRule.before(Embedd
edMongoDBRule.java:140) [test-classes/:na]
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
 [junit-4.11.jar:na]
        at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.11.jar:n
a]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11
.jar:na]
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(S
pringJUnit4ClassRunner.java:163) [spring-test-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:264) [surefire-junit4-2.17.jar:2.17]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:153) [surefire-junit4-2.17.jar:2.17]
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:124) [surefire-junit4-2.17.jar:2.17]
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
ssLoader(ForkedBooter.java:200) [surefire-booter-2.17.jar:2.17]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:153) [surefire-booter-2.17.jar:2.17]
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
103) [surefire-booter-2.17.jar:2.17]
Caused by: java.net.UnknownHostException: downloads.mongodb.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:184) ~[na:1.8.0_25]
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0
_25]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0
_25]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_25]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_25
]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.
0_25]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.
0_25]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_25
]
        at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_25]
        at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_25]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLC
onnection.java:1167) ~[na:1.8.0_25]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConn
ection.java:1146) ~[na:1.8.0_25]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:997) ~[na:1.8.0_25]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection
.java:931) ~[na:1.8.0_25]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1511) ~[na:1.8.0_25]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1439) ~[na:1.8.0_25]
        at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Down
loader.java:127) ~[de.flapdoodle.embed.process-1.50.0.jar:na]
        ... 15 common frames omitted
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.156 sec <<< FA
ILURE! - in com.capitalone.dashboard.repository.ScopeRepositoryTest
com.capitalone.dashboard.repository.ScopeRepositoryTest  Time elapsed: 0.156 sec
  <<< ERROR!
de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOExceptio
n: Could not open inputStream for http://downloads.mongodb.org/win32/mongodb-win
32-x86_64-2008plus-3.0.5.zip with proxy DIRECT
        at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:68)
        at com.capitalone.dashboard.repository.EmbeddedMongoDBRule.before(Embedd
edMongoDBRule.java:140)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)

        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(S
pringJUnit4ClassRunner.java:163)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
ssLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
103)
Caused by: java.io.IOException: Could not open inputStream for http://downloads.
mongodb.org/win32/mongodb-win32-x86_64-2008plus-3.0.5.zip with proxy DIRECT
        at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Down
loader.java:131)
        at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java
:69)
        at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(Art
ifactStore.java:66)
        at de.flapdoodle.embed.process.store.CachingArtifactStore.checkDistribut
ion(CachingArtifactStore.java:62)
        at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:55)
        at com.capitalone.dashboard.repository.EmbeddedMongoDBRule.before(Embedd
edMongoDBRule.java:140)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)

        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(S
pringJUnit4ClassRunner.java:163)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
ssLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
103)
Caused by: java.net.UnknownHostException: downloads.mongodb.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLC
onnection.java:1167)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConn
ection.java:1146)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:997)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection
.java:931)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1511)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1439)
        at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Down
loader.java:127)
        at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java
:69)
        at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(Art
ifactStore.java:66)
        at de.flapdoodle.embed.process.store.CachingArtifactStore.checkDistribut
ion(CachingArtifactStore.java:62)
        at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:55)
        at com.capitalone.dashboard.repository.EmbeddedMongoDBRule.before(Embedd
edMongoDBRule.java:140)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)

        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(S
pringJUnit4ClassRunner.java:163)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
ssLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
103)

Running com.capitalone.dashboard.util.EncryptionTests
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.
capitalone.dashboard.util.EncryptionTests

Results :

Tests in error:
  AuthenticationRepositoryTest.com.capitalone.dashboard.repository.Authenticatio
nRepositoryTest » Distribution
  DashboardCreateTests.com.capitalone.dashboard.repository.DashboardCreateTests
» Distribution
  FeatureRepositoryTest.com.capitalone.dashboard.repository.FeatureRepositoryTes
t » Distribution
  ScopeOwnerRepositoryTest.com.capitalone.dashboard.repository.ScopeOwnerReposit
oryTest » Distribution
  ScopeRepositoryTest.com.capitalone.dashboard.repository.ScopeRepositoryTest »
Distribution

Tests run: 28, Failures: 0, Errors: 5, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  2.247 s]
[INFO] com.capitalone.dashboard:core ...................... FAILURE [ 26.443 s]
[INFO] com.capitalone.dashboard:api ....................... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:stash-scm-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.125 s
[INFO] Finished at: 2016-06-16T08:28:53+05:30
[INFO] Final Memory: 43M/392M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
17:test (default-test) on project core: There are test failures.
[ERROR]
[ERROR] Please refer to C:\WMT\GLS\DevOps\OpenSource\Hygieia\Hygieia-master\core
\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :core`

Is there any way I can skip this as I was building inside a network.

Thanks,
Bimal

**Comment by bimalvv** [comment]
It was an issue with the HTTP_PROXY. Closing the issue

**Comment by ganeshgsh** [comment]
Hi ,
i didnt \set any proxy server,but getting above mention error,please help me.

**Comment by elangesk** [comment]
I am also getting HTTP_PROXY issue. could use please give your solution on this.

**Comment by mrpudn** [comment]
I'm not sure how this will work if you aren't behind a proxy, but if you are, make sure you have the `HTTP_PROXY` and `HTTPS_PROXY` environment variables set, or you'll get weird errors like this.

If you aren't behind a proxy, you shouldn't have these issues if the `HTTP_PROXY` and `HTTPS_PROXY` variables aren't set.

**Comment by elangesk** [comment]
Hi,

I  didn't set HTTP_PROXY and HTTPS_PROXY in my system and System.getenv() & System.getProperty() return null value to HTTP_PROXY and HTTPS_PROXY .

Any thing want to taken care in-terms of PROXY regarding. Need your advise on this.

**Comment by hackeys** [comment]
Setting HTTP_PROXY and HTTPS_PROXY variables on CentOS resolved this issue.
