### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat 'hygieia/UI/src/template-cache.js'

### ISSUE THREAD

**Issue by gumdelli** [capitalone/Hygieia#630]
Trying to build Hygieia and the UI piece fails with the following error:

```
Error: ENOENT: no such file or directory, lstat '/Users/<user>/Repos/hygieia/UI/src/template-cache.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:976:18)
    at DestroyableTransform.TransformStream [as _transform] (/Users/<user>/Repos/hygieia/UI/node_modules/gulp-header/index.js:38:12)
    at DestroyableTransform.Transform._read (/Users/<user>/Repos/hygieia/UI/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/<user>/Repos/hygieia/UI/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/<user>/Repos/hygieia/UI/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/<user>/Repos/hygieia/UI/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/<user>/Repos/hygieia/UI/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Users/<user>/Repos/hygieia/UI/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/<user>/Repos/hygieia/UI/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:632:7)ENOENT
```
node and npm versions: 
```
[~] $ node -v && npm -version
v6.2.1
3.9.3
```

Can anyone point me in the right direction?

**Comment by rodrigosiviero** [comment]
Same thing here, trying to build in aws ami

**Comment by tabladrum** [comment]
Master seems to be broken now. @amitmawkin is looking to fix it.

**Comment by tabladrum** [comment]
For reference: https://github.com/miickel/gulp-angular-templatecache/issues/124

**Comment by amitmawkin** [comment]
https://github.com/miickel/gulp-angular-templatecache/issues/124

**Comment by amitmawkin** [comment]
Fix was pushed an hour ago to NPM

**Comment by tabladrum** [comment]
its not there yet. Will wait for few more hours and kick off the build then.

**Comment by tabladrum** [comment]
https://github.com/capitalone/Hygieia/pull/633

**Comment by amitmawkin** [comment]
fixed , hence closing this  issue, please feel free to open another one if you feel the build is still broken
