### ISSUE TITLE
Stash failed to obtain commits

### ISSUE THREAD

**Issue by naccarati** [capitalone/Hygieia#674]
I'm trying to configure the stash collector, but I'm getting this same problem everytime:

Docker compose log:

**2016-07-06 11:39:40,104 INFO  c.c.d.collector.CollectorTask - Repo Count              1       40s
2016-07-06 11:39:40,104 INFO  c.c.d.collector.CollectorTask - New Commits             0       40s
2016-07-06 11:39:40,104 INFO  c.c.d.collector.CollectorTask - Finished                        40s
2016-07-06 11:40:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2016-07-06 11:40:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-06 11:40:00,003 INFO  c.c.d.collector.CollectorTask - Starting...
2016-07-06 11:40:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-06 11:40:40,051 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from STASH-REPO-HERE/commits?until=master&limit=300
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "STASH-REPO-HEREcommits?until=master&limit=300":stash.uol.intranet: unknown error; nested exception is java.net.UnknownHostException: stash.uol.intranet: unknown error
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:223) ~[bitbucket-scm-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:88) ~[bitbucket-scm-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:132) [bitbucket-scm-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.net.UnknownHostException: stash.uol.intranet: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_91]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_91]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_91]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_91]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_91]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_91]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44) ~[httpclient-4.3.6.jar!/:4.3.6]
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:102) ~[httpclient-4.3.6.jar!/:4.3.6]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319) ~[httpclient-4.3.6.jar!/:4.3.6]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363) ~[httpclient-4.3.6.jar!/:4.3.6]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219) ~[httpclient-4.3.6.jar!/:4.3.6]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195) ~[httpclient-4.3.6.jar!/:4.3.6]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86) ~[httpclient-4.3.6.jar!/:4.3.6]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[httpclient-4.3.6.jar!/:4.3.6]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.3.6.jar!/:4.3.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.3.6.jar!/:4.3.6]
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:569) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	... 15 common frames omitted**
________________________________________________________________________
Anyone know what is wrong?

**Comment by MarkRx** [comment]
Caused by: java.net.UnknownHostException

Are you sure your configuration is correct? Can you hit the REST api directly? What version of Bitbucket server are you running?

Example:
```
git.host=http://my.stash.com/
git.api=/rest/api/1.0/
```

https://my.stash.com/rest/api/1.0/projects/myproject/repos/myrepo/commits?until=master&limit=300

**Comment by naccarati** [comment]
MarkRx

Yes, if I put the query on the logs direct on the browser, it return what its supposed to return.

**Comment by MarkRx** [comment]
Do you need to configure it to work through a proxy perhaps?

If running on a docker image in a vagrant linux vm see if you can curl the url from the host machine. Based on the exception it seems to be due to some kind of networking or DNS configuration.

**Comment by satishc1** [comment]
@naccarati Is this still an issue ? If not please close.

**Comment by satishc1** [comment]
Closed. Reopen if still an issue.
