### ISSUE TITLE
Running mvn clean install from UI directory fails

### ISSUE THREAD

**Issue by charleswisniewski** [capitalone/Hygieia#704]
It looks like there are a lot of unmet dependencies.

I'm fixing the package.json file right now, has anyone else noticed this?

**Comment by tabladrum** [comment]
I did not see unmet dependencies other than version upgrades etc. Can you paste the log?

**Comment by charleswisniewski** [comment]
```
charles$ mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:UI 2.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UI ---
[INFO] 
[INFO] >>> maven-pmd-plugin:3.6:check (default) > :pmd @ UI >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ UI ---
[INFO] 
[INFO] <<< maven-pmd-plugin:3.6:check (default) < :pmd @ UI <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.6:check (default) @ UI ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:prepare-agent (default) @ UI ---
[INFO] argLine set to -javaagent:/Users/charles/.m2/repository/org/jacoco/org.jacoco.agent/0.7.6.201602180812/org.jacoco.agent-0.7.6.201602180812-runtime.jar=destfile=/Users/charles/dev/Hygieia/UI/target/jacoco.exec
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) @ UI ---
[INFO] Found proxies: []
[INFO] Node v5.4.1 is already installed.
[INFO] NPM 2.14.15 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.29:npm (npm install) @ UI ---
[INFO] Found proxies: []
[INFO] Running 'npm install' in /Users/charles/dev/Hygieia/UI
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp requires semver@'^4.1.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/semver,
[ERROR] npm WARN unmet dependency which is version 5.3.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/wiredep requires glob@'^4.0.5' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/glob,
[ERROR] npm WARN unmet dependency which is version 6.0.4
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-css-globbing requires glob@'^4.0.5' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/glob,
[ERROR] npm WARN unmet dependency which is version 6.0.4
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-csso requires gulp-util@'~2.2.14' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-util,
[ERROR] npm WARN unmet dependency which is version 3.0.7
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-ng-annotate requires gulp-util@'^2.2.14' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-util,
[ERROR] npm WARN unmet dependency which is version 3.0.7
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-useref requires glob@'^4.0.2' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/glob,
[ERROR] npm WARN unmet dependency which is version 6.0.4
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/main-bower-files requires glob@'^4.0.3' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/glob,
[ERROR] npm WARN unmet dependency which is version 6.0.4
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/browser-sync requires dev-ip@'^0.1.7' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/dev-ip,
[ERROR] npm WARN unmet dependency which is version 1.0.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/karma requires glob@'^7.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/glob,
[ERROR] npm WARN unmet dependency which is version 6.0.4
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/karma requires http-proxy@'^1.13.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/http-proxy,
[ERROR] npm WARN unmet dependency which is version 1.7.3
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/protractor requires glob@'~3.2' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/glob,
[ERROR] npm WARN unmet dependency which is version 6.0.4
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk/node_modules/has-ansi requires ansi-regex@'^0.2.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/ansi-regex,
[ERROR] npm WARN unmet dependency which is version 2.0.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk/node_modules/strip-ansi requires ansi-regex@'^0.2.1' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/ansi-regex,
[ERROR] npm WARN unmet dependency which is version 2.0.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-clean-css/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-clean-css/node_modules/gulp-util requires object-assign@'^3.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-clean-css/node_modules/object-assign,
[ERROR] npm WARN unmet dependency which is version 4.1.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/del/node_modules/globby requires glob@'^4.0.2' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/glob,
[ERROR] npm WARN unmet dependency which is version 6.0.4
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/del/node_modules/rimraf requires glob@'^7.0.5' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/glob,
[ERROR] npm WARN unmet dependency which is version 6.0.4
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-angular-templatecache/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-concat/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-concat/node_modules/gulp-util requires through2@'^2.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-concat/node_modules/through2,
[ERROR] npm WARN unmet dependency which is version 0.6.5
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-autoprefixer/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-autoprefixer/node_modules/gulp-util requires object-assign@'^3.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-autoprefixer/node_modules/object-assign,
[ERROR] npm WARN unmet dependency which is version 1.0.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-autoprefixer/node_modules/gulp-util requires through2@'^2.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-autoprefixer/node_modules/through2,
[ERROR] npm WARN unmet dependency which is version 0.6.5
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-filter/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-filter/node_modules/gulp-util requires through2@'^2.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-filter/node_modules/through2,
[ERROR] npm WARN unmet dependency which is version 0.6.5
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-inject/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-karma/node_modules/optimist requires minimist@'~0.0.1' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/minimist,
[ERROR] npm WARN unmet dependency which is version 1.2.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-karma/node_modules/gulp-util requires minimist@'^0.2.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/minimist,
[ERROR] npm WARN unmet dependency which is version 1.2.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-load-plugins/node_modules/findup-sync requires glob@'~3.2.9' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/glob,
[ERROR] npm WARN unmet dependency which is version 6.0.4
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-watch/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-watch/node_modules/gulp-util requires object-assign@'^3.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-watch/node_modules/object-assign,
[ERROR] npm WARN unmet dependency which is version 4.1.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-watch/node_modules/vinyl-file requires vinyl@'^1.1.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-watch/node_modules/vinyl,
[ERROR] npm WARN unmet dependency which is version 0.5.3
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/less-plugin-glob/node_modules/globby requires glob@'^5.0.3' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/glob,
[ERROR] npm WARN unmet dependency which is version 6.0.4
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/run-sequence/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-htmlmin/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-htmlmin/node_modules/gulp-util requires object-assign@'^3.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-htmlmin/node_modules/object-assign,
[ERROR] npm WARN unmet dependency which is version 4.1.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-imagemin/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-imagemin/node_modules/gulp-util requires object-assign@'^3.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-imagemin/node_modules/object-assign,
[ERROR] npm WARN unmet dependency which is version 2.1.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-yaml/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-flatten/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-flatten/node_modules/gulp-util requires through2@'^2.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-flatten/node_modules/through2,
[ERROR] npm WARN unmet dependency which is version 0.6.5
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-clean/node_modules/gulp-util requires minimist@'^0.2.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/minimist,
[ERROR] npm WARN unmet dependency which is version 1.2.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-clean/node_modules/gulp-util requires through2@'^0.5.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-clean/node_modules/through2,
[ERROR] npm WARN unmet dependency which is version 0.4.2
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-rev/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-rev/node_modules/gulp-util requires object-assign@'^3.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-rev/node_modules/object-assign,
[ERROR] npm WARN unmet dependency which is version 1.0.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-rev/node_modules/gulp-util requires through2@'^2.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-rev/node_modules/through2,
[ERROR] npm WARN unmet dependency which is version 0.6.5
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-rev-replace/node_modules/gulp-util requires minimist@'^0.2.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/minimist,
[ERROR] npm WARN unmet dependency which is version 1.2.0
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-rev-replace/node_modules/gulp-util requires through2@'^0.5.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-rev-replace/node_modules/through2,
[ERROR] npm WARN unmet dependency which is version 0.4.2
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-size/node_modules/gulp-util requires chalk@'^1.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/chalk,
[ERROR] npm WARN unmet dependency which is version 0.5.1
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-size/node_modules/gulp-util requires through2@'^2.0.0' but will load
[ERROR] npm WARN unmet dependency /Users/charles/dev/Hygieia/UI/node_modules/gulp-size/node_modules/through2,
[ERROR] npm WARN unmet dependency which is version 0.6.5
[INFO] dev-ip@1.0.1 node_modules/dev-ip
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.29:bower (bower install) @ UI ---
[INFO] Found proxies: []
[INFO] Running 'bower install' in /Users/charles/dev/Hygieia/UI
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.29:gulp (gulp build) @ UI ---
[INFO] Running 'gulp.js build' in /Users/charles/dev/Hygieia/UI
[ERROR] module.js:327
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module 'opn'
[ERROR]     at Function.Module._resolveFilename (module.js:325:15)
[ERROR]     at Function.Module._load (module.js:276:25)
[ERROR]     at Module.require (module.js:353:17)
[ERROR]     at require (internal/module.js:12:17)
[ERROR]     at Object.<anonymous> (/Users/charles/dev/Hygieia/UI/node_modules/browser-sync/lib/utils.js:4:19)
[ERROR]     at Module._compile (module.js:397:26)
[ERROR]     at Object.Module._extensions..js (module.js:404:10)
[ERROR]     at Module.load (module.js:343:32)
[ERROR]     at Function.Module._load (module.js:300:12)
[ERROR]     at Module.require (module.js:353:17)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.027 s
[INFO] Finished at: 2016-07-18T12:56:50-04:00
[INFO] Final Memory: 20M/311M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:gulp (gulp build) on project UI: Failed to run task: 'gulp.js build' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Got the same while trying to just run npm install

**Comment by tabladrum** [comment]
I am running node version:
$ node --version
v4.1.1

**Comment by charleswisniewski** [comment]
v5.2.0 here

**Comment by charleswisniewski** [comment]
running npm install worked, running it through the maven frontend plugin failed.
I've had mixed results using maven frontend plugin, re-titling this issue to match the original issue

**Comment by rohitstatic** [comment]
Running sulp serve I get the following error.

Error: Cannot find module 'dev-ip'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\mmt6407\Hygieia\UI\node_modules\browser-sync\lib\utils.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

I am running node version 4.4.7

**Comment by amitmawkin** [comment]
@charleswisniewski please open a new one , I am closing this due to no activity
