### ISSUE TITLE
jira-feature-collector -- Error

### ISSUE THREAD

**Issue by dinukool** [capitalone/Hygieia#783]
```
2016-08-31 14:45:00,013 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-08-31 14:45:00,014 INFO  c.c.d.collector.CollectorTask - https://MYJIRA.com/
2016-08-31 14:45:00,014 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-08-31 14:45:00,601 ERROR c.c.d.client.DefaultJiraClient - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(403), errorCollections=[]}
```
```properties
#Jira Connection Details

feature.jiraBaseUrl=https://MYJIRA.com/
feature.jiraQueryEndpoint=secure/RapidBoard.jspa?rapidView=491&view=planning&selectedIssue=TST-137&versions=visible
feature.jiraCredentials=XXXXXXXXXXWWWWWWWW=

#OAuth2.0 token credentials (currently not supported in this version)
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

feature.deltaCollectorItemStartDate=2016-06-01T00:00:00.000000
feature.deltaStartDate=2016-06-01T00:00:00.000000
feature.masterStartDate=2016-06-01T00:00:00.000000

#feature.jiraIssueTypeId=Story
#feature.jiraSprintDataFieldName=customfield_10017
#feature.jiraEpicIdFieldName=customfield_10018

#In-built folder housing prepared REST queries (required)
feature.queryFolder=jiraapi-queries

#Jira API Query file names (String template requires the files to have .st extension) (required)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done
#[{...name:"In Progress"...},{... name: "Done" ...},{... name: "To Do" ...}]
```
@tabladrum Looking for your help
@c-sreenivasulareddy @amitmawkin

Thanks in Advance!

**Comment by MarkRx** [comment]
403 is forbidden. It could be that the user you are using does not have access to the rest API. I've also seen this returned when the CAPTCHA response is triggered. If that is the case log out and back in in a browser.

**Comment by dinukool** [comment]
Via web browser my credentials works fine on JIRA portal

**Comment by MarkRx** [comment]
make sure the base64 credentials you created are correct and do not have a newline.

echo -n user:password | base64

**Comment by dinukool** [comment]
Thanks Now I'm able to see it connects to JIRA issues resolved fixing redo base64 encryption
but it displays as KANBAN how to change it to Sprint ?

**Comment by MarkRx** [comment]
See #678 

By default it is treating stories that do not have sprints associated to them (thus in the backlog) as being in a KANBAN sprint.

**Comment by dinukool** [comment]
How to change this to Sprint details on Hygieia end

**Comment by dinukool** [comment]
![image](https://cloud.githubusercontent.com/assets/21200506/18395606/18d9719c-768d-11e6-963a-6334a8248b08.png)

Nothings displays under FEATURES IN PROGRESS also.

How to change it to Sprint like below shown o/p.

![image](https://cloud.githubusercontent.com/assets/21200506/18395677/7cd53d02-768d-11e6-8dcf-6d8cf5f8a07f.png)

Need your help @amp5208 @MarkRx

**Comment by MarkRx** [comment]
You mustn't have sprints setup in jira or properly configured in your config file.

In your file you mentioned these shouldn't be commented out:

> #feature.jiraIssueTypeId=Story
> #feature.jiraSprintDataFieldName=customfield_10017
> #feature.jiraEpicIdFieldName=customfield_10018

You also need
feature.jiraStoryPointsFieldName

Ensure those fields are properly set.

**Comment by dinukool** [comment]
#feature.jiraSprintDataFieldName= **Where/How to find these values in JIRA. Need your help @amp5208 @MarkRx**

#feature.jiraEpicIdFieldName=
You also need
feature.jiraStoryPointsFieldName

**Comment by MarkRx** [comment]
fields are documented here:
https://github.com/capitalone/Hygieia/blob/master/collectors/feature/jira/README.md

**Comment by dinukool** [comment]
Still Values are Zero any idea?
![image](https://cloud.githubusercontent.com/assets/21200506/18564876/85603e90-7b5b-11e6-817c-f8fc91da6c30.png)

**Comment by dinukool** [comment]
@MarkRx
app.prop

feature.pageSize=50
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
#feature.jiraProxyUrl=
#feature.jiraProxyPort=
######################
feature.sprintDays=60
feature.sprintEndPrior=7
######################
feature.scheduledPriorMin=2
feature.deltaCollectorItemStartDate=2016-06-01T00:00:00.000000
spring.data.mongodb.database=dashboard
spring.data.mongodb.host=10.234.15.229
spring.data.mongodb.port=27017
spring.data.mongodb.username=db
spring.data.mongodb.password=dbpass
feature.jiraBaseUrl=http://myjira.com:8080/
feature.jiraCredentials=ZGV2r3BzXXXXdm9w0w==
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
feature.jiraIssueTypeId=Story

feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10001

feature.cron=0 * * * * *
feature.deltaStartDate=2016-06-01T00:00:00.000000
feature.masterStartDate=2016-06-01T00:00:00.000000

feature.todoStatuses[0]=Open
feature.todoStatuses[1]=Groom
feature.todoStatuses[2]=Selected for Development
feature.todoStatuses[3]=Backlog
feature.todoStatuses[4]=Grooming
feature.todoStatuses[5]=ToDo
feature.todoStatuses[6]=To Do
feature.todoStatuses[6]=Backlog1
feature.doingStatuses[0]=Validation
feature.doingStatuses[1]=Test
feature.doingStatuses[2]=In Process
feature.doingStatuses[3]=In Progress
feature.doingStatuses[4]=Awaiting Approval - 2
feature.doingStatuses[5]=Change Request - 2
feature.doneStatuses[0]=Awaiting Approval
feature.doneStatuses[1]=Done
feature.doneStatuses[2]=Resolved

@amp5208 looking for your help

**Comment by oshingc** [comment]
@MarkRx 
I also don't have Jira working:

My properties is:

# dashboard.properties
# dashboard.properties
dbhost=localhost
dbport=27017
dbname=dashboard
dbusername=dashboard
dbpassword=dashboard
server.port: ${PORT:0}
#Collector schedule (required)
feature.cron=0 0/10 * * * *
#Page size for data calls (Jira maxes at 1000)
feature.pageSize=50

#In-built folder housing prepared REST queries (required)
feature.queryFolder=jiraapi-queries

#Jira API Query file names (String template requires the files to have .st extension) (required)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

#Jira Connection Details
feature.jiraProxyUrl=
feature.jiraProxyPort=

# Trending Query:  Number of days in a sprint (not-required)
feature.sprintDays=30
# Trending Query:  Length of sprint week (not-required)
feature.sprintEndPrior=7

#Scheduled Job prior minutes to recover data created during execution time (usually, 2 minutes is enough)
feature.scheduledPriorMin=2

#Delta change date that modulates the collector item task - should be about as far back as possible, in ISO format (required)
feature.deltaCollectorItemStartDate=2016-08-01T00:00:00.000000


#Jira Connection Details
feature.jiraBaseUrl=https://onejira.verizon.com/
#feature.jiraBaseUrl=https://onejira.verizon.com/
feature.jiraQueryEndpoint=rest/api/2/
#64-bit encoded credentials with the pattern username:password


#Convert above username:password into e64 bit string

#Mandatory
feature.jiraCredentials=Z29tbWEzNToxMjNxd2UpKWd0
###
#OAuth2.0 token credentials (currently not supported in this version)
#feature.jiraOauthAuthtoken=
#feature.jiraOauthRefreshtoken=
#feature.jiraOauthRedirecturi=
#feature.jiraOauthExpiretime=


#Mandatory
# In Jira, this is your project or team
feature.jiraProjectId=VGROE
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a numerical ID reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType ID
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
feature.jiraIssueTypeId=10001
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name <em>com.atlassian.greenhopper.service.sprint.Sprint</em>;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10005
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10006



#Start dates from which to begin collector data, if no other data is present - usually, a month back is appropriate (required)
feature.deltaStartDate=2016-08-01T00:00:00.000000
feature.masterStartDate=2016-08-01T00:00:00.000000

logging.level.com.atlassian.jira=INFO
logging.level.com.capitalone.dashboard=DEBUG
logging.level.com.capitalone.dashboard.collector=DEBUG

feature.todoStatuses[0]=ToDo
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done

feature.jiraStoryPointsFieldName=customfield_10002




My error printed is:

2016-10-16 17:20:00,028 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-10-16 17:20:00,041 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-10-16 17:20:50,436 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1108
2016-10-16 17:20:57,253 INFO  c.c.d.collector.CollectorTask - Team Data            1108       57s
2016-10-16 17:20:57,258 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-10-16 17:21:56,479 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1108
2016-10-16 17:21:59,183 INFO  c.c.d.collector.CollectorTask - Project Data         1108       61s
2016-10-16 17:21:59,196 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2016-10-16 17:22:08,616 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2016-10-16 17:23:39,705 ERROR o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-3 [CLOSED] HTTP protocol exception: null
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257) ~[na:1.8.0_101]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300) ~[na:1.8.0_101]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSLIOSession.java:340) ~[httpcore-nio-4.2.2.jar:4.2.2]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:366) ~[httpcore-nio-4.2.2.jar:4.2.2]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:118) ~[httpcore-nio-4.2.2.jar:4.2.2]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:220) [httpcore-nio-4.2.2.jar:4.2.2]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:284) [httpcore-nio-4.2.2.jar:4.2.2]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106) [httpcore-nio-4.2.2.jar:4.2.2]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:604) [httpcore-nio-4.2.2.jar:4.2.2]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by MarkRx** [comment]
@dinukool you need to set feature.jiraStoryPointsFieldName if you want to use story points. The UI is configurable to use story points or hours with the latest code.

@oshingc commented @ #901

**Comment by oshingc** [comment]
In case this help, now I have my Jira working.

This is my properties:

`
dbhost=localhost
dbport=27017
dbname=vzrealtime1
dbusername=vzrealtime1
dbpassword=vzrealtime1
server.port: ${PORT:0}
feature.cron=0 0/10 * * * *
feature.pageSize=25
feature.queryFolder=jiraapi-queries

feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

feature.jiraProxyUrl=
feature.jiraProxyPort=
feature.sprintDays=30
feature.sprintEndPrior=7
feature.scheduledPriorMin=2
feature.deltaCollectorItemStartDate=2016-08-01T00:00:00.000000
feature.jiraBaseUrl=https://myjira.company.com/
feature.jiraQueryEndpoint=rest/api/2/

feature.jiraCredentials=myencodeduser:passto64bits
feature.jiraProjectId=11306
feature.jiraIssueTypeId=Story
feature.jiraSprintDataFieldName=customfield_10005
feature.jiraEpicIdFieldName=customfield_10006

feature.deltaStartDate=2016-08-01T00:00:00.000000
feature.masterStartDate=2016-08-01T00:00:00.000000

logging.level.com.atlassian.jira=INFO
logging.level.com.capitalone.dashboard=DEBUG
logging.level.com.capitalone.dashboard.collector=DEBUG

feature.todoStatuses[0]=ToDo
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done

feature.jiraStoryPointsFieldName=customfield_10002
`

**Comment by dinukool** [comment]
resolved thanks!

**Comment by smlcodes** [comment]
## Im getting below issue, their is no CAPTHA Isuue
`Query : key in (0.0,1.0,13.0,2.0,3.0,4.0,5.0,20.0,8.0)
2017-05-09 13:14:08,020 ERROR c.c.d.client.DefaultJiraClient - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={}, errorMessages=[The issue key '0.0' for field 'key' is invalid., The issue key '1.0' for field 'key' is invalid., The issue key '13.0' for field 'key' is invalid., The issue key '2.0' for field 'key' is invalid., The issue key '20.0' for field 'key' is invalid., The issue key '3.0' for field 'key' is invalid., The issue key '4.0' for field 'key' is invalid., The issue key '5.0' for field 'key' is invalid., The issue key '8.0' for field 'key' is invalid.]}]}
RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={}, errorMessages=[The issue key '0.0' for field 'key' is invalid., The issue key '1.0' for field 'key' is invalid., The issue key '13.0' for field 'key' is invalid., The issue key '2.0' for field 'key' is invalid., The issue key '20.0' for field 'key' is invalid., The issue key '3.0' for field 'key' is invalid., The issue key '4.0' for field 'key' is invalid., The issue key '5.0' for field 'key' is invalid., The issue key '8.0' for field 'key' is invalid.]}]}
	at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.claim(DelegatingPromise.java:47)
	at com.capitalone.dashboard.client.DefaultJiraClient.getEpics(DefaultJiraClient.java:294)
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.loadEpicData(StoryDataClientImpl.java:652)
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateMongoInfo(StoryDataClientImpl.java:260)
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:167)
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:125)
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:1)
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`
