### ISSUE TITLE
Data not reflecting in Jira widget

### ISSUE THREAD

**Issue by vikasm47** [capitalone/Hygieia#791]
Hi, I am not able to see Jira in Dashboard, Please find the screen shot and detailed logs and properties file I am using here.
Logs:-
++++++++++
2016-09-06 06:39:17,447 INFO  com.capitalone.dashboard.Application - Started Application in 13.585 seconds (J
M running for 15.824)
2016-09-06 06:40:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-09-06 06:40:00,017 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-09-06 06:40:00,017 INFO  c.c.d.collector.CollectorTask - https://reside.jira.com/
2016-09-06 06:40:00,025 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-09-06 06:40:02,795 INFO  c.c.d.collector.CollectorTask - Team Data               1        2s
2016-09-06 06:40:03,271 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-09-06 06:40:04,043 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-09-06 06:40:04,044 INFO  c.c.d.collector.CollectorTask - Finished                         4s
2016-09-06 06:41:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-09-06 06:41:00,005 INFO  c.c.d.collector.CollectorTask - -----------------------------------
+++++++++++++++++++++++++++++++++
Properties file:-
+++++++++++
feature.pageSize=50
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
#feature.jiraProxyUrl=
#feature.jiraProxyPort=
######################
feature.sprintDays=60
feature.sprintEndPrior=7
######################
feature.scheduledPriorMin=2
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000
spring.data.mongodb.database=dashboarddb
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.username=dashboarduser
spring.data.mongodb.password=1qazxSw2
feature.jiraBaseUrl=https://reside.jira.com/
#feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=************************
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
feature.jiraIssueTypeId=Story
feature.jiraSprintDataFieldName=customfield_100013
feature.jiraEpicIdFieldName=customfield_11243
feature.cron=0 * * * * *
feature.deltaStartDate=2015-03-01T00:00:00.000000
feature.masterStartDate=2008-01-01T00:00:00.000000
![jiraissue](https://cloud.githubusercontent.com/assets/21235049/18264205/8db68940-742c-11e6-826d-5d28625ebf32.PNG)
feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done

**Comment by vikasm47** [comment]
@amp5208 @MarkRx : Can you please help me to resolve this issue.
Thanks !

**Comment by vikasm47** [comment]
@amitmawkin

**Comment by raynaya** [comment]
whats the db name where the data is getting stored ? check looks like the db name has been changed in the code to dashboarddb. change your db name in api collector it will work

**Comment by vikasm47** [comment]
We already have dashboarddb. Where you are asking to make changes inside api collector folder ?

**Comment by raynaya** [comment]
which db does your api endpoint talk to ? The data is fetched by the api.  I had this issue and my api endpoint was talking to "dashboard".  The name should be in dashboard.properties file. If you are using docker it should be inside Dockerfile .

**Comment by vikasm47** [comment]
yes and it is dashboarddb only which i've mentioned in dashboard.properties file.
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=*******
dbhost=127.0.0.1
dbport=27017
server.contextPath=/api
server.port=8080

**Comment by raynaya** [comment]
ok .. can you check if the data is getting stored in the collection called feature in that db ?

**Comment by vikasm47** [comment]
Hi, inside C:\data\db i've created database dashboarddb and there is no such file or folder available for feature
![capture](https://cloud.githubusercontent.com/assets/21235049/18309379/cfa0cb00-7516-11e6-8dfd-33ccfb5ff027.PNG)

**Comment by raynaya** [comment]
Use something like robomongo. You cant see collections like this.

**Comment by vikasm47** [comment]
no data is not getting stored into db i think
![capture](https://cloud.githubusercontent.com/assets/21235049/18310763/07fe96ce-751e-11e6-87df-2f538b8d4e63.PNG)

**Comment by raynaya** [comment]
Check the collection named feature that is where jira details are stored. .. if not that will explain why you dont see anything  .. Then for some reason your collector is not storing in the correct db.. I would suggest to take a pull from master and then check all the config files and run the collector again

**Comment by vikasm47** [comment]
Didn't got "I would suggest to take a pull from master and then check all the config files and run the collector again ". Inside application.properties file of jira collector I've provided all the details as you can see, what else we can to do to get the data into database ?

**Comment by raynaya** [comment]
take a pull ( check with the latest code ) ... I see lot of commits in last one day

**Comment by RevaSawant** [comment]
@raynaya , you mean to take latest version of Hygieia-Master.zip ?

**Comment by raynaya** [comment]
If thats how you plan to get the new changes from this repo, then yes take the latest zipped code.

**Comment by vikasm47** [comment]
@raynaya , Hi Shamik, still I am not able to get the jira data into database, I have provided all the info in prop file

**Comment by vikasm47** [comment]
Hi @raynaya, I am able to jira project details into dashboard but it is displaying no values, plz find below screenshot and logs
![capture](https://cloud.githubusercontent.com/assets/21235049/18466685/4d490bd8-79ba-11e6-9f15-a41dcb734624.PNG)
logs are:- 
2016-09-13 07:10:08,004 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-09-13 07:10:08,014 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-09-13 07:10:08,014 INFO  c.c.d.collector.CollectorTask - https://reside.jira.com/
2016-09-13 07:10:08,015 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-09-13 07:10:08,473 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-09-13 07:10:08,937 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-09-13 07:10:09,736 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: https://reside.jira.com/rest/api/2/issuetype/status/
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_102]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_102]
        at java.net.URLConnection.getContent(Unknown Source) ~[na:1.8.0_102]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(Unknown Source) ~[na:1.8.0_102]
        at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:267) ~[ji
ra-feature-collector.jar!/:2.0.2-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:6
86) [jira-feature-collector.jar!/:2.0.2-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImp
l.java:147) [jira-feature-collector.jar!/:2.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jir
a-feature-collector.jar!/:2.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira
-feature-collector.jar!/:2.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.2-SNAPSHOT.ja
r!/:2.0.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingR
unnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [s
pring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_102]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na
:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_
102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_102]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_102]
2016-09-13 07:10:10,191 INFO  c.c.d.collector.CollectorTask - Story Data              0        1s
2016-09-13 07:10:10,192 INFO  c.c.d.collector.CollectorTask - Finished                         2s
2016-09-13 07:10:11,491 INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context
.annotation.AnnotationConfigApplicationContext@461fbca5: startup date [Tue Sep 13 07:09:43 UTC 2016]; root of
context hierarchy
2016-09-13 07:10:11,496 INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2016-09-13 07:10:11,524 INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'

**Comment by vikasm47** [comment]
@raynaya , @amp5208 : Hi, I am getting project name in feature settings of dashboard now, but not able to gather any info. screenshot for reference is
![capture](https://cloud.githubusercontent.com/assets/21235049/18501042/1fa075c0-7a6b-11e6-8de6-1912b4adc442.PNG)

logs are:- 
2016-09-13 15:03:00,007 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-09-13 15:03:00,130 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-09-13 15:03:00,139 INFO  c.c.d.collector.CollectorTask - https://reside.jira.com
2016-09-13 15:03:00,148 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-09-13 15:03:00,710 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-09-13 15:03:01,151 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-09-13 15:03:01,160 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:237) ~[jira-feature-collector.jar!/:2.0.2-SNAPSHOT]
   at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:6
86) ~[jira-feature-collector.jar!/:2.0.2-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImp
l.java:147) ~[jira-feature-collector.jar!/:2.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jir
a-feature-collector.jar!/:2.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira
-feature-collector.jar!/:2.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.2-SNAPSHOT.ja
r!/:2.0.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingR
unnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [s
pring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_102]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na
:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_
102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_102]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_102]

application.properties file parameters are:- 
feature.jiraIssueTypeId=Story
feature.jiraSprintDataFieldName=customfield_10740
feature.jiraEpicIdFieldName=customfield_11241

Can you please help to resolve this.

**Comment by MarkRx** [comment]
You need this in your configuration: 

> feature.jiraQueryEndpoint=rest/api/2/

**Comment by RevaSawant** [comment]
@MarkRx , yes that was a miss. After adding that we are getting screen
console log as follows , can you please help us to get data.

2016-09-14 12:43:04,007 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-09-14 12:43:04,017 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-09-14 12:43:04,023 INFO  c.c.d.collector.CollectorTask - https://reside.jira.com
2016-09-14 12:43:04,028 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-09-14 12:43:04,449 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-09-14 12:43:04,859 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-09-14 12:43:05,631 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-09-14 12:43:05,640 INFO  c.c.d.collector.CollectorTask - Finished                         1s


![image](https://cloud.githubusercontent.com/assets/19944547/18512517/24a80da8-7aa7-11e6-96d6-cc01e95990a4.png)

**Comment by vikasm47** [comment]
We are able to see data in Robomongo as well, but it is not reflecting into feature dashboard.

**Comment by MarkRx** [comment]
Something is not configured correctly. A healthy feature document will look something like this:

```
{
    "_id" : ObjectId("57d0521d4cedfd0011f88894"),
    "_class" : "com.capitalone.dashboard.model.Feature",
    "collectorId" : ObjectId("57d050004cedfd0013bcaaad"),
    "sId" : "197930",
    "sNumber" : "TAXSDLC-937",
    "sName" : "my story description",
    "sStatus" : "Backlog",
    "sState" : "Backlog",
    "sEstimate" : "3",
    "sEstimateTime" : 720,
    "changeDate" : "2016-09-06T19:01:10.0000000",
    "isDeleted" : "False",
    "sOwnersID" : [],
    "sOwnersIsDeleted" : [],
    "sOwnersChangeDate" : [],
    "sOwnersState" : [ 
        "Active"
    ],
    "sOwnersUsername" : [],
    "sOwnersFullName" : [],
    "sOwnersShortName" : [],
    "sTeamIsDeleted" : "False",
    "sTeamAssetState" : "",
    "sTeamChangeDate" : "",
    "sTeamName" : "Tax SDLC",
    "sTeamID" : "12420",
    "sSprintIsDeleted" : "False",
    "sSprintChangeDate" : "",
    "sSprintAssetState" : "ACTIVE",
    "sSprintEndDate" : "2016-09-20T06:21:00.0000000",
    "sSprintBeginDate" : "2016-09-06T19:21:39.2490000",
    "sSprintName" : "Sprint 24",
    "sSprintID" : "2837",
    "sEpicIsDeleted" : "False",
    "sEpicChangeDate" : "",
    "sEpicAssetState" : "In Progress",
    "sEpicType" : "",
    "sEpicEndDate" : "",
    "sEpicBeginDate" : "2016-08-08T14:06:45.0000000",
    "sEpicName" : "my epic",
    "sEpicNumber" : "TAXSDLC-849",
    "sEpicID" : "183186",
    "sProjectPath" : "",
    "sProjectIsDeleted" : "False",
    "sProjectState" : "",
    "sProjectChangeDate" : "",
    "sProjectEndDate" : "",
    "sProjectBeginDate" : "",
    "sProjectName" : "Tax SDLC",
    "sProjectID" : "TAXSDLC"
}
```

**Comment by vikasm47** [comment]
We are getting like this, 

{
    "_id" : ObjectId("57da6f29cc380e1bc4d85f8f"),
    "_class" : "com.capitalone.dashboard.model.Feature",
    "collectorId" : ObjectId("57d6a51dcc380e17c0dd7857"),
    "sId" : "178163",
    "sNumber" : "MDEL-10",
    "sName" : "New Marchandise Page ",
    "sStatus" : "Backlog",
    "sState" : "Backlog",
    "sEstimate" : "0",
    "sEstimateTime" : 0,
    "changeDate" : "2016-09-14T13:51:06.0000000",
    "isDeleted" : "False",
    "sOwnersID" : [ 
        "davin.leier"
    ],
    "sOwnersIsDeleted" : [],
    "sOwnersChangeDate" : [],
    "sOwnersState" : [ 
        "Active"
    ],
    "sOwnersUsername" : [ 
        "davin.leier"
    ],
    "sOwnersFullName" : [ 
        "Davin Leier"
    ],
    "sOwnersShortName" : [ 
        "davin.leier"
    ],
    "sTeamIsDeleted" : "False",
    "sTeamAssetState" : "",
    "sTeamChangeDate" : "",
    "sTeamName" : "M360DelTest",
    "sTeamID" : "27820",
    "sSprintIsDeleted" : "False",
    "sSprintChangeDate" : "",
    "sSprintAssetState" : "ACTIVE",
    "sSprintEndDate" : "2016-09-30T06:20:00.0000000",
    "sSprintBeginDate" : "2016-09-04T06:20:20.6890000",
    "sSprintName" : "M360DelT Sprint 1",
    "sSprintID" : "2208",
    "sEpicIsDeleted" : "False",
    "sEpicChangeDate" : "",
    "sEpicAssetState" : "",
    "sEpicType" : "",
    "sEpicEndDate" : "",
    "sEpicBeginDate" : "",
    "sEpicName" : "",
    "sEpicNumber" : "",
    "sEpicID" : "",
    "sProjectPath" : "",
    "sProjectIsDeleted" : "False",
    "sProjectState" : "",
    "sProjectChangeDate" : "",
    "sProjectEndDate" : "",
    "sProjectBeginDate" : "",
    "sProjectName" : "M360DelTest",
    "sProjectID" : "MDEL"
}

**Comment by MarkRx** [comment]
Number estimates do not show up because your estimate fields are 0:

> "sEstimate" : "0",
> "sEstimateTime" : 0,

This can be because either your feature.jiraStoryPointsFieldName property isn't set correctly or your stories do not have story points on them.

Features in progress do not show up because your epic data is empty:

> "sEpicEndDate" : "",
> "sEpicBeginDate" : "",
> "sEpicName" : "",
> "sEpicNumber" : "",

This can be because either your feature.jiraEpicIdFieldName property isn't set correctly or your stories do not have epics assigned to them.

If these properties have since been updated you will have to trigger an update to get the data in mongo updated. You can either wipe all documents in your feature collection or go into the UI and update something in your stories.

**Comment by dinukool** [comment]
where this feature document (JIRA) can be found and whats the file name for it?

**Comment by vikasm47** [comment]
@MarkRx : Thanks, we are now getting the jira information in feature for both kanban and M360DelT Sprint 1, hence closing this issue.
@dinukool : feature document is created or not you can see from mongo cli by running "show collections" command, and see the data in it you can use Robomongo tool, connect with database you created --> right click on feature collections and click on view documents, you can see all your jira data here.
