### ISSUE TITLE
JIRA status not showing up in Hygieia Dashboard

### ISSUE THREAD

**Issue by anchatho** [capitalone/Hygieia#850]
Hi, 

I am facing issue with JIRA status not showing up in Hygieia dashboard. Look like it is something to do with the application.properties.

In Hygieia only the JIRA Project Name appear when you select that no details will be shown.

Any solution or suggestion would be of great help.

Copied below is the content of the file.
# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutExcepti                                                                                                                     on)

feature.pageSize=100
# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern

feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000
# Chron schedule: S M D M Y [Day of the Week]

 feature.cron=0 \* \* \* \* *
# at 5 minutes every hour every day
# feature.cron=5 \* \* \* \* \* ?
# ST Query File Details - Required, but DO NOT MODIFY

feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.todoStatuses[0]=
feature.doingStatuses[0]=
feature.doneStatuses[0]=
# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
# feature.jiraProxyUrl=http://proxy.com
# feature.jiraProxyUrl=http://9.121.56.74:3128 - Commnented by Anoop
# feature.jiraProxyPort=3128

feature.jiraBaseUrl=http://9.124.119.74:9778/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
# feature.jiraCredentials=dXNlcm5hbWU6cGFzc3dvcmQ=

feature.jiraCredentials=YWRtaW46cGFzc3dvcmQ=
# OAuth is not fully implemented; please blank-out the OAuth values:
# commenting the below values
# feature.jiraOauthAuthtoken=
# feature.jiraOauthRefreshtoken=
# feature.jiraOauthRedirecturi=
# feature.jiraOauthExpiretime=
###### 
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/is                                                                                                                     suetype/
###### 

feature.jiraIssueTypeId=Story
# Details updated by Anoop
# feature.jiraIssueTypeId=Task
# feature.projectQuery=projectinfo
# feature.memberQuery=memberinfo
###### 
# In Jira, your instance will have its own custom field created for "sprint" or                                                                                                                      "timebox" details,
# which includes a list of information.  This field allows you to specify that d                                                                                                                     ata field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field nam                                                                                                                     e
# via the following URI, and look for a package name com.atlassian.greenhopper.s                                                                                                                     ervice.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
###### 

feature.jiraSprintDataFieldName=customfield_10000
###### 
# In Jira, your instance will have its own custom field created for "super story                                                                                                                     " or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that d                                                                                                                     ata field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the f                                                                                                                     ollowing URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custo                                                                                                                     m field name describes the
# epic value you expect to see, and is the only field that does this for a given                                                                                                                      issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
###### 

feature.jiraEpicIdFieldName=customfield_10002
###### 
# In Jira, your instance will have its own custom field created for "story point                                                                                                                     s"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name vi                                                                                                                     a the following URI where your
# queried user story issue has story points set on it; your custom field name de                                                                                                                     scribes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
###### 

feature.jiraStoryPointsFieldName=customfield_10003
###### 
# Internal Status Mappings - THESE SHOULD BE FILLED OUT FOR EVERY CUSTOM STATUS                                                                                                                      VALUE
# IN YOUR JIRA INSTANCE
# 
# Use the following API call to get all of your status mappings:  http://jira.yo                                                                                                                     ur.instance.com/rest/api/2/status/
###### 

feature.todoStatuses[0]=
feature.doingStatuses[0]=
feature.doneStatuses[0]=
# Status mappings, E.g.:
# 

feature.todoStatuses[0]=Open
feature.todoStatuses[1]=Groom
feature.todoStatuses[2]=Selected for Development
feature.todoStatuses[3]=Backlog
feature.todoStatuses[4]=Grooming
feature.todoStatuses[5]=ToDo
feature.todoStatuses[6]=To Do
feature.todoStatuses[6]=Backlog1
feature.doingStatuses[0]=Validation
feature.doingStatuses[1]=Test
feature.doingStatuses[2]=In Process
feature.doingStatuses[3]=In Progress
feature.doingStatuses[4]=Awaiting Approval - 2
feature.doingStatuses[5]=Change Request - 2
feature.doneStatuses[0]=Awaiting Approval
feature.doneStatuses[1]=Done
feature.doneStatuses[2]=Resolved

**Comment by dinukool** [comment]
Make sure you have entered below values correctly from your JIRA instance


feature.jiraStoryPointsFieldName= Enter correct value
feature.jiraEpicIdFieldName=
feature.jiraSprintDataFieldName=customfield_10000

**Comment by fcostanzo-homeaway** [comment]
The documentation in the docker yml file indicates that JIRA_ISSUE_TYPE_ID should be set to the ID of the User Story or Epic IssueType. However, in StoryDataClientImpl.java at line 194 it reads that value into a String issueTypeName, then compares each jira's issue type name against that ID. It never processes feature/sprint/assignee data in the loop. I found this in 2.0.2, but appears to be the same in master.
Changing line 210 to compare against issueType.getId() fixes the problem and jira data appears in the widget.

**Comment by MarkRx** [comment]
The docker-compose.yml documentation is incorrect. It should be something like this:

> #############################################################################
> # In Jira, general IssueType IDs are associated to various "issue"
> # attributes. However, there is one attribute which this collector's
> # queries rely on that change between different instantiations of Jira.
> # Please provide a string name reference to your instance's IssueType for
> # the lowest level of Issues (e.g., "user story") specific to your Jira
> # instance.  Note:  You can retrieve your instance's IssueType Name
> # listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
> #############################################################################
> feature.jiraIssueTypeId=Story

You want feature.jiraIssueTypeId=Story. The property is not named correctly.

**Comment by fcostanzo-homeaway** [comment]
This query doesn't work if I set JIRA_ISSUE_TYPE_ID to the name of the issue type, it returns an empty set.
(story.st)
story(changeDate,issueType) ::= "updatedDate>='$changeDate$' AND issueType='$issueType$' ORDER BY updated ASC"

**Comment by MarkRx** [comment]
What version of jira are you using?

**Comment by fcostanzo-homeaway** [comment]
JIRA v6.4.12

**Comment by anchatho** [comment]
Hi - Finally for a story workitem type I have added the fields like estimation and entering some hours got some data appearing on the dashboard. Attached is the snapshot of the same.

![jira_dashboard_feature](https://cloud.githubusercontent.com/assets/19856681/18910273/de746068-8594-11e6-8d0a-897415c604fe.jpg)

**Comment by ovinzhang** [comment]
@anchatho
hi  
Can you share your JIRA profile with the configuration file, I have been studying this issue lately, and it has been the 0 3
Thanks

**Comment by satishc1** [comment]
Closed. Reopen if you have any problems. Use latest codebase and follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137

**Comment by Clement06** [comment]
Hi Team,

Thanks for your great support and faster help. 

I have configured Jenkins successfully. Thanks again. :)

I am trying to configure Jira , I have launched from my local host and when I launch with the below command, I am getting the error, Please help me to complete my setup :(

Steps Followed:
1. local Jira : https://localhost:8085
2. Launching Jira with the command as: java -jar jira-feature-collector.jar --spring.config.name=jira --spring.config.location=G:\NewLearning\Hygieia-master\collectors\feature\jira\target\application.properties

Error as 

Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)


2017-02-26 00:22:23,224 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teamRepository': Invocation of init method failed; nested exception is org.springframework.data.mapping.PropertyReferenceException: No property teamId found for type Team!
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:736) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
	at com.capitalone.dashboard.Application.main(Application.java:21) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_91]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
Caused by: org.springframework.data.mapping.PropertyReferenceException: No property teamId found for type Team!
	at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:75) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:327) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:307) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:270) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:241) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.repository.query.parser.Part.<init>(Part.java:76) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.repository.query.parser.PartTree$OrPart.<init>(PartTree.java:235) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.repository.query.parser.PartTree$Predicate.buildTree(PartTree.java:373) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.repository.query.parser.PartTree$Predicate.<init>(PartTree.java:353) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.repository.query.parser.PartTree.<init>(PartTree.java:87) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.repository.query.PartTreeMongoQuery.<init>(PartTreeMongoQuery.java:54) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory$MongoQueryLookupStrategy.resolveQuery(MongoRepositoryFactory.java:152) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.<init>(RepositoryFactorySupport.java:408) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:206) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:251) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:237) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean.afterPropertiesSet(MongoRepositoryFactoryBean.java:108) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	... 20 common frames omitted

**Comment by Clement06** [comment]
MVN test is getting success from Jira folder, Below is my application.properties files attached

# Note: The following properties normally do not need to be updated:
feature.sprintDays=30
feature.sprintEndPrior=7
feature.scheduledPriorMin=2
feature.scheduledPriorMin=2
feature.deltaCollectorItemStartDate=2016-01-01T00:00:00.000000
feature.cron=0 * * * * *
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-01-01T00:00:00.000000
feature.pageSize=50
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
; feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
#########################
#Jira Connection Details
feature.jiraProxyUrl=https://localhost:8085
feature.jiraProxyPort=8085
#MongoDB Connection Details
dbname=dashboarddb
dbhost=127.0.0.1
dbport=27017
dbusername=dashboarduser
dbpassword=dbpassword
# Jira Connection Details
feature.jiraBaseUrl=https://localhost:8085
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=Clement==Mypassword
# These should be blank:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
# Only bring in ONE issue type ID
feature.jiraIssueTypeId=Story
feature.jiraSprintDataFieldName=customfield_10001
feature.jiraEpicIdFieldName=customfield_10400
#Core Artifacts
#feature.todoStatuses[0]=Backlog
feature.doingStatuses[0]=In Progress
feature.doingStatuses[0]=To Do
feature.doneStatuses[1]=Done

**Comment by MarkRx** [comment]
@Clement06 please open a new issue instead of using this one as it is closed.
