### ISSUE TITLE
CollectorTaskTests failing

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#870]
I don't get how the Travis build is passing. 

CollectorTask.run() should definitely save twice if enabled. Otherwise it should save once.
```
    public final void run() {
        LOGGER.info("Running Collector: {}", collectorName);
        T collector = getCollectorRepository().findByName(collectorName);
        if (collector == null) {
            // Register new collector
            collector = getCollectorRepository().save(getCollector());
        } else {
            // In case the collector options changed via collectors properties setup.
            // We want to keep the existing collectors ID same as it ties to collector items.
            T newCollector = getCollector();
            newCollector.setId(collector.getId());
            newCollector.setEnabled(collector.isEnabled());
            newCollector.setCollectorType(collector.getCollectorType());
            newCollector.setLastExecuted(collector.getLastExecuted());
            newCollector.setName(collector.getName());
            collector = getCollectorRepository().save(newCollector);
        }

        if (collector.isEnabled()) {
            // Do collection run
            collect(collector);

            // Update lastUpdate timestamp in Collector
            collector.setLastExecuted(System.currentTimeMillis());
            getCollectorRepository().save(collector);
        }
    }
```

```
    @Test
    public void run_enabled() {
    	Collector c = new Collector();
        c.setEnabled(true);
        long prevLastExecuted = c.getLastExecuted();
        when(baseCollectorRepository.findByName(COLLECTOR_NAME)).thenReturn(c);
        when(baseCollectorRepository.save(any(Collector.class))).thenReturn(c);
        task.run();

        assertThat(c.getLastExecuted(), greaterThan(prevLastExecuted));
        verify(baseCollectorRepository, times(1)).save(c);
    }

    @Test
    public void run_disabled() {
    	Collector c =  new Collector();
        c.setEnabled(false);
        when(baseCollectorRepository.findByName(COLLECTOR_NAME)).thenReturn(c);
        when(baseCollectorRepository.save(any(Collector.class))).thenReturn(c);
        task.run();

        verify(baseCollectorRepository, never()).save(c);
    }
```

> Results :
> 
> Failed tests:
>   CollectorTaskTests.run_disabled:64
> baseCollectorRepository.save(
>     com.capitalone.dashboard.model.Collector@1f
> );
> Never wanted here:
> -> at com.capitalone.dashboard.repository.CollectorTaskTests.run_disabled(CollectorTaskTests.java:64)
> But invoked here:
> -> at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:58)
> 
>   CollectorTaskTests.run_enabled:53
> baseCollectorRepository.save(
>     com.capitalone.dashboard.model.Collector@1f
> );
> Wanted 1 time:
> -> at com.capitalone.dashboard.repository.CollectorTaskTests.run_enabled(CollectorTaskTests.java:53)
> But was 2 times. Undesired invocation:
> -> at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:67)
> 
> 
> Tests run: 59, Failures: 2, Errors: 0, Skipped: 1

@tabladrum

**Comment by MarkRx** [comment]
Found it.

So the test is written to verify that save is called with the instance c one time.
`verify(baseCollectorRepository, times(1)).save(c);`

Save is called twice each with different instances. What is probably desired is checking that save is called twice using Mockito.any(Collector.class).

My failure is due to adding hashcode and equals to the BaseModel that is based on the ObjectId. When running junits the ObjectId is null so Collectors have the same hashcode and are equal. As a result it appears that save (c) is called twice since each invocation equality check works out.
