### ISSUE TITLE
Jira Collector - HTTP Protocol Exception - HttpAsyncRequestExecutor http-outgoing-3

### ISSUE THREAD

**Issue by oshingc** [capitalone/Hygieia#901]
Hi guys.
I found this error on Jira Collector, It still failing for me I don't get to have data at feature document in MongoDB.

I added a print from Exception in line 115 of DefaultJiraClient.java as the next image:

![code jira](https://cloud.githubusercontent.com/assets/3100819/19421589/4ea0f7c8-93ca-11e6-9a09-e12882e8a2f3.png)

Here my logs from JIRA COLLECTOR

```
![loggggggp](https://cloud.githubusercontent.com/assets/3100819/19421598/8617e040-93ca-11e6-805a-9f439646e20b.png)
```

And here the FULL JIRA LOG:

```
2016-10-16 17:20:00,041 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-10-16 17:20:50,436 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1108
2016-10-16 17:20:57,253 INFO  c.c.d.collector.CollectorTask - Team Data            1108       57s
2016-10-16 17:20:57,258 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-10-16 17:21:56,479 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1108
2016-10-16 17:21:59,183 INFO  c.c.d.collector.CollectorTask - Project Data         1108       61s
2016-10-16 17:21:59,196 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2016-10-16 17:22:08,616 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2016-10-16 17:23:39,705 ERROR o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-3 [CLOSED] HTTP protocol exception: null
java.nio.channels.ClosedChannelException: null
    at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257) ~[na:1.8.0_101]
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300) ~[na:1.8.0_101]
    at org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSLIOSession.java:340) ~[httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:366) ~[httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:118) ~[httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:220) [httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:284) [httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106) [httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:604) [httpcore-nio-4.2.2.jar:4.2.2]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
2016-10-16 17:23:39,708 ERROR c.c.d.client.DefaultJiraClient - ex exception
java.lang.RuntimeException: java.util.concurrent.TimeoutException
    at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-14.0.jar:na]
    at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:256) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:249) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:276) ~[atlassian-util-concurrent-2.4.0-M9.jar:na]
    at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:272) ~[atlassian-util-concurrent-2.4.0-M9.jar:na]
    at com.atlassian.util.concurrent.Promises$2.onFailure(Promises.java:167) ~[atlassian-util-concurrent-2.4.0-M9.jar:na]
    at com.google.common.util.concurrent.Futures$4.run(Futures.java:1145) ~[guava-14.0.jar:na]
    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293) ~[guava-14.0.jar:na]
    at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150) ~[guava-14.0.jar:na]
    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135) ~[guava-14.0.jar:na]
    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203) ~[guava-14.0.jar:na]
    at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68) ~[guava-14.0.jar:na]
    at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1$3.run(SettableFuturePromiseHttpPromiseAsyncClient.java:73) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:197) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:90) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:192) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: java.util.concurrent.TimeoutException: null
    at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1.doCancelled(SettableFuturePromiseHttpPromiseAsyncClient.java:67) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalContextAwareFutureCallback$3.run(SettableFuturePromiseHttpPromiseAsyncClient.java:152) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:90) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalContextAwareFutureCallback.cancelled(SettableFuturePromiseHttpPromiseAsyncClient.java:147) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at org.apache.http.impl.client.cache.CachingHttpAsyncClient$2.cancelled(CachingHttpAsyncClient.java:636) ~[httpasyncclient-cache-4.0-beta3-atlassian-1.jar:4.2.1-atlassian-2]
    at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:135) ~[httpcore-4.2.1.jar:4.2.1]
    at org.apache.http.impl.nio.client.DefaultResultCallback.cancelled(DefaultResultCallback.java:57) ~[httpasyncclient-4.0-beta3-atlassian-1.jar:4.0-beta3-atlassian-1]
    at org.apache.http.impl.nio.client.DefaultAsyncRequestDirector.cancel(DefaultAsyncRequestDirector.java:533) ~[httpasyncclient-4.0-beta3-atlassian-1.jar:4.0-beta3-atlassian-1]
    at org.apache.http.impl.nio.client.DefaultAsyncRequestDirector$1.abortConnection(DefaultAsyncRequestDirector.java:222) ~[httpasyncclient-4.0-beta3-atlassian-1.jar:4.0-beta3-atlassian-1]
    at org.apache.http.client.methods.HttpRequestBase.cleanup(HttpRequestBase.java:137) ~[httpclient-4.2.1-atlassian-2.jar:4.2.1-atlassian-2]
    at org.apache.http.client.methods.HttpRequestBase.abort(HttpRequestBase.java:151) ~[httpclient-4.2.1-atlassian-2.jar:4.2.1-atlassian-2]
    at com.atlassian.httpclient.base.RequestKiller$RequestEntry.abort(RequestKiller.java:98) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    at com.atlassian.httpclient.base.RequestKiller.run(RequestKiller.java:56) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar:na]
    ... 1 common frames omitted
2016-10-16 17:23:39,710 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 91093 ms
2016-10-16 17:23:39,710 INFO  c.c.d.collector.CollectorTask - Story Data              0      100s
2016-10-16 17:23:39,710 INFO  c.c.d.collector.CollectorTask - Finished                       219s
2016-10-16 17:23:40,707 ERROR o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-3 [CLOSED] HTTP protocol exception: null
java.nio.channels.ClosedChannelException: null
    at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257) ~[na:1.8.0_101]
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300) ~[na:1.8.0_101]
    at org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSLIOSession.java:340) ~[httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:366) ~[httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:118) ~[httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:220) [httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:284) [httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106) [httpcore-nio-4.2.2.jar:4.2.2]
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:604) [httpcore-nio-4.2.2.jar:4.2.2]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
2016-10-16 17:23:41,711 ERROR o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-3 [CLOSED] HTTP protocol exception: null
java.nio.channels.ClosedChannelException: null
```

MY PROPERTIES FILE IS:

``` properties
dbhost=localhost
dbport=27017
dbname=dashboard
dbusername=dashboard
dbpassword=dashboard
server.port: ${PORT:0}
feature.cron=0 0/10 * * * *
feature.pageSize=50

feature.queryFolder=jiraapi-queries

feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

feature.jiraProxyUrl=
feature.jiraProxyPort=

feature.sprintDays=30
feature.sprintEndPrior=7
feature.scheduledPriorMin=2
feature.deltaCollectorItemStartDate=2016-08-01T00:00:00.000000

feature.jiraBaseUrl=https://myjira.company.com/
feature.jiraQueryEndpoint=rest/api/2/

feature.jiraCredentials=Z29tbWEzNToxMjNxl2UpKWd0

feature.jiraProjectId=VGROE
feature.jiraIssueTypeId=10001
feature.jiraSprintDataFieldName=customfield_10005
feature.jiraEpicIdFieldName=customfield_10006


feature.deltaStartDate=2016-08-01T00:00:00.000000
feature.masterStartDate=2016-08-01T00:00:00.000000

logging.level.com.atlassian.jira=INFO
logging.level.com.capitalone.dashboard=DEBUG
logging.level.com.capitalone.dashboard.collector=DEBUG

feature.todoStatuses[0]=ToDo
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done

feature.jiraStoryPointsFieldName=customfield_10002
```

Did anyone had this issue before?

**Comment by MarkRx** [comment]
I see a TimeoutException and seeing that you have over 1000 projects I would image there are a lot of user stories. 

Here are a few things you could try:

- Double check this property. It should be a string despite its name. It needs to be renamed:
> feature.jiraIssueTypeId=Story
- Decrease the page size
- See if you can get a response using http REST. Example: 
> curl -u username:password "https://jira.instance.com/rest/api/2/search?jql=updatedDate%3E%3D%272016-08-01%2019%3A23%27%20AND%20issueType%3D%27Story%27%20ORDER%20BY%20updated%20ASC&fields=*all%2C-comment%2C-watches%2C-worklog%2C-votes%2C-reporter%2C-creator%2C-attachment&maxResults=200&startAt=0"
- See if someone could do some database turning in jira to improve query response time
- Check for network issues

**Comment by satishc1** [comment]
@oshingc @MarkRx  
Another suggestion for 
org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSLIOSession.java:340) ~

Is your jira using a self-signed SSL cert ? Check if your logs have any SSL cert exceptions. Try starting up the jira collector with -Djavax.net.ssl.trustStore=<yourtruststore> where <yourtruststore> is file containing the public key of your cert.
Refer https://github.com/capitalone/Hygieia/issues/335

**Comment by oshingc** [comment]
@MarkRx 
I followed the thre first steps you mentioned and now it's working thanks a lot!
In other hand, I have a question about the third step:

> See if you can get a response using http REST. Example: > curl -u username:password 

> "https://jira.instance.com/rest/api/2/search?jql=updatedDate%3E%3D%272016-08-01%2019%3A23%27%20AND%20issueType%3D%27Story%27%20ORDER%20BY%20updated%20ASC&fields=*all%2C-comment%2C-watches%2C-worklog%2C-votes%2C-reporter%2C-creator%2C-attachment&maxResults=200&startAt=0"

 I wonder why after running curl jira collector worked?
Do I have to run that command always at the beginning of using a JIRA REST API?

Thanks

**Comment by mrpudn** [comment]
The JIRA collector should work if the JIRA API is running - there's no curl-based initialization sequence, as you describe :)

I'm closing this one - feel free to open a new issue if you have a problem collecting the data

**Comment by magma7** [comment]
Can you please advice how to run Jira collector with -Djavax.net.ssl.trustStore= ?
how to put this value? and where?
