### ISSUE TITLE
issue with configuring gitlab for Hygieia

### ISSUE THREAD

**Issue by anchatho** [capitalone/Hygieia#910]
Hi,

We have tried to configure git lab for hygieia but getting the below error

```
2016-10-25 13:45:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2016-10-25 13:45:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-10-25 13:45:00,008 INFO  c.c.d.collector.CollectorTask - Starting...
2016-10-25 13:45:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-10-25 13:45:00,036 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient.normalizeUrl(DefaultGitlabGitClient.java:239) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient.getCommits(DefaultGitlabGitClient.java:68) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collecteur.GitlabGitCollectorTask.collect(GitlabGitCollectorTask.java:76) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

gitlab.properties file is as below

``` properties
#Database Name
dbname=dashboard
#Database HostName - default is localhost
dbhost=IP address
#Database Port - default is 27017
dbport=27017
#Database Username - default is blank
dbusername=db
#Database Password - default is blank
dbpassword=dbpassword
gitlab.cron=0 0/1 * * * *
gitlab.server=https://HOSTNAME.in.team.company.com/
gitlab.branche=master
gitlab.key=7K5zNK2h7x67GddAsKMicFi9yMLKJU
gitlab.saveLog=true
```

Attached is the snapshot of the same.
![gitlab_ui](https://cloud.githubusercontent.com/assets/19856681/19679790/ea0da5f6-9ac0-11e6-945c-f8837b900c28.jpg)

**Comment by rob-miller-777** [comment]
@anchatho We actually ran into similar issues when trying to use the gitlab collector.  It turns out there are quite a few hard coded values throughout the code, and settings that don't get used. I have actually been working on a pretty substantial rewrite of the gitlab collector which I intend to open a pull request for in the coming days that should help you out.  Right now we are going through the process of reviewing the CLA and signing it before we can actually contribute back.  Here is a link to the branch I intend to open a pull request for in case you were interested.  https://github.com/StateFarmIns/Hygieia/tree/gitlabEnhancements

**Comment by xpdable** [comment]
Same here + 1

**Comment by rob-miller-777** [comment]
Just opened #936 which should address most of the issues with this collector.

**Comment by xpdable** [comment]
@rob-miller-777 Thanks it is correctly connected to our GitLab, but meet this error :

2016-11-17 11:38:00,542 INFO  c.c.d.c.DefaultGitlabGitClient - Failed to retrieve data from: https://git.a.b.c.com/api/v3/projects/proj
m%2Fproj1/repository/commits/?ref_name=master&since=2016-11-17T11:28:00Z&per_page=100

However this url works fine directly in my browser. Could you guide to to the correct solution.

BTW, this is a private repo, and I notice that the there is an API Key input in the UI dialog. Could you let me know where I could get it?

**Comment by rob-miller-777** [comment]
To get the API key, just go to your profile settings in Gitlab.  Click the Access Tokens tab, and create a token there.  This token will represent you, so it has access to all private repos that you do.  That seems to be the problem you are having right now.  If that doesn't fix the issue, let me know and we can look at it more.

**Comment by xpdable** [comment]
@rob-miller-777 I get it working by your guidance. Thanks!

**Comment by rob-miller-777** [comment]
No problem, glad I could help!!! Let me know if you run into anything else.

**Comment by marrwa** [comment]
hello , 
i'm trying to run gitlab collector from hygieia application and i've got this bellow error : 
` Failed to retrieve data, the repo or collector is most likey misconfigured: http://root@localhost/gitlab/root/proj3.git, 401 Unauthorized
`
please help 
my applictaion.properties file:

> 
  dbname=dashboard
  dbhost=localhost
  dbport=27017
  dbusername=dashboarduser
  dbpassword=dbpass
  gitlab.cron=0 0/1 * * * *
  gitlab.server=http://localhost/gitlab/
  gitlab.branche=master
  gitlab.saveLog=true
 gitlab.apiToken=FN4K4h6zzRA9sueVxajX
