### ISSUE TITLE
AWS Collector can't find crendetials

### ISSUE THREAD

**Issue by JustLeo** [capitalone/Hygieia#917]
Hello, I have created the Environment Variables (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`) and also I created the profile file under `~/.aws/credentials` but still I getting the following error:
```
2016-10-27 17:10:00.001  INFO 3249 --- [taskScheduler-1] c.c.dashboard.collector.CollectorTask    : Running Collector: AWSCloud
2016-10-27 17:10:00.029  INFO 3249 --- [taskScheduler-1] c.c.dashboard.collector.CollectorTask    : Starting AWS collection...
2016-10-27 17:10:00.029  INFO 3249 --- [taskScheduler-1] c.c.dashboard.collector.CollectorTask    : Collecting AWS Cloud Data...
2016-10-27 17:10:00.168 ERROR 3249 --- [taskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
        at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:12783)
        at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:8865)
        at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:12330)
        at com.capitalone.dashboard.collector.DefaultAWSCloudClient.getCloundInstances(DefaultAWSCloudClient.java:95)
        at com.capitalone.dashboard.collector.AWSCloudCollectorTask.collectInstances(AWSCloudCollectorTask.java:137)
        at com.capitalone.dashboard.collector.AWSCloudCollectorTask.collect(AWSCloudCollectorTask.java:122)
        at com.capitalone.dashboard.collector.AWSCloudCollectorTask.collect(AWSCloudCollectorTask.java:51)
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
What i'm missing here? Is somebody facing the same issue? 
Thanks in advance

**Comment by amitmawkin** [comment]
can you paste your properties file here - scrub your credentials etc

**Comment by JustLeo** [comment]
Problem resolved, thought this was taking the default profile by default. So after explicity telling which profile to use, it started working just fine.

# AWS Profile to be used if any
aws.profile=default

**Comment by amitmawkin** [comment]
That would be the case of running it locally, if you run on an EC2 instance with a proper IAM profile , you dont need to supply profile. The IAM profile with appropriate permission does so

**Comment by ansmirza** [comment]
if running locally which file needs to be configured ?

**Comment by shreesri** [comment]
@amitmawkin : i am getting following stack but not able to get the aws wizard in Hygieia dashboard.

2017-09-19 15:06:56,007 INFO c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...
2017-09-19 15:06:56,859 INFO c.c.d.collector.CollectorTask - Finished Cloud collection.
2017-09-19 15:06:57,003 INFO c.c.d.collector.CollectorTask - Running Collector: AWSCloud
2017-09-19 15:06:57,007 INFO c.c.d.collector.CollectorTask - Starting AWS collection...
2017-09-19 15:06:57,008 INFO c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...
2017-09-19 15:06:57,848 INFO c.c.d.collector.CollectorTask - Finished Cloud collection.
2017-09-19 15:06:58,004 INFO c.c.d.collector.CollectorTask - Running Collector: AWSCloud
2017-09-19 15:06:58,010 INFO c.c.d.collector.CollectorTask - Starting AWS collection...
2017-09-19 15:06:58,011 INFO c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...
2017-09-19 15:06:59,027 INFO c.c.d.collector.CollectorTask - Finished Cloud collection.
2017-09-19 15:07:00,000 INFO c.c.d.collector.CollectorTask - Running Collector: AWSCloud
2017-09-19 15:07:00,005 INFO c.c.d.collector.CollectorTask - Starting AWS collection...
2017-09-19 15:07:00,005 INFO c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...
2017-09-19 15:07:00,950 INFO c.c.d.collector.CollectorTask - Finished Cloud collection.
2017-09-19 15:07:01,003 INFO c.c.d.collector.CollectorTask - Running Collector: AWSCloud
2017-09-19 15:07:01,007 INFO c.c.d.collector.CollectorTask - Starting AWS collection...
2017-09-19 15:07:01,007 INFO c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...
2017-09-19 15:07:01,856 INFO c.c.d.collector.CollectorTask - Finished Cloud collection.
2017-09-19 15:07:02,001 INFO c.c.d.collector.CollectorTask - Running Collector: AWSCloud
2017-09-19 15:07:02,011 INFO c.c.d.collector.CollectorTask - Starting AWS collection...
2017-09-19 15:07:02,013 INFO c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...
2017-09-19 15:07:02,882 INFO c.c.d.collector.CollectorTask - Finished Cloud collection.
2017-09-19 15:07:03,001 INFO c.c.d.collector.CollectorTask - Running Collector: AWSCloud
2017-09-19 15:07:03,007 INFO c.c.d.collector.CollectorTask - Starting AWS collection...
2017-09-19 15:07:03,008 INFO c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...
2017-09-19 15:07:03,853 INFO c.c.d.collector.CollectorTask - Finished Cloud collection.
2017-09-19 15:07:04,001 INFO c.c.d.collector.CollectorTask - Running Collector: AWSCloud
2017-09-19 15:07:04,008 INFO c.c.d.collector.CollectorTask - Starting AWS collection...
2017-09-19 15:07:04,008 INFO c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...
2017-09-19 15:07:04,853 INFO c.c.d.collector.CollectorTask - Finished Cloud collection.
2017-09-19 15:07:05,000 INFO c.c.d.collector.CollectorTask - Running Collector: AWSCloud
2017-09-19 15:07:05,007 INFO c.c.d.collector.CollectorTask - Starting AWS collection...
2017-09-19 15:07:05,008 INFO c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...
2017-09-19 15:07:05,864 INFO c.c.d.collector.CollectorTask - Finished Cloud collection.
2017-09-19 15:07:06,006 INFO c.c.d.collector.CollectorTask - Running Collector: AWSCloud
2017-09-19 15:07:06,009 INFO c.c.d.collector.CollectorTask - Starting AWS collection...
2017-09-19 15:07:06,010 INFO c.c.d.collector.CollectorTask - Collecting AWS Cloud Data...

**Comment by pavannellore** [comment]
@JustLeo  Hello , I am also geeting the same error . What is aws profile name in AWS . I am not getting in AWS console .Please help 

2018-07-17 15:02:01,076 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
        at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131) ~[aws-java-sdk-core-1.10.46.jar!/:na]
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:12783) ~[aws-java-sdk-ec2-1.10.46.jar!/:na]
        at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:8865) ~[aws-java-sdk-ec2-1.10.46.jar!/:na]
        at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:12330) ~[aws-java-sdk-ec2-1.10.46.jar!/:na]
        at com.capitalone.dashboard.collector.DefaultAWSCloudClient.getCloudInstances(DefaultAWSCloudClient.java:95) ~[aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AWSCloudCollectorTask.collectInstances(AWSCloudCollectorTask.java:137) ~[aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AWSCloudCollectorTask.collect(AWSCloudCollectorTask.java:122) ~[aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AWSCloudCollectorTask.collect(AWSCloudCollectorTask.java:51) ~[aws-cloud-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_
