### ISSUE TITLE
Jenkins Collector - HttpClientErrorException: 404 Not Found

### ISSUE THREAD

**Issue by xpdable** [capitalone/Hygieia#932]
Against Jenkins : Jenkins ver. 1.593

Getting below exception on Jenkins collector:

```
2016-11-07 16:15:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2016-11-07 16:15:00,018 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-07 16:15:00,020 INFO  c.c.d.collector.CollectorTask - http://10.35.13.193
2016-11-07 16:15:00,023 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-07 16:15:00,035 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 404 Not Found
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandle
r.java:91) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614) ~[spring-web-4.
1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570) ~[spring-web-4.1.7.R
ELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.REL
EASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RE
LEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:372)
 ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:9
6) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) [jenk
ins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenk
ins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.4-SNAPSHOT.
jar!/:2.0.4-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlin
gRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [
na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.
0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_91]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
2016-11-07 16:15:00,041 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://10.35.13.193 0s
```

**Comment by xpdable** [comment]
My application.properties:


   #Database Name
    dbname=dashboard

    #Database HostName - default is localhost
    dbhost=10.35.24.62

    #Database Port - default is 27017
    dbport=27017

    #Database Username - default is blank
    dbusername=db

    #Database Password - default is blank
    dbpassword=dbpass

    #Collector schedule (required)
    jenkins.cron=0 0/1 * * * *

    #Jenkins server (required) - Can provide multiple
    jenkins.servers[0]=http://10.35.13.193:8080/

**Comment by MarkRx** [comment]
Are you sure? log says you are hitting http://10.35.13.193 without port 8080.

Logging can be turned up with

> logging.level.com.capitalone.dashboard.collector=DEBUG

404 indicates your networking isn't set up. Trying curling the url from where you are running. If running in a vm additional network setup might be needed.

**Comment by xpdable** [comment]
@MarkRx  Thanks. No. I setup the url like this jenkins.servers[0]=http://10.35.13.193:8080/
However, I am either confused that the logs show that 8080 is not hit. 
For the network connection, the Jenkins server and the Hygieia I setup are both on physical server, in the same LAN physically.

**Comment by xpdable** [comment]
I pulled latest version and now everything's working fine

**Comment by shilpsl1** [comment]
Hi,

I am facing similar issue, Could you please help me how did you resolve it. What latest version did you pull, it is jenkins collector ? 

ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 404 Not Found
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:461) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:98) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:91) [jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522) [na:1.8.0-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:277) [na:1.8.0-internal]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191) [na:1.8.0-internal]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [na:1.8.0-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153) [na:1.8.0-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [na:1.8.0-internal]
	at java.lang.Thread.run(Thread.java:785) [na:1.8.0-internal]
2017-01-17 15:25:00,149 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://10.0.0.0:8000/ 0s

**Comment by xpdable** [comment]
@shilpsl1 Now I am working fine the latest master branch.
