### ISSUE TITLE
unable to enter password - Bitbucket configuration

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#938]
Team,
 can you please help for the below,
I just did git clone, brough up API & UI, later when I enter my code repo info, getting the below error.

![bitbucketerr](https://cloud.githubusercontent.com/assets/10332154/20172880/d60abbfe-a75c-11e6-9269-89c2bef7bc53.png)

**Comment by smsuresh** [comment]
Below is the console log:


oundTripTimeNanos=417947}
2016-11-10 10:03:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2016-11-10 10:03:00,129 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2016-11-10 10:03:00,144 INFO  com.capitalone.dashboard.Application - Started Application in 7.593 seconds (JVM running for 8.93)
2016-11-10 10:03:00,171 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-10 10:03:00,172 INFO  c.c.d.collector.CollectorTask - Starting...
2016-11-10 10:03:00,172 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-10 10:03:00,218 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2016-11-10 10:03:00,218 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2016-11-10 10:03:00,218 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2016-11-10 10:04:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2016-11-10 10:04:00,017 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-10 10:04:00,018 INFO  c.c.d.collector.CollectorTask - Starting...
2016-11-10 10:04:00,018 INFO  c.c.d.collector.CollectorTask - -----------------------------------

**Comment by smsuresh** [comment]
Below is the property file:


# Database Username - default is blank
spring.data.mongodb.username=mydashboardusername

# Database Password - default is blank
spring.data.mongodb.password=mydbpassword

# Collector schedule (required)
git.cron=0 0/1 * * * *

# mandatory:
git.host=bitbucket.myreposite.com
git.api=/rest/api/1.0/

# Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

# Page size for rest calls.
#   Only applicable to Bitbucket Server.
#   Only applicable to Bitbucket Cloud.
git.pageSize=25

# Bitbucket product
#   Set to "cloud" to use Bitbucket Cloud (formerly known as Bitbucket)
#   Set to "server" to use Bitbucket Server (formerly known as Stash)
#   More information can be found here:
#     https://github.com/capitalone/Hygieia/issues/609
git.product=server

**Comment by smsuresh** [comment]
When I enter like the below is UI,

![bitbucketerr2](https://cloud.githubusercontent.com/assets/10332154/20206161/a126734e-a804-11e6-8dbd-20364a99088e.png)


Below is the console Error:


2016-11-11 06:13:19,462 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:11}] to localhost:27017
2016-11-11 06:13:19,463 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 0]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=439075}
2016-11-11 06:13:20,250 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2016-11-11 06:13:20,265 INFO  com.capitalone.dashboard.Application - Started Application in 7.54 seconds (JVM running for 8.739)
2016-11-11 06:14:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2016-11-11 06:14:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-11 06:14:00,006 INFO  c.c.d.collector.CollectorTask - Starting...
2016-11-11 06:14:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-11 06:14:00,635 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https://bitbucket.mySite.com/rest/api/1.0/projects/svec/repos/las/commits?until=develop&limit=25
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:466) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:232) ~[bitbucket-scm-collector-2.0.3.jar!/:2.0.3]
        at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:88) ~[bitbucket-scm-collector-2.0.3.jar!/:2.0.3]
        at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:132) [bitbucket-scm-collector-2.0.3.jar!/:2.0.3]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.3.jar!/:2.0.3]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2016-11-11 06:14:00,641 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2016-11-11 06:14:00,641 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2016-11-11 06:14:00,641 INFO  c.c.d.collector.CollectorTask - Finished                         0s

**Comment by smsuresh** [comment]
Below are my command line to invoke &  property file details.




ubuntu@myhostname:/opt/myHygieia/conf$ **sudo java -jar /opt/myHygieia/mHygieia/bitbucket-scm-collector-2.0.3.jar --spring.config.location=/opt/myHygieia/conf/bitbucket.properties**


ubuntu@myhostname:/opt/myHygieia/conf$ cat **/opt/myHygieia/conf/bitbucket.properties**
# dashboard.properties
dbname=mydashboarddbName
dbusername=mydashboarduserName
dbpassword=mydbpassword
dbhost=localhost
dbport=27017
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]
server.contextPath=/api
server.port=8080
#version.number=@application.version.number@


# Database Name
spring.data.mongodb.dbname=mydashboarddbName

# Database HostName - default is localhost
spring.data.mongodb.host=localhost

# Database Port - default is 27017
spring.data.mongodb.port=27017

# Database Username - default is blank
spring.data.mongodb.username=mydashboarduserName

# Database Password - default is blank
spring.data.mongodb.password=mydbpassword

# Collector schedule (required)
git.cron=0 0/1 * * * *

# mandatory:
git.host=bitbucket.pearson.com
git.api=/rest/api/1.0/

# Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

# Page size for rest calls.
#   Only applicable to Bitbucket Server.
#   Only applicable to Bitbucket Cloud.
git.pageSize=25

# Bitbucket product
#   Set to "cloud" to use Bitbucket Cloud (formerly known as Bitbucket)
#   Set to "server" to use Bitbucket Server (formerly known as Stash)
#   More information can be found here:
#     https://github.com/capitalone/Hygieia/issues/609
git.product=server

**Comment by satishc1** [comment]
@smsuresh To save private repo credentials..
Functionality merged in https://github.com/capitalone/Hygieia/pull/835
Refer to the "Encryption for private repos" section in the UI module readme.

**Comment by smsuresh** [comment]
Thankyou, now im getting data, but graph is missing @satishc1 , can you give a clue?

**Comment by smsuresh** [comment]
2016-11-17 06:11:36,405 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:353}] to localhost:27017
2016-11-17 06:11:36,405 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 0]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=459889}
2016-11-17 06:11:36,908 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2016-11-17 06:11:36,909 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2016-11-17 06:11:36,910 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2016-11-17 06:11:36,922 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@4afc07fc, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@6d8f2ab6, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@28ec2cce, socketFactory=javax.net.DefaultSocketFactory@7075fb53, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2016-11-17 06:11:37,084 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:355}] to localhost:27017
2016-11-17 06:11:37,087 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 0]}, minWireVersion=0, maxWireVersion=5, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=3159673}
2016-11-17 06:11:37,842 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2016-11-17 06:11:37,852 INFO  com.capitalone.dashboard.Application - Started Application in 7.651 seconds (JVM running for 8.877)
2016-11-17 06:12:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2016-11-17 06:12:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-17 06:12:00,007 INFO  c.c.d.collector.CollectorTask - Starting...
2016-11-17 06:12:00,007 INFO  c.c.d.collector.CollectorTask - -----------------------------------




--------
There is no movement further ,can you give some hint?  @MarkRx @satishc1 @tabladrum

**Comment by smsuresh** [comment]
but process/collector is still running..

**Comment by oshingc** [comment]
I have the same error... :/

**Comment by satishc1** [comment]
@smsuresh Set the log level to DEBUG.  What's the output of the following line that's in DefaultBitbucketServerClient
LOG.debug("Rest Url: " + queryUri);
Are you able to see the commits when you directly access that url ?

**Comment by nitin1706** [comment]
@smsuresh : are you still seeing this? can you try with latest code and share logs.

**Comment by nitin1706** [comment]
re-open with complete logs if issue still exists.
