### ISSUE TITLE
Issue with configuring gitlab for Hygieia

### ISSUE THREAD

**Issue by vetrivelan25** [capitalone/Hygieia#961]
2016-11-21 09:10:33,945 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2016-11-21 09:10:33,952 INFO  com.capitalone.dashboard.Application - Started Application in 3.489 seconds (JVM running for 4.131)
2016-11-21 09:11:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2016-11-21 09:11:00,007 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-21 09:11:00,007 INFO  c.c.d.collector.CollectorTask - Starting...
2016-11-21 09:11:00,007 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-21 09:11:00,024 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient.normalizeUrl(DefaultGitlabGitClient.java:239) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient.getCommits(DefaultGitlabGitClient.java:68) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collecteur.GitlabGitCollectorTask.collect(GitlabGitCollectorTask.java:76) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by rob-miller-777** [comment]
Do you have the latest version of the code pulled down?  Your stack trace is showing lines that no longer exist in the current code base.  I made some changes last week that might resolve your issue.

**Comment by rob-miller-777** [comment]
#957 Looks like this person is having the same issue.

**Comment by Ragavendira1** [comment]
Hi Team, 

Whenever i am running Gitlab collector, i am getting only as 0 repo. and below is log details. 
 2017-07-13 15:22:16,793 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=26541745,type=ConfigurationPropertiesRebinder]
2017-07-13 15:22:16,832 INFO  com.capitalone.dashboard.Application - Started Application in 5.443 seconds (JVM running for 5.931)
2017-07-13 15:23:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2017-07-13 15:23:00,014 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-07-13 15:23:00,014 INFO  c.c.d.collector.CollectorTask - Starting...
2017-07-13 15:23:00,014 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-07-13 15:23:00,054 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2017-07-13 15:23:00,054 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2017-07-13 15:23:00,054 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-07-13 15:24:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2017-07-13 15:24:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------

Also, please find the below my application.properties file details and still i unable to configure gitlabe widget as save button is non functional when ever i clicked. kindly through some lights so that i will configure this widget. 

# Database Name
dbname=dashboard

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=db

# Database Password - default is blank
dbpassword=dbpass

# Logging File location
logging.file=./logs/gitlab.log

#Collector schedule (required)
gitlab.cron=0 0/1 * * * *

#Gitlab host (optional, defaults to "gitlab.com")
gitlab.host=192.168.22.172

#Gitlab protocol (optional, defaults to "http")
gitlab.protocol=

#Gitlab port (optional, defaults to protocol default port)
gitlab.port=80

#Gitlab path (optional, if your instance of gitlab requires a path)
gitlab.path=

#If your instance of Gitlab is using a self signed certificate, set to true, default is false
gitlab.selfSignedCertificate=false

#Gitlab API Token (required, token of user the collector will use by default, can be overriden on a per repo basis from the UI. API token provided by Gitlab)
gitlab.apiToken=JWtLUemzTuVt-WAsNKxL

#Maximum number of days to go back in time when fetching commits
gitlab.commitThresholdDays=15
