### ISSUE TITLE
Hygieia Hudson/Jenkins Collector Breaks due to MongoDB BSON Document Size Restrictions

### ISSUE THREAD

**Issue by hackeys** [capitalone/Hygieia#971]
Hi ,

Hygieia Jenkins Collector break due to MongoDB BSON Document Size restriction which doesnt allow user to store document size above 16Mb .

Getting below error ,
```
   at com.capitalone.dashboard.collector.HudsonCollectorTask.addNewBuilds(HudsonCollectorTask.java:197) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:95) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-11-22 21:33:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2016-11-22 21:33:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-22 21:33:00,006 INFO  c.c.d.collector.CollectorTask - http://10.14.34.73:9090
2016-11-22 21:33:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-22 21:33:00,015 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2016-11-22 21:33:00,015 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2016-11-22 21:33:08,344 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.bson.BsonSerializationException: Size 18446453 is larger than MaxDocumentSize 16793600.
        at org.bson.BsonBinaryWriter.backpatchSize(BsonBinaryWriter.java:364) ~[mongo-java-driver-3.0.2.jar!/:na]
        at org.bson.BsonBinaryWriter.doWriteEndDocument(BsonBinaryWriter.java:122) ~[mongo-java-driver-3.0.2.jar!/:na]
        at org.bson.AbstractBsonWriter.writeEndDocument(AbstractBsonWriter.java:293) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:130) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:61) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.CompoundDBObjectCodec.encode(CompoundDBObjectCodec.java:48) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.CompoundDBObjectCodec.encode(CompoundDBObjectCodec.java:27) ~[mongo-java-driver-3.0.2.jar!/:na]
        at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63) ~[mongo-java-driver-3.0.2.jar!/:na]
        at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:99) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:43) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBody(BaseWriteCommandMessage.java:112) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBody(BaseWriteCommandMessage.java:35) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.RequestMessage.encode(RequestMessage.java:132) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.BaseWriteCommandMessage.encode(BaseWriteCommandMessage.java:89) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.WriteCommandProtocol.sendMessage(WriteCommandProtocol.java:170) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:73) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:66) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:37) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:155) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:219) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerConnection.insertCommand(DefaultServerConnection.java:108) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.InsertOperation.executeCommandProtocol(InsertOperation.java:76) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:111) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:106) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:186) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:177) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:106) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:58) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.Mongo.execute(Mongo.java:747) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.Mongo$2.execute(Mongo.java:730) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:327) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBCollection.insert(DBCollection.java:323) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBCollection.insert(DBCollection.java:314) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBCollection.insert(DBCollection.java:284) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBCollection.insert(DBCollection.java:250) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBCollection.insert(DBCollection.java:187) ~[mongo-java-driver-3.0.2.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate$9.doInCollection(MongoTemplate.java:990) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:462) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.insertDBObject(MongoTemplate.java:985) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.doInsert(MongoTemplate.java:798) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.insert(MongoTemplate.java:743) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.save(SimpleMongoRepository.java:76) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
```

**Comment by tabladrum** [comment]
Are you storing jenkins log too? If yes, turn that off.

**Comment by hackeys** [comment]
Can you please guide me on turning it off ?

**Comment by tabladrum** [comment]
In your properties file turn the following off
# Determines if build console log is collected - defaults to false
jenkins.saveLog=true

**Comment by hackeys** [comment]
I have not mentioned it explicitly . What is the default setting ?

@tabladrum  Thanks a lot for quick response

**Comment by tabladrum** [comment]
default setting is true. Try setting it to false. If that works, please close the issue.
