### ISSUE TITLE
Issue installing jenkins plugin in jenkin server

### ISSUE THREAD

**Issue by anjana83** [capitalone/Hygieia#972]
Hi,
Can you please help me. I am getting below error while installing hygieia-jenkin plugin in jenkin server.

Installing Plugins/Upgrades
Preparation	
hygieia-publisher	
 Failure -
java.io.IOException: Failed to dynamically deploy this plugin
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1317)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1116)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:104)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Failed to install hygieia-publisher plugin
	at hudson.PluginManager.dynamicLoad(PluginManager.java:453)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1313)
	... 5 more
Caused by: java.io.IOException: Dependency multiple-scms (0.6) doesn't exist
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:488)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:443)
	... 6 more

**Comment by anjana83** [comment]
any help here Please. I tried to install hygieia plugin multiple time and facing same issue.

**Comment by tabladrum** [comment]
which Jenkins version are you using?

**Comment by tabladrum** [comment]
Also, can you please install multiple-scm plugin and then try again?

**Comment by anjana83** [comment]
thanks for your response. I re-installed my local Jenkin and also installed all recommended plugins with it. It is working now.
