### ISSUE TITLE
Gitlab collector failed

### ISSUE THREAD

**Issue by vetrivelan25** [capitalone/Hygieia#973]
```
2016-11-23 12:44:53,550 WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitlabGitCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at com.capitalone.dashboard.Application.main(Application.java:16) [gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.NullPointerException: null
        at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73) ~[core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 22 common frames omitted
2016-11-23 12:44:53,560 INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'
2016-11-23 12:44:53,565 INFO  o.s.b.l.ClasspathLoggingApplicationListener - Application failed to start with classpath: [jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/core-2.0.4-SNAPSHOT.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-boot-1.2.5.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-test-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-data-mongodb-1.8.0.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-expression-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-data-commons-1.11.0.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/slf4j-api-1.7.12.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/jcl-over-slf4j-1.7.12.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/querydsl-jpa-3.6.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/querydsl-core-3.6.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/guava-18.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/jsr305-1.3.9.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/mysema-commons-lang-0.2.4.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/bridge-method-annotation-1.13.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/querydsl-apt-3.6.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/querydsl-codegen-3.6.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/codegen-0.6.5.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/ecj-4.3.1.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/javax.inject-1.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/querydsl-mongodb-3.6.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/validation-api-1.1.0.Final.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/hibernate-validator-5.1.3.Final.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/jboss-logging-3.1.3.GA.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/classmate-1.0.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/javax.el-api-2.2.4.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/commons-beanutils-1.9.2.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/commons-collections-3.2.1.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-boot-starter-data-mongodb-1.2.5.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-boot-starter-1.2.5.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-boot-autoconfigure-1.2.5.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-boot-starter-logging-1.2.5.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/jul-to-slf4j-1.7.12.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/log4j-over-slf4j-1.7.12.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/logback-classic-1.1.3.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/logback-core-1.1.3.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/snakeyaml-1.14.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/mongo-java-driver-3.0.2.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-core-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-tx-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/junit-4.12.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/hamcrest-core-1.3.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-web-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-aop-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/aopalliance-1.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-beans-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-context-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/json-simple-1.1.1.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/commons-lang3-3.3.2.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/commons-codec-1.9.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/httpclient-4.3.6.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/httpcore-4.3.3.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/joda-time-2.7.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/joda-convert-1.8.1.jar!/]
2016-11-23 12:44:53,568 INFO  o.s.b.a.l.AutoConfigurationReportLoggingInitializer -

Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)


2016-11-23 12:44:53,569 ERROR o.s.boot.SpringApplication - Application startup failed
```

**Comment by rob-miller-777** [comment]
org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.scheduling.support.CronSequenceGenerator.(CronSequenceGenerator.java:95) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.scheduling.support.CronSequenceGenerator.(CronSequenceGenerator.java:82) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.scheduling.support.CronTrigger.(CronTrigger.java:44) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73) ~[core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]

Based on that section of the stack trace, my guess is you didn't include a cron sequence in your properties file, or an invalid one.  Makes sure you having something like the line below in your application properties file.  
`gitlab.cron=0 0/1 * * * *`

**Comment by vetrivelan25** [comment]
Thanks for you help after i changed my gitlab.cron i didn't that issue but  i'm getting below issue
 It's trying to fetch the gitlab details form default gitlab url not for my specified ipaddress url. If i give gitlab.host in gitlab.properties i'm getting message  java.lang.IllegalArgumentException: Invalid character ':' for HOST_IPV4 in "http://66.228.26.201:8282/".But if try with gitlab.server in gitlab.properties file its started but fetching form default not mine.
gitlab.properties file:

dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
gitlab.cron=0 0/1 * * * *
gitlab.server=http://66.228.26.201:8282/ (Sample one not exact ip address)
gitlab.branche=master
gitlab.apiToken=CAvxoN_MByFws4MQKxZ2
gitlab.saveLog=true

gitlab jar Command:
 sudo java -jar gitlab-git-collector-2.0.4-SNAPSHOT.jar --spring.config.name=gitlab --spring.config.location=/home/ubuntu/Hygieia-master/collectors/scm/gitlab/target/gitlab.properties

Issue: (Its fetching the data form some other url not for our specified gitlab ip address)
-----------------------------------------------------------------------------------------------
2016-11-25 06:05:32,575 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2016-11-25 06:05:32,590 INFO  com.capitalone.dashboard.Application - Started Application in 6.15 seconds (JVM running for 7.234)
2016-11-25 06:06:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2016-11-25 06:06:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-25 06:06:00,006 INFO  c.c.d.collector.CollectorTask - Starting...
2016-11-25 06:06:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-25 06:06:00,749 INFO  c.c.d.c.DefaultGitlabGitClient - Failed to retrieve data from: https://gitlab.com/api/v3/projects/vetrivelan%2FTest/repository/commits/?ref_name=master&since=2016-11-25T05:56:00Z&per_page=100
2016-11-25 06:06:00,851 INFO  c.c.d.c.DefaultGitlabGitClient - Failed to retrieve data from: https://gitlab.com/api/v3/projects/repository/commits/?ref_name=master&since=2016-11-25T05:56:00Z&per_page=100
2016-11-25 06:06:00,852 INFO  c.c.d.collector.CollectorTask - Repo Count              2        0s
2016-11-25 06:06:00,853 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2016-11-25 06:06:00,853 INFO  c.c.d.collector.CollectorTask - Finished                         0s

**Comment by rob-miller-777** [comment]
Think you are now at the same point as #957 , I will be working on a fix for that this week.  Your properties file does need to be updated however.  Server, branche, and saveLog are no longer properties.  Instead use the properties below.  I will be adding two new properties for port and protocol to support the issue in 957.  

```
gitlab.cron=0 0/3 * * * *
gitlab.apiToken={token}
gitlab.host={host}
gitlab.selfSignedCertificate=false
gitlab.commitThresholdDays=15
```

**Comment by vetrivelan25** [comment]
Kindly inform once gitlab the issue is fixed

**Comment by mrpudn** [comment]
Marking this one as a duplicate and closing - please track the status on #957 and PR #990 

Thanks!
