### ISSUE TITLE
Gitlab collector error

### ISSUE THREAD

**Issue by vetrivelan25** [capitalone/Hygieia#976]
While run the Git lab collector i'm getting below issue JVM is running but some problem occur in Scheduler .I verified that original host url is working on browser.
i tried the url with below possibility also getting same issue and also i tried to change the gitlab.cron value also 
gitlab.host=http://66.228.26.201:8282/
gitlab.host=66.228.26.201:8282
gitlab.host=66.228.26.201:8282

My gitlab.properties file:

dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
logging.file=./logs/gitlab.log
gitlab.cron=0 0/1 * * * *
gitlab.host=http://66.228.26.201:8282/        -> (Sample Url not original)
gitlab.selfSignedCertificate=false
gitlab.commitThresholdDays=15

2016-11-24 10:19:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2016-11-24 10:19:00,010 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-24 10:19:00,010 INFO  c.c.d.collector.CollectorTask - Starting...
2016-11-24 10:19:00,011 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-24 10:19:00,033 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalArgumentException: Invalid character ':' for HOST_IPV4 in "http://66.228.26.201:8282/"
        at org.springframework.web.util.HierarchicalUriComponents.verifyUriComponent(HierarchicalUriComponents.java:304) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.util.HierarchicalUriComponents.verify(HierarchicalUriComponents.java:269) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.util.HierarchicalUriComponents.<init>(HierarchicalUriComponents.java:88) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.web.util.UriComponentsBuilder.build(UriComponentsBuilder.java:364) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collecteur.GitlabUrlUtility.buildApiUrl(GitlabUrlUtility.java:61) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient.getCommits(DefaultGitlabGitClient.java:61) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collecteur.GitlabGitCollectorTask.collect(GitlabGitCollectorTask.java:98) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by rob-miller-777** [comment]
Same issue as #957
