### ISSUE TITLE
Cannot run UI anymore

### ISSUE THREAD

**Issue by bodiam** [capitalone/Hygieia#98]
After syncing with the latest version of Hygieia, whenever I run `gulp serve`, the initial login page shows, but after that, I get an error:

````
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.writeHead (_http_server.js:195:21)
    at ProxyServer.<anonymous> (/Users/erikp/Userfiles/Klanten/Rabobank/Projects/cqc-dashboard/UI/gulp/proxy.js:32:7)
    at ProxyServer.emit (/Users/erikp/Userfiles/Klanten/Rabobank/Projects/cqc-dashboard/UI/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
    at ClientRequest.proxyError (/Users/erikp/Userfiles/Klanten/Rabobank/Projects/cqc-dashboard/UI/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:139:16)
    at ClientRequest.emit (events.js:129:20)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
````

**Comment by bodiam** [comment]
Update: just checked at a different pc (also Mac) from a colleague, and the same problem there with the same error message.

**Comment by tabladrum** [comment]
Can you join the chat?

**Comment by tyrion70** [comment]
Hey, experiencing the same issue when running from within a docker container:
phusion/baseimage:latest
maven 3.2.5
latest node

**Comment by rubengeertsema** [comment]
Hi, I'm getting the same error as @bodiam.

```
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.writeHead (_http_server.js:195:21)
    at ProxyServer.<anonymous> (/Users/rubengeertsema/Development/Hygieia/UI/gulp/proxy.js:32:7)
    at ProxyServer.emit (/Users/rubengeertsema/Development/Hygieia/UI/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
    at ClientRequest.proxyError (/Users/rubengeertsema/Development/Hygieia/UI/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:139:16)
    at ClientRequest.emit (events.js:129:20)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
```

maven: 3.3.3 
node: 0.12.7
npm: 2.12.1
bower: 1.5.2

**Comment by amitmawkin** [comment]
can you please print the out put of 
http://localhost:8080/api/dashboard.

**Comment by tyrion70** [comment]
For some reason I'm not having this issue now anymore.. I did notice however that sometimes the build job for UI succeeds even if some parts failed. Especially during the npm install. I had to install make, gcc and g++ to fix all those issues, as well as ensure that the user building the UI is the same user that's running it. Maybe this helps. 

The Dockerfile I added in my PR shows exactly what I installed, maybe that helps a little.

**Comment by tyrion70** [comment]
Issue is back again :( I think it has something to do with the jenkins log:

I see an 
ERR_INCOMPLETE_CHUNKED_ENCODING
error in the console of the browser on this url:
http://192.168.2.5:3000/api/build/?componentId=55e22090e4b0b616d9cc9b2b&numberOfDays=15

the output of /api/dashboard looks fine (to me). It seems like if the jenkins log is to large on the latest build it screws up. 

I can reproduce it I think, if you build Hygieia itself in Jenkins and add that job to the dashboard it will fail. Jobs that don't have to much logging don't fail.

Workaround might be to disable the jenkins logs with

    jenkins.saveLog=false

Hope this helps..

**Comment by tabladrum** [comment]
What web server are you using? I am assuming you are using chrome browser.

**Comment by tyrion70** [comment]
Chrome browser and the builtin gulp server. Do you need the version number?

**Comment by tyrion70** [comment]
Hmm, just updated the Docker file to run with apache.. guess what; the error is gone.. I have a gulp serve that is now restarting every time, while apache is still running without errors. I'll push my changes shortly, both the apache and gulp will be running (on ports 3000 (gulp) and apache(3001))

**Comment by bodiam** [comment]
Hi @tyrion70, I'm not surprised. Running the app on Apache is currently the only way I can run it. My knowledge of Node isn't good enough to fix this, all I know is that it used to work, and it doesn't anymore..

**Comment by tabladrum** [comment]
Closing as per gitter chat.

**Comment by bodiam** [comment]
So... this is fixed? Or not using gulp anymore? What has been discussed in the chat?

**Comment by tabladrum** [comment]
Seems like you are able to run the UI? no?

**Comment by bodiam** [comment]
I'm not, no, nor did I ever mention that in the chat. I just went through it, and the last 200 messages don't mention anything like it.

**Comment by tabladrum** [comment]
Check Aug 27 15:32 message: 
ah like that
bodiam Aug 27 15:32
apache is restarted
let me check if it works.
proxy works
rest also
srid99 Aug 27 15:33
screw node :stuck_out_tongue_winking_eye:
bodiam Aug 27 15:34
for sure!

**Comment by tabladrum** [comment]
Ah! I get it.. gulp still not working on your Mac?

**Comment by bodiam** [comment]
That's what I'm saying. It's a workaround. Gulp is working, it's just not working with Hyieia. But I see you mention in #97 that it's is fixed, so that why I say that maybe I missed something?

**Comment by bodiam** [comment]
Okay, I did a fresh checkout, everything new, etc,etc, and this is the result:

````
[BS] Local URL: http://localhost:3000/
[BS] External URL: http://192.168.1.7:3000/
[BS] Serving files from: .tmp
[BS] Serving files from: src
[BS] Watching files...
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.writeHead (_http_server.js:195:21)
    at ProxyServer.<anonymous> (/private/tmp/Hygieia/UI/gulp/proxy.js:32:7)
    at ProxyServer.emit (/private/tmp/Hygieia/UI/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
    at ClientRequest.proxyError (/private/tmp/Hygieia/UI/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:139:16)
    at ClientRequest.emit (events.js:129:20)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
````

**Comment by bodiam** [comment]
Can you reopen this?

**Comment by tyrion70** [comment]
Erik, can you try to run the api without console logging? @tabladrum asked
that yesterday evening in the chat).

Op donderdag 3 september 2015 heeft Erik Pragt <notifications@github.com>
het volgende geschreven:

**Comment by bodiam** [comment]
Sure. How do I turn that off?

**Comment by tyrion70** [comment]
He said in the application properties.. I assume with console.log=false? Doesnt it say in de docs? 

Verstuurd vanaf mijn iPhone

**Comment by bodiam** [comment]
I checked the docs, but couldn't find anything. I also don't know what the application properties are; do you mean the properties file, or the logback.xml? Not sure why turning logging of in a logback would have any effect on gulp though...
