### ISSUE TITLE
Jira collector - Failing to Collect Data

### ISSUE THREAD

**Issue by hackeys** [capitalone/Hygieia#997]
Hi All , 

I am getting following error , when run jira collector on same machine as Jira .
```
2016-12-01 17:12:22,308 INFO  com.capitalone.dashboard.Application - Started Application in 10.674 seconds (JVM running for 12.247)
2016-12-01 17:15:00,016 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-12-01 17:15:00,068 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-12-01 17:15:00,068 INFO  c.c.d.collector.CollectorTask - http://10.14.34.78:8080/
2016-12-01 17:15:00,068 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-12-01 17:15:02,199 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.RuntimeException: java.net.ConnectException: Connection refused
        at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-14.0.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:256) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:249) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:276) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:272) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.atlassian.util.concurrent.Promises$2.onFailure(Promises.java:167) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1145) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68) ~[guava-14.0.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1$2.run(SettableFuturePromiseHttpPromiseAsyncClient.java:59) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:197) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:90) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:192) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
```

My Application.properties file look like 

[app.prop.txt](https://github.com/capitalone/Hygieia/files/624424/app.prop.txt)

Howver , server and port is accessible over telnet .

telnet 10.14.34.78 8080
Trying 10.14.34.78...
Connected to 10.14.34.78.
Escape character is '^]'.
^]

Jira UI 
![jira](https://cloud.githubusercontent.com/assets/2296676/20792990/caa9371a-b7ea-11e6-8680-f2729031cb4c.png)

**Comment by satishc1** [comment]
@hackeys See if https://github.com/capitalone/Hygieia/issues/866 and https://github.com/capitalone/Hygieia/issues/901 helps.  Reopen if still an issue.

If you decide to use the latest codebase then you'll need to follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137

**Comment by hackeys** [comment]
Hi All ,

With new code base i could run jira collector with few exceptions around ,

https://github.com/capitalone/Hygieia/pull/1030
